### ISSUE TITLE
Resource strings referenced by COUNTED_REASON_CONTEXT 

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-driver-docs-ddi#1000]
The [COUNTED_REASON_CONTEXT](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntpoapi/ns-ntpoapi-_counted_reason_context) article claims:

> The DIAGNOSTIC_REASON_DETAILED_STRING flag supports localization. If the localized resource file specified by <b>ResourceFileName</b> exists, the power manager retrieves a set of resource strings from the file and uses these strings in place of the strings contained in the <b>ReasonStrings</b> array. <b>ResourceId</b> specifies the resource index of the first string in the file to use as a reason string, and <b>StringCount</b> specifies the number of resource strings to use as reason strings. The resource strings must have consecutive resource indexes.

That is, if <b>ResourceId</b> is 42 and <b>StringCount</b> is 3, then the article says the resource file should contain resource strings with IDs 42, 43, and 44.

I suspect this documentation is wrong and the power manager instead retrieves only one resource string and then uses something like [FormatMessageW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessagew) to replace `%1`, `%2`, etc. placeholders with the <b>ReasonStrings</b>. Those semantics would be more consistent with how the user-mode [REASON_CONTEXT](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-reason_context) structure is documented, and more useful for driver developers. I have not tested what the power manager actually does, though.

In addition, it would be good to explicitly state whether the power manager retrieves the resource strings from [STRINGTABLE resources](https://docs.microsoft.com/en-us/windows/win32/menurc/stringtable-resource) or from a [MESSAGETABLE resource](https://docs.microsoft.com/en-us/windows/win32/menurc/messagetable-resource).

(There is no DIAGNOSTIC_REASON_DETAILED_STRING in <https://github.com/microsoft/Windows-driver-samples>.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca75555-1bf1-2079-aed0-1766e8f09cc9
* Version Independent ID: 35bfca22-4fbd-2506-7e37-be77a70f8e77
* Content: [_COUNTED_REASON_CONTEXT (ntpoapi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntpoapi/ns-ntpoapi-_counted_reason_context)
* Content Source: [wdk-ddi-src/content/ntpoapi/ns-ntpoapi-_counted_reason_context.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntpoapi/ns-ntpoapi-_counted_reason_context.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the detailed report @KalleOlaviNiemitalo 

I have just updated https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntpoapi/ns-ntpoapi-_counted_reason_context#remarks accordingly.  See the last two paragraphs.

Thanks again for bringing this to our attention!
