### ISSUE TITLE
Dereferencing object obtained from FltGetDiskDeviceObject

### ISSUE THREAD

**Issue by sormo** [MicrosoftDocs/windows-driver-docs-ddi#1001]
It doesn't look like device object obtained using `FltGetDiskDeviceObject` should be dereferenced with `FltObjectDereference`. Please check this. Looks like dereferencing should be done with `ObDereferenceObject` .

Also it would be great if you clarify when `FltGetDiskDeviceObject` can be called. Is it safe to be called in `InstanceSetup` callback or in custom ioctl?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccdb935-3977-db86-a2b7-2dba02bc83e8
* Version Independent ID: 7a58c6d0-f018-a4cd-61b6-e407e50bee16
* Content: [FltGetDiskDeviceObject function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetdiskdeviceobject)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetdiskdeviceobject.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetdiskdeviceobject.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Wow, great catch @sormo ! I've updated the page with the fix. Thanks for reporting this.
