### ISSUE TITLE
Including specified header file yields 'This header should not be included directly!' error

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#1017]
I'm building a UMDF driver project (based upon the MS `video\IndirectDisplay` sample). To specify `DISPLAYCONFIG_VIDEO_SIGNAL_INFO` for a supported display mode, I need to include `videoStandard`. [The page describing the DISPLAYCONFIG_VIDEO_SIGNAL_INFO struct](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-displayconfig_video_signal_info) states:

> `DUMMYUNIONNAME.AdditionalSignalInfo.videoStandard`
> 
> The video standard (if any) that defines the video signal. For a list of possible values, see the `D3DKMDT_VIDEO_SIGNAL_STANDARD` enumerated type.

Looking at the page that describes this enumerated type (this page), we're instructed to include **d3dkmdt.h**. Doing so, however, yields a compile-time error:

> `c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\d3dkmdt.h(20): fatal error C1189: #error:  This header should not be included directly!`

I've tried various other header files...
```
//#include <windef.h>
//#include <d3d9.h>
//#include <d3d9types.h>
//#include <d3dkmddi.h>
#include <d3dkmdt.h>      // D3DKMDT_VSS_OTHER
//#include <d3dkmthk.h>
//#include <Ntddk.h>
//#include <Ntifs.h>
//#include <Wdm.h>
```
...but most of them aren't in the include path for a UMDF driver project, and since many of these header files have 'km' (kernel mode) in their names, it's not clear that it's safe to add include paths that would allow them to be included...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07cc762f-21f1-bc6a-0c35-a979bb85871e
* Version Independent ID: 7244fbbe-ccde-3f35-539a-a3bd1a9cac59
* Content: [_D3DKMDT_VIDEO_SIGNAL_STANDARD (d3dkmdt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_signal_standard)
* Content Source: [wdk-ddi-src/content/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_signal_standard.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_signal_standard.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mr-intj , our doc tooling automatically adds the header file with the words "include xxx.h" to every refpage, so I cannot remove the word "include". I'll take it up with our tool folks to understand why the include instruction is there. You are correct that you cannot include this file in an indirect display project. The Indirect Display Sample simply adds the hardcoded numerical value of 255 (D3DKMDT_VSS_OTHER) for videoStandard. If you don't want to hardcode the value, the dev team suggested that one approach would be to copy the D3DKMDT_VIDEO_SIGNAL_STANDARD definition to your project. Hope your project is going well - appreciate the issues that you've been filing!
