### ISSUE TITLE
Insufficient documentation on struct member

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#1018]
> RequiredBandwidth
> 
> The display pipeline bandwidth required for this mode.

I've been unable to find any mention of this struct member other than on this page, and the single line above is the only documentation on the page. Searches over MS docs for phrases like "pipeline bandwidth" also yield _only this page_.

Similarly, this member doesn't appear to be referenced in any of the MS driver samples (or any other source code that I could find online).

There's no guidance at all on how to calculate this, what units it might be in, whether or not it's required. I can't find any mentions of "pipeline bandwidth" or similar phrases anywhere in the docs, so this is a complete mystery/wildcard. In diagnosing any errors or unexpected behavior in my driver (or apps relying on my driver), "not having specified this correctly" will always be a possible cause...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377d9ba9-8a04-4377-8572-34751d51837c
* Version Independent ID: 7ca823ff-b6d0-c4bf-547f-d166911da779
* Content: [IDDCX_TARGET_MODE (iddcx.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/iddcx/ns-iddcx-iddcx_target_mode)
* Content Source: [wdk-ddi-src/content/iddcx/ns-iddcx-iddcx_target_mode.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/iddcx/ns-iddcx-iddcx_target_mode.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mr-intj , thanks for the request for details. I've updated this page to link to the page that better describes bandwidth.
