### ISSUE TITLE
IddCxMonitorArrival parameter documentation seems incorrect

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#1019]
> ```
> NTSTATUS IddCxMonitorArrival(
>   IDDCX_MONITOR            AdapterObject,
>   IDARG_OUT_MONITORARRIVAL *pOutArgs
> );
> ```
>
> Parameters
> ===
> 
> __AdapterObject__
> 
> [in] The adapter object that is hosting the newly arrived monitor

This seems incorrect. The first parameter is an `IDDCX_MONITOR`, but the documentation discusses the (parent?) adapter object.

---
The header file has similarly confusing information:
```
/// <summary>
/// An OS callback function the driver calls report a monitor arrival on the WDDM graphics adapter
/// </summary>
/// <param name="AdapterObject">The adapter object that is hosting the newly arrived monitor</param>
/// <param name="pInArgs">Input arguments to the function</param>
/// <param name="pOutArgs">Output arguments to the function</param>
/// <returns>If the routine succeeds it return S_OK otherwise an appropriate error code</returns>
_Must_inspect_result_
NTSTATUS
FORCEINLINE
IddCxMonitorArrival(
    _In_
    IDDCX_MONITOR AdapterObject,
    _Out_
    IDARG_OUT_MONITORARRIVAL* pOutArgs
    )
```
(there is no **pInArgs** parameter)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0348c28c-46e9-0f0e-c1eb-f55dff1adefd
* Version Independent ID: b4dd592e-4715-130f-24fc-1c2044654afe
* Content: [IddCxMonitorArrival function (iddcx.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/iddcx/nf-iddcx-iddcxmonitorarrival)
* Content Source: [wdk-ddi-src/content/iddcx/nf-iddcx-iddcxmonitorarrival.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/iddcx/nf-iddcx-iddcxmonitorarrival.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @mr-intj ! I've fixed the refpage and reported the code comment error for the dev team to fix.
