### ISSUE TITLE
Including d3dkmdt.h yields compile error "This header should not be included directly!"

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#1024]
This page says to include **d3dkmdt.h**, but I need the `D3DKMDT_VIDEO_SIGNAL_STANDARD` enum type in a _UMDF IddCx driver project_, and including this file yields the following compiler error:
```
1>c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\d3dkmdt.h(20): fatal error C1189: #error:  This header should not be included directly!
```
Perhaps there is some pre-requisite header file that doesn't get included in a non-kernel-mode driver project, and that's what's triggering this error?

I spent a few hours Googling and experimenting, but wasn't able to figure it out. I ended up just having to copy/paste the enum typedef into my source file.  :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07cc762f-21f1-bc6a-0c35-a979bb85871e
* Version Independent ID: 7244fbbe-ccde-3f35-539a-a3bd1a9cac59
* Content: [_D3DKMDT_VIDEO_SIGNAL_STANDARD (d3dkmdt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_signal_standard)
* Content Source: [wdk-ddi-src/content/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_signal_standard.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_signal_standard.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mr-intj , I did find a way to remove the "include d3dkmdt.h" directive since it is not at all accurate per GitHub issue #1017 . Again, you did the right thing by copying the enum typedef into your source.
