### ISSUE TITLE
Page doesnot display properly

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/windows-driver-docs-ddi#1026]
This page has some overlap issues. 

Thanks,
Amit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35d49678-517e-cbe3-0020-5a58cb2e864d
* Version Independent ID: 1c91d8e4-f061-8cd5-eabb-3009ee4fd39c
* Content: [DXGKDDI_RENDER (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/nc-d3dkmddi-dxgkddi_render)
* Content Source: [wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_render.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_render.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @aguptadel . Per issue #1025 (reported about the same time) it is now fixed.
