### ISSUE TITLE
Is this long hand for "This is not optional"

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1027]
> The caller must specify a value for DisableReadAhead in each call to CcSetAdditionalCacheAttributes, even if a value was already specified in a previous call.

It is difficult how you cannot specify a BOOLEAN value which is not marked as optional in the header file.

This obviously means something, But I'm not sure what.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0e8316-a28b-f086-91f3-a8c0bc3cd087
* Version Independent ID: a2cd7b4f-e458-00ca-19b2-e6d4e11316c4
* Content: [CcSetAdditionalCacheAttributes function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ccsetadditionalcacheattributes)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ccsetadditionalcacheattributes.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ccsetadditionalcacheattributes.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , thanks for the issue, and fair enough about Booleans lol! I've updated the page with more precise language.
