### ISSUE TITLE
Incorrect return value

### ISSUE THREAD

**Issue by GabeSJones** [MicrosoftDocs/windows-driver-docs-ddi#103]
IoAcquireRemoveLock returns an NTSTATUS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff43c16-5161-b97d-e498-bbc5d2659fba
* Version Independent ID: 26169519-6e0e-42b2-851e-d8fc67a1b03a
* Content: [IoAcquireRemoveLock macro](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioacquireremovelock)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioacquireremovelock.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioacquireremovelock.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @GabeSJones 
@PageWriter-MSFT can you verify and update?

**Comment by PageWriter-MSFT** [comment]
Hi @GabeSJones 

**IoAcquireRemoveLockEx** returns NTSTATUS as you mention but **IoAcquireRemoveLock** is a macro that wraps **IoAcquireRemoveLockEx**:

#define IoAcquireRemoveLock(RemoveLock, Tag) \
        IoAcquireRemoveLockEx(RemoveLock, Tag, "", 1, sizeof (IO_REMOVE_LOCK)).

Calling **IoAcquireRemoveLockEx** is not recommended. Please see this topic: https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/ioacquireremovelockex

Let us know if you have other questions,'

Regards,

Page Writer

**Comment by GabeSJones** [comment]
I'm confused.  Calling IoAcquireRemoveLockEx is not recommended, but calling IoAcquireRemoveLock and checking its return value is common practice for WDM drivers.  You need look no further than Microsoft's own WDK samples for a number of examples:

https://github.com/Microsoft/Windows-driver-samples/search?q=ioacquireremovelock&unscoped_q=ioacquireremovelock

**Comment by jmc5113** [comment]
Why is this thread closed if the document still says that the return type for IoAcquireRemoveLock is void?

**Comment by tedhudek** [comment]
See my comment in #662, which is the open issue still tracking this.

**Comment by tedhudek** [comment]
All is addressed in #662
