### ISSUE TITLE
Hyperlinks on enumerations

### ISSUE THREAD

**Issue by darugeri** [MicrosoftDocs/windows-driver-docs-ddi#1030]
I think it might be good to put hyperlinks on the following enumerations:

- DEVICE_POWER_STATE
- SYSTEM_POWER_STATE
- PC_EXIT_LATENCY

I see other pages with similar hyperlinks, so it could be consistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a40172b-8e60-6a8e-a05c-161898a0be5a
* Version Independent ID: c9bf6e91-8122-299f-7886-2c34fd806a02
* Content: [IAdapterPowerManagement3::PowerChangeState3 (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nf-portcls-iadapterpowermanagement3-powerchangestate3#feedback)
* Content Source: [wdk-ddi-src/content/portcls/nf-portcls-iadapterpowermanagement3-powerchangestate3.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nf-portcls-iadapterpowermanagement3-powerchangestate3.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@darugeri - Links have been added. As I mentioned, you are always welcome to do a PR from the topic on any improvements that you see.
