### ISSUE TITLE
Is the first `NtSetQuotaInformationFile` wrong?  Shouble be `NtQueryQuotaInformationFile` ??

### ISSUE THREAD

**Issue by enuuicode** [MicrosoftDocs/windows-driver-docs-ddi#1035]
[Enter feedback here]

> System service parameters for NtSetQuotaInformationFile.
> 
> Parameters.QueryQuota.Length
> 
> Parameters.QueryQuota.StartSid
> 
> Parameters.QueryQuota.SidList
> 
> Parameters.QueryQuota.SidListLength
> 
> Parameters.SetQuota
> 
> System service parameters for NtSetQuotaInformationFile.
> 
> Parameters.SetQuota.Length
> 
> Parameters.QueryDeviceRelations
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b1c00f-1701-5665-cdeb-6120305abc72
* Version Independent ID: 2f6bf8f4-3e19-e4e1-36f4-fcaa8e40c467
* Content: [_IO_STACK_LOCATION (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_io_stack_location)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_io_stack_location.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_io_stack_location.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the eagle eye @enuuicode - this is now fixed
