### ISSUE TITLE
Is parameter 2 really required if you're just trying to get the size?

### ISSUE THREAD

**Issue by snowkoan** [MicrosoftDocs/windows-driver-docs-ddi#1036]
Pendator here.

VolumeGuidName
[out] Pointer to a caller-allocated UNICODE_STRING structure that receives the volume's GUID name. This parameter is required and cannot be NULL.

This is clear but I'm wondering if it's accurate if you're just trying to obtain the size. I passed NULL and it worked fine. I would expect that it behaves similarly to the FltGetVolumeName function, which allows NULL when obtaining the size.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9daaf22a-e7c6-4cc8-88e4-58f56d2c325b
* Version Independent ID: 2848df9d-7d1f-67d5-4221-7c740f578c00
* Content: [FltGetVolumeGuidName function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetvolumeguidname)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetvolumeguidname.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetvolumeguidname.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this issue, @snowkoan. You're correct that the behavior is similar to FltGetVolumeName when trying to obtain the needed size. I've updated the page accordingly.
