### ISSUE TITLE
incorrect links

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#104]
The links for PORT_CONFIGURATION_INFORMATION should point to the page describing that structure in storport.h. The current links do not contain the proper information for this function HwStorFindAdapter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4615741-cc9f-7fe9-5f0b-8c376dfe2503
* Version Independent ID: 38f2a792-6fdc-c25c-375c-f761df914c26
* Content: [HW_FIND_ADAPTER](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/storport/nc-storport-hw_find_adapter)
* Content Source: [wdk-ddi-src/content/storport/nc-storport-hw_find_adapter.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/storport/nc-storport-hw_find_adapter.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks @BenWestbrook 
Fixed in PR #110
