### ISSUE TITLE
More info on the flags parameter

### ISSUE THREAD

**Issue by AzAgarampur** [MicrosoftDocs/windows-driver-docs-ddi#1040]
The new flags parameter has a list of values, but there seem to be no documentation on what these values actually do. Can this information be added onto this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9897ce0b-9630-a00c-3fbe-425ec7f12ee6
* Version Independent ID: 27c22def-632e-f2d4-3d50-1f8023683373
* Content: [MmSecureVirtualMemoryEx function - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-mmsecurevirtualmemoryex)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-mmsecurevirtualmemoryex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-mmsecurevirtualmemoryex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hello @AzAgarampur 

Thank you for the feedback!  I just pushed an update to the page in question - should be live in 30 min.

In the meantime, here is the table I added on the flags:

|Flag|Description|
|--- |--- |
|**MM_SECURE_EXCLUSIVE**|Securing only succeeds if there are no other secures already pinned anywhere onto the VAD in question.|
|**MM_SECURE_NO_CHANGE**|Once applied, no protection changes are allowed for the supplied virtual address region.  The region can still be deleted if the process is exiting.|
|**MM_SECURE_USER_MODE_ONLY**|The protection specified by this securing will only be applied to subsequent calls from user mode that are trying to change the protection (kernel mode callers will bypass this securing).|
|**MM_SECURE_NO_INHERIT**|If the process is cloned, then unlike the parent process, VAD of the child process will not be secured.|
