### ISSUE TITLE
Unnecessary Cautions

### ISSUE THREAD

**Issue by timrprobocom** [MicrosoftDocs/windows-driver-docs-ddi#1042]
Each of the tables on bInterval has a note saying that values > 255 are prohibited by the USB specification.  This field is 8 bits wide (hence the name "bInterval"); it is impossible to provide a value > 255.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cecaa4ed-4d40-c9c6-7e74-338882430bb1
* Version Independent ID: af0f300d-0179-73e0-02ea-f1c73e64bafa
* Content: [_USB_ENDPOINT_DESCRIPTOR (usbspec.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/usbspec/ns-usbspec-_usb_endpoint_descriptor)
* Content Source: [wdk-ddi-src/content/usbspec/ns-usbspec-_usb_endpoint_descriptor.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbspec/ns-usbspec-_usb_endpoint_descriptor.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by billlattimer** [comment]
@timrprobocom thank you for helping to improve our docs! Although the rationale might appear redundant, it provides the rationale for the datatype, i.e. that it's bound by the standards specification and can't be extended by Microsoft or by the developer.
