### ISSUE TITLE
Incorrect description of PriorityAssignmentTable member of struct NDIS_QOS_PARAMETERS

### ISSUE THREAD

**Issue by MrDavid949** [MicrosoftDocs/windows-driver-docs-ddi#1044]
[Enter feedback here]
On this page:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_qos_parameters

This text is wrong:
PriorityAssignmentTable

An array of UCHAR elements that specifies an IEEE 802.1p priority level for each traffic class. The PriorityAssignmentTable array is indexed by the 802.1p priority level (0–7).

The correct text should be:
PriorityAssignmentTable

An array of UCHAR elements where each element represents the traffic class associated with an IEEE 802.1p priority level. The PriorityAssignmentTable array is indexed by the 802.1p priority level (0–7).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18a2491-1114-cb60-b438-8b235ef9733f
* Version Independent ID: 3cd65f6b-4f79-fde8-977e-045f8c799473
* Content: [_NDIS_QOS_PARAMETERS (ntddndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_qos_parameters)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_qos_parameters.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_qos_parameters.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks for opening this issue @MrDavid949. I agree that your suggested wording is much clearer than the original, and I've updated this page. Thanks again.
