### ISSUE TITLE
NVMe ZNS api is not described

### ISSUE THREAD

**Issue by tim-oleksii** [MicrosoftDocs/windows-driver-docs-ddi#1045]
Hello,

Lee Prewitt presented ZNS in OCP summit, there are news about ZNS usage for Azure.

is it possible to describe NVMe ZNS API? I cannot find any syscalls to work with drive from user space.

Thanks!

**Comment by lorihollasch** [comment]
Thanks for asking, @tim-oleksii . Currently the ZNS APIs are reserved for internal use only. If ZNS support is enabled in client/server in the future, we will definitely document them.
