### ISSUE TITLE
Flags member of struct NDIS_QOS_PARAMETERS is not defined

### ISSUE THREAD

**Issue by MrDavid949** [MicrosoftDocs/windows-driver-docs-ddi#1046]
On this page:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_qos_parameters

The description for the Flags member of the structure has a link named "Overview of the Flags Member".  This link goes to a generic page and there is no useful description anywhere of what NDIS_QOS_PARAMETERS::Flags should contain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18a2491-1114-cb60-b438-8b235ef9733f
* Version Independent ID: 3cd65f6b-4f79-fde8-977e-045f8c799473
* Content: [_NDIS_QOS_PARAMETERS (ntddndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_qos_parameters)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_qos_parameters.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_qos_parameters.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks @MrDavid949. The link should go to the section "Overview of the Flags Member" at the bottom of the page (not a new page). I'll close this issue once the fix is live on the site.
