### ISSUE TITLE
Macro actually returns access token

### ISSUE THREAD

**Issue by PisarevSergey** [MicrosoftDocs/windows-driver-docs-ddi#1048]
It is stated that this macro returns nothing while it is actually returns access token

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0160d3bf-9971-cfd1-9901-5774fc783590
* Version Independent ID: 177909bc-93d1-2933-a3c8-56238c1737dd
* Content: [SeQuerySubjectContextToken macro (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-sequerysubjectcontexttoken)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-sequerysubjectcontexttoken.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-sequerysubjectcontexttoken.md)
* Product: **windows-hardware**,
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @PisarevSergey . I've added the missing info in 22ab87b9, which will go live soon.
