### ISSUE TITLE
Link to another reference page

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs-ddi#1050]
Please add a link to https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-selective-suspend from this page. It has relevant information to this IOCTL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2c8ab1-4dbb-502d-e333-cfa240acfcf5
* Version Independent ID: 82564412-db53-2e2f-d1c6-e7a535c1d626
* Content: [IOCTL_INTERNAL_USB_SUBMIT_IDLE_NOTIFICATION (usbioctl.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/usbioctl/ni-usbioctl-ioctl_internal_usb_submit_idle_notification)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_submit_idle_notification.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_submit_idle_notification.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Thanks @Shyamal-V I just pushed this fix.  Appreciate the suggestion.
