### ISSUE TITLE
Conflicting docs for using MmGetSystemAddressForMdlSafe on partial mdl

### ISSUE THREAD

**Issue by jcbottorff-ampere** [MicrosoftDocs/windows-driver-docs-ddi#1051]
The docs for IoBuildPartialMdl  say "A driver can map a partial MDL into the system address space by using the MmGetSystemAddressForMdlSafe macro". The docs at https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/using-mdls say "Note that when you build a partial MDL by using the IoBuildPartialMdl routine, the caller should use MmGetMdlVirtualAddress instead of the MmGetSystemAddressForMdlSafe routine when determining the virtual address to pass in". 

Docs currently say both do and don't use MmGetSystemAddressForMdlSafe on partial mdls. Based on some current debugging, not using MmGetSystemAddressForMdlSafe on a partial mdl (MDL_PARTIAL flags set) seems to be correct. As a driver passing an mdl from another driver may not know if it's a partial mdl or not, it seem like drivers may often have to test the flag to determine the correct function to call. I'm debugging an I2C driver that may get passed requests with mdl's from either the ipmi driver or the acpi region mapper, and one caller uses partial mdls and the other doesn't.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecbb6900-b965-1808-9a2f-ad9b00a8bbca
* Version Independent ID: e73a8962-722e-8b0b-608c-25b4d38c757e
* Content: [IoBuildPartialMdl function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iobuildpartialmdl)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iobuildpartialmdl.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iobuildpartialmdl.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback @jcbottorff-ampere.  Great points. See the two PRs above that I just merged with related changes to the docs.  These changes should appear on the live site (docs.microsoft.com) within an hour.
