### ISSUE TITLE
WDF object delete - timer deadlock

### ISSUE THREAD

**Issue by casubram** [MicrosoftDocs/windows-driver-docs-ddi#1053]
Hi, I am a developer at Microsoft and I recently ran into some difficulty with this function. The scenario I was testing was just deleting a WDF timer object from its own (passive level) callback. This consistently resulted in a deadlock, which I was not expecting just from having read this documentation. 

I spent some time trying to find the root cause of the issue, and I found some statements in the WDF logs along the lines of "Warning: deleting a timer object from its own callback will always result in deadlock".  I was not looking at [this documentation ](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdftimer/nc-wdftimer-evt_wdf_timer) at the time, which does warn about that issue. 

I think it might be useful to also include a mention of that in the WdfObjectDelete docs as well. That way developers who, for whatever reason, did not think to look at the timer callback documentation will be aware that deadlock will occur if you try to delete a timer from its own passive callback. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 862de38f-205f-7c67-1021-8596ad490f70
* Version Independent ID: f1b0ef84-97c7-54b4-327d-ce8fcb7c7d3d
* Content: [WdfObjectDelete function (wdfobject.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfobject/nf-wdfobject-wdfobjectdelete)
* Content Source: [wdk-ddi-src/content/wdfobject/nf-wdfobject-wdfobjectdelete.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfobject/nf-wdfobject-wdfobjectdelete.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @casubram for letting us know.  I added a Note to the callback page -- https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdftimer/nc-wdftimer-evt_wdf_timer#remarks -- and I linked to it from https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfobject/nf-wdfobject-wdfobjectdelete#remarks.

Appreciate the assist!
