### ISSUE TITLE
Unrelated text?

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#1057]
What is the meaning of "only the last component of the path can be changed"?
It appears as if this was copied from a REG_RENAME_KEY_INFORMATION page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81d861a0-89c8-5a4a-244a-1486f7ab16d2
* Version Independent ID: b3bcbe75-3c44-fb32-d33e-423f05ce56bd
* Content: [_REG_SAVE_KEY_INFORMATION (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_reg_save_key_information)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_reg_save_key_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_reg_save_key_information.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Right you are @alfaunits, thanks for the heads-up.  I just pushed the change - should appear on the live site within the hour.
