### ISSUE TITLE
Copy/paste error?

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#1058]
The following texts:
"only the last component of the path can be changed" (in remarks)
and
"A pointer to a registry key object for the key whose name is about to be changed." (in parameter description)
seem to be a copy paste from a RENAME_KEY page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db90a137-e2f7-fcfd-6452-2e2c8d8ddb41
* Version Independent ID: 05445010-d842-436a-823a-ce55bedb2149
* Content: [_REG_RESTORE_KEY_INFORMATION (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_reg_restore_key_information)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_reg_restore_key_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_reg_restore_key_information.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Again, appreciate the eagle eye, @alfaunits.  This one will also be live momentarily.
