### ISSUE TITLE
Incorrect argument information for generic access rights

### ISSUE THREAD

**Issue by D4stiny** [MicrosoftDocs/windows-driver-docs-ddi#1061]
For several different functions on MSDN, the "Generic access rights" such as GENERIC_READ, GENERIC_WRITE, and GENERIC_EXECUTE claim that the "set of specific access rights" includes the SYNCHRONIZE right. This is not true.

For example, the long representation of GENERIC_READ is `0x80000000L` and SYNCHRONIZE is `0x00100000L`. If you take the bitwise AND of these two rights, you will see that GENERIC_READ does not contain SYNCHRONIZE.

I stumbled upon this issue while attempting to open a file via NtCreateFile. The operation was failing because I was specifying the FILE_SYNCHRONOUS_IO_NONALERT create option, which requires the SYNCHRONIZE access right, however, I kept getting STATUS_INVALID_PARAMETER because I was passing only GENERIC_READ (which is supposed to have the SYNCHRONIZE flag according to the documentation).

Additional pages where this incorrect information is present can be found below (from a quick Google search):
[ZwCreateFile](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwcreatefile)
[IoCreateFileSpecifyDeviceObjectHint](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-iocreatefilespecifydeviceobjecthint)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f1f8884-1882-1dd4-df7f-2b4456869131
* Version Independent ID: 7552855b-d66b-832a-54c0-dbb2b0ace0be
* Content: [NtCreateFile function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntcreatefile)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ntcreatefile.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ntcreatefile.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@D4stiny , thanks for filing this issue. The information on this page was technically accurate, but I've edited it to add clarity about generic, standard and specific rights, and their values (the mapping of generic rights to specific does not mean that their bitwise value is equal). I also added a NOTE saying that some CreateOptions flags require that certain DesiredAccess flags be set. One such instance is that SYNCHRONIZE must be set in DesiredAccess when CreateOptions is FILE_SYNCHRONOUS_IO_ALERT or FILE_SYNCHRONOUS_IO_NONALERT.
