### ISSUE TITLE
CallbackData parameter is not marked as optional

### ISSUE THREAD

**Issue by PisarevSergey** [MicrosoftDocs/windows-driver-docs-ddi#1063]
It is not stated clear if CallbackData can be null.

I don’t know if this is on purpose, however as I can see from disassembly this function checks callbackdata for nullptr before calling FsRtlCancellableWaitForMultipleObjects internally. It would be great to know if this is expected behavior or just current implementation detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d261d360-abec-7694-da3c-b9af4b76f40f
* Version Independent ID: 4d182644-f680-e639-066d-e53ec7d4a0b5
* Content: [FltCancellableWaitForMultipleObjects function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltcancellablewaitformultipleobjects)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcancellablewaitformultipleobjects.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcancellablewaitformultipleobjects.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@PisarevSergey , great question. I've consulted with the feature team who this is expected behavior akin to [FltCancellableWaitForSingleObject](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltcancellablewaitforsingleobject). I've updated the page with this clarification.
