### ISSUE TITLE
Behavior of PshedRegisterPlugin changes when using WDK 10.0.18362.1 or later

### ISSUE THREAD

**Issue by jesweare** [MicrosoftDocs/windows-driver-docs-ddi#1067]
The **Parameters** section of `PshedRegisterPlugin` has the following description.  
>`Packet`
>[in, out] A pointer to an initialized WHEA_PSHED_PLUGIN_REGISTRATION_PACKET structure that describes the PSHED plug-in's registration information.

However, WHEA_PSHED_PLUGIN_REGISTRATION_PACKET is defined as [WHEA_PSHED_PLUGIN_REGISTRATION_PACKET_V2](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/ns-ntddk-whea_pshed_plugin_registration_packet_v2) starting with WDK 10 version 18362 (10.0.18362.1), and the conditions of `PshedRegisterPlugin` changes when the V2 packet is used. Specifically, V2 packets are not expected to register Error Source Discovery callbacks that are exemplified in the document [Participating in Error Source Discovery](https://docs.microsoft.com/en-us/windows-hardware/drivers/whea/participating-in-error-source-discovery).

Adding the likes of the following passage to the **Remarks** section would help developers understand the implied changes:
>When supplying the API with [WHEA_PSHED_PLUGIN_REGISTRATION_PACKET_V2](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/ns-ntddk-whea_pshed_plugin_registration_packet_v2) in the `Packet` parameter, do not register [Error Source Discovery](https://docs.microsoft.com/en-us/windows-hardware/drivers/whea/error-source-discovery) callbacks in the packet information.  Doing so will cause the API to return with `STATUS_INVALID_PARAMETER`.  If supplying Error Source Discovery callbacks is necessary, please use the [WHEA_PSHED_PLUGIN_REGISTRATION_PACKET_V1](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/ns-ntddk-whea_pshed_plugin_registration_packet_v1) structure for the `Packet` parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6231dadb-57d4-b147-1a6a-6b57a387428c
* Version Independent ID: f892f60a-4900-f84d-3411-496298541566
* Content: [PshedRegisterPlugin function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-pshedregisterplugin)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-pshedregisterplugin.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-pshedregisterplugin.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for raising the issue @jesweare
