### ISSUE TITLE
incorrect structure type BALANCED_LINKS

### ISSUE THREAD

**Issue by PisarevSergey** [MicrosoftDocs/windows-driver-docs-ddi#1069]
BALANCED_LINKS used while this is nonexistent type.
It is actually should be RTL_BALANCED_LINKS. 

fix: BALANCED_LINKS should be replaced with RTL_BALANCED_LINKS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6732fb0-1298-6690-f36f-d3b737f23b19
* Version Independent ID: 9514456b-f6a0-72b7-a756-3d6f5eddda15
* Content: [RtlInsertElementGenericTableAvl function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-rtlinsertelementgenerictableavl)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-rtlinsertelementgenerictableavl.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-rtlinsertelementgenerictableavl.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by mhopkins-msft** [comment]
Hi @PisarevSergey,

Thank you for reporting this. The topic is updated.

 ~ *Mark*

#please-close
