### ISSUE TITLE
CmUnRegisterCallback documentation error.

### ISSUE THREAD

**Issue by neitsa** [MicrosoftDocs/windows-driver-docs-ddi#1070]
The note in the [documentation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-cmunregistercallback) for `CmUnRegisterCallback ` reads:

> A driver must not call CmRegisterCallback from its implementation of the RegistryCallback routine. That call will result in a deadlock.

I think it should read:

```
A driver must not call **CmUnRegisterCallback** from its implementation [...]
```

I think you're not supposed to unregister the callback from the callback itself (I don't see the point in calling `CmRegisterCallback ` from the callback itself, since you already have called it somewhere else).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff97c6c-186c-3efa-1990-7683c667088d
* Version Independent ID: ae94fa15-1b0e-ed93-6859-1f24932c1bd5
* Content: [CmUnRegisterCallback function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-cmunregistercallback?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(WDM%252FCmUnRegisterCallback);k(CmUnRegisterCallback);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-cmunregistercallback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-cmunregistercallback.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the sharp eye @neitsa - you are correct!  I made the change in the commit above - should reach the live site within 30 minutes or so.
