### ISSUE TITLE
PsSetCreateProcessNotifyRoutineEx: callback removal note.

### ISSUE THREAD

**Issue by neitsa** [MicrosoftDocs/windows-driver-docs-ddi#1073]
I think it should be mentioned in the documentation that the callback can not be removed from itself; that is, calling `PsSetCreateProcessNotifyRoutineEx(OnProcessNotify, TRUE);`  from `OnProcessNotify` itself (or, obviously, any of its descendant functions in its call graph).

As stupid as it sounds, I stumbled upon that behavior from a process monitoring code. The code (driver) started monitoring a specific process and all its children. When the last process in the tree exited, the driver code was removing the callback from itself.

It actually "works" (the callback is removed), but has the side effect of "zombifying" that process (it just sit there doing nothing and can't be killed afterward). 

Note that other "hooking" callback functions (e.g. the registry one, see [`CmUnRegisterCallback`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-cmunregistercallback)) documents the fact that you can't remove the callback from the callback function itself.

I guess this should also apply to [`PsSetCreateProcessNotifyRoutine`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-pssetcreateprocessnotifyroutine).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9488c316-657f-4b4e-171a-811958d1c0fb
* Version Independent ID: 4ef55be1-52e0-e587-1cae-897cbb6228b4
* Content: [PsSetCreateProcessNotifyRoutineEx function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-pssetcreateprocessnotifyroutineex)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-pssetcreateprocessnotifyroutineex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-pssetcreateprocessnotifyroutineex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks again @neitsa, that's a great find. I updated the docs in the commit above.  The fix should appear on the live site within 30 minutes or so.
