### ISSUE TITLE
Link to KeDeregisterBugCheckReasonCallback actually links to KeDeregisterBugCheckCallback

### ISSUE THREAD

**Issue by jcbottorff-ampere** [MicrosoftDocs/windows-driver-docs-ddi#1074]
In the text that says "Drivers can use the KeDeregisterBugCheckReasonCallback routine to remove the bug check callback registration". The hyperlink for KeDeregisterBugCheckReasonCallback  actually goes to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kederegisterbugcheckcallback which is NOT the correct function to deregister a bugcheck reason callback. The should link to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kederegisterbugcheckreasoncallback. This may cause a developer to use the wrong function. The system can then crash if an unloaded driver is reloaded, giving the bugcheck "SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD (d4)
A driver unloaded without cancelling lookaside lists, DPCs, worker threads, etc."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 831ec76c-5bf3-15ef-1ef9-229e9521816b
* Version Independent ID: e69d0496-53f6-abc4-b1ab-84cf20051d8a
* Content: [KeRegisterBugCheckReasonCallback function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-keregisterbugcheckreasoncallback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-keregisterbugcheckreasoncallback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-keregisterbugcheckreasoncallback.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by DOMARS** [comment]
@jcbottorff-ampere - Thanks for filing this issue, as this was an error in the docs. I updated the topic, so that the link goes to the correct target - KeDeregisterBugCheckReasonCallback. Thanks again for filing this issue, and good luck with your work on bugchecks.
