### ISSUE TITLE
No documentation on how to use IDebugAdvanced::Request with DEBUG_REQUEST_GET_TEXT_COMPLETIONS_ANSI parameter

### ISSUE THREAD

**Issue by maximebl** [MicrosoftDocs/windows-driver-docs-ddi#1081]
Is it possible to get some information on how to use this method in order to get auto-completion results from the debug engine?  When the user types `.ec`, windbg will auto-complete to `.echo`. From what I gathered from the docs, this is the function you need to use and the usage would look something like this:

```
DEBUG_GET_TEXT_COMPLETIONS_IN in;
in.Flags = 0;
in.MatchCountLimit = 0;

DEBUG_GET_TEXT_COMPLETIONS_OUT out;
out.Flags = DEBUG_GET_TEXT_COMPLETIONS_IS_DOT_COMMAND;
out.MatchCount = 0;
out.ReplaceIndex = 0;

ULONG outsize = 0;
hr = advanced->Request(DEBUG_REQUEST_GET_TEXT_COMPLETIONS_ANSI,
          (void *)&in, sizeof(DEBUG_GET_TEXT_COMPLETIONS_IN),
          (void *)&out, sizeof(DEBUG_GET_TEXT_COMPLETIONS_OUT), &outsize);
```
This is clearly wrong, but I'm just guessing here because there's no information about how to use `DEBUG_REQUEST_GET_TEXT_COMPLETIONS_ANSI` with `IDebugAdvanced::Request`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4846673e-3e64-d756-0dca-d1090067e308
* Version Independent ID: d8e81071-57ff-b88e-2adc-d0499bd73fe8
* Content: [IDebugAdvanced3::Request (dbgeng.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgeng/nf-dbgeng-idebugadvanced3-request?source=docs)
* Content Source: [wdk-ddi-src/content/dbgeng/nf-dbgeng-idebugadvanced3-request.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dbgeng/nf-dbgeng-idebugadvanced3-request.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@maximebl - I'm not aware of how to use the dbgeng for auto complete on commands, but here are a few ideas that may help in your investigation. Of course you would want to look at which elements IDebugAdvanced::Request use pointers and reflect that in your code.

If you have not already, I would search and then post on the OSR forum. I found this thread that does mention  IDebugAdvanced::Request, (along with a number of other things).
https://community.osr.com/discussion/211412

You could look at the code in engextcpp.h, it wraps dbgeng in a number of different ways with multiple overloads for input and output.
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/engextcpp/nf-engextcpp-extremotetyped-set(pcstr_ulong64_bool_pulong64_pcstr)

If you are going to extensive new work, we would recommend transitioning to the new debugger model. Although to be clear, I'm not sure if the command line buffer is available in the debugger model.

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/data-model-cpp-overview
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgmodel/

There are samples here.
https://github.com/Microsoft/WinDbg-Samples/tree/master/DataModelHelloWorld

And there is also a JavaScript interface to the object model.
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/javascript-debugger-scripting

Good luck with your debugger automation work.
