### ISSUE TITLE
Document is missing

### ISSUE THREAD

**Issue by SJKU** [MicrosoftDocs/windows-driver-docs-ddi#1087]
"In this case, the callout should set the actionType member of the FWPS_CLASSIFY_OUT0 structure pointed to by the classifyOut parameter of the classifyFn function to one of the following values."

The above paragraph mentions a value to be set from a list of values. But the list is missing. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7c5e2f-5d4e-b418-e0eb-12519b90aa63
* Version Independent ID: fe57b077-aba7-b118-db1d-af146566bbb7
* Content: [FwpsQueryPacketInjectionState0 function (fwpsk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nf-fwpsk-fwpsquerypacketinjectionstate0)
* Content Source: [wdk-ddi-src/content/fwpsk/nf-fwpsk-fwpsquerypacketinjectionstate0.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fwpsk/nf-fwpsk-fwpsquerypacketinjectionstate0.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks @SJKU for letting us know about the missing text. The actionType member in this case should be either FWP_ACTION_CONTINUE or FWP_ACTION_PERMIT.  This allows the packet to proceed to the next callout. This fix will be published on the live page later today.
