### ISSUE TITLE
You can flush, or flush and purge but not just purge (I think)

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1091]
Hey Lori,

All of this page is written in terms of it being possible to flush (only) , to purge (only) or to flush *and* purge.

However there is only one flag present which allows you to flush (only).  I don't see a way to purge (only).

I also don't see an easy way to change the language to indicate this state of affairs (but I'm a coder, not a writer).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b08506-a8aa-15d0-f0e7-c14a01807b3d
* Version Independent ID: d974f3cc-8dd0-e249-fdd5-1f70b1aefdae
* Content: [CcCoherencyFlushAndPurgeCache function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-cccoherencyflushandpurgecache)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-cccoherencyflushandpurgecache.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-cccoherencyflushandpurgecache.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hey @rodwiddowson , I am finally getting around to knocking off some GitHub issues, including this one. Thanks for submitting this - appreciate your diligence and expertise to make the docs correct and complete!
