### ISSUE TITLE
Memory barriers should be explicitly called out on this page and others like it

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs-ddi#1092]
WRITE_REGISTER_* and READ_REGISTER_* include memory fencing.  These pages should call that out and explain exactly what is and is not guaranteed by that memory fencing.  For instance, the fencing guarantees that the reads and writes will be observed in the order that they're written in the code.  It may not guarantee that a hardware device has observed a write before the next instructions are executed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a3cf66e-5af1-20f8-6e42-e2a518e048e4
* Version Independent ID: ec600bb1-e32f-de88-aa77-0fba121b7549
* Content: [WRITE_REGISTER_ULONG function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-write_register_ulong?source=docs)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-write_register_ulong.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-write_register_ulong.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hey @jakeoshins, thanks for the feedback.  Any chance you'd want to take a shot at a PR for this?

**Comment by jakeoshins** [comment]
Ted, I went to this page because I wanted to know the answer.  I ended up having to read the kernel source to truly satisfy myself.  I don’t have time to figure out a pull request for this.  I suggest you ask Jason Wohlgemuth or whomever he suggests.

**Comment by tedhudek** [comment]
Thanks Jake - the update is now live.  See for example:

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-write_register_ulong
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-read_register_buffer_ulong
