### ISSUE TITLE
UDP RSC feature is not documented

### ISSUE THREAD

**Issue by ybendito** [MicrosoftDocs/windows-driver-docs-ddi#1093]
[Enter feedback here]
UdpRecvSegCoalesceOffloadInfo is defined and even respective NDIS_UDP_RSC_OFFLOAD_NET_BUFFER_LIST_INFO structure is defined in the ndis.h
But the documentation does not explain them at all and it is completely unclear how to control this feature.
Existing documentation about RSC just states the RSC does not support UDP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f1b3a8-4d59-d444-dd69-f7a680a8070f
* Version Independent ID: 71b37fe3-074a-6a83-0869-2284e248426d
* Content: [_NDIS_NET_BUFFER_LIST_INFO (ndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/ne-ndis-_ndis_net_buffer_list_info)
* Content Source: [wdk-ddi-src/content/ndis/ne-ndis-_ndis_net_buffer_list_info.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/ne-ndis-_ndis_net_buffer_list_info.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks @ybendito for opening this issue. UdpRecvSegCoalesceOffloadInfo is not an IHV feature, and this is why it is not documented. We've updated the UdpRecvSegCoalesceOffloadInfo element description on [NDIS_NET_BUFFER_LIST_INFO](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/nblinfo/ne-nblinfo-ndis_net_buffer_list_info) to: Reserved for protocol driver use. Please open another issue if you have further questions.
