### ISSUE TITLE
D3DSHADER_PARAM_REGISTER_TYPE are without explicit initializers

### ISSUE THREAD

**Issue by lanyizi** [MicrosoftDocs/windows-driver-docs-ddi#1101]
Currently on Microsoft's documentation, `D3DSHADER_PARAM_REGISTER_TYPE` has no explicit initializers. This will let people assume that values of the enum would be defined in the "default" way, like
```c
typedef enum _D3DSHADER_PARAM_REGISTER_TYPE {
  D3DSPR_TEMP    /* = 0 */,
  D3DSPR_INPUT   /* = 1 */,
  D3DSPR_CONST   /* = 2 */,
  D3DSPR_ADDR    /* = 3 */,
  D3DSPR_TEXTURE /* = 4 */,
  // ...
};
```
But that's **not** true. For example, `D3DSPR_TEXTURE` is not `4`, but it has the same value as `D3DSPR_ADDR`, which is `3`.
This can be verified in any `d3d9types.h` header file, for example there:
(These are the first d3d9 headers that appear on the google search)
https://github.com/kinvolk-archives/mesa/blob/master/include/D3D9/d3d9types.h
https://github.com/apitrace/dxsdk/blob/master/Include/d3d9types.h

Probably there are also other `enum`s inside `d3d9types.h` with the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f47c509-f813-91aa-dcf6-efeaaafd9ed5
* Version Independent ID: c9552379-8df0-1434-c293-1712e4d452fe
* Content: [_D3DSHADER_PARAM_REGISTER_TYPE (d3d9types.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d9types/ne-d3d9types-_d3dshader_param_register_type)
* Content Source: [wdk-ddi-src/content/d3d9types/ne-d3d9types-_d3dshader_param_register_type.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3d9types/ne-d3d9types-_d3dshader_param_register_type.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@lanyizi , thanks for taking the time to report this issue. We agree that the enum syntax block on the refpage should match the header file to avoid confusion. I'm closing this issue because there is an in-progress internal work item tracking this issue. Our tool development team is expected to complete this feature by July 2021 - stay tuned!
