### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by darugeri** [MicrosoftDocs/windows-driver-docs-ddi#1108]
The link for the methods (below "...has these types of members") is wrong: it redirects to the main page for MS Docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c1f6e5-0b8a-00ef-08ad-1df84d4dd7de
* Version Independent ID: f32997f8-34b7-34a1-4a1b-6cab827738fb
* Content: [IMiniportAudioEngineNode (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nn-portcls-iminiportaudioenginenode#feedback)
* Content Source: [wdk-ddi-src/content/portcls/nn-portcls-iminiportaudioenginenode.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nn-portcls-iminiportaudioenginenode.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@darugeri - Thanks for this issue. I found many other of these blank links that end up going to docs.microsoft.com. They link is removed here, as the methods are listed directly below, and we are working on the rest of the docs. So thanks for pointing this out, as we found a class of a problem we are now working to fix across the docs.
