### ISSUE TITLE
win

### ISSUE THREAD

**Issue by Arman7717** [MicrosoftDocs/windows-driver-docs-ddi#1112]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df3f705d-6ea1-2ca1-fadc-08fbc80582da
* Version Independent ID: c64cc08e-d150-1a7d-30f5-8a81d10c5b99
* Content: [NDIS_OBJECT_HEADER - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/objectheader/ns-objectheader-ndis_object_header)
* Content Source: [wdk-ddi-src/content/objectheader/ns-objectheader-ndis_object_header.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/objectheader/ns-objectheader-ndis_object_header.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @Arman7717, I'm closing this as no issue is described. Please open a new issue with a description if you have a comment or question. Thanks.
