### ISSUE TITLE
ReturnValue field in documentation is wrong. 

### ISSUE THREAD

**Issue by pankajbharti** [MicrosoftDocs/windows-driver-docs-ddi#1115]
[Enter feedback here]

Suggested the article says Return value is None, which is not correct. Remarks sesion and signature clearly say that the return value is NTSTATUS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b50201-ea38-2862-1ae4-b72dddf23d4c
* Version Independent ID: 72388b48-638a-6729-87cf-a35b2bdb303c
* Content: [IoAcquireRemoveLock macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-ioacquireremovelock?source=docs)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioacquireremovelock.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioacquireremovelock.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@pankajbharti, thanks for pointing out the missing return value information. The topics has been updated.
