### ISSUE TITLE
Image links in this page are not valid

### ISSUE THREAD

**Issue by peterwie** [MicrosoftDocs/windows-driver-docs-ddi#114]
There are two embedded diagrams in this routine description that aren't loading for me.  I assume the IMG links are stale.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba114bf3-7d30-f00a-cd5e-0ff01a2ae33b
* Version Independent ID: 38b1177c-f31f-bf6c-f24b-dfbf59ba22b0
* Content: [KeSetSystemGroupAffinityThread function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-kesetsystemgroupaffinitythread)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-kesetsystemgroupaffinitythread.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-kesetsystemgroupaffinitythread.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
@peterwie this is tracking in Internal Task 17622561, FYI

**Comment by EliotSeattle** [comment]
Resolve as fixed. The images are now appearing throughout the reference repo as they have in the conceptual repo.
