### ISSUE TITLE
POOL_FLAGS link is dead.

### ISSUE THREAD

**Issue by wurdack** [MicrosoftDocs/windows-driver-docs-ddi#1173]
Documentation for `Flags` parameter:

> Flags
> 
> A ULONG64-typed value specifying the type of pool memory along with required and optional attributes. Multiple flag values can be combined using bit-wise OR. See POOL_FLAGS for possible values.
> 

POOL_FLAGS link is 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4088c928-a19e-b223-3f6f-503e8c7f459e
* Version Independent ID: 9f39cccc-fcb4-7ea0-b915-95497671100b
* Content: [ExAllocatePool2 - Windows drivers](https://review.docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool2?branch=kernel-manganese)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/drivers/_git/wdk-ddi/?path=%2fwdk-ddi-src%2fcontent%2fwdm%2fnf-wdm-exallocatepool2.md&version=GBkernel-manganese&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/drivers/_git/wdk-ddi/?path=%2fwdk-ddi-src%2fcontent%2fwdm%2fnf-wdm-exallocatepool2.md&version=GBkernel-manganese&_a=contents)
* Product: **windows-hardware**
* Technology: **windows-devices**
* Git Login: **tedhudek**
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @wurdack.  The **Content** link in the **Document Details** block above goes to a page on the review site.  The live page is https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool2, from which the link to [POOL_FLAGS](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/pool_flags) works.

If you know how you reached the page on the review site, that might help us prevent others from landing there.
