### ISSUE TITLE
Better?

### ISSUE THREAD

**Issue by jhngrn** [MicrosoftDocs/windows-driver-docs-ddi#1176]
This page is ambiguous and leaves more questions than answers.

https://stackoverflow.com/questions/68966493/zwquerydirectoryfile-buffer-overflow
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d520f6-57db-69c7-c1ca-a118c1da31ef
* Version Independent ID: 20c66a6f-c2d1-7698-ae16-816a789d1a2b
* Content: [ZwQueryDirectoryFile function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-zwquerydirectoryfile#remarks)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-zwquerydirectoryfile.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-zwquerydirectoryfile.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@jhngrn , thanks for reaching out through this issue. A dev has answered your question on StackOverflow and I've updated this page to make the information you needed more obvious.
