### ISSUE TITLE
Clarify that WdfWorkItemFlush also waits on in-flight workitem callback to complete.

### ISSUE THREAD

**Issue by wurdack** [MicrosoftDocs/windows-driver-docs-ddi#1177]
> If your driver calls the WdfWorkItemFlush method, the method does not return until a system worker thread has removed the specified work item from the work-item queue and called the driver's EvtWorkItem callback function, and the EvtWorkItem callback function has subsequently returned after processing the work item.

It isn't clear from this description that this routine will wait for an _already running_ workitem callback to complete. I had two people read this and arrive at the same conclusion that they would not trust the routine to block until an existing callback completed. 

Inspection of the sources says that it will in fact block (which is good!), but the verbiage here leaves that open to an ambiguous interpretation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcdc552d-37d7-83b9-fcd8-7ef19a196900
* Version Independent ID: d0639391-8dd3-6158-e534-9e308aa2abd4
* Content: [WdfWorkItemFlush function (wdfworkitem.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfworkitem/nf-wdfworkitem-wdfworkitemflush)
* Content Source: [wdk-ddi-src/content/wdfworkitem/nf-wdfworkitem-wdfworkitemflush.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfworkitem/nf-wdfworkitem-wdfworkitemflush.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for reporting this, Richard.  See the fix in #1178 - should hit the live site in about half an hour.
