### ISSUE TITLE
Nit: Possible status list missing

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1180]
The text says
> Error status codes include the following:

And then there is no list.  My suggestion is that this be removed

Listing the error status you could get back is rarely useful.  The obvious exceptions (although none spring to mind) being when implication is not immediately obvious (in which case a better text might be "Any valid error status can be returned but the following are of note".  

The problem is that people then tend to assume that the list is absolutely and unchanging and then ask if they get back a non listed error...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82eeb3d9-c090-a5a2-51c0-b49133e488d9
* Version Independent ID: 0bd9625c-00a0-ca56-ceae-7bbccac8b330
* Content: [FsRtlProcessFileLock function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlprocessfilelock?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NTIFS%252FFsRtlProcessFileLock);k(FsRtlProcessFileLock);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlprocessfilelock.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlprocessfilelock.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @rodwiddowson - I removed the incomplete clause!
