### ISSUE TITLE
This macro returns a value

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1184]
Lori,
Sorry I didn't notice this when  input in the last fix (or maybe it changed as a result of the last fix?)

This macro returns a boolean (did it work)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c93a56b3-b784-779e-fd3a-460599f55bfc
* Version Independent ID: f4bd5c2a-0667-a128-b9c7-529580f79664
* Content: [FsRtlFastLock macro (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-fsrtlfastlock?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(STRUCTS%252F_ISOL_CONTEXT%253A%253AFsRtlFastLock);k(_ISOL_CONTEXT%253A%253AFsRtlFastLock);k(FsRtlFastLock);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlfastlock.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlfastlock.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson, thanks - I missed that too! Adding the return value to the syntax block required that I override the auto-generated one, so I went ahead and also added meaningful descriptors for each parameter per your original ask. :)
