### ISSUE TITLE
Typo: Uncorrectable -> Correctable for two links

### ISSUE THREAD

**Issue by hansberryjam** [MicrosoftDocs/windows-driver-docs-ddi#1194]
[Enter feedback here]
Both `CorrectableErrorStatus` and `CorrectableErrorMask` link to PCI_EXPRESS_UNCORRECTABLE_ERROR_STATUS.  However they should link to 
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_pci_express_correctable_error_status
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_pci_express_correctable_error_mask

Also their descriptions need matching to correctable

`CorrectableErrorStatus`

A PCI_EXPRESS_UNCORRECTABLE_ERROR_STATUS structure that describes the PCIe uncorrectable error status register of the PCIe AER capability structure.

`CorrectableErrorMask`

A PCI_EXPRESS_UNCORRECTABLE_ERROR_MASK structure that describes the PCIe uncorrectable error mask register of the PCIe AER capability structure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0343890-b06a-7560-07ca-7a2873ec70a2
* Version Independent ID: b8b3877a-bdd9-fdf7-830e-e601f1765d87
* Content: [_PCI_EXPRESS_AER_CAPABILITY (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_pci_express_aer_capability#feedback)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_pci_express_aer_capability.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_pci_express_aer_capability.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@hansberryjam, thanks for pointing out the incorrect links and text in the structure member descriptions.

The topic has been updated per your feedback.
