### ISSUE TITLE
DxgkDdiAddDevice with multiple devices serviced

### ISSUE THREAD

**Issue by pacampbe** [MicrosoftDocs/windows-driver-docs-ddi#1208]
What is the behavior of `DxgkDdiAddDevice`  for a driver which services multiple devices in regards to ordering and/or multi-threading? Is it possible that `DxgkDdiAddDevice` can be called multiple times simultaneously for each matching device? or will Windows iterate over one device at a time serially.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d16c0-e3f5-2a4e-50f0-194b8a86b08f
* Version Independent ID: 751d4d7d-f7ea-ca0a-9475-8b11fd01883d
* Content: [DXGKDDI_ADD_DEVICE (dispmprt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dispmprt/nc-dispmprt-dxgkddi_add_device)
* Content Source: [wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_add_device.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_add_device.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@pacampbe , I've updated this page to answer your questions - thanks!
