### ISSUE TITLE
Mention Ntdll.lib for Library

### ISSUE THREAD

**Issue by alarsen123** [MicrosoftDocs/windows-driver-docs-ddi#1211]
[Enter feedback here]
Library should specify Ntdll.lib for user mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf6e22db-2466-f984-6a07-690f68ddcc6f
* Version Independent ID: c3762308-5f74-60cf-2d02-782234d2a215
* Content: [RtlUnicodeStringToInteger function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlunicodestringtointeger)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtlunicodestringtointeger.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlunicodestringtointeger.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@alarsen123, thanks for pointing out the missing user mode library. The topic has been updated per your feedback and the changes should be live soon.
