### ISSUE TITLE
Double negatives are difficult to understand

### ISSUE THREAD

**Issue by camptatopenmars** [MicrosoftDocs/windows-driver-docs-ddi#1212]
The source handle cannot be opened with FILE_DIRECTORY_FILE.
The source handle cannot be a directory opened without either FILE_DIRECTORY_FILE or FILE_NON_DIRECTORY_FILE.

These two statements seem to contradict each other, the second statement makes use of a double negative to indicate that the source handle must be opened with one of FILE_DIRECTORY_FILE or FILE_NON_DIRECTORY_FILE which directly contradicts the first statement.

I _suspect_ these statements where intended to convey that for a stream rename, the source handle must be a FILE for the case of renaming a stream within a file, and must be a DIRECTORY for the case of renaming a stream within a directory.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458144c-41ea-41a8-be0b-a7e8a786105b
* Version Independent ID: 17c91e00-d2a1-8984-30b3-db44d430f0f4
* Content: [_FILE_RENAME_INFORMATION (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_rename_information)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_file_rename_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_file_rename_information.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@camptatopenmars , thanks for the issue - the double negative language _was_ confusing! I've updated the section on renaming NTFS data streams.
