### ISSUE TITLE
ndis_udp_segmentation_offload link is incorrect

### ISSUE THREAD

**Issue by sandilyabhagi** [MicrosoftDocs/windows-driver-docs-ddi#1213]
Currently the URL for NDIS_UDP_SEGMENTATION_OFFLOAD is set to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_offload and it needs to be changed to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_udp_segmentation_offload

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b23eb5-cf94-4dbe-dd3d-65228f6954d7
* Version Independent ID: 4013a778-05bf-9c9c-8af5-45b0282690df
* Content: [_NDIS_OFFLOAD (ntddndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_offload)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_offload.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_offload.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks very much @sandilyabhagi for letting us know. This link is now fixed on https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_offload.
