### ISSUE TITLE
This page says the structure is obsolete.  It's not.

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs-ddi#1217]
This page says that PCI_COMMON_CONFIG is obsolete because it's only used by HalGetBusData and variants.  This is flat-out wrong.  It's also used by GetBusData and SetBusData in BUS_INTERFACE_STANDARD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce542afa-f4b6-bebc-9eb4-190455b722a6
* Version Independent ID: f8462881-5ba9-6b4e-d667-ab74e5684399
* Content: [_PCI_COMMON_CONFIG (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_pci_common_config)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_pci_common_config.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_pci_common_config.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@jakeoshins, thanks for pointing out the incorrect text in this topic. The "obsolete" text has been removed.
