### ISSUE TITLE
Whether ISensorDriver interface supports Universal API

### ISSUE THREAD

**Issue by 99HHs** [MicrosoftDocs/windows-driver-docs-ddi#122]
Consult an expert
Whether ISensorDriver interface supports Universal API
thank
99HHs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db0a7822-7489-6117-d067-ab93585f4883
* Version Independent ID: 08f548f0-b786-e836-58d6-b15b0937045e
* Content: [ISensorDriver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/sensorsclassextension/nn-sensorsclassextension-isensordriver)
* Content Source: [wdk-ddi-src/content/sensorsclassextension/nn-sensorsclassextension-isensordriver.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/sensorsclassextension/nn-sensorsclassextension-isensordriver.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by JocelynBerrendonner** [comment]
Yes, drivers written through the ISensorDriver interface are useable by universal applications through the WinRT API. That said, there are some limitations:
- ISensorDriver based drivers only work on Windows Desktop (note that there are limitations on Windows Desktop as well: drivers do not work out of the box on Windows "N" versions for example)
- Newer sensor types (all sensors added in Windows 10) are *not* supported through the ISensorDriver
- ISensorDriver based drivers will be deprecated sometime in the future (no date yet)

Going forward, our recommendation is to use the Universal driver model for Windows 10: https://docs.microsoft.com/en-us/windows-hardware/drivers/sensors/converged-sensor-driver-model-for-windows-10

Best regards,
Jocelyn Berrendonner
