### ISSUE TITLE
cchDest shows wrong max

### ISSUE THREAD

**Issue by poweradminllc** [MicrosoftDocs/windows-driver-docs-ddi#1220]
After stepping through the code, it looks like the max value for cchDests is NTSTRSAFE_UNICODE_STRING_MAX_CCH and not NTSTRSAFE_MAX_CCH as shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf8d7cc-48b3-6ded-8972-91a7daafc911
* Version Independent ID: c20a9a40-537f-6660-af9c-ed95468958f6
* Content: [RtlStringCchCopyUnicodeString function (ntstrsafe.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntstrsafe/nf-ntstrsafe-rtlstringcchcopyunicodestring)
* Content Source: [wdk-ddi-src/content/ntstrsafe/nf-ntstrsafe-rtlstringcchcopyunicodestring.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntstrsafe/nf-ntstrsafe-rtlstringcchcopyunicodestring.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @poweradminllc thanks for the report - you are correct!  I've updated the doc source in f871692bc462c179307b31c1cf4d066239e3cb07 -- this should appear on the Docs site within 30 min.
