### ISSUE TITLE
FltCreateSectionForDataScan ObjectAttributes parameter is confusing.

### ISSUE THREAD

**Issue by camptatopenmars** [MicrosoftDocs/windows-driver-docs-ddi#1222]
The statement "[in, optional] ObjectAttributes

A pointer to an OBJECT_ATTRIBUTES structure that specifies the object name and other attributes. Use the InitializeObjectAttributes macro to initialize this structure. Because FltCreateSectionForDataScan inserts this object into the process handle table, the caller must specify the OBJ_KERNEL_HANDLE attribute when it calls InitializeObjectAttributes."

I believe the default behavior is that FltCreateSectionForDataScan is to create a user handle unless OBJ_KERNEL_HANDLE is specified in the OBJECT_ATTRIBUTES parameter, as written it sort of implies that it will always be a user handle... which leaves us asking why we must specify a KERNEL_HANDLE if so....  I believe the use of 'object' is also not appropriate since it is the _handle_ that it would insert into the respective table, the section object itself is a kernel object. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e812a1-9d9a-78fb-297e-099676149507
* Version Independent ID: 7765b998-7e93-417b-1672-01208a6a3058
* Content: [FltCreateSectionForDataScan function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltcreatesectionfordatascan)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcreatesectionfordatascan.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcreatesectionfordatascan.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for filing this issue, @camptatopenmars - great call on needing clarity of user handles (default) and kernel handles. I've updated the ObjectAttributes and SectionHandle parameter descriptions, and added a paragraph in the Remarks.
