### ISSUE TITLE
Minifilter driver modification when AccessMode is KernelMode

### ISSUE THREAD

**Issue by SJKU** [MicrosoftDocs/windows-driver-docs-ddi#1227]
**If the AccessMode parameter is KernelMode, the requested access is always allowed. If AccessMode is UserMode, the requested access is compared to the granted access for the object.**

In the description of this function it is mentioned that when AccessMode is KernelMode, the request access is always granted. So even in the minifilter driver's POB_PRE_OPERATION_CALLBACK callback when some of the accesses are denied by the driver, those will be ignored by the OS and requested access will be granted? Could you please clarify

**Comment by lorihollasch** [comment]
Closing as this duplicates issue #1226.
