### ISSUE TITLE
WdfDeviceAddQueryInterface cannot be used with nonpnp devices

### ISSUE THREAD

**Issue by wizfromoz** [MicrosoftDocs/windows-driver-docs-ddi#1228]
Hi,

I'm not sure if this is a WDF bug or a documentation issue, but if you use *WdfDeviceAddQueryInterface* on a nonpnp device, the system will crash in this API call. No restrictions are mentioned on the documentation page, but the crash has been reported TWICE, see: 

https://community.osr.com/discussion/293248/drivers-irql-already-2-when-calling-wdfdeviceaddqueryinterface

Regards,
Milan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2db618-0ca9-d272-c356-1c09e7d5e1c6
* Version Independent ID: b2f46ccc-b76d-fa22-1569-7422225491c0
* Content: [WdfDeviceAddQueryInterface function (wdfqueryinterface.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfqueryinterface/nf-wdfqueryinterface-wdfdeviceaddqueryinterface)
* Content Source: [wdk-ddi-src/content/wdfqueryinterface/nf-wdfqueryinterface-wdfdeviceaddqueryinterface.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfqueryinterface/nf-wdfqueryinterface-wdfdeviceaddqueryinterface.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @wizfromoz, appreciate your letting us know.  I've added a Note to the top of the Remarks section of the page to clarify.

Thanks for helping the docs, hopefully this will alleviate future such problems with this.
