### ISSUE TITLE
content missing

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#123]
RequestPriority lacks sufficient information to implement correctly. For example, are lower numbers lower priority and higher number higher priority?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a38a6a3-d5c3-be82-5c62-0ef5577d68d1
* Version Independent ID: accc3f73-42be-43c1-990e-9735971b9119
* Content: [_STORAGE_REQUEST_BLOCK](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/srb/ns-srb-_storage_request_block)
* Content Source: [wdk-ddi-src/content/srb/ns-srb-_storage_request_block.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/srb/ns-srb-_storage_request_block.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BenWestbrook, sorry for the delay in getting this answered for you. I've added information about possible RequestPriority values to the page, and those changes should be live later today or on Monday. Thanks again for the question!
