### ISSUE TITLE
Unclear process pointers

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/windows-driver-docs-ddi#1235]
The struct is documented as having pointers to "process objects", but it is not clear what is meant by this. The type of the fields should give a clue, but it's a `PVOID` which could be anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 966a4151-12c0-1bb6-59ad-13cec4262a2a
* Version Independent ID: b5cc7fc2-a66d-9a58-e404-591e7a325648
* Content: [_OB_PRE_DUPLICATE_HANDLE_INFORMATION (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_ob_pre_duplicate_handle_information)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_ob_pre_duplicate_handle_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_ob_pre_duplicate_handle_information.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Hi @henke37 - thanks for the question.  My guess is that these process objects are the opaque EPROCESS structures mentioned at the top of https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/eprocess.  Because they are opaque, I think they are not designed for manipulation.

Is there a specific task you are trying to accomplish using these?  I can try to get more info if the descriptions for *SourceProcess* and *TargetProcess* on https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_ob_pre_duplicate_handle_information are not sufficient.

**Comment by henke37** [comment]
Drivers that register for this callback at the very least need to be able to identify the process to the same extent as user mode process manipulation apis, with basic metadata such as the process id and main executable.

**Comment by tedhudek** [comment]
@henke37 you could use [PsGetProcessId](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-psgetprocessid), which takes the PEPROCESS as input and returns the PID.

But be aware that unless you are taking a reference on the process in question, it could go away after the call returns and the PID could be reused.

Does that help?

**Comment by henke37** [comment]
Yeah, it seems that it would work for the main use case of the callback here.

The intended use case of this callback is for drivers to protect processes by removing privileges from the granted privilege set. Knowing which process is trying to access which process is fundamental information for this policy decision.

**Comment by tedhudek** [comment]
Thanks again for the feedback.  I'm going to leave the info above off the page for now because of the caveats we discussed.  We appreciate your interest in the docs :)
