### ISSUE TITLE
Is normal that HTREE\ROOT\0 is 'unknow'

### ISSUE THREAD

**Issue by RobertoB74** [MicrosoftDocs/windows-driver-docs-ddi#1237]
i am beginner in a drivers devellopment .... if i have understand correctly this is the root of the hierarchy ...
but is it not weird that is 'Unkow' the class, producer and so on?

istance ID:  HTREE\ROOT\0
description: Unknow
class name:  Unknow
GUID class:  Unknow
producer:    Unknow
State:       Start

**Comment by tedhudek** [comment]
Hi @RobertoB74, is there a specific doc page you are asking about?

If you are looking for general technical assistance, I suggest posting your question in the following forums, where driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [windows-hardware-wdk](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk.html)
* [OSR's NTDEV forum](https://community.osr.com/categories/ntdev)

**Comment by tedhudek** [comment]
Closing out due to lack of info, please reopen if still needed
