### ISSUE TITLE
possible inaccuracy

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#124]
In the syntax section, the second to the last item in the structure is probably extraneous. The middle item below.

...
  _STORAGE_REQUEST_BLOCK POINTER_ALIGN *NextSrb;
  struct                               _STORAGE_REQUEST_BLOCK;
  ULONG                                SrbExDataOffset[ANYSIZE_ARRAY];
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a38a6a3-d5c3-be82-5c62-0ef5577d68d1
* Version Independent ID: accc3f73-42be-43c1-990e-9735971b9119
* Content: [_STORAGE_REQUEST_BLOCK](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/srb/ns-srb-_storage_request_block)
* Content Source: [wdk-ddi-src/content/srb/ns-srb-_storage_request_block.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/srb/ns-srb-_storage_request_block.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @BenWestbrook, thanks for letting us know about this. This appears to be an issue with the content rendering with this topic. I'll close this and follow up with our site team for possible fixes.
