### ISSUE TITLE
SUPPORTED_FS_FEATURES_BYPASS_IO (0x8)

### ISSUE THREAD

**Issue by scottnoone** [MicrosoftDocs/windows-driver-docs-ddi#1248]
Documentation for this flag is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 082caca6-0df3-363b-8c66-2aff0cbdbc8f
* Version Independent ID: 1d4d1da3-0961-b48f-a0e8-8f98809e14c9
* Content: [FsRtlGetSupportedFeatures function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-fsrtlgetsupportedfeatures)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlgetsupportedfeatures.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlgetsupportedfeatures.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @scottnoone! I've added the missing flag to the page.
