### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#125]
"...Specifies the OBJECT_ATTRIBUTES structure to initialize..."

might better read

"...A pointer to the OBJECT_ATTRIBUTES structure to initialize..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75aca267-3561-e63a-4737-e1844c635d49
* Version Independent ID: 94de8e18-cf27-3b40-5e88-f53e1bff9827
* Content: [InitializeObjectAttributes macro](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wudfwdm/nf-wudfwdm-initializeobjectattributes)
* Content Source: [wdk-ddi-src/content/wudfwdm/nf-wudfwdm-initializeobjectattributes.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wudfwdm/nf-wudfwdm-initializeobjectattributes.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Updated.  Thanks for the note @BenWestbrook
