### ISSUE TITLE
Clarification in IoSkipCurrentIrpStackLocation documentation

### ISSUE THREAD

**Issue by ilay122** [MicrosoftDocs/windows-driver-docs-ddi#1251]
In the documentation it states that if you use IoSkipCurrentIrpStackLocation but also set a completion routine afterwards you might overwrite a completion routine set by the driver _below_ it. But I think it should be _above_.

IoSetCompletionRoutine sets the completion routine on the _next_ stack location (IE IoGetNextIrpStackLocation, IE CurrentStackLocation - 1).
IoSkipCurrentIrpStackLocation just does
```
(Irp)->CurrentLocation++; \
(Irp)->Tail.Overlay.CurrentStackLocation++;
```
while IofCallDriver does 
```
Irp->CurrentLocation--;
...
StackPtr = IoGetNextIrpStackLocation(Irp);
Irp->Tail.Overlay.CurrentStackLocation = StackPtr;
...
```

So if you do both you actually overwrite the completion set by the driver above and not below because the stack location stays the same. If the stack location is the same the completion routine there belongs to the driver above us (as IoSetCompletionRoutine sets the completion routine on the lower-level driver).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba0bfa34-1cee-7cc9-6233-35005388e5b5
* Version Independent ID: ee0cbdfc-4258-bd30-2c65-0d5a66921c7a
* Content: [IoSkipCurrentIrpStackLocation - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-ioskipcurrentirpstacklocation)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioskipcurrentirpstacklocation.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioskipcurrentirpstacklocation.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Hi @ilay122 - you are correct!  Thank you for the report.  I've made the correction on https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-ioskipcurrentirpstacklocation.
