### ISSUE TITLE
WdfDriverRetrieveDriverDataDirectoryString 'not found' and more

### ISSUE THREAD

**Issue by RobertoB74** [MicrosoftDocs/windows-driver-docs-ddi#1254]
Hi i am apologize if you aren't interested about it ... but 
browsing on the doc pages ....  qucly:
1) this function isn't resolvable/don't exist  (less than i am in error)
2) the word 'Retrive' and the description maybe the second parameter SAL descriptor __in is incorrect

bye.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50aa4190-a4f8-bc36-ed5a-6e89c5b2ea6c
* Version Independent ID: a7ac0b0f-93b5-0cfb-3afe-a9041a35c322
* Content: [WdfDriverRetrieveDriverDataDirectoryString function (wdfdriver.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdriver/nf-wdfdriver-wdfdriverretrievedriverdatadirectorystring)
* Content Source: [wdk-ddi-src/content/wdfdriver/nf-wdfdriver-wdfdriverretrievedriverdatadirectorystring.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdriver/nf-wdfdriver-wdfdriverretrievedriverdatadirectorystring.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @RobertoB74 this function is UMDF only, as indicated on the page, starting with version 2.27 (RS5).  The SAL annotations match the header.

For more about UMDF versioning, please see [UMDF Version History](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/umdf-version-history).
