### ISSUE TITLE
missing link or perhaps a bad cut and paste

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#126]
"...For more information about how to use this routine, see KeWaitForSingleObject..." does not have a link but does appear to reference this page. May the whole sentence can simply be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2679ffa-4774-8de8-3ee8-d75c18aa48f4
* Version Independent ID: af7a279a-93aa-5e5b-fbb5-1e0c2ee14a07
* Content: [KeWaitForSingleObject function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-kewaitforsingleobject)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-kewaitforsingleobject.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-kewaitforsingleobject.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Fixed by removing the circular reference. Thanks, @BenWestbrook for catching this.
