### ISSUE TITLE
Incorrect documentation on return.

### ISSUE THREAD

**Issue by MartinCHarvey** [MicrosoftDocs/windows-driver-docs-ddi#1268]
IoAcquireRemoveLock returns an NTSTATUS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b50201-ea38-2862-1ae4-b72dddf23d4c
* Version Independent ID: 72388b48-638a-6729-87cf-a35b2bdb303c
* Content: [IoAcquireRemoveLock macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-ioacquireremovelock)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioacquireremovelock.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioacquireremovelock.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Thanks @MartinCHarvey for spotting this.  I just pushed a fix - live site should be updated within 30 minutes.

Please re-open if you don't see it after that point.
