### ISSUE TITLE
missing content

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#127]
"...TBD..."

considering the age of this API, it's probably time to fill in the TBD sections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 831fb347-ca21-4bca-a0c1-a1dd4b0155ec
* Version Independent ID: b1ecd8b4-dfc0-7564-b6ec-88407ff1ad37
* Content: [KeAcquireSpinLock macro](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-keacquirespinlock)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-keacquirespinlock.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-keacquirespinlock.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello,

The topic has now been updated.

Thanks for finding this!

Page Writer
