### ISSUE TITLE
[ForHelp] How to offline deploy  this doc

### ISSUE THREAD

**Issue by hustcsxg** [MicrosoftDocs/windows-driver-docs-ddi#1273]
How to offline deploy  this doc? use docfx? 
can you add CI to this Repo and publish the html release.

**Comment by tedhudek** [comment]
I think if you choose Help/Add and Remove Help Content in Visual Studio, it will open the Microsoft Help Viewer.  Then you can choose which docs you want to download for offline use.  For WDK, you would want:

![image](https://user-images.githubusercontent.com/14337110/156861219-214c3140-62fa-4a9c-baf1-8674e6fa09f2.png)

Hope this helps!
