### ISSUE TITLE
redundant enum entry in "FILE_INFORMATION_CLASS enumeration (wdm.h)"

### ISSUE THREAD

**Issue by npc1054657282** [MicrosoftDocs/windows-driver-docs-ddi#1275]
redundant "FileCaseSensitiveInformationForceAccessCheck,   // 75"
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ne-wdm-_file_information_class

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8119f8b-9c83-60f2-ac36-0478b88c4ab0
* Version Independent ID: 404ee010-b7dc-6a9e-7bbe-7cee72809333
* Content: [_FILE_INFORMATION_CLASS (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ne-wdm-_file_information_class)
* Content Source: [wdk-ddi-src/content/wdm/ne-wdm-_file_information_class.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ne-wdm-_file_information_class.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@npc1054657282, thanks for pointing out the redundant constant in the syntax. It has been removed.
