### ISSUE TITLE
return value is void (none)?

### ISSUE THREAD

**Issue by chaotsungpeng** [MicrosoftDocs/windows-driver-docs-ddi#1277]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bdbb1d-d149-89fd-8e87-3b2c00d2e75d
* Version Independent ID: 21d3eba4-0b4d-bfb4-cae8-22cf3b21c3dd
* Content: [MmGetMdlPfnArray - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-mmgetmdlpfnarray)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmgetmdlpfnarray.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmgetmdlpfnarray.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@chaotsungpeng, thanks for pointing this out. The topic has been updated with the correct return value information.
