### ISSUE TITLE
USB Type-C Connector System Software Interface (UCSI) driver

### ISSUE THREAD

**Issue by omnialx** [MicrosoftDocs/windows-driver-docs-ddi#1278]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6cf262b-3d33-603a-1d17-6015ec045dc4
* Version Independent ID: 08cf8ae0-3335-c778-f0b1-e18c2153ecd7
* Content: [EVT_WDF_DEVICE_D0_ENTRY (wdfdevice.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdevice/nc-wdfdevice-evt_wdf_device_d0_entry)
* Content Source: [wdk-ddi-src/content/wdfdevice/nc-wdfdevice-evt_wdf_device_d0_entry.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdevice/nc-wdfdevice-evt_wdf_device_d0_entry.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Did you mean to leave feedback?
