### ISSUE TITLE
Unclear Summary for RtlCompareMemory

### ISSUE THREAD

**Issue by Jack-McDowell** [MicrosoftDocs/windows-driver-docs-ddi#1280]
The page for RtlCompareMemory current summarizes the function as follows:
> The RtlCompareMemory routine compares two blocks of memory and returns the number of bytes that match.

While it later clarifies that RtlCompareMemory actually returns the number of bytes up until the first difference, this initial description may give readers the impression that it instead returns the number of bytes that are the same between the two buffers, not stopping at the first difference. I suggest the following modification to clarify.
> The RtlCompareMemory routine compares two blocks of memory and returns the number of bytes that match until the first difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8638fdc-4cb2-10d5-c906-0fb6286df0ed
* Version Independent ID: f0d3b637-f5fe-9ca8-b486-f5c6808d2076
* Content: [RtlCompareMemory function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlcomparememory)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtlcomparememory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlcomparememory.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@Jack-McDowell, thanks for pointing this out.  The topic is now updated with your suggested text.
