### ISSUE TITLE
Improve documentation for MmAllocatePagesForMdl regarding APCs

### ISSUE THREAD

**Issue by tkreuzer** [MicrosoftDocs/windows-driver-docs-ddi#1281]
The documentation for `MmAllocatePagesForMdl` says that you can call it at IRQL <= APC_LEVEL.
This might be interpreted as it is ok to call this function from a special kernel APC. But that is not the case!
Calling it from a special kernel APC can lead to a recursive acquisition of an exclusive lock, which is only in a critical region (with user/normal kernel APCs disabled) but not in a guarded region (all APCs disabled)
Since special kernel APCs are possibly the most relevant use case for running at APC_LEVEL, this should be noted in the documentation.

If the described behavior (critical region instead of guarded region) is not intended, I'm happy to provide more details to fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ab478e7-774e-3315-0e76-e5df915c4c3b
* Version Independent ID: 2f406cd4-a882-6ce5-ec7f-66805ca0c9a5
* Content: [MmAllocatePagesForMdl function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-mmallocatepagesformdl)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmallocatepagesformdl.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmallocatepagesformdl.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by mhopkins-msft** [comment]
Hi @tkreuzer,

Thank you for submitting this suggestion. I've added a note to the page. It should be published later today.

Thanks for helping improve the docs!

 ~ *Mark*
