### ISSUE TITLE
Incorrect SAL annotation causing code analysis warning

### ISSUE THREAD

**Issue by wmjdgla** [MicrosoftDocs/windows-driver-docs-ddi#1282]
> `[in] Context`
> 
> A pointer to caller-defined context information to be passed as the Context parameter of the callback routine specified in the WorkerRoutine parameter.

WorkerRoutine is declared as:
```c
typedef VOID
(*PFLT_DEFERRED_IO_WORKITEM_ROUTINE) (
      _in PFLT_DEFERRED_IO_WORKITEM  FltWorkItem,
      __in PFLT_CALLBACK_DATA  CallbackData,
      __in_opt PVOID  Context
      );
```
WorkerRoutine's Context parameter is marked as `__in_opt`, meaning it can be NULL, and indeed there can be cases where there is no need for any Context in WorkerRoutine. However FltQueueDeferredIoWorkItem's Context parameter is marked as `in`. So if the caller pass in NULL for FltQueueDeferredIoWorkItem's Context because they have no need for any Context in WorkerRoutine, code analysis would produce C6387 - `'_Param_(5)' could be '0': this does not adhere to the specification for the function 'FltQueueDeferredIoWorkItem'.`

Also, the SAL used for WorkerRoutine's declaration is inconsistent (`_in` vs `__in`) and do not match the actual declaration fltkernel.h (`_In_`, `_In_opt_`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c68fdef-072f-0a16-60d5-c0c3c2b04c93
* Version Independent ID: 5307944c-6802-a6bb-c58c-239eb0d94bdc
* Content: [FltQueueDeferredIoWorkItem function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltqueuedeferredioworkitem)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltqueuedeferredioworkitem.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltqueuedeferredioworkitem.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this issue, @wmjdgla - great catch! I have fixed WorkerRoutine's SAL on this page. The engineering team has filed an internal bug about FltQueueDeferredIoWorkItem's incorrect SAL annotation - its Context parameter should indeed be _In_opt_ like the WorkerRoutine.
