### ISSUE TITLE
2 fields both named PhysicalAddress ?

### ISSUE THREAD

**Issue by chaotsungpeng** [MicrosoftDocs/windows-driver-docs-ddi#1283]
union {
    [in/out] PHYSICAL_ADDRESS       PhysicalAddress;
             D3DGPU_VIRTUAL_ADDRESS VirtualAddress;
  };
  [in/out] PHYSICAL_ADDRESS PhysicalAddress;

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69682ac4-a065-8b83-8f16-086463be977d
* Version Independent ID: 9e0069d3-73b5-939f-3935-245f8c68e87b
* Content: [_DXGK_ALLOCATIONLIST (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ns-d3dkmddi-_dxgk_allocationlist)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_allocationlist.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_allocationlist.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@chaotsungpeng, thanks for filing this issue - apologies for the confusion about the two PhysicalAddress members. Our doc generation tool has certain limitations around C preprocessor directives, so I did a syntax override to include the directives and thus eliminate the confusion.
Regarding your other issues: I've reached out to the dev team and will address them once I hear back. Have a great weekend!
