### ISSUE TITLE
STRSAFE_NO_TRUNCATION flag documentation doesn't match behavior

### ISSUE THREAD

**Issue by brettw** [MicrosoftDocs/windows-driver-docs-ddi#1286]
The ntstrsafe documentation lists the flag:

```
STRSAFE_NO_TRUNCATION: If set and the function returns STATUS_BUFFER_OVERFLOW, the contents of the destination buffer are not modified.
```

Testing shows that this is incorrect. Testing at least `RtlStringCchCopyExW()` shows that in the truncation case with `STRSAFE_NO_TRUNCATION` passed, the copy is attempted until the limit is reached, then the function aborts and writes a null to the first character of the destination. This is identical to the `STRSAFE_NULL_ON_FAILURE` case.

Furthermore, the intersection of `STRSAFE_NO_TRUNCATION` and the flags indicating what to do on error is not specified. Testing shows that both `STRSAFE_FILL_ON_FAILURE` and `STRSAFE_FILL_BEHIND_NULL` apply in this case.

I also tested `RtlStringCcyCatExW()' and it has similar behavior. I strongly suspect all "Ex" strsafe functions with a flags parameter have the same behavior.

I believe the documentation for the flag on "copy" strsafe functions should read something like:

```
STRSAFE_NO_TRUNCATION: If set and the function returns STATUS_BUFFER_OVERFLOW:
  * If STRSAFE_FILL_ON_FAILURE is additionally specified, fills the destination buffer accordingly.
  * Otherwise the contents of the destination buffer will be set to the empty string, even if `STRSAFE_NULL_ON_FAILURE` is not set. `STRSAFE_FILL_BEHIND_NULL` is ignored.
```

The documentation on the "cat" strsafe functions should read:

```
STRSAFE_NO_TRUNCATION: If set and the function returns STATUS_BUFFER_OVERFLOW:
  * If STRSAFE_FILL_ON_FAILURE is additionally specified, fills the destination buffer accordingly.
  * Otherwise the destination buffer will be unmodified.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fc62d43-e994-dae8-faea-ffb159b17245
* Version Independent ID: d59ad1b9-0dcd-1b7c-b0c7-369d615ae6a1
* Content: [RtlStringCchCopyExW function (ntstrsafe.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntstrsafe/nf-ntstrsafe-rtlstringcchcopyexw)
* Content Source: [wdk-ddi-src/content/ntstrsafe/nf-ntstrsafe-rtlstringcchcopyexw.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntstrsafe/nf-ntstrsafe-rtlstringcchcopyexw.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by mhopkins-msft** [comment]
Hi @brettw,

Thank you for reporting this to us. I really appreciate all the work you did to assess the situation! I've updated the doc pages for all the CopyEx and CatEx functions in the ntstrsafe.h header with the information you provided. The changes will be published later today.

Thank you for helping us make the docs better!
 ~ *Mark*
