### ISSUE TITLE
DmaBufferPhysicalAddress should not be the physical address?

### ISSUE THREAD

**Issue by chaotsungpeng** [MicrosoftDocs/windows-driver-docs-ddi#1287]
DmaBufferPhysicalAddress should not be "segment physical address" when DmaBufferSegmentId is nonzero as mentioned in the doc? it should more likely to be "segment address" (somewhat like kind of virtual address) since if it's already physical address then we should not use GetAperturePhysicalAddress() to convert to physical address as below, right?
https://github.com/microsoft/graphics-driver-samples/blob/master/render-only-sample/roskmd/RosKmdAdapter.cpp#L713

////////////////////////////////////////
[in] DmaBufferPhysicalAddress

A PHYSICAL_ADDRESS data type (which is defined as LARGE_INTEGER) that indicates the physical address where the DMA buffer was paged in.

If DmaBufferSegmentId is zero, DmaBufferPhysicalAddress is the physical address in system memory where the DMA buffer is located.

If DmaBufferSegmentId is nonzero, DmaBufferPhysicalAddress is the segment physical address for the DMA buffer (that is, DXGK_SEGMENTDESCRIPTOR.BaseAddress + DmaBuffer.SegmentOffset).

Note that DmaBufferPhysicalAddress always refers to the beginning of the DMA buffer even though the driver might be required to patch or submit a section of the DMA buffer that does not include the beginning of the DMA buffer (that is, if the DmaBufferSubmissionStartOffset member is nonzero).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8610a54a-0006-568a-37f1-bee09f8077c3
* Version Independent ID: 3e1ce891-6b53-0198-2279-d831bd3a551b
* Content: [_DXGKARG_SUBMITCOMMAND (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ns-d3dkmddi-_dxgkarg_submitcommand)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgkarg_submitcommand.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgkarg_submitcommand.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi again @chaotsungpeng. Similar to your issue #1285, this page was technically correct. I did update it, adding a bit of detail to DmaBufferPhysicalAddress. I also added a link to a page that provides details about aperature segments.
