### ISSUE TITLE
Documentation for d3dkmtsetprocessschedulingpriorityclass does not match function

### ISSUE THREAD

**Issue by stsoe** [MicrosoftDocs/windows-driver-docs-ddi#1288]
unnamedParam1 and unnamedParam2 are reversed in Parameters section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68e5e419-46bc-6b5b-f94f-3a1f670abee7
* Version Independent ID: 7f9f30f6-aa30-d1ce-171d-351214c81c71
* Content: [D3DKMTSetProcessSchedulingPriorityClass function (d3dkmthk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmthk/nf-d3dkmthk-d3dkmtsetprocessschedulingpriorityclass)
* Content Source: [wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtsetprocessschedulingpriorityclass.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtsetprocessschedulingpriorityclass.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @stsoe - great catch! I've fixed the page.
