### ISSUE TITLE
small inconsistency

### ISSUE THREAD

**Issue by rzenko** [MicrosoftDocs/windows-driver-docs-ddi#129]
Return Value
STATUS_SUCCESS - the resultant destination buffer _is_ null-terminated.
Remarks
The function does _not_ terminate the resultant string with a null character value (that is, with zero).

Only one can be true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc10b3c3-e56e-7319-9095-298c824a3974
* Version Independent ID: 0d5314bf-2805-b56e-cd60-6038e9ef2f70
* Content: [RtlUnicodeStringCbCopyStringN function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntstrsafe/nf-ntstrsafe-rtlunicodestringcbcopystringn)
* Content Source: [wdk-ddi-src/content/ntstrsafe/nf-ntstrsafe-rtlunicodestringcbcopystringn.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntstrsafe/nf-ntstrsafe-rtlunicodestringcbcopystringn.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks @rzenko for pointing this out. @PageWriter-MSFT can you please correct the misstatement, whichever one it is?

**Comment by PageWriter-MSFT** [comment]
Hello @rzenko 

Thanks for pointing out the conflicting statements! The resultant string is not null-terminated. I have updated the topic. It should be live soon.

Page Writer
