### ISSUE TITLE
MmGetMdlByteCount is not a void function.

### ISSUE THREAD

**Issue by aruproy14** [MicrosoftDocs/windows-driver-docs-ddi#1292]
MmGetMdlByteCount returns a value. The docs are self-inconsistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aef0192-7a6f-ce69-4c75-e069d3f27de0
* Version Independent ID: d142ef47-a9a9-a031-55ab-ba1395c2156c
* Content: [MmGetMdlByteCount macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-mmgetmdlbytecount)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmgetmdlbytecount.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmgetmdlbytecount.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@aruproy14, thanks for pointing out the incorrect return type. The topic has been updated with the correct information.
