### ISSUE TITLE
WdfDeviceStopIdle does have a return value

### ISSUE THREAD

**Issue by rahul-ramadas** [MicrosoftDocs/windows-driver-docs-ddi#1299]
The "Return value" section says "none". But syntax shows that it does have a return value, and the "Remarks" section talks about the various return values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d750aa2-2d1a-3216-eec6-b26599a0d631
* Version Independent ID: 4a13a005-6a06-fe76-d101-63da6ebe1216
* Content: [WdfDeviceStopIdle macro (wdfdevice.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdevice/nf-wdfdevice-wdfdevicestopidle)
* Content Source: [wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicestopidle.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicestopidle.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Fixed!  Thanks for the report, Rahul.
