### ISSUE TITLE
Please update WDDM versions for W10 21h1/h2 and W11

### ISSUE THREAD

**Issue by kevinf28** [MicrosoftDocs/windows-driver-docs-ddi#1300]
Page has missing WDDM versions and build numbers. This is the central place to map WDDM versions to Windows versions, so its very key to keep updated. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 504c6508-5f83-159f-be97-2c19af548d04
* Version Independent ID: 7b284030-fd41-c4e1-5455-514529df33ac
* Content: [_DXGK_WDDMVERSION (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ne-d3dkmddi-_dxgk_wddmversion)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ne-d3dkmddi-_dxgk_wddmversion.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ne-d3dkmddi-_dxgk_wddmversion.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@kevinf28, thanks for pointing this out! I've updated the page with the missing WDDM versions.
