### ISSUE TITLE
Link still point to 'previous version' doc

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1301]
[Enter feedback here]
Both this page and the `Exclusive` homolog have links to a release function in the `previous-versions` tree.

This is because the acquire versions are missing.

In fact looking at the source tree there are *no*  acquire spinlock desrcriptions present
```
H:\Perforce\github\windows-driver-docs-ddi\wdk-ddi-src\content\wdm [staging ≡]> dir *spinlock*


    Directory: H:\Perforce\github\windows-driver-docs-ddi\wdk-ddi-src\content\wdm


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        14/02/2022     15:06           2660 nf-wdm-exreleasespinlockexclusive.md
-a----        14/02/2022     15:06           2626 nf-wdm-exreleasespinlockshared.md
-a----        29/10/2021     10:24           3301 nf-wdm-extryconvertsharedspinlockexclusive.md
-a----        05/01/2021     11:24           3836 nf-wdm-keacquirespinlock.md
-a----        29/10/2021     10:24           3274 nf-wdm-keacquirespinlockatdpclevel.md
-a----        29/10/2021     10:24           2710 nf-wdm-kefreleasespinlockfromdpclevel.md
-a----        29/10/2021     10:24           3816 nf-wdm-keinitializespinlock.md
-a----        29/10/2021     10:24           2633 nf-wdm-kereleaseinstackqueuedspinlock.md
-a----        29/10/2021     10:24           2745 nf-wdm-kereleaseinstackqueuedspinlockfordpc.md
-a----        29/10/2021     10:24           2422 nf-wdm-kereleaseinstackqueuedspinlockfromdpclevel.md
-a----        29/10/2021     10:24           2278 nf-wdm-kereleaseinterruptspinlock.md
-a----        29/10/2021     10:24           2848 nf-wdm-kereleasespinlock.md
-a----        29/10/2021     10:24           2288 nf-wdm-kereleasespinlockfordpc.md
-a----        29/10/2021     10:24           2702 nf-wdm-kereleasespinlockfromdpclevel.md
-a----        29/10/2021     10:24           2397 nf-wdm-ketestspinlock.md
-a----        29/10/2021     10:24           3305 nf-wdm-ketrytoacquirespinlockatdpclevel.md
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76b7fffb-a4e3-8f1d-c32c-1cede34e4528
* Version Independent ID: 65098ad8-9078-b19a-657b-56d467278521
* Content: [ExReleaseSpinLockShared function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exreleasespinlockshared)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exreleasespinlockshared.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exreleasespinlockshared.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by mhopkins-msft** [comment]
Hi @rodwiddowson 

Thank you for bringing this to our attention. I've created a new page for **ExAcquireSpinLockShared** and pointed **ExReleaseSpinLockShared** to the newly created page. The updates should be published later today.

Thank you for helping improve our docs!

 ~ *Mark*
