### ISSUE TITLE
Lack of purge flags

### ISSUE THREAD

**Issue by blueocean987** [MicrosoftDocs/windows-driver-docs-ddi#1306]
Lack of purge flags in input buffer section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df4a2a8d-9f27-2233-e18e-f41bb9f2675e
* Version Independent ID: 8e2fb32a-025c-30be-c627-626c645bddd0
* Content: [IOCTL_SERIAL_PURGE (ntddser.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddser/ni-ntddser-ioctl_serial_purge#feedback)
* Content Source: [wdk-ddi-src/content/ntddser/ni-ntddser-ioctl_serial_purge.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddser/ni-ntddser-ioctl_serial_purge.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the heads up @blueocean987!  This is now fixed.

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddser/ni-ntddser-ioctl_serial_purge
