### ISSUE TITLE
Missing hint to NDIS_OID_REQUEST_REVISION_2

### ISSUE THREAD

**Issue by hanzzzzz** [MicrosoftDocs/windows-driver-docs-ddi#1307]
The `NDIS_OID_REQUEST` structure is different depending on the NDIS version used. The fields starting at `SwitchId` are only available for NDIS V6.50 and higher. For those versions, the header fields need to refer to `NDIS_OID_REQUEST_REVISION_2` and `NDIS_SIZEOF_OID_REQUEST_REVISION_2`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca00ecb2-5017-17ed-6802-04cd8bac6c25
* Version Independent ID: cd93fdfe-89b7-1113-663f-6fd18e811468
* Content: [NDIS_OID_REQUEST - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/oidrequest/ns-oidrequest-ndis_oid_request)
* Content Source: [wdk-ddi-src/content/oidrequest/ns-oidrequest-ndis_oid_request.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/oidrequest/ns-oidrequest-ndis_oid_request.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @hanzzzzz, 
Thanks for letting us know about this issue. We have updated the header member with this info: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/oidrequest/ns-oidrequest-ndis_oid_request
