### ISSUE TITLE
Link for MmGetMdlPfnArray is wrong.

### ISSUE THREAD

**Issue by paul-rosswurm-1** [MicrosoftDocs/windows-driver-docs-ddi#1310]
[MmGetMdlPfnArray](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/mm-bad-pointer#mmgetmdlpfnarray) takes one to mm-bad-pointer, the correct link is https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-mmgetmdlpfnarray. Looks like some other links might be wrong as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8beff88c-c22b-179c-de6c-d0e502279244
* Version Independent ID: 58a0ee70-fe5b-398c-5fcf-a9bf795ba056
* Content: [_MDL (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_mdl)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_mdl.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_mdl.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by mhopkins-msft** [comment]
Hi @paul-rosswurm-1

Thank you for pointing this out to us. I've updated the links to point to the correct and current pages. The updates should be published later today.

Thanks for helping us improve the docs!

 ~ *Mark*
