### ISSUE TITLE
how does VidMM set a upperbound for the allocate physical address of aperture segment?

### ISSUE THREAD

**Issue by chaotsungpeng** [MicrosoftDocs/windows-driver-docs-ddi#1314]
Since Aperture segment is allocated/managed by VidMM at runtime, how can we make sure the physical address of Aperture segment is under 4G? otherwise GPU might not be able to access the memory range. Or this is an implicit setting in dxgkrnl?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dc89ef3-405f-ab2c-d63e-e8fc16522333
* Version Independent ID: cbd37e51-bee2-0989-ff88-3456d008530c
* Content: [_DXGK_SEGMENTDESCRIPTOR3 (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ns-d3dkmddi-_dxgk_segmentdescriptor3)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_segmentdescriptor3.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_segmentdescriptor3.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi @chaotsungpeng - thanks for your question, which I ran past the dev team. They had two different interpretations for your question - I've copied the answers they provided below. I also wrote up details about the [WDDM 3.0 IOMMU DMA Remapping feature](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/iommu-dma-remapping) referenced in Answer #2. Hope this helps.
1) Although the aperture segment’s address space is virtual, we internally often refer to this as the physical address of the allocation, even though it maps to system memory under the hood. So if their question is about the size of the aperture segment itself, and how to restrict its physical address space, then it’s just a matter of setting the size themselves. The aperture segment is created by the driver just like memory segments, and the Size specified in the segment descriptor during initialization controls the upper bound of its address space.
2) How do we ensure that the physical system memory that gets mapped to the aperture range is within 4GB (e.g. The hardware on the GPU that decodes the aperture range and fetches from system memory only has 32-bits)?
The short answer is: You cannot. All video memory allocations are considered to come from the pageable memory pool, and when pageable memory is locked, there are no bound restrictions for the physical address it gets assigned by NT’s memory manager.
The longer answer is: We support this through a WDDM 3.0 feature called the IOMMU. The IOMMU is a piece of hardware that sits between the device (GPU) and system memory. This allows us to create a second layer of indirection, and we control the address space. In this case, we create an address space on the IOMMU that is the size of what the device can see (e.g. 32-bit/4GB) and we map that address range to the locked physical pages on the IOMMU hardware. The device itself then programs the aperture with the IOMMU addresses, and all accesses to that physical page will get translated a second time by the IOMMU hardware, which can always see the full physical address space.
