### ISSUE TITLE
This project will involve managing a contiguous region of memory of size MAX where addresses may range from 0 ... MAX − 1. Your program must respond to three different requests: 1. Request for a contiguous block of memory 2. Release of a contiguous block of memory 3. Report the regions of free and allocated memory Your program will be passed the initial amount of memory at startup.

### ISSUE THREAD

**Issue by shoaib78616** [MicrosoftDocs/windows-driver-docs-ddi#1319]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e99b7a9-b770-4e84-d732-d429ab3a494a
* Version Independent ID: 83232dca-8185-8b85-bd07-03957d3058a9
* Content: [MmAllocateContiguousMemorySpecifyCacheNode function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-mmallocatecontiguousmemoryspecifycachenode)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-mmallocatecontiguousmemoryspecifycachenode.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-mmallocatecontiguousmemoryspecifycachenode.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Unclear what the feedback is - please reopen with detail if still needed, thanks!
