### ISSUE TITLE
missed opportunity for helpful link

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#132]
It would be nice if there were a link to TIME_FIELDS from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e3c736a-a2e5-3680-6a36-4943259e0305
* Version Independent ID: eb313ab2-0d55-c0bd-198b-38d5beffae2e
* Content: [RtlTimeToTimeFields function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtltimetotimefields)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtltimetotimefields.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtltimetotimefields.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @BenWestbrook 
I added a remark linking to the RtlTimeFieldsToTime function (https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtltimefieldstotime), which describes the structure. Should be on the live site within a few hours.
