### ISSUE TITLE
FLT_TAG_DATA_BUFFER Documentation incomplete

### ISSUE THREAD

**Issue by NoGitHubPlease** [MicrosoftDocs/windows-driver-docs-ddi#1332]
[Enter feedback here]

Your Text:

TagData

Pointer to an [FLT_TAG_DATA_BUFFER](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/ns-fltkernel-_flt_tag_data_buffer) structure that contains reparse point data for the I/O operation. This pointer is valid only in the post-create path. Thus only a minifilter's postoperation callback routine can change the value of this member. A minifilter's post-create callback routine can change this member to point to a different FLT_TAG_DATA_BUFFER structure. However, if it changes the member to point to a different structure, it must **first free** the existing structure to prevent a pool memory leak.

My Question:

Which methods to use to Malloc/Free to avoid a pool memory leak ??? GlobalAlloc, HeapAlloc, C - malloc .... ??????
This information should be added to all those structures, which might be modified dynamically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a39b4d45-43aa-5a0c-9a37-fb0e32beb698
* Version Independent ID: 6d767c49-f9e4-2fe1-68b6-c3d24fe61ee9
* Content: [FLT_CALLBACK_DATA (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/ns-fltkernel-_flt_callback_data)
* Content Source: [wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_callback_data.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_callback_data.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi @NoGitHubPlease - thanks for the issue. It's generally well-known to use ExFreePool on kernel-mode memory, which is why you won't see it called out explicitly on most reference pages. I went ahead and added it here - the additional clarity doesn't hurt!
