### ISSUE TITLE
An error in wdm's document

### ISSUE THREAD

**Issue by intel-whye** [MicrosoftDocs/windows-driver-docs-ddi#1336]
[IoGetDmaAdapter function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iogetdmaadapter)
"On success, the DmaOperations member of the routine's return value points to a DMA_ADAPTER structure."
I think it's should be "On success, the routine's return value points to a DMA_ADAPTER structure."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc39ea86-b9d2-5312-8f69-a316e4fa950a
* Version Independent ID: a0d41bf2-964f-1558-2849-96644cad94bd
* Content: [IoGetDmaAdapter function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iogetdmaadapter)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iogetdmaadapter.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iogetdmaadapter.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Thanks for reporting this @intel-whye.  You are correct!  I just pushed the fix, it should appear on the live site soon.

Note that if you find other issues in the docs you can submit a pull request if you like.  To start a PR, click the Edit button from any page on docs.microsoft.com and then click Edit again on the GitHub page.
