### ISSUE TITLE
NET_ADAPTER_RECEIVE_SCALING_PROTOCOL_TYPE ProtocolType is actually a bitmask

### ISSUE THREAD

**Issue by msudhakargit** [MicrosoftDocs/windows-driver-docs-ddi#1344]
[Enter feedback here]

NET_ADAPTER_RECEIVE_SCALING_PROTOCOL_TYPE ProtocolType is actually a bitmask, could explicitly mention that. i.e. it specifically isn't any more an exact NET_ADAPTER_RECEIVE_SCALING_PROTOCOL_TYPE.
Also clarify whether driver should retain the previous protocol bitmask (i.e. OR the current one with previous one) or should it overwrite with the the existing existing one. Probably the later, but explicit mention will remove any scope for any misinterpretation. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b39d56b-d091-0361-af17-0b6435d37cf5
* Version Independent ID: 9f853bda-6c78-7d2d-e3a0-3e6448d590f2
* Content: [EVT_NET_ADAPTER_RECEIVE_SCALING_ENABLE (netreceivescaling.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/netreceivescaling/nc-netreceivescaling-evt_net_adapter_receive_scaling_enable)
* Content Source: [wdk-ddi-src/content/netreceivescaling/nc-netreceivescaling-evt_net_adapter_receive_scaling_enable.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/netreceivescaling/nc-netreceivescaling-evt_net_adapter_receive_scaling_enable.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @msudhakargit,
Thanks for opening this issue. The ProtocolType param links to the [NET_ADAPTER_RECEIVE_SCALING_PROTOCOL_TYPE enumeration](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/netreceivescaling/ne-netreceivescaling-_net_adapter_receive_scaling_protocol_type). Please see the enum description and remarks for more information. And yes, the driver should overwrite the previous protocol bitmask when the new one is sent down. Please open a new issue if you have further comments or questions.
Thanks again.
