### ISSUE TITLE
is there detailed explanation regarding the data type and usage of the data corresponding to these enum values?

### ISSUE THREAD

**Issue by chaotsungpeng** [MicrosoftDocs/windows-driver-docs-ddi#1346]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9e39d9-7f61-9c33-a82d-6383158b705c
* Version Independent ID: d8fca3e4-617f-af6d-9fca-cd3438037543
* Content: [FWPS_FIELDS_INBOUND_MAC_FRAME_ETHERNET_ (fwpsk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ne-fwpsk-fwps_fields_inbound_mac_frame_ethernet_)
* Content Source: [wdk-ddi-src/content/fwpsk/ne-fwpsk-fwps_fields_inbound_mac_frame_ethernet_.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fwpsk/ne-fwpsk-fwps_fields_inbound_mac_frame_ethernet_.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @chaotsungpeng,
Thanks for opening this issue. Please see [Filtering Layer Identifiers](https://docs.microsoft.com/en-us/windows/win32/fwp/management-filtering-layer-identifiers-) for more info.
