### ISSUE TITLE
WdfRegistryRemoveKey documentation must be enhanced

### ISSUE THREAD

**Issue by d0vgan** [MicrosoftDocs/windows-driver-docs-ddi#1348]
WdfRegistryRemoveKey returns 0xC0000121 (STATUS_CANNOT_DELETE) when there is any existing value under the given key. In order to WdfRegistryRemoveKey to succeed, all the values under it must be deleted.
This must be mentioned in the documentation. I've wasted a whole day experimenting with different approaches and scenarios to find it out!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f032280-930c-bfef-4517-50c8d9911eaf
* Version Independent ID: fc19ef06-3551-8953-4872-f1f1bc08747d
* Content: [WdfRegistryRemoveKey function (wdfregistry.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfregistry/nf-wdfregistry-wdfregistryremovekey)
* Content Source: [wdk-ddi-src/content/wdfregistry/nf-wdfregistry-wdfregistryremovekey.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfregistry/nf-wdfregistry-wdfregistryremovekey.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @d0vgan looks like there was already a warning on https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfregistry/nf-wdfregistry-wdfregistryremovekey --

> WdfRegistryRemoveKey does not return STATUS_SUCCESS if the specified key object represents a registry key that has subkeys. In other words, the driver must remove the subkeys first.

But I went ahead and removed this, replacing it with the same Note that I just put in https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwdeletekey.  Should be live in 30 min or so.  Thanks again for opening these.
