### ISSUE TITLE
ZwDeleteKey documentation must be enhanced

### ISSUE THREAD

**Issue by d0vgan** [MicrosoftDocs/windows-driver-docs-ddi#1349]
ZwDeleteKey can fail with status 0xC0000121 (CANNOT_DELETE). In order to succeed, all the keys and values under the given key must be deleted first. For example, see here:
https://community.osr.com/discussion/52479/zwdeletekey
This information must be added to the ZwDeleteKey documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a5264a7-688d-86c2-be35-cec88516633b
* Version Independent ID: 5048e07d-95cc-bcf7-c1b7-8d98df52fd54
* Content: [ZwDeleteKey function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwdeletekey)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwdeletekey.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwdeletekey.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Thanks @d0vgan this is a great suggestion.  I verified that this is expected behavior, and added a note to the Remarks of https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwdeletekey.
