### ISSUE TITLE
Table at end of page is missing content

### ISSUE THREAD

**Issue by badasahog** [MicrosoftDocs/windows-driver-docs-ddi#1363]
The table at the end of the page only lists the header file, not the DLL, LIB, or minimum platform

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ee9413f-822b-d12e-fdf2-11ad147fb8b1
* Version Independent ID: a5555176-ed71-f086-975a-1134abb222e4
* Content: [NtOpenThreadToken - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntopenthreadtoken)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ntopenthreadtoken.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ntopenthreadtoken.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for the issue, @badasahog - appreciate you taking the time to make the docs better. I've updated the page with the missing table info.
