### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by JunjieHe** [MicrosoftDocs/windows-driver-docs-ddi#1365]
[Enter feedback here]
For "[in] pAllocationList" description, there is duplicate content, please help to update it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80fef27b-3509-18bc-4f6c-60fbda3b591f
* Version Independent ID: 5a358979-5ed0-9c8f-aad3-bfdbf75f59c3
* Content: [_DXGKARG_PRESENT (d3dkmddi.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ns-d3dkmddi-_dxgkarg_present)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgkarg_present.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgkarg_present.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this issue, @JunjieHe! I've removed the duplicate content.
