### ISSUE TITLE
TBD instead of params

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#137]
The params and simple descriptions are in the source but not on the site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b7727e-8c3f-500c-08f1-07146aac9cf7
* Version Independent ID: bf2623e7-ea0e-56c5-4ad4-df385c898e4e
* Content: [StorPortEnablePassiveInitialization function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/storport/nf-storport-storportenablepassiveinitialization)
* Content Source: [wdk-ddi-src/content/storport/nf-storport-storportenablepassiveinitialization.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/storport/nf-storport-storportenablepassiveinitialization.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @csm10495 
Made PR and should be live shortly after  review.
