### ISSUE TITLE
warning not hilighted

### ISSUE THREAD

**Issue by badasahog** [MicrosoftDocs/windows-driver-docs-ddi#1373]
the "Call IoCallDriver instead" warning is not hilighted, and readers will likely not notice it.

This is unlike most other pages on msdn, where warning appear in a yellow or red bubble

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6af668c-ee77-f4df-884b-4cee3bddf949
* Version Independent ID: 89f35920-ec8b-b8d5-cf3b-a96cd0e42282
* Content: [IofCallDriver function (wdm.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iofcalldriver)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iofcalldriver.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iofcalldriver.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Updated!  Thanks @badasahog for the suggestion.
