### ISSUE TITLE
Modifying assigned interrupt resources processor affinity in place using EvtWdfDeviceFilterResourceRequirements

### ISSUE THREAD

**Issue by msudhakargit** [MicrosoftDocs/windows-driver-docs-ddi#1375]
[Enter feedback here]
Hi 

I am using EvtWdfDeviceFilterResourceRequirements to modify the assigned processor affinity of my MSI-X interrupt resources.
But I do not see that taking effect. Is there any requirement on the driver on what type of Interrupt Affinity Device policy (https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ne-wdm-_irq_device_policy) it uses in the INF for this API to work.
(For instance, say for MSI-X MsgId=n, it was affinized to logical-processor 'x', I am trying to change the affinity to logical-processor 'Y'. But I do not see that being taking effect. Seems i should be able to achieve this using this API).

Any clarification on any pre-requisites for this API to work will be helpful

Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b780b469-ae1f-4289-e706-7c45233f921a
* Version Independent ID: 789dec00-c7d5-2514-cb7e-660c61c1b8ee
* Content: [EVT_WDF_DEVICE_FILTER_RESOURCE_REQUIREMENTS (wdffdo.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdffdo/nc-wdffdo-evt_wdf_device_filter_resource_requirements)
* Content Source: [wdk-ddi-src/content/wdffdo/nc-wdffdo-evt_wdf_device_filter_resource_requirements.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdffdo/nc-wdffdo-evt_wdf_device_filter_resource_requirements.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hello @msudhakargit and thank you for the question.

First please review the Remarks section of https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfinterrupt/nf-wdfinterrupt-wdfinterruptsetpolicy.  (I added a link to this page on https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdffdo/nc-wdffdo-evt_wdf_device_filter_resource_requirements which should be live soon.)

The related code is available here on GitHub, if you want to understand or trace into exactly how IRP_MN_FILTER_RESOURCE_REQUIREMENTS is processed.

https://github.com/microsoft/Windows-Driver-Frameworks/blob/main/src/framework/shared/irphandlers/pnp/km/fxpkgfdokm.cpp#L43

FxPkgFdo::PnpFilterResourceRequirements()

-   call EvtDeviceFilterRemoveResourceRequirements if available
-   pass IRP down
-   FxPkgPnp::FilterResourceRequirements
-   call EvtDeviceFilterAddResourceRequirements if available

https://github.com/microsoft/Windows-Driver-Frameworks/blob/main/src/framework/shared/irphandlers/pnp/km/fxpkgpnpkm.cpp#L16

FxPkgPnp::FilterResourceRequirements()

-   FxInterrupt::FilterResourceRequirements

https://github.com/microsoft/Windows-Driver-Frameworks/blob/main/src/framework/shared/irphandlers/pnp/km/interruptobjectkm.cpp#L216

FxInterrupt::FilterResourceRequirements()

-   Apply policy if WdfInterruptSetPolicy was called

Hope this helps!
