### ISSUE TITLE
Extra text in minimum supported client field

### ISSUE THREAD

**Issue by badasahog** [MicrosoftDocs/windows-driver-docs-ddi#1378]
The Minimum supported client field is stuffed with extra text, makes it needlessly difficult to read quickly

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e5a91d4-cfc3-76b7-3f20-b00a5e5028f6
* Version Independent ID: 2c2c7aee-d163-f822-ea46-dab6bda3a09e
* Content: [RtlNtStatusToDosErrorNoTeb function (ntifs.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlntstatustodoserrornoteb)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-rtlntstatustodoserrornoteb.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-rtlntstatustodoserrornoteb.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
That was indeed quite a mouthful to say little, @badasahog! I've reduced the verbosity on this page (any many other ntifs.h refpages).
