### ISSUE TITLE
Device Power Management section has repititions

### ISSUE THREAD

**Issue by msudhakargit** [MicrosoftDocs/windows-driver-docs-ddi#1381]
[Enter feedback here]

Just a minor, Device Power Management section 3'rd/4'th paras are repetition of para 1 and 2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0a69c83-8e5a-df94-2fb6-c2e19bc2b60a
* Version Independent ID: 6de870f8-62d4-c6a8-1b70-69b5276437e0
* Content: [Windows kernel - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/_kernel/#device-power-management)
* Content Source: [wdk-ddi-src/content/_kernel/index.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/_kernel/index.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the sharp eye!  I just pushed a fix for this, should appear on the live site shortly.
