### ISSUE TITLE
Fields undocumented in FEATURE_DATA_CORE

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/windows-driver-docs-ddi#1386]
Leaving fields without even a single line of text is not good.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c54a1-bf8a-feaf-6edf-ef4e9cb90236
* Version Independent ID: 70645bad-b510-5172-eada-84527b9d6502
* Content: [_FEATURE_DATA_CORE (ntddmmc.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddmmc/ns-ntddmmc-_feature_data_core)
* Content Source: [wdk-ddi-src/content/ntddmmc/ns-ntddmmc-_feature_data_core.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddmmc/ns-ntddmmc-_feature_data_core.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Really appreciate your issue reports/PRs, @henke37! I've updated the fields that were previously empty.
