### ISSUE TITLE
DeviceType links to incorrect page

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/windows-driver-docs-ddi#1388]
The explanation for the `DeviceType` field links to an unrelated page that is incompatible with the actual `#define` directives in the header file (scsi.h lines 2816-2842 in my copy).
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d59b068-c4a4-00e3-9fd8-1b8690f03e7b
* Version Independent ID: 4d6e6277-8410-72a4-b721-ec5d6c08f11a
* Content: [INQUIRYDATA (scsi.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/scsi/ns-scsi-_inquirydata)
* Content Source: [wdk-ddi-src/content/scsi/ns-scsi-_inquirydata.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/scsi/ns-scsi-_inquirydata.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hey @henke37, thanks so much for this issue! I've corrected the page with the scsi.h-defined values.
