### ISSUE TITLE
RscTcpTimestampDelta is of type ULONG but listed as NDIS_RSC_NBL_INFO (which is incorrect)

### ISSUE THREAD

**Issue by deepaknarula** [MicrosoftDocs/windows-driver-docs-ddi#139]
Information regarding RscTcpTimestampDelta is incorrect on the page https://msdn.microsoft.com/en-us/library/windows/hardware/ff566569(v=vs.85).aspx.
This is of type ULONG but is listed as NDIS_RSC_NBL_INFO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c62dd790-c5b6-d0fe-cc59-d9a040f99207
* Version Independent ID: 970dc63b-c5cb-58e8-7b18-af94099a7da6
* Content: [_NDIS_NET_BUFFER_LIST_INFO](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/ne-ndis-_ndis_net_buffer_list_info)
* Content Source: [wdk-ddi-src/content/ndis/ne-ndis-_ndis_net_buffer_list_info.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/ne-ndis-_ndis_net_buffer_list_info.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @deepaknarula , it looks like the description from the parameter above it was copied to that one. Good catch. I've corrected it to say that the value is a ULONG, and the update should be live later today.

Thanks! For corrections like this in the future, also feel free to submit a pull request and we can merge it in for you.
