### ISSUE TITLE
incorrect header file listed

### ISSUE THREAD

**Issue by badasahog** [MicrosoftDocs/windows-driver-docs-ddi#1390]
In the header file field it says "d3dkmdt.h", but the d3dkmdt.h file contains the following preprocessor directives:

#if !defined(_D3DKMDDI_H_)      && \
    !defined(_D3DKMDDI_PEXT_H_) && \
    !defined(_DXGDMM_H_)        && \
    !defined(_VIDPRIV_H_)       && \
    !defined(_DISPMPRT_H_)      && \
    !defined(_DMM_DIAG_H_)      && \
    !defined(_D3DKMTHK_H_)
   #error This header should not be included directly!
#endif

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07cc762f-21f1-bc6a-0c35-a979bb85871e
* Version Independent ID: 7244fbbe-ccde-3f35-539a-a3bd1a9cac59
* Content: [_D3DKMDT_VIDEO_SIGNAL_STANDARD (d3dkmdt.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_signal_standard)
* Content Source: [wdk-ddi-src/content/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_signal_standard.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_signal_standard.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for the issue, @badasahog. The header definition was correct (file in which it is declared), but the include details were missing (file(s) to actually include) - I've added those!
