### ISSUE TITLE
Is the table with possible values used for `Mask` arguments up-to-date?

### ISSUE THREAD

**Issue by kdluzews** [MicrosoftDocs/windows-driver-docs-ddi#1391]
[Enter feedback here]
Based on nttdk.h header in WDK there are more values than the ones mentioned in this documentation page. Are those missing or are not supported by KeSaveExtendedProcessorState function?

Values in nttdk.h:
```
#define XSTATE_MASK_LEGACY_FLOATING_POINT   (1ui64 << (XSTATE_LEGACY_FLOATING_POINT))
#define XSTATE_MASK_LEGACY_SSE              (1ui64 << (XSTATE_LEGACY_SSE))
#define XSTATE_MASK_LEGACY                  (XSTATE_MASK_LEGACY_FLOATING_POINT | \
                                             XSTATE_MASK_LEGACY_SSE)

#define XSTATE_MASK_GSSE                    (1ui64 << (XSTATE_GSSE))
#define XSTATE_MASK_AVX                     (XSTATE_MASK_GSSE)
#define XSTATE_MASK_MPX                     ((1ui64 << (XSTATE_MPX_BNDREGS)) | \
                                             (1ui64 << (XSTATE_MPX_BNDCSR)))

#define XSTATE_MASK_AVX512                  ((1ui64 << (XSTATE_AVX512_KMASK)) | \
                                             (1ui64 << (XSTATE_AVX512_ZMM_H)) | \
                                             (1ui64 << (XSTATE_AVX512_ZMM)))

#define XSTATE_MASK_IPT                     (1ui64 << (XSTATE_IPT))
#define XSTATE_MASK_CET_U                   (1ui64 << (XSTATE_CET_U))
#define XSTATE_MASK_CET_S                   (1ui64 << (XSTATE_CET_S))
#define XSTATE_MASK_AMX_TILE_CONFIG         (1ui64 << (XSTATE_AMX_TILE_CONFIG))
#define XSTATE_MASK_AMX_TILE_DATA           (1ui64 << (XSTATE_AMX_TILE_DATA))
#define XSTATE_MASK_LWP                     (1ui64 << (XSTATE_LWP))
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 344914d3-da14-ab3c-ac5e-232b1c5f3d9b
* Version Independent ID: 27ade4b4-946a-21ac-7602-42f70f21173a
* Content: [KeSaveExtendedProcessorState function (wdm.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kesaveextendedprocessorstate)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-kesaveextendedprocessorstate.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-kesaveextendedprocessorstate.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Hi Karol, thanks for the feedback.  It turns out that there were 4 missing entries from that table.  I have added them to the page.  Hope this helps!  

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kesaveextendedprocessorstate
