### ISSUE TITLE
NdisMMapIoSpace links point to SDV rule rather than function

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-driver-docs-ddi#1392]
In the "NdisMoveMemory macro (ndis.h)" article, the "NdisMMapIoSpace" links point to [NdisMMapIoSpace rule (ndis)](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/ndis-ndismmapiospace), but they should point to [NdisMMapIoSpace function (ndis.h)](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/nf-ndis-ndismmapiospace).

I did not check whether other articles have the same error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 658062ef-1831-edeb-756b-81fa00ebdf99
* Version Independent ID: 76fa06c9-1783-c0ce-c9a8-a420ef8cd6a2
* Content: [NdisMoveMemory macro (ndis.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/nf-ndis-ndismovememory)
* Content Source: [wdk-ddi-src/content/ndis/nf-ndis-ndismovememory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nf-ndis-ndismovememory.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @KalleOlaviNiemitalo, Thanks for letting us know about this issue. I've updated the links to the NdisMMapIoSpace function in this article as well as others that had the same bug. Appreciate you taking the time to let us know!
