### ISSUE TITLE
The link to ZwQueryDirectoryFile leads to ZwQueryVirtualMemory

### ISSUE THREAD

**Issue by zefklop** [MicrosoftDocs/windows-driver-docs-ddi#1394]
Title says it all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5382448c-3096-a543-1f02-321ba8b17909
* Version Independent ID: 8c0dfb6a-79cf-5af4-339c-d5ef2e38cc86
* Content: [FILE_NAMES_INFORMATION (ntifs.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_names_information)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_file_names_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_file_names_information.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @zefklop! I've fixed the link.
