### ISSUE TITLE
what is pCryptoType?

### ISSUE THREAD

**Issue by yantangx** [MicrosoftDocs/windows-driver-docs-ddi#1398]
[Enter feedback here]
Could you describe what is pCryptoType used for and what is the value of it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c544fc6e-03be-95f2-7913-a37a86028061
* Version Independent ID: 1a0687a0-fcb1-822a-75d7-32321c83d5a8
* Content: [D3DWDDM2_0DDI_VIDEO_CAPABILITY_DECODER_CAPS (d3d10umddi.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d10umddi/ns-d3d10umddi-d3dwddm2_0ddi_video_capability_decoder_caps)
* Content Source: [wdk-ddi-src/content/d3d10umddi/ns-d3d10umddi-d3dwddm2_0ddi_video_capability_decoder_caps.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3d10umddi/ns-d3d10umddi-d3dwddm2_0ddi_video_capability_decoder_caps.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting the missing info, @yantangx! I've updated the page.
