### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by shaharlux** [MicrosoftDocs/windows-driver-docs-ddi#140]
Isn't that structure supported on Windows 7 (SP1) as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fe2f032-89db-c787-ee72-ecca90fb1fe0
* Version Independent ID: fd400891-666b-3937-e51e-dfd1d1db9d25
* Content: [_FILE_FS_SECTOR_SIZE_INFORMATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/ns-ntddk-_file_fs_sector_size_information)
* Content Source: [wdk-ddi-src/content/ntddk/ns-ntddk-_file_fs_sector_size_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/ns-ntddk-_file_fs_sector_size_information.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @shaharlux, it looks like this structure is supported on Windows 7. Thanks for letting us know; I'll update the documentation!
