### ISSUE TITLE
inconsistent value of D3D11_1DDI_VIDEO_FUNCTIONS

### ISSUE THREAD

**Issue by xyliu** [MicrosoftDocs/windows-driver-docs-ddi#1402]
```
n19041/Include/10.0.19041.0/um/d3d10umddi.h
7090:#define D3D11_1DDI_VIDEO_FUNCTIONS   2       // Sub ID for video function table
7093:#define D3DWDDM2_0DDI_VIDEO_FUNCTIONS   3    // Sub ID for 2.0 video function table
7096:#define D3DWDDM2_1DDI_VIDEO_FUNCTIONS   5    // Sub ID for 2.1 video function table
7099:#define D3DWDDM2_4DDI_VIDEO_FUNCTIONS_RS4_0   6    // Sub ID for 2.4 video function table
7100:#define D3DWDDM2_4DDI_VIDEO_FUNCTIONS         7    // Sub ID for 2.4 video function table
```
in d3d10umddi.h, `D3D11_1DDI_VIDEO_FUNCTIONS`  is 2, but the page said it's 1.

<html>
<body>
<p style="box-sizing: inherit; outline-color: inherit; margin: 1rem 0px 0px; padding: 0px; overflow-wrap: break-word; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="box-sizing: inherit; outline-color: inherit; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 13.6px; direction: ltr; background-color: var(--theme-inline-code); overflow-wrap: break-word; border-radius: 3px; padding: 0.1em 0.2em;">SubDeviceID</code></p><p style="box-sizing: inherit; outline-color: inherit; margin: 1rem 0px 0px; padding: 0px; overflow-wrap: break-word; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The function table being retrieved, with the following possible values.</p><div class="has-inner-focus" style="box-sizing: inherit; outline-color: inherit; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Value | Meaning
-- | --
1 | A video function table that is described as a structure. The function returns a D3D11_1DDI_VIDEODEVICEFUNCS structure in the buffer referenced by the pOutputParamsBuffer parameter.

</div>
</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c8ba5a6-10d0-47d9-3af6-fd6d5e68fcc1
* Version Independent ID: 4c015007-cbcf-8e0e-04f0-715ac117eed3
* Content: [PFND3D10DDI_RETRIEVESUBOBJECT (d3d10umddi.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d10umddi/nc-d3d10umddi-pfnd3d10ddi_retrievesubobject?redirectedfrom=MSDN)
* Content Source: [wdk-ddi-src/content/d3d10umddi/nc-d3d10umddi-pfnd3d10ddi_retrievesubobject.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3d10umddi/nc-d3d10umddi-pfnd3d10ddi_retrievesubobject.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**1	A video function table that is described as a structure. The function returns a [D3D11_1DDI_VIDEODEVICEFUNCS](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d10umddi/ns-d3d10umddi-d3d11_1ddi_videodevicefuncs) structure in the buffer referenced by the pOutputParamsBuffer parameter.SubDeviceID

The function table being retrieved, with the following possible values.

Value	Meaning
1	A video function table that is described as a structure. The function returns a [D3D11_1DDI_VIDEODEVICEFUNCS](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d10umddi/ns-d3d10umddi-d3d11_1ddi_videodevicefuncs) structure in the buffer referenced by the pOutputParamsBuffer parameter.
3	A WDDM 2.0 and later video function table that is described as a structure. The function returns a [D3DWDDM2_0DDI_VIDEODEVICEFUNCS](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d10umddi/ns-d3d10umddi-d3dwddm2_0ddi_videodevicefuncs) structure in the buffer referenced by the pOutputParamsBuffer parameter.
Supported starting with WDDM 2.0.SubDeviceID

The function table being retrieved, with the following possible values.

Value	Meaning
1	A video function table that is described as a structure. The function returns a [D3D11_1DDI_VIDEODEVICEFUNCS](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d10umddi/ns-d3d10umddi-d3d11_1ddi_videodevicefuncs) structure in the buffer referenced by the pOutputParamsBuffer parameter.

**Comment by lorihollasch** [comment]
Thanks for reporting this inconsistency, @xyliu! I've updated the page, correcting the values and adding missing info.
