### ISSUE TITLE
The unicode format codes that require IRQL passive in dbgprint

### ISSUE THREAD

**Issue by bradhodge** [MicrosoftDocs/windows-driver-docs-ddi#1404]
The unicode format codes that is mentioned should be the following list:

(%C, %S, %lc, %ls, %wc, %ws, and %wZ). In this page, only two is mentioned. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdd9c906-0122-7c0f-e9bf-61021e1d8fde
* Version Independent ID: 475e8ab8-c62a-91f3-831a-f0cfc46315a5
* Content: [DbgPrint function (wdm.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-dbgprint)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-dbgprint.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-dbgprint.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by DOMARS** [comment]
@bradhodge - Thanks for this PR and I agree that the list was partial and not complete. I updated the topic to list out all of the unicode strings, which I think is a bit more clear. So thanks for filing this issue, and helping to improve the Windows developer docs.
