### ISSUE TITLE
Getting STATUS_INVALID_PARAMETER with IRP_MJ_READ

### ISSUE THREAD

**Issue by poweradminllc** [MicrosoftDocs/windows-driver-docs-ddi#1405]
The documentation indicates STATUS_INVALID_PARAMETER will be returned if FltLockUserBuffer is called on IRPs other than those listed above.  However, I am getting that results from IRP_MJ_READ on Windows Server 2019, so apparently there are other cases as well.  It would be nice to know what those cases are (i.e. why it is happening).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eedb269e-54b6-4a9f-0879-58c159f9f598
* Version Independent ID: 023ca106-8610-4721-c468-056a77868b6d
* Content: [FltLockUserBuffer function (fltkernel.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltlockuserbuffer)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltlockuserbuffer.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltlockuserbuffer.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this issue, @poweradminllc! There is indeed a special case where INVALID_PARAM is returned for READ and WRITE IRPs that have IRP_MN_MDL. I've updated the page to note this special case and included an explanation for it.
