### ISSUE TITLE
IRQL for pre operations of minifilters need to be specified in a table.

### ISSUE THREAD

**Issue by bradhodge** [MicrosoftDocs/windows-driver-docs-ddi#1407]
In this page, the following sentence is vague "The IRQL for this generic callback routine depends on its specific IO paths", because there is no other MSDN page that specifies for example what is the IRQL for pre create or pre write?

There need to be a table of some sort in this page or another page, that specifies the IRQL for each possible callback. I as a developer need to know the IRQL for every possible pre callback such as create, read, write, etc. 

There is also another page, https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/writing-preoperation-callback-routines that kinda explains this, but that one is still vague, and I need to know exactly whether the pre create callback for example is called at passive or equal or less than dispatch or..

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b2e99d-ff12-2ff8-5ae9-7c9e93f6a283
* Version Independent ID: 1e9882d1-f043-3f2f-0301-ea25695f6786
* Content: [PFLT_PRE_OPERATION_CALLBACK (fltkernel.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nc-fltkernel-pflt_pre_operation_callback)
* Content Source: [wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_pre_operation_callback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_pre_operation_callback.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Sorry @bradhodge, but a comprehensive table of I/O paths isn't possible. I've updated this page with a link to KeGetCurrentIRQL (which is just a quick register check). I also created an IRQL section on "[Writing Pre-op Callback Routines](https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/writing-preoperation-callback-routines)" with additional information (including an explanation of FltMgr's dilemma).
