### ISSUE TITLE
DeviceObjectList must be allocated from nonpaged pool

### ISSUE THREAD

**Issue by stoitchog** [MicrosoftDocs/windows-driver-docs-ddi#1408]
[Enter feedback here]
The method internally acquires a spinlock, thus elevating the IRQL to DISPATCH. 
The **DeviceObjectList** memory is accessed at DISPATCH and has to be allocated from NONPAGED pool.
This has to be mentioned because even the driver verifier doesn't catch this issue. The reason being is that the ddi internally uses **KeAcquireQueuedSpinLock** the latter being internal OS ddi looks like is not hooked/monitored by the driver versifier.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43fef58d-83de-7563-c191-696025328d99
* Version Independent ID: ff4032f7-f197-822f-ac3f-a33d2f5b442f
* Content: [IoEnumerateDeviceObjectList function (ntifs.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ioenumeratedeviceobjectlist)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ioenumeratedeviceobjectlist.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ioenumeratedeviceobjectlist.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Great call-out, @stoitchog - I've added the nonpaged mem requirement to the parameter description. Thanks for pointing this out!
