### ISSUE TITLE
Documentation conflicts with example

### ISSUE THREAD

**Issue by GF-Huang** [MicrosoftDocs/windows-driver-docs-ddi#1409]
> Make all changes to the FWPS_CONNECT_REQUEST0 structure that was returned by [FwpsAcquireWritableLayerDataPointer0](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nf-fwpsk-fwpsacquirewritablelayerdatapointer0). Only the **remoteAddressAndPort, portReservationToken, localRedirectTargetPID, localRedirectHandle, localRedirectContext, and localRedirectContextSize** members can be modified.

Given the above, why the [WFPSampler](https://github.com/microsoft/windows-driver-samples/tree/main/network/trans/WFPSampler) still setting the `localAddressAndPort` member?

![image](https://user-images.githubusercontent.com/4510984/213631678-51110a94-8965-4100-a879-ddec68ee74d4.png)

https://github.com/microsoft/Windows-driver-samples/blob/2c0c8763300988d92ddd139cadf012f5ab1b12e1/network/trans/WFPSampler/sys/ClassifyFunctions_ProxyCallouts.cpp#L1376-L1384

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a094452f-3181-c5c2-72a2-4ee16e5fc13e
* Version Independent ID: 2d8f6130-7df5-00a6-10bf-85883a7f9141
* Content: [_FWPS_CONNECT_REQUEST0 (fwpsk.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ns-fwpsk-_fwps_connect_request0)
* Content Source: [wdk-ddi-src/content/fwpsk/ns-fwpsk-_fwps_connect_request0.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fwpsk/ns-fwpsk-_fwps_connect_request0.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @GF-Huang,
Thanks for opening this issue. The WFPSampler is for both bind_redirect and connect_redirect. At the connect_redirect layers, modifying the localAddressAndPort is not supported (as the documentation for FWPS_CONNECT_REQUEST0 mentions). At the bind_redirect layers, you can set localAddressAndPort. Please see [FWPS_BIND_REQUEST0 structure](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ns-fwpsk-_fwps_bind_request0) for more information.
Thanks again. Please open a new issue if you have further questions.
