### ISSUE TITLE
Wrong content or wrong link?

### ISSUE THREAD

**Issue by LudekZaloudek** [MicrosoftDocs/windows-driver-docs-ddi#1419]
[Enter feedback here]

The Microsoft page https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ points to this page under the link marked as "I2C/SPI", however this page seems to be about "SPB" only. Am I missing something here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1b27f8a-0a9c-8d6d-b7a0-7b6481032b91
* Version Independent ID: 175f1daf-6cd7-392f-cf15-ab5a786e76e6
* Content: [Simple Peripheral Bus (SPB) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/_spb/)
* Content Source: [wdk-ddi-src/content/_spb/index.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/_spb/index.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by mhopkins-msft** [comment]
Hi @LudekZaloudek,

Thanks for reaching out to us. The link to SPB is correct, but the link text is outdated. I've updated the text to better reflect the link.

Thanks for helping us make the docs better!

 ~ *Mark*
