### ISSUE TITLE
Parameters unnamed for PHDAUDIO_DMA_NOTIFICATION_CALLBACK 

### ISSUE THREAD

**Issue by coolstar** [MicrosoftDocs/windows-driver-docs-ddi#1420]
Parameters for PHDAUDIO_DMA_NOTIFICATION_CALLBACK are unnamed. It's safe to assume the first one is the context, but the second parameter is unclear what it's supposed to be.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe7b3c6c-c7ae-f9dc-ddaa-570cc1e88e66
* Version Independent ID: 5fd0ee33-36b7-ce9a-55aa-b8db49ba6c22
* Content: [PHDAUDIO_DMA_NOTIFICATION_CALLBACK - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/hdaudio/nc-hdaudio-phdaudio-dma_notification_callback)
* Content Source: [wdk-ddi-src/content/hdaudio/nc-hdaudio-phdaudio-dma_notification_callback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/hdaudio/nc-hdaudio-phdaudio-dma_notification_callback.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@coolstar - Thanks for this issue. I believe we are having an issue with the publishing system not rendering the callback signature, and then as the field names don't match, not rendering the existing field descriptions that are in the topic.

As a work around, you can view the reference content in raw view. For this topic, for example:

https://raw.githubusercontent.com/MicrosoftDocs/windows-driver-docs-ddi/staging/wdk-ddi-src/content/hdaudio/nc-hdaudio-phdaudio-dma_notification_callback.md

That content shows the two (named) parameters.

### -param Context:

Driver-specific context value used when registering the callback routine.

### -param QPCDMANotificationTimestamp:

The QPC time when the IOC ISR handled the DMA interrupt.

I hope that we are able to restore the field level rendering as soon as possible, to avoid the use of the work around described above.
