### ISSUE TITLE
Type in MyEvtGpioPrepareControler code block for GPIO_CLIENT_PREPARE_CONTROLLER

### ISSUE THREAD

**Issue by matt1va** [MicrosoftDocs/windows-driver-docs-ddi#1421]
There is a type in the code block. There are two "r"s on the end of MyEvtGpioPrepareControler
```
_Use_decl_annotations_
NTSTATUS
  MyEvtGpioPrepareControllerr(
    WDFDEVICE Device,
    PVOID Context,
    WDFCMRESLIST ResourcesRaw,
    WDFCMRESLIST ResourcesTranslated
)
{ ... }
```

Should be 

```
_Use_decl_annotations_
NTSTATUS
  MyEvtGpioPrepareController(
    WDFDEVICE Device,
    PVOID Context,
    WDFCMRESLIST ResourcesRaw,
    WDFCMRESLIST ResourcesTranslated
)
{ ... }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c973bd9-d846-864c-f09e-ae28c479941e
* Version Independent ID: df66ad7f-ef51-1107-d093-8a32c46cdccc
* Content: [GPIO_CLIENT_PREPARE_CONTROLLER (gpioclx.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/gpioclx/nc-gpioclx-gpio_client_prepare_controller)
* Content Source: [wdk-ddi-src/content/gpioclx/nc-gpioclx-gpio_client_prepare_controller.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/gpioclx/nc-gpioclx-gpio_client_prepare_controller.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @matt1va, this is now fixed.  Appreciate the heads-up!
