### ISSUE TITLE
Boot Driver Callback cannot return STATUS_SUCCESS

### ISSUE THREAD

**Issue by assarbad** [MicrosoftDocs/windows-driver-docs-ddi#143]
The documentation of the **Boot Driver Callback** (_not_ the `IoRegisterBootDriverCallback` function itself!) states:

> **Return Value**
> 
> If the **BOOT_DRIVER_CALLBACK_FUNCTION** routine returns STATUS_SUCCESS, the boot-start driver was able to perform all necessary actions in response to the specific callback.

Alas, this cannot be the case, because the function type is (`VOID` return type):

```
typedef
VOID
BOOT_DRIVER_CALLBACK_FUNCTION (
    _in_opt_ PVOID CallbackContext,
    _in_ BDCB_CALLBACK_TYPE CallbackType,
    _in_opt_ PBDCB_IMAGE_INFORMATION CallbackTypeContext
    );
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25cedc30-4de9-6bd6-65aa-026e351f538a
* Version Independent ID: 1e912924-18b4-786d-9656-20030d543949
* Content: [IoRegisterBootDriverCallback function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-ioregisterbootdrivercallback)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-ioregisterbootdrivercallback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-ioregisterbootdrivercallback.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Thanks @assarbad, I've gone and fixed that. This should be live in the next day or so.

Thanks for catching this and bringing it to our attention!
