### ISSUE TITLE
  IN_CONST_HANDLE hContext definition is incorrect. Does not point to the context. 

### ISSUE THREAD

**Issue by jalpa14** [MicrosoftDocs/windows-driver-docs-ddi#1432]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1b13df3-5c86-03d6-4357-5b16bbbd1f3e
* Version Independent ID: 8eea9675-aa17-9997-0abb-5459ef6ee016
* Content: [DXGKDDI_VALIDATESUBMITCOMMAND (d3dkmddi.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/nc-d3dkmddi-dxgkddi_validatesubmitcommand)
* Content Source: [wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_validatesubmitcommand.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_validatesubmitcommand.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for pointing this out, @jalpa14! I've corrected the description (and updated some of the associated Submit/Validate refpages).
