### ISSUE TITLE
Heading and context are mismatching

### ISSUE THREAD

**Issue by Parihar07** [MicrosoftDocs/windows-driver-docs-ddi#1436]
""KSAUDIOMODULE_PROPERTY structure (ksmedia.h)
Article
04/01/2021
2 minutes to read
The _**KSAUDIOMODULE_DESCRIPTOR**_ structure describes the static, external properties of the audio modules.

Syntax
C++

Copy
typedef struct _KSAUDIOMODULE_PROPERTY {
  KSPROPERTY Property;
  GUID       ClassId;
  ULONG      InstanceId;
} KSAUDIOMODULE_PROPERTY, *PKSAUDIOMODULE_PROPERTY;"""

the one highlighted text should be "PKSAUDIOMODULE_PROPERTY" or this is wantedly shown likewise if so why ??
---
#### Document Details 

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae50d732-09e8-cc84-68b1-b0d84aabd239
* Version Independent ID: db5f3028-e150-b8ac-09f2-e47cd1c53479
* Content: [_KSAUDIOMODULE_PROPERTY (ksmedia.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ksmedia/ns-ksmedia-_ksaudiomodule_property)
* Content Source: [wdk-ddi-src/content/ksmedia/ns-ksmedia-_ksaudiomodule_property.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ksmedia/ns-ksmedia-_ksaudiomodule_property.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Thank you Parihar, you are exactly right!  The description had a typo, for which I just pushed a fix.  The fix should appear on the live site within the next hour or so.  Thanks again for letting us know.
