### ISSUE TITLE
NetAdapterSetCurrentLinkLayerAddress and NetAdapterSetPermanentLinkLayerAddress pages should link to NET_ADAPTER_LINK_LAYER_ADDRESS

### ISSUE THREAD

**Issue by guyharris** [MicrosoftDocs/windows-driver-docs-ddi#1438]
The pages for [`NetAdapterSetCurrentLinkLayerAddress()`](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/netadapter/nf-netadapter-netadaptersetcurrentlinklayeraddress) and [`NetAdapterSetPermanentLinkLayerAddress()`](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/netadapter/nf-netadapter-netadaptersetpermanentlinklayeraddress) mention `NET_ADAPTER_LINK_LAYER_ADDRESS` in some places, but neither of those like to it.

They should probably link those references to https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/netadapter/ns-netadapter-net_adapter_link_layer_address. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1e37526-fac2-5df7-5010-0fe25357e1ef
* Version Independent ID: 63f791ae-96b8-49b8-a910-a314adce87ef
* Content: [NetAdapterSetCurrentLinkLayerAddress function (netadapter.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/netadapter/nf-netadapter-netadaptersetcurrentlinklayeraddress)
* Content Source: [wdk-ddi-src/content/netadapter/nf-netadapter-netadaptersetcurrentlinklayeraddress.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/netadapter/nf-netadapter-netadaptersetcurrentlinklayeraddress.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks for helping us improve the docs, @guyharris! We've added these links.
