### ISSUE TITLE
hyperlink to EVT_PACKET_QUEUE_CANCEL is pointing to EVT_PACKET_QUEUE_ADVANCE

### ISSUE THREAD

**Issue by TriumphantAkash** [MicrosoftDocs/windows-driver-docs-ddi#1439]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4b10ba-b1b9-1c07-7b79-368d0ef100b6
* Version Independent ID: 878a8122-d967-3832-78e5-5724b732d731
* Content: [NET_PACKET_QUEUE_CONFIG_INIT function (netpacketqueue.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/netpacketqueue/nf-netpacketqueue-net_packet_queue_config_init)
* Content Source: [wdk-ddi-src/content/netpacketqueue/nf-netpacketqueue-net_packet_queue_config_init.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/netpacketqueue/nf-netpacketqueue-net_packet_queue_config_init.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks for pointing out this doc bug @TriumphantAkash! Link is now fixed.
