### ISSUE TITLE
Possible return values are missing

### ISSUE THREAD

**Issue by GabeSJones** [MicrosoftDocs/windows-driver-docs-ddi#144]
Subject says it all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed73ca2d-b1dd-41dc-4eb3-fe8a9dd27484
* Version Independent ID: d14a8675-e218-61f2-9940-29cdd2f6764a
* Content: [ZwDeleteKey function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwdeletekey)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwdeletekey.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwdeletekey.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @GabeSJones 
Added the following text that was dropped in a content migration:
ZwDeleteKey returns an NTSTATUS value. Possible return values include:
STATUS_SUCCESS
STATUS_ACCESS_DENIED
STATUS_INVALID_HANDLE
