### ISSUE TITLE
Incorrect documentation or mistake in API deployment

### ISSUE THREAD

**Issue by gnif** [MicrosoftDocs/windows-driver-docs-ddi#1441]
This page states that this API is available in `Windows 10, version 22H2` however windows 10 22H2 does not ship with this version of IddCx. Currently Windows 10 22H2 fully updated and patched only comes with IddCx 1.5.01 (`IddCxGetVersion` reports 0x1501).

According to https://learn.microsoft.com/en-us/windows-hardware/drivers/display/iddcx-versions windows 10 doesn't support this method either.

Can we please get an update for IddCx for Windows 10 to enable access to these features? or at the very minimum correct the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22f10e20-3b92-ca85-1205-54de0245845b
* Version Independent ID: 22f10e20-3b92-ca85-1205-54de0245845b
* Content: [IddCxSetRealtimeGPUPriority - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/iddcx/nf-iddcx-iddcxsetrealtimegpupriority)
* Content Source: [wdk-ddi-src/content/iddcx/nf-iddcx-iddcxsetrealtimegpupriority.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/iddcx/nf-iddcx-iddcxsetrealtimegpupriority.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Apologies for the confusion, @gnif, and thanks for reporting this! It was a typo - I've updated the OS to Windows 11 22H2.
