### ISSUE TITLE
Clarification needed on possible combinations of return value & output parameter

### ISSUE THREAD

**Issue by wmjdgla** [MicrosoftDocs/windows-driver-docs-ddi#1442]
Each of the `FltGetXxxContext` routines returns:
- a `NTSTATUS` value indicating whether the operation succeeded and;
- a context pointer via an output parameter.

Given this interface, the natural assumption would be:
| Returned Status | Context Pointer | Possible? |
| --- | --- | --- |
| STATUS_SUCCESS | not NULL | Yes |
| not STATUS_SUCCESS | NULL | Yes |
| STATUS_SUCCESS | NULL | No |
| not STATUS_SUCCESS | not NULL | No |

However, this isn't stated anywhere in the documentation, so callers always have to check both the returned status value and context pointer to make sure that they are not in the last 2 scenarios of the table. Can the documentation clarify this? If the behavior shown in the table is always true, then callers can just check the returned context pointer to know whether the operation succeeded.

Other affected pages:
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetcontexts
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetcontextsex
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetfilecontext
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetstreamcontext
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetstreamhandlecontext
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgettransactioncontext
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetvolumecontext

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3328e0e9-505b-03a2-b0b7-2d5d5aa5c3c1
* Version Independent ID: 77d47f4f-1a7c-8100-dc3c-48531f7f780a
* Content: [FltGetInstanceContext function (fltkernel.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetinstancecontext)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetinstancecontext.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetinstancecontext.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@wmjdgla, I've added clarifying comments to all of the FltGetXXXContext pages. Thanks for filing this issue!
