### ISSUE TITLE
Can you specify POOL_ZERO_ALLOCATION to PoolType?

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1445]
Lori, Dave,

It feels like, at least on modern OSs, it should be possible to specify `PagedPool | POOL_ZERO_ALLOCATION` to the 4 parameter.

Given the (excellent) work that has gone in to pushing zero allocation into the kernel and thus the documentation it would be nice to have a definitive answer.  Either
* You cannot specify this flag
* You can specify this flag from OS versions XXXXX
* You do not need to specify this flag because the memory is zeros.
Empirically it isn't on W1022H2 although that might be the best answer.
 
Thanks as always
            /Rod
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85a89578-ff87-89ed-722c-a1a2553efd24
* Version Independent ID: 05c5211a-559d-0f02-519c-1e0eaf2d218e
* Content: [FltAllocateContext function (fltkernel.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltallocatecontext?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(FLTKERNEL%252FFltAllocateContext)%3Bk(FltAllocateContext)%3Bk(vs.tfs.vctrl.DiffMerge.Legend)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltallocatecontext.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltallocatecontext.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
I've added details about the allocated context's contents, @rodwiddowson. Bottom line is: zeroed allocation was added where possible but it's not possible in all cases; and using POOL_ZERO_ALLOCATION could have detrimental performance issues. Really great issue to file - thanks as always!
