### ISSUE TITLE
Maximum timeout for DxgkDdiCollectDbgInfo

### ISSUE THREAD

**Issue by pacampbe** [MicrosoftDocs/windows-driver-docs-ddi#1448]
Is there a maximum time the driver can spend in `DxgkDdiCollectDbgInfo` before Windows takes some corrective action? I can't seem to find any mention of it in this page or another page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d145848-247e-15cc-c8b7-ededf22b5125
* Version Independent ID: 5ead064a-8e3a-0c44-3f41-173456b517ba
* Content: [DXGKDDI_COLLECTDBGINFO (d3dkmddi.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/nc-d3dkmddi-dxgkddi_collectdbginfo)
* Content Source: [wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_collectdbginfo.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_collectdbginfo.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hey @pacampbe , I updated the page with the info you were looking for (no max time). Thanks for filing a doc issue!
