### ISSUE TITLE
"Synchronization events are rarely used in a typical driver."

### ISSUE THREAD

**Issue by camptatopenmars** [MicrosoftDocs/windows-driver-docs-ddi#1449]
The statement "Synchronization events are rarely used in a typical driver." has been in the documentation for KeInitializeEvent I think essentially 'from the beginning of time'.  I've never found the statement to be true however, and in fact has misdirected me several times in my life to using a NotificationEvent when I intended to have a SynchronizationEvent.  Nearly every driver I've ever written uses SynchronizationEvents in the manner described... however "rarely used" is unhelpful editorial in this context and may scare inexperienced driver developers into using the wrong sychronization model causing bugs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18f579b1-0a03-2d6d-57f4-16a1c43b353c
* Version Independent ID: b61fccdd-6831-34a6-acff-b18db2c62dd3
* Content: [KeInitializeEvent function (wdm.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-keinitializeevent)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-keinitializeevent.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-keinitializeevent.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Thanks for the feedback @camptatopenmars.  You'll be pleased to know that after consultation with the kernel team, we've removed the sentence in question.  Appreciate your interest in the accuracy/helpfulness of the docs.
