### ISSUE TITLE
Recent phy types are missing in enum definition

### ISSUE THREAD

**Issue by Chanz82** [MicrosoftDocs/windows-driver-docs-ddi#1450]
[Enter feedback here]

dot11_phy_type_dmg, dot11_phy_type_he,  dot11_phy_type_eht are described in Constant section.
However, there are missing enum definition.

like...
dot11_phy_type_dmg = 9,  //11ad
 dot11_phy_type_he=10,     //11ax
 dot11_phy_type_eht=11,   //11be

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8763e75-7e14-bc14-2430-03b22e426cc7
* Version Independent ID: e5554518-42fc-0aa5-6e45-744df8c249e6
* Content: [_DOT11_PHY_TYPE (windot11.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/windot11/ne-windot11-_dot11_phy_type)
* Content Source: [wdk-ddi-src/content/windot11/ne-windot11-_dot11_phy_type.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/windot11/ne-windot11-_dot11_phy_type.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @Chanz82,
Thanks for opening this issue. I've updated the page with the new enum values.
Thanks for helping us improve our documentation!
