### ISSUE TITLE
Remarks is mistake

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/windows-driver-docs-ddi#1453]
[Enter feedback here]

I found out that the FILE_LINK_ENTRY_INFORMATION structure is 8-byte aligned.

so the code is :

        PFILE_LINK_ENTRY_INFORMATION Entry = &FileInformation->Entry;
        for (; ; Entry = (PFILE_LINK_ENTRY_INFORMATION)(((PBYTE)Entry + Entry->NextEntryOffset))) {
            printf("ParentFileId:%llx, FileName:%ls.\r\n", Entry->ParentFileId, Entry->FileName);

            //OpenFileById。

            if (0 == Entry->NextEntryOffset) {
                break;
            }
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52b3d7d7-3d4a-16da-0bad-7c6367d20de5
* Version Independent ID: a7d05cbf-eb3c-5ca5-45ce-db86ade13642
* Content: [_FILE_LINKS_INFORMATION (ntifs.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_links_information)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_file_links_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_file_links_information.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting the erroneous remarks, @kouzhudong! I finally got a moment to correct the page.
