### ISSUE TITLE
Wrong SIZEOF of NDIS_PM_PARAMETERS structure

### ISSUE THREAD

**Issue by dimaruinskiy-intel** [MicrosoftDocs/windows-driver-docs-ddi#1463]
The 'Members' section of the page instructs to set the Size member of the NDIS_OBJECT_HEADER to  NDIS_SIZEOF_NDIS_PM_CAPABILITIES_REVISION_X. It should be NDIS_SIZEOF_NDIS_PM_PARAMETERS_REVISION_X.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a53c218-18be-5fb4-8a41-ede2d7b8ecda
* Version Independent ID: a7c40a8d-e6c6-9cdb-355f-a44ce05ce015
* Content: [_NDIS_PM_PARAMETERS (ntddndis.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_pm_parameters)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_pm_parameters.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_pm_parameters.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks, @dimaruinskiy-intel, for helping us improve the docs! We've updated this API page.
