### ISSUE TITLE
section is mssing

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/windows-driver-docs-ddi#1464]
`You must declare the function by using the EVT_WDF_DRIVER_UNLOAD type. For more information, see the following Example section.`

But Example section does not exist in the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ae9d-cf43-bbbf-c461-a338c48160aa
* Version Independent ID: 6aa7ba67-edcf-6d87-7e28-b0d7f02ec759
* Content: [EVT_WDF_DRIVER_UNLOAD (wdfdriver.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdriver/nc-wdfdriver-evt_wdf_driver_unload)
* Content Source: [wdk-ddi-src/content/wdfdriver/nc-wdfdriver-evt_wdf_driver_unload.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdriver/nc-wdfdriver-evt_wdf_driver_unload.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @hsebs for the sharp eye.  This was part of some old boilerplate and there was another occurrence on another nc* page.  I just removed it from both pages.
