### ISSUE TITLE
Requirements: DLL	NtDll.dll (user mode); NtosKrnl.exe (kernel mode)

### ISSUE THREAD

**Issue by markyoung2u** [MicrosoftDocs/windows-driver-docs-ddi#1467]
Under Requirements it has "DLL" and shows "NtDll.dll (user mode); NtosKrnl.exe (kernel mode)" - should .exe be .dll for NtosKrnl.exe?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd24a719-9e17-c052-6b4a-de939ed1170e
* Version Independent ID: b877dadf-a254-e953-8e03-d94bf72fad3b
* Content: [RtlCopyMemory macro (wdm.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlcopymemory)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtlcopymemory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlcopymemory.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@markyoung2u, thanks for filing an issue with the Windows driver docs team. The NtosKrnl.exe filename is correct as shown in the requirements section of the article. You can search the C:\Windows folder on your system and find multiple architecture-specific versions of the file. For example, C:\Windows\System32\ntoskrnl.exe (you may need to show hidden items to see these files).

For more information about ntoskrnl.exe, see the first paragraph of the [Libraries and Headers](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/libraries-and-headers) article.
