### ISSUE TITLE
Please document `SeLocateProcessImageName`

### ISSUE THREAD

**Issue by gabriellandau** [MicrosoftDocs/windows-driver-docs-ddi#1474]
Hello again!  `SeLocateProcessImageName` (described by CodeMachine [here](https://codemachine.com/articles/top_ten_kernel_apis.html#SeLocateProcessImageName)) provides kernel drivers with a way to query an EPROCESS's image's filename:

```
NTSTATUS
SeLocateProcessImageName(
    _Inout_ PEPROCESS Process,
    _Outptr_ PUNICODE_STRING *pImageFileName
    );
```

It's more performant than the following method of obtaining this information because it doesn't require any handle creation/destruction/references and can be done in a single function call.

1. `ObOpenObjectByPointer(pProcess, &hProcess)`
2. `ZwQueryInformationProcess(hProcess, ProcessImageFileName)` to get length
3. `ExAllocatePool`
4. `ZwQueryInformationProcess(hProcess, ProcessImageFileName)` to get the path
5. `ZwClose(hProcess)`

Since it's listed in ntifs.h in at least the 22000.0 & 22621.0 EWDKs, could you please document it for safe use?

**Comment by lorihollasch** [comment]
Hi again, @gabriellandau! Thanks as always for your issues. This function's refpage is now live: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-selocateprocessimagename

**Comment by gabriellandau** [comment]
Looks great.  Thanks @lorihollasch!
