### ISSUE TITLE
DbgPrompt bug

### ISSUE THREAD

**Issue by lxzlovelyidiot** [MicrosoftDocs/windows-driver-docs-ddi#1476]
OS: Windows 11 22H2 22621.2134
API: ntdll!RtlAssert

in ntdll!RtlAssert
DbgPrompt return 0(STAUS_SUCCESS), but the response(param 2) is not overwritten, then windbg is not break. 

example:
RtlAssert((PVOID)"express", (PVOID)__FILE__, __LINE__, "will output loop any more");

windbg:
will output "will output loop any more" loop

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53868ae7-ec68-d928-3021-04b4c71a4237
* Version Independent ID: df2be679-ea12-265c-5b27-5b5b5dace2ac
* Content: [DbgPrompt function (ntddk.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-dbgprompt)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-dbgprompt.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-dbgprompt.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by DOMARS** [comment]
@lxzlovelyidiot - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don't have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [OSR's ntdev List](https://community.osr.com/categories/ntdev) or [OSR's windbg List](https://community.osr.com/categories/windbg). You can post your question there, and the community of developers usually give feedback fairly quickly. Good luck with your use of the DbgPrompt function.
