### ISSUE TITLE
WdfIoQueueReadyNotify

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs-ddi#148]
The "See also" section of this page should reference WdfIoQueueReadyNotify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7de6b858-0ba8-df0b-e115-d88ef34940bd
* Version Independent ID: b23b8d83-86e4-fb10-7d80-2ba0b2e2b1df
* Content: [_WDF_IO_QUEUE_CONFIG](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfio/ns-wdfio-_wdf_io_queue_config#feedback)
* Content Source: [wdk-ddi-src/content/wdfio/ns-wdfio-_wdf_io_queue_config.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfio/ns-wdfio-_wdf_io_queue_config.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @jakeoshins 
Updated in source. Should be live within 24 hours.
