### ISSUE TITLE
Wrong description of struct field

### ISSUE THREAD

**Issue by wmjdgla** [MicrosoftDocs/windows-driver-docs-ddi#1482]
> `CompletionRoutine`
> 
> The completion routines that is invoked depending on the flags in the preceding flags field.

It depends on the `Control` field, not the `Flags` field. There are no flags described for the `Flags` field that controls when the completion routine is invoked. If you use windbg to start a kernel debug session and dump an IRP:
```
0: kd> !irp ac598dc8
Irp is active with 2 stacks 1 is current (= 0xac598e38)
 No Mdl: No System Buffer: Thread 8d1c7bc0:  Irp stack trace.  
     cmd  flg cl Device   File     Completion-Context
>[IRP_MJ_FILE_SYSTEM_CONTROL(d), N/A(0)]
            1 e1 8a6434d8 ac598d40 853220cb-a89682d8 Success Error Cancel pending
           \FileSystem\Npfs fltmgr!FltpPassThroughCompletion
            Args: 00000000 00000000 00110008 00000000
 [IRP_MJ_FILE_SYSTEM_CONTROL(d), N/A(0)]
            1  0 8a799710 ac598d40 00000000-00000000    
           \FileSystem\FltMgr
            Args: 00000000 00000000 0x00110008 00000000
```
It shows that the `fltmgr!FltpPassThroughCompletion` completion routine will be executed on success, error, or cancel.

If we `dt` the current `IO_STACK_LOCATION`, you'll find that the `Control` field is set with the following flags:
- `SL_INVOKE_ON_SUCCESS`
- `SL_INVOKE_ON_ERROR`
- `SL_INVOKE_ON_CANCEL`
- `SL_PENDING_RETURNED`
Which matches exactly what `!irp` shows.

---

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1b1c00f-1701-5665-cdeb-6120305abc72
* Version Independent ID: 2f6bf8f4-3e19-e4e1-36f4-fcaa8e40c467
* Content: [IO_STACK_LOCATION (wdm.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_io_stack_location)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_io_stack_location.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_io_stack_location.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Thanks @wmjdgla for the feedback.  You are correct!  I have updated the description of the Control member on https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_io_stack_location to reflect this.
