### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by anrossi** [MicrosoftDocs/windows-driver-docs-ddi#1483]
The Remarks section references GSO when it intends RSC. I assume this is a simple copy&paste error while writing the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bf8a33c-12c3-9d9c-1182-49b1b58411c7
* Version Independent ID: 0e44bf42-70a9-c6d3-4928-0212f37d957b
* Content: [NET_ADAPTER_OFFLOAD_RSC_CAPABILITIES_INIT function (netadapteroffload.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/netadapteroffload/nf-netadapteroffload-net_adapter_offload_rsc_capabilities_init)
* Content Source: [wdk-ddi-src/content/netadapteroffload/nf-netadapteroffload-net_adapter_offload_rsc_capabilities_init.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/netadapteroffload/nf-netadapteroffload-net_adapter_offload_rsc_capabilities_init.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks for helping us improve the docs @anrossi! The fix will be live on the site soon.
