### ISSUE TITLE
The documentation of DDI - "DxgkDdiResetHwEngine" is missing.

### ISSUE THREAD

**Issue by rts2-work** [MicrosoftDocs/windows-driver-docs-ddi#1484]
This page lists documentation of the DDI - "DxgkDdiResumeHwEngine"; however, documentation of the corresponding reset-handling DDI - "DxgkDdiResetHwEngine" is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02923479-e551-4914-a834-3bb7d36f0bf3
* Version Independent ID: d8d1c36c-2714-be46-6354-81839784fc2d
* Content: [DXGKDDI_RESUMEHWENGINE (d3dkmddi.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/nc-d3dkmddi-dxgkddi_resumehwengine)
* Content Source: [wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_resumehwengine.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_resumehwengine.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for pointing out the missing page, @rts2-work. A page for [DxgkDdiResetHwEngine](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/nc-d3dkmddi-dxgkddi_resethwengine) is now live.
