### ISSUE TITLE
Does this function return STATUS_ACCESS_DENIED

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1485]
It is sort of inferred that this is a shim on `MmProbeAndLockPages`  followed by `MmGetSystemAddressForMdlSafe` (this page talks about `IoWriteAccess` and `IoReadAccess`), but the return status doesn't include  a status to return ("user is pulling a fast one and trying to get access to memory they shouldn't) - it does say "and other statuses),

Can we improve the text to make it explicit that the memory is probed *or* that the caller needs to do it,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eedb269e-54b6-4a9f-0879-58c159f9f598
* Version Independent ID: 023ca106-8610-4721-c468-056a77868b6d
* Content: [FltLockUserBuffer function (fltkernel.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltlockuserbuffer?devlangs=cpp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(FLTKERNEL%252FFltLockUserBuffer)%3Bk(FltLockUserBuffer)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltlockuserbuffer.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltlockuserbuffer.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi @rodwiddowson and thanks for this issue. I've add clarification that FltLockUserBuffer does indeed probe user buffers.
