### ISSUE TITLE
NET_BUFFER_FIRST_MDL does not return void, it returns a MDL

### ISSUE THREAD

**Issue by nhamer** [MicrosoftDocs/windows-driver-docs-ddi#1487]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd7aeeff-97c0-81f6-b50e-a90f8d5401c5
* Version Independent ID: 2e112fa8-a1ef-fd3f-68f9-fcbfa924adb4
* Content: [NET_BUFFER_FIRST_MDL - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/nblaccessors/nf-nblaccessors-net_buffer_first_mdl)
* Content Source: [wdk-ddi-src/content/nblaccessors/nf-nblaccessors-net_buffer_first_mdl.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/nblaccessors/nf-nblaccessors-net_buffer_first_mdl.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thank you for helping us improve the docs, @nhamer. The fix for this issue will be live on the site shortly.
