### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by DarkLinux** [MicrosoftDocs/windows-driver-docs-ddi#1488]
[Enter feedback here]
_Specifies **he** time that the file was last written to._
Should be _the_
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8de2bc24-bcf6-8c8e-46a0-be6c4934d175
* Version Independent ID: b9315d9a-6a43-d433-63ec-471daa1a45b2
* Content: [_FILE_NETWORK_OPEN_INFORMATION (wdm.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_file_network_open_information)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_file_network_open_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_file_network_open_information.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Thanks @DarkLinux appreciate the sharp eye.  I just pushed a fix, should be on the live site within the hour.
