### ISSUE TITLE
Missing key information for proper use

### ISSUE THREAD

**Issue by nottoc** [MicrosoftDocs/windows-driver-docs-ddi#1489]
Other functions of this type, call it first with no buffer, it returns the count of items that would be returned. Call it a second time after allocating space it the results. Yet there is no mention in this documentation, or if this is how this function works. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5deebc-f61f-7f58-7fee-53e744a250d5
* Version Independent ID: 27442469-f3d1-6202-0613-25eebb091b17
* Content: [D3DKMTGetDisplayModeList function (d3dkmthk.h) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmthk/nf-d3dkmthk-d3dkmtgetdisplaymodelist)
* Content Source: [wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtgetdisplaymodelist.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtgetdisplaymodelist.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for the issue, @nottoc! I've added the missing details to the page.
