### ISSUE TITLE
Any reason why CcSetFileSizesEx is not documented?

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1506]
### Type of issue

Typo

### Feedback

Hey @lorihollasch , @tedhudek 

I just discovered that VS had "helped me" some time ago and autocompleted a `CcSetFileSizes` into a `CcSetFileSizesEx`.  This is an old bug fix and I am now wondering whether the difference mattered.

But the newer function  isn't mentioned in here I assume that
* This is an oversight _or_
* This is a "paws off" function and I should change my code back
This is by way of asking which? 

Thanks (and festive what-nots by the way)

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ccsetfilesizes

### Content source URL

Dunno

### Author

Dunno

**Comment by lorihollasch** [comment]
Hi @rodwiddowson - apologies for my slow reponse on this issue! I've created a page for CcSetFileSizesEx. It basically does the same thing as CcSetFileSizes but also returns an NTSTATUS code. Hope you were able to enjoy some down time over the holidays - cheers to you!
