### ISSUE TITLE
wrong prototype NdisInterlockedRemoveHeadList and wrong "Return value" section

### ISSUE THREAD

**Issue by ybendito** [MicrosoftDocs/windows-driver-docs-ddi#1508]
### Type of issue

Typo

### Feedback

void - should be PLIST_ENTRY
Return value: the entry from the list or NULL
See proper article https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exinterlockedremoveheadlist?devlangs=cpp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(WDM%252FExInterlockedRemoveHeadList)%3Bk(ExInterlockedRemoveHeadList)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/nf-ndis-ndisinterlockedremoveheadlist?devlangs=cpp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NDIS56COMMON%252FPARANDIS_RECEIVE_QUEUE%253A%253ANdisInterlockedRemoveHeadList)%3Bk(PARANDIS_RECEIVE_QUEUE%253A%253ANdisInterlockedRemoveHeadList)%3Bk(NdisInterlockedRemoveHeadList)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nf-ndis-ndisinterlockedremoveheadlist.md

### Author

@aviviano

**Comment by aviviano** [comment]
Thanks @ybendito for helping us improve the docs! The fix will be love on the site shortly.
