### ISSUE TITLE
incorrect structure with _SRTL_ADVANCED_FCB_HEADER

### ISSUE THREAD

**Issue by Mas0nShi** [MicrosoftDocs/windows-driver-docs-ddi#1510]
@lorihollasch Thank you for your reply.
Sure, You are right. but, I think you misunderstood me...
I know about this, but the windbg show the last members of `FSRTL_ADVANCED_FCB_HEADER ` structure is

```
   +0x068 BypassIoOpenCount : Uint4B
   +0x070 ReservedContext  : Ptr64 _FSRTL_PER_STREAM_CONTEXT
```

but spec shows:

```
  PVOID                   ReservedContext;
  ULONG                   BypassIoOpenCount;
} FSRTL_ADVANCED_FCB_HEADER;
```

I think you need reopen this case to be honest.

_Originally posted by @Mas0nShi in https://github.com/MicrosoftDocs/windows-driver-docs-ddi/issues/1505#issuecomment-1836953949_

**Comment by lorihollasch** [comment]
@Mas0nShi , closing this as duplicate. Please see #1505 for information that will be of use to you.
