### ISSUE TITLE
Customer feedback - issues with KBUGCHECK_REASON_CALLBACK_ROUTINE

### ISSUE THREAD

**Issue by zephyr-fun** [MicrosoftDocs/windows-driver-docs-ddi#1511]
### Type of issue

Other (describe below)

### Feedback

Hi Barry, thank you for sharing this document—it's very helpful.

I am currently working on a driver for a device that monitors system state primarily by using the KBUGCHECK_REASON_CALLBACK_ROUTINE callback to report when the system issues a bug check and to provide a crash dump for analysis. However, I encountered unexpected behavior when attempting to write crash dump data to devices other than the disk by implementing the KbCallbackDumpIo routine.

According to the documentation, when the system issues a bug check, it will call the registered KBUGCHECK_REASON_CALLBACK_ROUTINE multiple times with a KBUGCHECK_DUMP_IO structure in this case. The data inside should eventually form a complete dump file. In my implementation, each time the system calls the bug check function, it transfers the buffer in the input parameter ReasonSpecificData (which, in this situation, should be a KBUGCHECK_DUMP_IO struct type) to the device. However, after the system completes the entire bug check process, only mini dumps are in a valid format (containing correct information), while core dumps and full dumps, although appearing to have correct file sizes, are actually invalid files that cannot be used.

Two details may be relevant:

1. When I print out the addresses of the buffers (referring to three parts of the dump file), only a small part of the address for the body type buffer appears valid. Starting from a certain buffer, all addresses for the body type buffer become 0x00.
2. The data read from address 0x00 is consistently 0xff, indicating that no useful and correct information is being written to the dump file.

I also used binary comparison software to compare the dump file I wrote to the device with the corresponding dump file on the hard drive generated by the system. Aside from a small amount of matching header and secondary information, the rest of the information was incorrect.

Could there be an issue with the usage of KBUGCHECK_REASON_CALLBACK_ROUTINE, or are there system limitations during bug check that are not mentioned in the documentation?

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nc-wdm-kbugcheck_reason_callback_routine

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nc-wdm-kbugcheck_reason_callback_routine.md

### Author

@barrygolden

**Comment by barrygolden** [comment]
@zephyr-fun, thanks for reaching out to the Windows Driver Developer Documentation team.  

Unfortunately, we are a small team and do not have the resources to provide technical support to individual driver developers.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. 

[Microsoft Q&A: Windows Hardware development](https://docs.microsoft.com/answers/topics/windows-hardware.html)

[OSR Developer Community](https://community.osr.com/)
