### ISSUE TITLE
Can't this API be called at any IRQL?

### ISSUE THREAD

**Issue by scottnoone** [MicrosoftDocs/windows-driver-docs-ddi#1512]
### Type of issue

Other (describe below)

### Feedback

Documentation says this API must be called at IRQL <= DISPATCH_LEVEL, but can't it be called at any IRQL?

Also, it would be good if this page notes that DisablePagingExecutive must be set for this to reliably work at IRQL >= DISPATCH_LEVEL (https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc757875(v=ws.10))

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlcapturestackbacktrace

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-rtlcapturestackbacktrace.md

### Author

@lorihollasch

**Comment by lorihollasch** [comment]
Thanks for the issue, @scottnoone. I checked with NealC who said that RtlCaptureStackBackTrace can only be called at IRQL < DISPATCH_LEVEL. I'll correct the page to indicate this change. Before I do, can you clarify your comment about DisablePagingExecutive being set: do you want the comment that it must be set on the RtlCaptureStackBackTrace page? I can do that, but don't have ownership of the DisablePagingExec page (and won't find an owner since it's an archived page).

**Comment by scottnoone** [comment]
Hi!

I was actually arguing the opposite: that the API can be called at any IRQL. Switching the documentation to saying < DISPATCH_LEVEL would make it even more restrictive.

The point of DisablePagingExecutive is that in order for the stack walk to work the .pdata records of the relevant drivers need to be paged in. AFAIK the API will not crash if the data is not there, however the resulting stack walk will be incomplete as the data necessary to reconstruct the stack is paged out. Therefore if a driver is going to use this API at IRQL >= DISPATCH_LEVEL then they should also set DisablePagingExecutive to increase the accuracy of resulting stack walk. This is also alluded to in the documentation around capturing ETW traces with stack walking enabled. For example:

Typically, on 64-bit computers, you cannot capture the kernel stack in certain contexts when page faults are not allowed. To enable walking the kernel stack on x64, set the DisablePagingExecutive Memory Management registry value to 1. The DisablePagingExecutive registry value is located under the following registry key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management. This should only be done for temporary diagnosis purposes because it increases memory usage of the system.

ENABLE_TRACE_PARAMETERS (evntrace.h) - Win32 apps | Microsoft Learn<https://learn.microsoft.com/en-us/windows/win32/api/evntrace/ns-evntrace-enable_trace_parameters#remarks>

That same text would be a good note in the documentation for RtlCaptureStackBacktrace

Thanks!

**Comment by lorihollasch** [comment]
Glad you pushed back, @scottnoone. Turns out that Neal was looking at the wrong stack trace when he answered me - lots going on! I've removed the IRQL restriction and added the paragraph about DisablePagingExecutive. Thanks for taking the time to improve the docs.
