### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by sandilya-xilinx** [MicrosoftDocs/windows-driver-docs-ddi#1513]
### Type of issue

Typo

### Feedback

hKmdCpuEvent

[in] Handle to the KMD CPU event object.

This should be out. Refer to <WDK_KIT>\shared\d3dkmddi.h

hKmdCpuEvent

[out] Handle to the KMD CPU event object.

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ns-d3dkmddi-dxgkarg_createcpuevent

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-dxgkarg_createcpuevent.md

### Author

@lorihollasch

**Comment by lorihollasch** [comment]
Great catch, @sandilya-xilinx! Thanks for reporting this - I've updated the page.
