### ISSUE TITLE
ApcRoutine parameter for ZwNotifyChangeKey incorrectly described

### ISSUE THREAD

**Issue by sebastian-nowak-resilio** [MicrosoftDocs/windows-driver-docs-ddi#1517]
### Type of issue

Missing information

### Feedback

in parameter ApcRoutine description, there is info that it must be NULL for kernel mode, this is most probably not true. In the next parameter description (ApcContext) for kernel mode it defines how the ApcRoutine parameter is interpreted, which means that it may not be null for kernel mode.

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-zwnotifychangekey

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-zwnotifychangekey.md

### Author

sebastian-nowak-resilio

**Comment by lorihollasch** [comment]
Great catch, @sebastian-nowak-resilio! Thanks so much for filing this issue. I've corrected the descriptions for ApcRoutine and ApcContext.
