### ISSUE TITLE
Customer feedback - Incomplete documentation

### ISSUE THREAD

**Issue by sandilya-xilinx** [MicrosoftDocs/windows-driver-docs-ddi#1521]
### Type of issue

Missing information

### Feedback

Can you please elaborate about the members of D3DDDI_SEGMENTPREFERENCE

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dukmdt/ns-d3dukmdt-_d3dddi_segmentpreference

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dukmdt/ns-d3dukmdt-_d3dddi_segmentpreference.md

### Author

@lorihollasch

**Comment by lorihollasch** [comment]
Thanks for reporting this blank page, @sandilya-xilinx - oops! I've populated the page with details. :)

**Comment by sandilya-xilinx** [comment]
Thank you @lorihollasch for updating the page. Also, I want to thank MSFT to provide feedback link which is easy to submit our request/feedback for the MSDN pages and the turnaround time is impressive. Thank you again.
