### ISSUE TITLE
KEY_QUERY_VALUE is not nescessary for some information classes

### ISSUE THREAD

**Issue by OZ1** [MicrosoftDocs/windows-driver-docs-ddi#153]
KeyNameInformation and KeyHandleTagsInformation don't require KEY_QUERY_VALUE access on KeyHandle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68a22613-e97b-aa54-5a5c-b72b6995f447
* Version Independent ID: ad448216-3eb6-d584-0616-aa53df8df8e5
* Content: [ZwQueryKey function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwquerykey)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwquerykey.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwquerykey.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
@OZ1 Thanks for pointing this out. I have updated the topic with a note. It should be live shortly

Page Writer

**Comment by OZ1** [comment]
thanks)
