### ISSUE TITLE
Enquiry of UFS info access method

### ISSUE THREAD

**Issue by taoyunfeng** [MicrosoftDocs/windows-driver-docs-ddi#1532]
### Type of issue

Missing information

### Feedback

Can MS provide some of sample code to read descriptor/attribute/flag of UFS by Win10 10.0.22621 SDK? I've tried many ways but it doesn't work.

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ufs/ns-ufs-ufs_device_descriptor?source=recommendations

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ufs/ns-ufs-ufs_device_descriptor.md

### Author

@lorihollasch

**Comment by lorihollasch** [comment]
Thanks for your question, @taoyunfeng. We can't specifically document and provide samples for miniport drivers for the various specific types of hardware (UFS miniport driver in this case), sorry. Check out the [Storport Miniport driver documentation](https://learn.microsoft.com/windows-hardware/drivers/storage/storport-miniport-drivers) for implementation details, and there are a couple of [storage miniport sample drivers](https://learn.microsoft.com/windows-hardware/drivers/samples/storage-driver-samples) that should help you.
