### ISSUE TITLE
Please document missing `10.0.22621` functions

### ISSUE THREAD

**Issue by gabriellandau** [MicrosoftDocs/windows-driver-docs-ddi#1535]
### Type of issue

Missing content

### Feedback

Hello again.  Happy 2024!

I just spotted functions in [the latest EWDK](https://go.microsoft.com/fwlink/?linkid=2249942)'s `Program Files\Windows Kits\10\Include\10.0.22621.0\km\ntddk.h` which aren't yet documented.  When you have time, could you please document these for safe use by the community?  Documentation will reduce AV/Anti-Cheat incentives to directly access opaque `EPROCESS`/`ETHREAD` structures, improving Windows stability for everyone.

```c
_IRQL_requires_max_(APC_LEVEL)
NTKERNELAPI
BOOLEAN
PsIsCurrentThreadPrefetching (
    VOID
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
NTKERNELAPI
ULONGLONG
PsGetProcessStartKey(
    _In_ PEPROCESS Process
    );

_IRQL_requires_max_(APC_LEVEL)
NTKERNELAPI
NTSTATUS
PsGetProcessExitStatus(
    _In_ PEPROCESS Process
    );

_IRQL_requires_max_(APC_LEVEL)
NTKERNELAPI
NTSTATUS
PsGetThreadExitStatus(
    _In_ PETHREAD Thread
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
NTKERNELAPI
HANDLE
PsGetThreadId(
    _In_ PETHREAD Thread
     );

_IRQL_requires_max_(DISPATCH_LEVEL)
NTKERNELAPI
PVOID
PsGetThreadProperty(
    _In_ PETHREAD Thread,
    _In_ ULONG_PTR Key,
    _In_ ULONG Flags
    );

NTKERNELAPI
LONGLONG
PsGetThreadCreateTime(
    _In_ PETHREAD Thread
    );
```

### Page URL

n/a

### Content source URL

n/a

### Author

n/a

**Comment by tedhudek** [comment]
Thank you @gabriellandau and Happy 2024 to you as well.  I verified that these are defined in latest public ntddk.h.  Stay tuned, working on this one...

**Comment by gabriellandau** [comment]
One more please.  I'd be happy to file another issue if it's too late to add now:

```c
//
// Reserve byte 1 of the RtlWalkFrameChain flags for
// specifying a number of frames to skip.
//

#define RTL_STACK_WALKING_MODE_FRAMES_TO_SKIP_SHIFT     8

//@[comment("MVI_tracked")]
NTSYSAPI
ULONG
NTAPI
RtlWalkFrameChain (
    _Out_writes_(Count - (Flags >> RTL_STACK_WALKING_MODE_FRAMES_TO_SKIP_SHIFT)) PVOID *Callers,
    _In_ ULONG Count,
    _In_ ULONG Flags
    );
```

**Comment by tedhudek** [comment]
Thanks Gabriel.

Instead of RtlWalkFrameChain, we recommend https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlcapturestackbacktrace instead.  

Sometime soon, we will add doc pages for:

- PsGetProcessStartKey
- PsGetProcessExitStatus
- PsGetThreadExitStatus
- PsGetThreadId
- PsGetThreadCreateTime

**Comment by gabriellandau** [comment]
> Sometime soon, we will add doc pages

Great.  Thank you @tedhudek.

> Instead of RtlWalkFrameChain, we recommend https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlcapturestackbacktrace instead.

Thank you for the suggestion.  Unfortunately `nt!RtlCaptureStackBackTrace` can only capture kernel stacks, not user stacks.  In order to capture user mode stacks, we need to set the low bit in `RtlWalkFrameChain`s third parameter (`Flags`), like how [SysInternals Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon)'s driver does [here](https://gist.github.com/gabriellandau/96b53f3e07f72bb9b5f88b99121897cb#file-procmon24_rtlwalkframechain_wrapper-c-L87).  Contrast that to [earlier in the same function](https://gist.github.com/gabriellandau/96b53f3e07f72bb9b5f88b99121897cb#file-procmon24_rtlwalkframechain_wrapper-c-L18) where it captures kernel stack frames by passing `Flags=0`.

`RtlCaptureStackBackTrace` [employs a shift operation](https://gist.github.com/gabriellandau/f904b75589ef5d4f9525fcb8ebb0bb15#file-rtlcapturestackbacktrace-c-L21) (` << 8`) that zeroes the low 8 bits on the `Flags` it passes to `RtlWalkFrameChain`, so it cannot capture user stacks..

**Comment by tedhudek** [comment]
Hi Gabriel, the following pages are now live.  I'll leave this issue open while I circle back on your comment immediately above.

•	https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-psgetprocessstartkey
•	https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-psgetprocessexitstatus
•	https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-psgetthreadexitstatus
•	https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-psgetthreadid
•	https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-psgetthreadcreatetime
•	https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-psgetthreadproperty
•	https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-rtlwalkframechain

FYI, the Requirements block table (bottom of each page) formatting is messed up on these (and all function pages) – known issue, we’re working on it.

**Comment by tedhudek** [comment]
Hi again Gabriel, so that's all I have for you right now on this. We’re aware that it would be useful to be able to capture a usermode stack from kernelmode and are evaluating various options for how we could do that.

Thanks again for caring about the docs!  Also see the announcement in #1543.

**Comment by gabriellandau** [comment]
> We’re aware that it would be useful to be able to capture a usermode stack from kernelmode and are evaluating various options for how we could do that.

Thanks!  Is that conversation being tracked anywhere like a GH issue?  The ability to capture UM callstacks from KM is [really useful for security products](https://www.elastic.co/security-labs/upping-the-ante-detecting-in-memory-threats-with-kernel-call-stacks).

> Hi Gabriel, the following pages are now live

They look great - thanks again.  I just noticed [their parent page](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/) is missing descriptions.  Example:
![image](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/assets/42078554/f7cdfefa-f0e9-48c6-85d1-2497d747aa5a)
