### ISSUE TITLE
Customer feedback - more commonality with the old style functions

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1536]
### Type of issue

Other (describe below)

### Feedback

@lorihollasch … just when you thought it was safe to go back into the water……

I happened upon this tremendous function as I was reviewing the latest changes. Sadly I cannot use it because I need to support win10.

But I was struck by the incredibly useful phrase about ‘making sure that the cache map is setup and remains valid’ and it seems like you could usefully add it to the two old versions we have just been talking about.

Also this function isn’t documented to throw exceptions (and it *does* return a status) but if it does the neophyte needs to know and if it doesn’t the old timers need to know…..

apologies for any typos, doing this on a tablet…

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ccsetcachefilesizes

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ccsetcachefilesizes.md

### Author

@lorihollasch

**Comment by lorihollasch** [comment]
You're cracking me up, @rodwiddowson! But seriously, great discovery and call-out to make these very similar pages consistent. Let me know if I missed anything, thanks.
