### ISSUE TITLE
Typo.

### ISSUE THREAD

**Issue by HollisTech** [MicrosoftDocs/windows-driver-docs-ddi#154]
The line: "Drivers must always use explicitly free any lookaside lists they create before unloading. "   The word "use" should be deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9997626f-029a-0e86-119f-186d8c0ab281
* Version Independent ID: be15ccf4-a32d-b14d-4eb7-8b911a5ec8c7
* Content: [ExInitializeNPagedLookasideList function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-exinitializenpagedlookasidelist)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exinitializenpagedlookasidelist.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exinitializenpagedlookasidelist.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @HollisTech 
I've made this change. Should be live within 24 hours. In the future, feel free to edit the content and submit a PR for changes. It'll make your breath fresher and leave you feeling refreshed. ;-)
