### ISSUE TITLE
Link to RTL_BITMAP structure is broken

### ISSUE THREAD

**Issue by scottnoone** [MicrosoftDocs/windows-driver-docs-ddi#1541]
### Type of issue

Typo

### Feedback

The links to the RTL_BITMAP structure redirect to documentation on the EPROCESS:

https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/eprocess

This error also appears in the RtlSetBits documentation:

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlsetbits

I didn't look at any others to see if the problem exists elsewhere.

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlinitializebitmap

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlinitializebitmap.md

### Author

@barrygolden

**Comment by tedhudek** [comment]
Thanks Scott, great find.  I just pushed an update to repoint 40 occurrences of that link to https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/eprocess#rtl_bitmap.  Should reach the live site soon.
