### ISSUE TITLE
Missing "Minimum Supported Client"

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#1542]
### Type of issue

Missing information

### Feedback

@lorihollasch , @tedhudek  My apologies, I tried to do this with a PR but the markup macros defeated me.

The WDK has this only supported "Windows 19H1 or later."

I went to the source but I don't see the source for the Requirements section (nothing between `-remarks` and `-see-also`) so I couldn't add it..

(Also note I had to hard code the PageURL/Content Source/Author so sorry if I got that wrong

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltflushbuffers2

### Content source URL

git@github.com:MicrosoftDocs/windows-driver-docs-ddi.git/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltflushbuffers2

### Author

@lorihollasch

**Comment by lorihollasch** [comment]
I've added the min OS to this page, @rodwiddowson, thanks. FYI that we insert this information via metadata in the source .md ("req.target-min-winverclnt: Windows 10, version 1903" in this case).
