### ISSUE TITLE
Typo that KSAUDIO_SPEAKER_5POINT1_SURROUND has no center channel?

### ISSUE THREAD

**Issue by thxkiwi** [MicrosoftDocs/windows-driver-docs-ddi#1544]
### Type of issue

Typo

### Feedback

It appears that merging PR 20132 (https://github.com/MicrosoftDocs/windows-driver-docs-ddi/commit/596d9cb2d796847f32ecabbde4040f552699e2ce) dropped SPEAKER_FRONT_CENTER from KSAUDIO_SPEAKER_5POINT1_SURROUND.

Was this intentional or a typo?

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ksmedia/ns-ksmedia-ksaudio_channel_config

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/5dd6a4736313eecc1e1d34f9580fcbbe37183059/wdk-ddi-src/content/ksmedia/ns-ksmedia-ksaudio_channel_config.md?plain=1#L120

### Author

barrygolden

**Comment by barrygolden** [comment]
@thxkiwi, thanks for catching the missing speaker position! 

The article has been updated and SPEAKER_FRONT_CENTER has been restored in the KSAUDIO_SPEAKER_5POINT1_SURROUND configuration.
