### ISSUE TITLE
Duplicated structure members

### ISSUE THREAD

**Issue by emuzychenko** [MicrosoftDocs/windows-driver-docs-ddi#156]
Members are duplicated (ULONGLONG/DWORDLONG).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a64e69a-9577-a5c7-72db-3915b21b4d64
* Version Independent ID: e68ab92a-f06a-cab9-9897-14083877e43c
* Content: [KSAUDIO_POSITION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ksmedia/ns-ksmedia-ksaudio_position)
* Content Source: [wdk-ddi-src/content/ksmedia/ns-ksmedia-ksaudio_position.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ksmedia/ns-ksmedia-ksaudio_position.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
@emuzychenko thanks for pointing out the duplicated structure members in the KSAUDIO_POSITION syntax. This is a known issue with our documentation build system which does not currently correctly handle conditionals inside of construct definitions. This will be addressed in a future build system update.
