### ISSUE TITLE
Broken hyperlink - "Driver-Managed Queues" link in the Remarks section

### ISSUE THREAD

**Issue by BarryBo** [MicrosoftDocs/windows-driver-docs-ddi#157]
For more information about using driver-managed internal queues, see Driver-Managed Queues.  That link jumps to the top of the DDK reference, not to documentation on Driver-Managed Queues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74a9834f-f682-a5ca-ce68-e84a4fa52d89
* Version Independent ID: 980f704d-b365-9aab-4321-ce56cc26288d
* Content: [KeInitializeQueue function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-keinitializequeue)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-keinitializequeue.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-keinitializequeue.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @BarryBo I've updated the link in question. The fix should be live by the end of the day.
