### ISSUE TITLE
Incorrect link in description of field "ProcessorEnableMask"

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/windows-driver-docs-ddi#161]
The description of field "ProcessorEnableMask" contains a hyperlink on the type "KAFFINITY", but that link just points (via redirects) to this page. Instead, it should point to a page documenting type KAFFINITY.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0149c84-578d-435f-6b87-be74f68a08ee
* Version Independent ID: 3921138b-c159-85a0-9c68-bccb127804fa
* Content: [IoConnectInterrupt function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioconnectinterrupt)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioconnectinterrupt.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioconnectinterrupt.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hi @fpl9000 

This is now fixed. Thanks for letting us know!

Page Writer
