### ISSUE TITLE
Missing structure definition

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#168]
Where is the definition of USB_BUS_NOTIFICATION? Expecting us to dig into a header file is unreasonable! Why isn't there a link from this article to the structure definition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a236318f-550f-0b6c-0834-84600dbb0fd0
* Version Independent ID: 7740e959-4af8-f6cf-0235-f436fd74cd28
* Content: [IOCTL_INTERNAL_USB_GET_BUS_INFO](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_bus_info#feedback)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_bus_info.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_bus_info.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Closing this issue as the link to USB_BUS_NOTIFICATION has since been added.
