### ISSUE TITLE
Output parameter description incorrect

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#171]
The output is the filled-in USB_HUB_NAME structure, not just a bare string as described

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38bfb11e-8780-c53c-c0b3-c6a086899b16
* Version Independent ID: 315bc6a3-01d8-679c-f1a2-063fd262a223
* Content: [IOCTL_INTERNAL_USB_GET_HUB_NAME](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_hub_name)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_hub_name.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_hub_name.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
