### ISSUE TITLE
What should we use?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#172]
If we are not allowed to use this, then what should we use to get this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 449e4700-7021-65da-8afa-29c6becc6363
* Version Independent ID: 28344d71-84c1-96cb-636c-7996b62ac97b
* Content: [IOCTL_INTERNAL_USB_GET_PARENT_HUB_INFO](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_parent_hub_info)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_parent_hub_info.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_parent_hub_info.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
