### ISSUE TITLE
PortAttributes not all defined

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#176]
USB_PORTATTR_NO_OVERCURRENT_UI is defined in USB.h, not Usbioctl.h
There are 5 other USB_PORTATTR_xxx bits defined in that header. Why aren't they described here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd79f3b-f1ae-ed9a-dc59-dd055c4f2964
* Version Independent ID: b807ee1a-551b-6f98-39d2-d2f09d823acd
* Content: [_USB_NODE_CONNECTION_ATTRIBUTES](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ns-usbioctl-_usb_node_connection_attributes)
* Content Source: [wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_node_connection_attributes.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_node_connection_attributes.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
