### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#177]
The USB_PORTATTR_xxx flags for USB_NODE_CONNECTION_ATTRIBUTES are defined in USB.h, so that should also be a requirement of this IOCTL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a90b50c-655d-039e-086f-480d8a3350ae
* Version Independent ID: b3ff6e4a-1ef9-3741-aef5-15255398eee0
* Content: [IOCTL_USB_GET_NODE_CONNECTION_ATTRIBUTES](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_attributes)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_attributes.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_attributes.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
