### ISSUE TITLE
Missing field description

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#178]
The description of ChangeNotificationInputFlags is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ddeb16d-aae3-b2f5-c9af-4c01af498e7b
* Version Independent ID: 2dc782f5-bd7f-c0ee-886f-34bd250d2334
* Content: [_USB_TRANSPORT_CHARACTERISTICS_CHANGE_REGISTRATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ns-usbioctl-_usb_transport_characteristics_change_registration)
* Content Source: [wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_transport_characteristics_change_registration.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_transport_characteristics_change_registration.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
