### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by javier-intel** [MicrosoftDocs/windows-driver-docs-ddi#182]
[Enter feedback here]
On the description for D3D12DDI_HEAP_SERIALIZATION_TIER_0041_1 Texture BandWidth Compression is spelled incorrectly as TWBC instead of TBWC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 376d5316-d27a-8edc-402f-57e2db908ec6
* Version Independent ID: 8a8e467c-eb15-1625-2a1d-61b80881131e
* Content: [D3D12DDI_HEAP_SERIALIZATION_TIER_0041](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3d12umddi/ne-d3d12umddi-d3d12ddi_heap_serialization_tier_0041)
* Content Source: [wdk-ddi-src/content/d3d12umddi/ne-d3d12umddi-d3d12ddi_heap_serialization_tier_0041.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3d12umddi/ne-d3d12umddi-d3d12ddi_heap_serialization_tier_0041.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Got that bad boy fixed in the source, and it's on it's way to the live version as I type. Thanks, @javier-intel for catching that!
