### ISSUE TITLE
Unclear output description

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#183]
In the description of the Output Buffer, what exactly does "The leading "\xxx\ " text is not included in the retrieved string" mean? Also, the returned string is Unicode, which should be mentioned!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047b14b8-a217-42dc-dcca-3d59d5358cfd
* Version Independent ID: 2f53a88c-5a97-803f-53b8-d3673ec828e6
* Content: [IOCTL_USB_GET_ROOT_HUB_NAME](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_usb_get_root_hub_name)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_root_hub_name.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_root_hub_name.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @BrianCatlin for this and the spate of other issues. @PageWriter-MSFT will triage and respond to them as she is able.

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
