### ISSUE TITLE
How to get from user mode?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#184]
How can topology be queried from user mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb6fdb5b-5b6d-4926-b55d-3d128a6c4c50
* Version Independent ID: 0f749787-7efb-7a6a-1776-b0b0facd8348
* Content: [IOCTL_INTERNAL_USB_GET_TOPOLOGY_ADDRESS](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_topology_address)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_topology_address.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_internal_usb_get_topology_address.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by BrianCatlin** [comment]
Getting the HubPortNumber array from the USB_TOPOLOGY_ADDRESS really needs to be supported from user-mode; otherwise, the user will have to enumerate the entire USB device tree to calculate it!

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
