### ISSUE TITLE
Link under the Remarks section is broken

### ISSUE THREAD

**Issue by Arush-Agarampur** [MicrosoftDocs/windows-driver-docs-ddi#185]
The link for 'Strings' leads to the main windows api page,  not a page on strings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aaa5e54-647a-8520-da58-40ba6c951db3
* Version Independent ID: 6fa4842a-63c5-0c24-32c8-55a1cc97a9b6
* Content: [RtlCreateUnicodeString function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlcreateunicodestring)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-rtlcreateunicodestring.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-rtlcreateunicodestring.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @Arush-Agarampur for letting us know about this. I've updated the page with the correct link: https://docs.microsoft.com/windows-hardware/drivers/ddi/content/_kernel/#run-time-library-rtl-routines 
Should be live soon.
