### ISSUE TITLE
Consequences not specified

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#186]
The description reads, "Do not send this request to the root hub". What is the expected response if it is sent to a root hub? Given an unknown hub (possibly a root hub or an external hub), how can we determine whether it is a root hub or external hub if we are not allowed to send this? There really needs to be a recommended sequence of operations for enumerating and walking the USB device tree.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09979e6c-618e-098d-5c08-3538030f7008
* Version Independent ID: 9602de14-4732-4a1a-35da-ab95cb7eeaa6
* Content: [IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX_V2](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information_ex_v2)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information_ex_v2.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information_ex_v2.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
