### ISSUE TITLE
The page about FILE_STAT_LX_INFORMATION has the Remarks from REPARSE_DATA_BUFFER

### ISSUE THREAD

**Issue by DHowett-MSFT** [MicrosoftDocs/windows-driver-docs-ddi#187]
As in the title. The Remarks section contains:

> The REPARSE_DATA_BUFFER structure is used by Microsoft file systems, filters, and minifilter drivers, as well as the I/O manager, to store data for a reparse point. 

This is not the page about REPARSE_DATA_BUFFER.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9b24ccd-979a-aca4-3434-f749047a8aff
* Version Independent ID: 06366d41-7795-9a38-2c0e-2ec593211258
* Content: [_FILE_STAT_LX_INFORMATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_file_stat_lx_information)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_file_stat_lx_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_file_stat_lx_information.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @DHowett-MSFT, for pointing this out. 
We decided just to remove the errant remarks for the time being.
