### ISSUE TITLE
How do we diagnose STATUS_INVALID_PARAMETER?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#190]
This applies to all IOCTLs.
If an IOCTL returns STATUS_INVALID_PARAMETER, how do we troubleshoot this? How about telling us WHICH parameter is bad (after all, there are status values specifically for this purpose, such as STATUS_INVALID_PARAMETER_1, _2, _3, ..._12)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ded8b2-3552-5f5a-bd1b-989f6d8b5616
* Version Independent ID: 25704ae5-3d6f-8d75-86f4-5302c3600377
* Content: [IOCTL_USB_GET_NODE_CONNECTION_NAME](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_name)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_name.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_name.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @BrianCatlin 
@PageWriter-MSFT can you please forward this to the correct PM or Dev for consideration? Thank you.

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
