### ISSUE TITLE
Missing description of field 'UxdSettings'

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#198]
UxdSettings is not defined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b88c77d-d9a8-9cfe-7cea-d2a502fb9248
* Version Independent ID: 7dbc8a6f-c34d-ba6b-dfc0-b4e12472e402
* Content: [_HUB_DEVICE_CONFIG_INFO_V1](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ns-usbioctl-_hub_device_config_info_v1)
* Content Source: [wdk-ddi-src/content/usbioctl/ns-usbioctl-_hub_device_config_info_v1.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ns-usbioctl-_hub_device_config_info_v1.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
