### ISSUE TITLE
Need value mapping

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#201]
The values for DevInstKeyType need to be related to the values specified in the link under DevInstKeyType, e.g. what registry path corresponds with PLUGPLAY_REGKEY_DEVICE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6f193f-8962-a4b6-2cd9-3a5b5b085a51
* Version Independent ID: a301bec6-13df-754e-952d-79c3a178fc23
* Content: [IoOpenDeviceRegistryKey function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioopendeviceregistrykey)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioopendeviceregistrykey.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioopendeviceregistrykey.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Fixed
