### ISSUE TITLE
Unspecified values for SetupPacket.bmRequest

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#202]
What values can SetupPacket.bmRequest have? What is the definition of the bitfield? Are there enums, macros, or structures that define the values for "standard, class, or vendor"? Is the BM_REQUEST_TYPE in usbspec.h compatible with this field? Pointing at the entire USB spec (which spec? 1.1, 2.0, 3.0?), which is 650 pages (v2.0) is not helpful in the slightest!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54400e45-c407-85bc-bef3-a76ca63dabe8
* Version Independent ID: b924dee7-5660-6ef9-395a-a410bdb43b18
* Content: [_USB_DESCRIPTOR_REQUEST](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ns-usbioctl-_usb_descriptor_request)
* Content Source: [wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_descriptor_request.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_descriptor_request.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
