### ISSUE TITLE
Header for constants used for SetupPacket.wValue not specified

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#203]
USB_DEVICE_DESCRIPTOR_TYPE, USB_CONFIGURATION_DESCRIPTOR_TYPE, etc. are in usbspec.h, not usbioctl.h

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54400e45-c407-85bc-bef3-a76ca63dabe8
* Version Independent ID: b924dee7-5660-6ef9-395a-a410bdb43b18
* Content: [_USB_DESCRIPTOR_REQUEST](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ns-usbioctl-_usb_descriptor_request)
* Content Source: [wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_descriptor_request.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_descriptor_request.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hi @BrianCatlin 

They are available in both. The core spec definitions were declared in usbioctl.h. Starting in Windows 8, they were also added in usbspec.h as a common header for all USB spec-related APIs. I will add "usbspec.h" as the include header. 

Thanks

Page Writer
