### ISSUE TITLE
The explanation for too many fields is "see USB spec"

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#204]
Which spec? Which version? Which section? People who want to use USB should not have to be experts in the minutia of the USB, and have neither the time nor the interest in wading through hundreds of pages of a spec to find out how to use your IOCTL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54400e45-c407-85bc-bef3-a76ca63dabe8
* Version Independent ID: b924dee7-5660-6ef9-395a-a410bdb43b18
* Content: [_USB_DESCRIPTOR_REQUEST](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ns-usbioctl-_usb_descriptor_request)
* Content Source: [wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_descriptor_request.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_descriptor_request.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @BrianCatlin 
@PageWriter-MSFT from I can see, this was added by a writer in the past as a catchall. See if you think there's a better solution than just removing the phrase. Look the docs over to see where you find it. I see some variation or another in 10 instances in 5 topics. There may be more than the ones I see:
usbioctl\ns-usbioctl-_usb_descriptor_request.md
  line 73,533
  line 78,359 
  line 146,114 
  line 151,137 
usbioctl\ns-usbioctl-_usb_node_connection_information_ex.md
  line 73,183
usbioctl\ns-usbioctl-_usb_node_connection_information.md
  line 73,195
usbspec\ns-usbspec-_usb_configuration_descriptor.md
  line 83,154
usbspec\ns-usbspec-_usb_hub_descriptor.md
  line 78,70
  line 83,131
  line 95,135

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
