### ISSUE TITLE
Link in the remarks section is broken

### ISSUE THREAD

**Issue by Arush-Agarampur** [MicrosoftDocs/windows-driver-docs-ddi#206]
The link for "Kernel handles" in the remarks section is broken and leads to the WDK home page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f59738d9-c5ee-15de-20db-22f40301af8b
* Version Independent ID: b4db1515-61ce-d798-fd12-dd18c78dbd6e
* Content: [ZwTerminateProcess function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-zwterminateprocess)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-zwterminateprocess.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-zwterminateprocess.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @Arush-Agarampur for pointing this out. The old link was for a glossary that we deprecated. I've added the definition and included a link for more info about creating a kernel handle.
