### ISSUE TITLE
Misleading enum member values!

### ISSUE THREAD

**Issue by abhinavtyagi** [MicrosoftDocs/windows-driver-docs-ddi#208]
The enum members don't have values in incrementing order but do have the values in increasing order index of bit i.e. BIT(x). The way it is presented on this page is misleading and hence incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 206b7425-c152-21cb-a087-9c57a5370e8f
* Version Independent ID: 1c013a56-7e94-985a-4098-dffc19890984
* Content: [D3D12DDI_RESOURCE_STATES](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3d12umddi/ne-d3d12umddi-d3d12ddi_resource_states)
* Content Source: [wdk-ddi-src/content/d3d12umddi/ne-d3d12umddi-d3d12ddi_resource_states.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3d12umddi/ne-d3d12umddi-d3d12ddi_resource_states.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @abhinavtyagi 
@mimisasouvanh can you look into this?

**Comment by mimisasouvanh** [comment]
Hello @abhinavtyagi,
I sincerely apologize for taking so long to respond. Are you talking about the Syntax section of the document? 
Thanks!

**Comment by mimisasouvanh** [comment]
@abhinavtyagi 
Hi Abhi,
I have inserted a new Syntax with enum member values. It should be published in the next 24 hours or so. 
Thanks!
Mimi

**Comment by abhinavtyagi** [comment]
I can't correlate the page where I did comment and pointed the problem. If
the comment or page link is included, it'd be possible to go back and see
what have changed.


Thanks,
Abhinav

**Comment by mimisasouvanh** [comment]
Here is the link: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3d12umddi/ne-d3d12umddi-d3d12ddi_resource_states
