### ISSUE TITLE
Rename to avoid confusion

### ISSUE THREAD

**Issue by beemavishnu** [MicrosoftDocs/windows-driver-docs-ddi#209]
Should not 'NdisTimerFunction' be replaced to 'NetTimerCallback' ? This is bit confusion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae1c217-aa71-f519-3afd-7534adc0fe68
* Version Independent ID: a5d811a9-136c-3f5f-33ad-846b8a9377a6
* Content: [NDIS_TIMER_FUNCTION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/nc-ndis-ndis_timer_function)
* Content Source: [wdk-ddi-src/content/ndis/nc-ndis-ndis_timer_function.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nc-ndis-ndis_timer_function.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @beemavishnu , great point. I think this was a remnant from our content migration we did a few months back, where the old page was called "NetTimerCallback." Technically, the correct name of the callback function is "NdisTimerFunction," so I've replaced all the instances of "NetTimerCallback" with the correct name. Thanks for catching this and thanks for your interest in the docs!
