### ISSUE TITLE
Could you put an example on this webpage, please?

### ISSUE THREAD

**Issue by javadbayat** [MicrosoftDocs/windows-driver-docs-ddi#210]
I wrote a code for a console application in C++ in which this function (RtlCreateSystemVolumeInformationFolder) is used, but I didn't import Ntoskernel.lib to my project. Instead, I used LoadLibrary and GetProcAddress to dynamically link to ntoskernel.exe.  When I run my app, calling this function results in an Access Violation exception. I was wondering if you could place a short code example on how to call this function correctly.
Here is a short code indicating my problem, but it's not the actual code of the project I'm working on:

    #include <Windows.h>
    #include <winternl.h>
    
    typedef NTSTATUS (NTAPI *PROC_C_SVI_FOLDER)(PCUNICODE_STRING);
    typedef VOID (NTAPI *PROC_I_UNC_STR)(PUNICODE_STRING, PCWSTR);
    
    #define STATUS_SUCCESS 0
    
    void main()
    {
    	HMODULE lib = LoadLibrary("ntoskrnl.exe");
    	if (lib != NULL)
    	{
    		PROC_C_SVI_FOLDER CreateSystemVolumeInformation = (PROC_C_SVI_FOLDER) GetProcAddress(lib, "RtlCreateSystemVolumeInformationFolder");
    		PROC_I_UNC_STR InitUnicodeString = (PROC_I_UNC_STR) GetProcAddress(lib, "RtlInitUnicodeString");
    
    		UNICODE_STRING volRootPath;
    		InitUnicodeString(&volRootPath, L"E:");
    
    		if (CreateSystemVolumeInformation(&volRootPath) != STATUS_SUCCESS)
    			MessageBox(NULL, "RtlCreateSystemVolumeInformation failed.", "Error", MB_OK | MB_ICONSTOP);
    
    		FreeLibrary(lib);
    	}
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9b956b4-0a9c-6066-982a-0fd269e89a4f
* Version Independent ID: cc7ba42a-7e57-db40-1745-1a9d93e2b1b9
* Content: [RtlCreateSystemVolumeInformationFolder function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlcreatesystemvolumeinformationfolder)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-rtlcreatesystemvolumeinformationfolder.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-rtlcreatesystemvolumeinformationfolder.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @javadbayat and thanks for your request. It's a great idea, but unfortunately, I am wrapped up with a ton of high-priority tasks for the foreseeable future. You might want to ask for examples on the [Windows Hardware WDK and Driver Development forum](https://go.microsoft.com/fwlink/p/?LinkId=613308). Or if you do create one, feel free to submit it to the docs for consideration, using a commit.
Sorry I can't be of more help.
@EliotSeattle
