### ISSUE TITLE
"INTERFACE" links on this page go to NETBT interface docs

### ISSUE THREAD

**Issue by wurdack** [MicrosoftDocs/windows-driver-docs-ddi#215]
I think you want them to go to the WDK's INTERFACE definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5261bd1e-6bfb-963c-a372-662c7fe27ef5
* Version Independent ID: a8b747b7-dbb9-2ee5-917f-c03493a3f87f
* Content: [WDF_QUERY_INTERFACE_CONFIG_INIT function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfqueryinterface/nf-wdfqueryinterface-wdf_query_interface_config_init)
* Content Source: [wdk-ddi-src/content/wdfqueryinterface/nf-wdfqueryinterface-wdf_query_interface_config_init.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfqueryinterface/nf-wdfqueryinterface-wdf_query_interface_config_init.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
OHO! Thanks, @wurdack, for the eagle-eyed catch. @tedhudek, I believe you want to change the reference to https://docs.microsoft.com/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_interface, but I'll leave it to you to verify and compete.

**Comment by tedhudek** [comment]
Thanks @wurdack for the feedback, @EliotSeattle is correct. I have updated the links on the page. Fix will be live later in the day today
