### ISSUE TITLE
IRQL?

### ISSUE THREAD

**Issue by wurdack** [MicrosoftDocs/windows-driver-docs-ddi#216]
Are there _any_ general IRQL requirements around InterfaceReference/Dereference, or is this a property of a specific interface implementation? In other words, if I grab an interface from a remote target, and find I need to deref the interface at DISPATCH level, can I in general do that safely? My guess is yes, but nothing in the docs appear to disallow an implementation from doing something like putting the deref routine in a paged section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31c9ab84-036c-8696-0101-98c8098e02ee
* Version Independent ID: 671cf9d9-48db-9312-cf4f-57b7ec270bb5
* Content: [PINTERFACE_REFERENCE](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nc-wdm-pinterface_reference)
* Content Source: [wdk-ddi-src/content/wdm/nc-wdm-pinterface_reference.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nc-wdm-pinterface_reference.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @wurdack sorry for the delay.  It is a per interface contract.  I added a note to the docs, should be live within the hour.  Thanks for the feedback!
