### ISSUE TITLE
Link to PsGetCurrentProcess

### ISSUE THREAD

**Issue by kITerE** [MicrosoftDocs/windows-driver-docs-ddi#217]
Broken link: there is no separate page for PsGetCurrentProcess (https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-iogetcurrentprocess#remarks)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f965c2b-c18b-34c7-42b1-61e83c4eeb95
* Version Independent ID: c39a61d0-becb-a088-76c8-f4a1540c2636
* Content: [PsGetCurrentProcessId function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-psgetcurrentprocessid)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-psgetcurrentprocessid.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-psgetcurrentprocessid.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Fixed in source
