### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by joshbooks** [MicrosoftDocs/windows-driver-docs-ddi#219]
s/Comperand/Comparand/g

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 552b2c09-82f1-87a0-7b93-3ea91ee3e37a
* Version Independent ID: d10cf6fc-7282-09b6-c3f7-85ba6ddd2357
* Content: [InterlockedCompareExchange function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-interlockedcompareexchange)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-interlockedcompareexchange.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-interlockedcompareexchange.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Fixed. Thanks, @joshbooks
