### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by joshbooks** [MicrosoftDocs/windows-driver-docs-ddi#220]
s/Comperand/Comparand/g

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80a34a0d-69ca-0f46-59f3-dc20e603c9ab
* Version Independent ID: f2ff59a3-e9d3-1006-2a07-afa4668c426c
* Content: [InterlockedCompareExchangePointer function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-interlockedcompareexchangepointer)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-interlockedcompareexchangepointer.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-interlockedcompareexchangepointer.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @joshbooks 
Got these, too
