### ISSUE TITLE
Page content update

### ISSUE THREAD

**Issue by sathishcg** [MicrosoftDocs/windows-driver-docs-ddi#223]
Hi,

 Providing a link to correlation vector will be helpful for users. 

We have recently open sourced MS  internal CV implementation. Can I have a quick chat on this with the content team?

-Sathish
 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b651c9-07aa-dfda-1aba-466cfeb15263
* Version Independent ID: ddabcc7a-b09f-0e77-036e-8bb8a4125e00
* Content: [CORRELATION_VECTOR](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/ns-ntddk-correlation_vector#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/ns-ntddk-correlation_vector.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/ns-ntddk-correlation_vector.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks again @sathishcg for the PRs.  Closing out this issue since the work is done.
