### ISSUE TITLE
Both links to PsGetCurrentProcess are dead links

### ISSUE THREAD

**Issue by assarbad** [MicrosoftDocs/windows-driver-docs-ddi#228]
The gist is already in the subject line. The two links to `PsGetCurrentProcess` are dead links.

Best regards,

Oliver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe860a8c-e67b-4419-6b5e-bd8085baa859
* Version Independent ID: becfef9c-98b6-b2b9-37d1-0f03b9fbd46d
* Content: [KeStackAttachProcess function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-kestackattachprocess)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-kestackattachprocess.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-kestackattachprocess.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by kITerE** [comment]
RP #222 (fix for entire repository)
