### ISSUE TITLE
IoCheckQuerySetFileInformation: no description of parameters and return value

### ISSUE THREAD

**Issue by kITerE** [MicrosoftDocs/windows-driver-docs-ddi#229]
IoCheckQuerySetFileInformation has no descriptions of the parameters and the return value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70d82db7-c2ec-68de-6c54-ae31362f9b46
* Version Independent ID: eed13283-16f4-fc33-30d1-57b074c2c239
* Content: [IoCheckQuerySetFileInformation function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-iocheckquerysetfileinformation)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-iocheckquerysetfileinformation.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-iocheckquerysetfileinformation.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by lorihollasch** [comment]
@klTerE, thanks again for reporting this and apologies for the delay! IoCheckQuerySetFileInformation is now documented.
