### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by SIISII** [MicrosoftDocs/windows-driver-docs-ddi#23]
A link to "device interface class" at the very beginning of the article is broken, the correct one is https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-interface-classes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b05d0517-f5b1-a2e2-d9ef-bdb413e8062b
* Version Independent ID: 27f22c7c-d8cd-5390-d5e2-4319075e6a15
* [Content](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioregisterdeviceinterface#feedback)
* [Content Source](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioregisterdeviceinterface.md)
* Service: unspecified

**Comment by EliotSeattle** [comment]
Thanks, @SIISII. The update should be live shortly. Appreciate you taking the time to open the Issue. Feel empowered to make future updates in the source and submit a pull request. too!
