### ISSUE TITLE
RtlLongToUInt8, etc. docs not in sync

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/windows-driver-docs-ddi#231]
One of many examples, `RtlLongToUInt8` appears differently on the web vs. what's in this repository. I was going to correct a bunch of these docs, but they're not in sync with the repo.

Will await guidance.

Web: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntintsafe/nf-ntintsafe-rtllongtouint8

Repository: https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntintsafe/nf-ntintsafe-rtllongtouint8.md

**Comment by EliotSeattle** [comment]
Thanks, @riverar 
@PageWriter-MSFT can you see why this and other rendered pages differ from the source? IS the build system injecting something wrong/right? Thanks.

**Comment by PageWriter-MSFT** [comment]
Hi @riverar 

Thanks for pointing that out! There was a bug in our backend tools which was fixed today. So you will find the page fixed with previously missing information.

Apologize for the inconvenience,

Page Writer
