### ISSUE TITLE
Information field meaning

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#232]
On this page there is a reference to a status block and information field. Where is this information/status stored? Both the input and output buffer appear to be of size 0. We need a bit of clarification on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 698b6c0a-bd0a-fa0c-1b31-4f4b4e6bedd5
* Version Independent ID: eaf32b1f-9fee-dbf1-30c1-fccce772b119
* Content: [IOCTL_STORAGE_REINITIALIZE_MEDIA](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddstor/ni-ntddstor-ioctl_storage_reinitialize_media)
* Content Source: [wdk-ddi-src/content/ntddstor/ni-ntddstor-ioctl_storage_reinitialize_media.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddstor/ni-ntddstor-ioctl_storage_reinitialize_media.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @csm10495. The status is part of the [_IO_STATUS_BLOCK structure](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_io_status_block). There's more info about using IO_STATUS_BLOCK in [How to Complete an IRP in a Dispatch Routine](https://docs.microsoft.com/windows-hardware/drivers/kernel/how-to-complete-an-irp-in-a-dispatch-routine). I'll add links in the topic. I also added a little more info from the devs.

Hope this helps.
