### ISSUE TITLE
What are the possible values for IpOptionsSupported, TcpOptionsSupported, etc...

### ISSUE THREAD

**Issue by russli1993** [MicrosoftDocs/windows-driver-docs-ddi#239]
The documentation did not actually state what are the options for IpOptionsSupported, TcpOptionsSupported, etc. It says "These members can have one of the following values:" and ends. Please fix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228f2b4d-b68c-8806-2fbf-d53cb1bb73dc
* Version Independent ID: 9b66c03e-6e9e-97a4-fa7f-d938fc8a701d
* Content: [_NDIS_TCP_IP_CHECKSUM_OFFLOAD](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddndis/ns-ntddndis-_ndis_tcp_ip_checksum_offload)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_tcp_ip_checksum_offload.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_tcp_ip_checksum_offload.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @russli1993 , thanks for finding this. It looks like the lists that were supposed to follow those sentences got lost in a content migration we did a few months back, so I've added them back in. The changes should be live later today. Thanks for helping to improve the docs!
