### ISSUE TITLE
Wrong syntax

### ISSUE THREAD

**Issue by bartlomiejcieszkowski** [MicrosoftDocs/windows-driver-docs-ddi#242]
The syntax is wrong as this is not a void macro - see "returns FALSE if the pointer is NULL. Otherwise, it returns TRUE", my guess is BOOL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c258c72-d438-2ee6-9ac4-89db7f7874f5
* Version Independent ID: 6020b7d2-8dfa-3e0e-7241-a072da3736b3
* Content: [ARGUMENT_PRESENT macro](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wudfwdm/nf-wudfwdm-argument_present)
* Content Source: [wdk-ddi-src/content/wudfwdm/nf-wudfwdm-argument_present.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wudfwdm/nf-wudfwdm-argument_present.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @bartlomiejcieszkowski thanks for opening this.  It's a macro so it's technically not a return value, but I went ahead and updated https://docs.microsoft.com/windows-hardware/drivers/ddi/content/wudfwdm/nf-wudfwdm-argument_present to try and make it a bit clearer.
