### ISSUE TITLE
Automatic method name extraction fails

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#243]
Something has gone dreadfully wrong with the auto conversion here.  FsRtlIsNameInExpression is in the 
extern "C" 
namespace and _FSRTL_ADVANCED_FCB_HEADER is a (somewhat heavily kludged) standard C structure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a79a15-8ae0-3056-e883-994969448a60
* Version Independent ID: 36a2a3cc-5b46-eaad-514b-40ad9baf1001
* Content: [FsRtlIsNameInExpression function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlisnameinexpression)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlisnameinexpression.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlisnameinexpression.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by lorihollasch** [comment]
@rodwiddowson, I believe our build tool has been modified to fix the problem you reported here. Let me know if there is still an issue and I can reopen this. Sorry for the slow response - thanks as always for reporting issues!
