### ISSUE TITLE
missing description

### ISSUE THREAD

**Issue by bjkessler** [MicrosoftDocs/windows-driver-docs-ddi#244]
Can we get a description of all the bits?
I can assume that Stereo  is set for a stereo capable monitor. But what about SyncLockIdentical or the others?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 288a5c88-bac6-457b-59c0-c43c5ab93500
* Version Independent ID: efa0c7dc-e9e2-7a0c-1521-cac1a8740f67
* Content: [_DXGK_MONITORLINKINFO_CAPABILITIES](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmdt/ns-d3dkmdt-_dxgk_monitorlinkinfo_capabilities#members)
* Content Source: [wdk-ddi-src/content/d3dkmdt/ns-d3dkmdt-_dxgk_monitorlinkinfo_capabilities.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmdt/ns-d3dkmdt-_dxgk_monitorlinkinfo_capabilities.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
Hello @bjkessler,

I've inserted descriptions for the SyncLockIdentical, TargetIndependentPrimary, and HDR10Plus members. The changes should be published in the next 24 hours.

Thanks!
Mimi
