### ISSUE TITLE
Reference to Device Properties goes to a WIA page

### ISSUE THREAD

**Issue by rgough71** [MicrosoftDocs/windows-driver-docs-ddi#246]
I was looking for a list of property types available for use via Io[G|S]etDevicePropertyData. This article points to https://docs.microsoft.com/en-us/windows-hardware/drivers/image/device-properties for this information, instead of something that would list out the properties shown in devpkey.h (available in the SDK).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e045093e-e34d-7b62-bbed-c5301f9cba85
* Version Independent ID: bc406bac-e095-78ea-0609-71a3c7171c2a
* Content: [IoGetDevicePropertyData function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-iogetdevicepropertydata)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iogetdevicepropertydata.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iogetdevicepropertydata.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @rgough71 thanks for the feedback and apologies for the delay.  Take a look at [DEVPROP_TYPE_BYTE](https://docs.microsoft.com/windows-hardware/drivers/install/devprop-type-byte) and adjacent pages for `DEVPROP_TYPE_*`.  I've added a note with this suggestion to both ref pages that will go live later today.
