### ISSUE TITLE
Missing links to related structures, lack of info

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#247]
The mentioned structures (DXGK_SET_TIMING_FLAGS, DXGK_SET_TIMING_RESULTS, DXGK_SET_TIMING_PATH_INFO) have no hyperlinks, forcing me back to google to locate them.  I'm finding this is very common throughout all of the new iteration of the display driver documentation.

There is also useful information missing that used to be included at the bottom of every driver entry point article next to the header its in, such as what IRQL is it called at?  What Threading and Synchronization Level is this function in?  Also useful would be which WDDM versions is this function called for?  I know through experimentation that when running as WDDM 1.3 this function is not called, and running as WDDM 2.2 it is, but what are the specifics?  These data points seem to be missing for every display driver entry point in the WDK programming reference.

By the way, I find the "table of contents" sidebar on the left that organizes the reference pages by what header a function or structure is included in to be far less useful than the previous categorical groupings of "Functions called by the user mode display driver", "Functions implemented by the kernel mode display driver", etc.  Do pages that organize it this way still exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e9e91e4-5ef5-48f9-7f01-b7230da3f945
* Version Independent ID: ab03d46d-a027-2bac-a4db-eb2546a44bdf
* Content: [_DXGKARG_SETTIMINGSFROMVIDPN](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/ns-d3dkmddi-_dxgkarg_settimingsfromvidpn)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgkarg_settimingsfromvidpn.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgkarg_settimingsfromvidpn.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
@englishb  Hi Ben,
Thank you for valuable feedback! I've taken note and will make these improvements for new DDIs moving forward:
- Calling out functions that are for user mode driver vs kernel mode driver
- Calling out WDDM versions
- IRQL
- Threading and Synchronization levels
Let me know if I've missed anything else. In the meantime, I've added the links to members as you suggested. 
Best,
Mimi
