### ISSUE TITLE
FltGetFileNameInformation: FO_CLEANUP_COMPLETE (not a post-close)

### ISSUE THREAD

**Issue by kITerE** [MicrosoftDocs/windows-driver-docs-ddi#253]
> FltGetFileNameInformation cannot get file name information in the post-close path. 

FltGetFileNameInformation returns **STATUS_FLT_INVALID_NAME_REQUEST** much earlier than in post-close. As I understand it, function returns an error if target file object has FO_CLEANUP_COMPLETE. That is: post-cleanup and later (including pre close).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c69953-3606-33d2-1c71-fa25b72a82da
* Version Independent ID: 67b78c7c-0fdc-ab17-d7d7-53a6b3eaded0
* Content: [FltGetFileNameInformation function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltgetfilenameinformation)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetfilenameinformation.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetfilenameinformation.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by kITerE** [comment]
[FltGetFileNameInformationUnsafe](https://docs.microsoft.com/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltgetfilenameinformationunsafe#remarks) has correct description:
> … following types of circumstances, where querying the file system for name information can cause deadlocks: 
> ….
> * After an IRP_MJ_CLEANUP operation is completed.

**Comment by lorihollasch** [comment]
@kITerE , this another important correction that needed to be made - I have updated the page - thanks!
