### ISSUE TITLE
What error status codes?

### ISSUE THREAD

**Issue by Compynerd255** [MicrosoftDocs/windows-driver-docs-ddi#255]
The return values section says this,

&gt; **ZwAllocateVirtualMemory** returns either STATUS_SUCCESS or an error status code. Possible error status codes include the following:

And then it just stops. What are the error codes it returns?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63532e27-812d-b8c3-b9b8-46e6cbb3f45b
* Version Independent ID: 9cac464a-c5d6-9b5c-1816-f17fb2d41944
* Content: [NtAllocateVirtualMemory function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntallocatevirtualmemory)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ntallocatevirtualmemory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ntallocatevirtualmemory.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for catching this, @Compynerd255. I've added the values. It should be in the doc and live shortly.

STATUS_ACCESS_DENIED 
STATUS_ALREADY_COMMITTED 
STATUS_COMMITMENT_LIMIT 
STATUS_CONFLICTING_ADDRESSES 
STATUS_INSUFFICIENT_RESOURCES 
STATUS_INVALID_HANDLE 
STATUS_INVALID_PAGE_PROTECTION 
STATUS_NO_MEMORY 
STATUS_OBJECT_TYPE_MISMATCH 
STATUS_PROCESS_IS_TERMINATING
