### ISSUE TITLE
Invalid PowerManaged enum name

### ISSUE THREAD

**Issue by PawelWMS** [MicrosoftDocs/windows-driver-docs-ddi#256]
This is a small issue: the description for the *PowerManaged* argument mentions *WdfDefault* as one of the options, while the proper name is *WdfUseDefault*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7de6b858-0ba8-df0b-e115-d88ef34940bd
* Version Independent ID: b23b8d83-86e4-fb10-7d80-2ba0b2e2b1df
* Content: [_WDF_IO_QUEUE_CONFIG](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfio/ns-wdfio-_wdf_io_queue_config)
* Content Source: [wdk-ddi-src/content/wdfio/ns-wdfio-_wdf_io_queue_config.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfio/ns-wdfio-_wdf_io_queue_config.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Well, thank you very much, @PawelWMS! I made that fix and put it in the queue to go live.
