### ISSUE TITLE
Wrong field order (Usage and UsagePage swapped)

### ISSUE THREAD

**Issue by FreezyLemon** [MicrosoftDocs/windows-driver-docs-ddi#260]
The docs show:

```c
typedef struct _HIDP_CAPS {
  USAGE  UsagePage;
  USAGE  Usage;
  //...
} HIDP_CAPS, *PHIDP_CAPS;
```

When installing the Windows Driver Kit and manually opening the `hidpi.h` header, these two fields are "swapped" in order:

```c
typedef struct _HIDP_CAPS
{
    USAGE    Usage;
    USAGE    UsagePage;
    // ...
} HIDP_CAPS, *PHIDP_CAPS;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1318d88-5516-41f7-e56e-7d0409802f3e
* Version Independent ID: 9cbb51bf-6ae3-db3a-bebc-e1aff629b549
* Content: [_HIDP_CAPS](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/hidpi/ns-hidpi-_hidp_caps)
* Content Source: [wdk-ddi-src/content/hidpi/ns-hidpi-_hidp_caps.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/hidpi/ns-hidpi-_hidp_caps.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @FreezyLemon thanks for the feedback and apologies for the delay.  I've just pushed a change to fix this.  It should appear on the live site within a half hour or so.
