### ISSUE TITLE
Copy/paste error

### ISSUE THREAD

**Issue by AlanAtWork** [MicrosoftDocs/windows-driver-docs-ddi#263]
Title says FindModuleByLocation but this is a copy of FindModuleByName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc52ac6a-c7bb-b279-379e-03d0432186b0
* Version Independent ID: 85686d4d-05d3-90d6-f8c6-5787a35e5c5f
* Content: [IDebugHostSymbols::FindModuleByLocation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dbgmodel/nf-dbgmodel-idebughostsymbols-findmodulebylocation)
* Content Source: [wdk-ddi-src/content/dbgmodel/nf-dbgmodel-idebughostsymbols-findmodulebylocation.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dbgmodel/nf-dbgmodel-idebughostsymbols-findmodulebylocation.md)
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
haha! Thanks, @AlanAtWork 
@DOMARS, looks like we have the content flipped in  FindModuleByLocation and FindModuleByName. Can you untangle this tangled web we weaved?

**Comment by AlanAtWork** [comment]
Oops! I didn't actually look at the other page and realize they were flipped.

**Comment by DOMARS** [comment]
@AlanAtWork - Thanks for seeing this error. The incorrect content inversion is properly re-inverted and the tangle of these two web topics is now detangled. The corrected topics should be live in 24 hours.
