### ISSUE TITLE
Missing valid statuses for NBL completion

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs-ddi#264]
The documentation declares that only certain statuses are valid for NBL completion but the list is missing.

> The miniport driver must set one of the following status codes in the Status member of each NET_BUFFER_LIST structure that the NetBufferLists parameter specifies:

...and no list of status codes follows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58abd70-5827-557b-179c-06f91693521c
* Version Independent ID: 40823fe7-e7a4-00b4-52f9-41ceb0788f34
* Content: [NdisMSendNetBufferListsComplete function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/nf-ndis-ndismsendnetbufferlistscomplete#feedback)
* Content Source: [wdk-ddi-src/content/ndis/nf-ndis-ndismsendnetbufferlistscomplete.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nf-ndis-ndismsendnetbufferlistscomplete.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks so much, @I-gor-C 
I added the status values and descriptions. Should be live shortly.
