### ISSUE TITLE
Also requires Usb.h

### ISSUE THREAD

**Issue by efalk** [MicrosoftDocs/windows-driver-docs-ddi#27]
If you don't include Usb.h first, usbdlib.h will throw hundreds of lines of syntax and other errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523d6870-fb41-ffb0-9f82-d622a33dff97
* Version Independent ID: c7c62028-6012-c8fd-46ca-3896c24bad76
* Content: [USBD_CreateHandle function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbdlib/nf-usbdlib-usbd_createhandle)
* Content Source: [wdk-ddi-src/content/usbdlib/nf-usbdlib-usbd_createhandle.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbdlib/nf-usbdlib-usbd_createhandle.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello Edward,

Thanks for pointing it out. I have updated the content to reflect your change. Should be published soon.

PageWriter
