### ISSUE TITLE
Grammatical error in ZwMapViewOfSection page

### ISSUE THREAD

**Issue by dsasmblr** [MicrosoftDocs/windows-driver-docs-ddi#270]
The first sentence of the [ZwMapViewOfSection](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwmapviewofsection) page is written as follows:

> The ZwMapViewOfSection routine maps a of a section into the virtual address space of a subject process.

It appears to be missing the word "view", which would correctly appear as follows:

> The ZwMapViewOfSection routine maps a view of a section into the virtual address space of a subject process.

This oversight appears to be due to [a previously filed issue](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/issues/80) in which the word "view" contained a bad link. It appears the word was removed in its entirety as opposed to just the hyperlink.

**Comment by tedhudek** [comment]
Looks like this got fixed in 09d39119235c889c1360a8b5369e32423e5d832c.  Thanks for the feedback @dsasmblr
