### ISSUE TITLE
WaveRT event driven mode for USB audio

### ISSUE THREAD

**Issue by lixiaogangkkk** [MicrosoftDocs/windows-driver-docs-ddi#272]
Does it possible to have a customized WaveRT event driven mode driver for USB audio device? 
Now I'm working on implementing a driver for my USB audio device, now the driver works correctly with push mode. But after adding support event driven mode (implement IMiniportWaveRTStreamNotification), I found there is noise in both playback and recording. I just launch a timer in kernel driver and active the notification event after the update position is ahead of pointer point to mid of the cyclic buffer or end of the cyclic buffer (here NotificationCount is 2). I'm not sure it's a design limitation or the noise issue is caused by incorrect buffer update strategy.

Thanks,
Steven

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e66408c-f318-609a-a59d-5d8292f7ab90
* Version Independent ID: e512e61e-a8cd-b34b-5f00-a043a1076784
* Content: [IMiniportWaveRTStreamNotification](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/portcls/nn-portcls-iminiportwavertstreamnotification)
* Content Source: [wdk-ddi-src/content/portcls/nn-portcls-iminiportwavertstreamnotification.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nn-portcls-iminiportwavertstreamnotification.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@lixiaogangkkk - Apologies for not responding to this sooner. If the information that describes buffering flow is not sufficient, I would recommend these resources.
- The SYSVAD Audio sample. 
- [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
- [OSR's ntdev List](https://community.osr.com/categories/ntdev)

The last forum is used by many driver developers and is a great resource.
