### ISSUE TITLE
Inaccurate csum calculation requirement

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs-ddi#273]
> If the TCP/IP transport sets the IsIPv4 or IsIPv6 flag, it also sets the IpHeaderChecksum, TcpChecksum, or UdpChecksum flags that are required to indicate which checksums the miniport driver should calculate for the packet.

Since there is no such thing as IPv6 checksum I think it should be stated clearly that IpHeaderChecksum flag is relevant to IPv4 only to avoid misinterpretations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0f8051-e6e2-449a-ecb4-9bafbcef2cb3
* Version Independent ID: ee070510-41ca-8f7e-f265-242fdd3ddacf
* Content: [_NDIS_TCP_IP_CHECKSUM_NET_BUFFER_LIST_INFO](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/ns-ndis-_ndis_tcp_ip_checksum_net_buffer_list_info)
* Content Source: [wdk-ddi-src/content/ndis/ns-ndis-_ndis_tcp_ip_checksum_net_buffer_list_info.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/ns-ndis-_ndis_tcp_ip_checksum_net_buffer_list_info.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @I-gor-C, thanks for pointing this out. You're right; there is no such thing as IPv6 checksum. I've updated the wording to say this instead: 

If the TCP/IP transport sets the IsIPv4 or IsIPv6 flag, it also sets the appropriate flags that are required to indicate which checksums the miniport driver should calculate for the packet. For IPv4, this includes the IpHeaderChecksum, TcpChecksum, or UdpChecksum flags. For IPv6, this includes the TcpChecksum or UdpChecksum flags. 

This updated wording should be live later today.
