### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by reuvenab** [MicrosoftDocs/windows-driver-docs-ddi#277]
In the Callback section 
Link underneath "Power-Setting Callback" is pointing to https://docs.microsoft.com/ which seems to be incorrect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14e2768-8f46-1b33-6d16-3a5cffebff60
* Version Independent ID: 9282ccd6-4161-b7db-f4d6-c11b2e655dea
* Content: [PoRegisterPowerSettingCallback function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-poregisterpowersettingcallback)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-poregisterpowersettingcallback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-poregisterpowersettingcallback.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for pointing this out, @reuvenab. I've fixed this in the code and pushed it. Should be live shortly.
