### ISSUE TITLE
List of return values is empty

### ISSUE THREAD

**Issue by Arush-Agarampur** [MicrosoftDocs/windows-driver-docs-ddi#279]
The partial list of return values for this function is empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2db8c7db-e044-aeda-d424-dd0fa494d35f
* Version Independent ID: 92cadf47-d035-055f-ae03-d8b8e4a3cd4b
* Content: [IoCreateDevice function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-iocreatedevice)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iocreatedevice.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iocreatedevice.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @Arush-Agarampur 
Thanks for catching this. The return values that we include in the partial list are 
STATUS_INSUFFICIENT_RESOURCES
STATUS_OBJECT_NAME_COLLISION
I've made the change in source and it will go live later today or Monday morning.
Have a great weekend.
