### ISSUE TITLE
Typo in function prototype

### ISSUE THREAD

**Issue by MajorTom2oo1** [MicrosoftDocs/windows-driver-docs-ddi#28]
I found a minor Typo. 2nd parameter should be

  _In_    PUNICODE_STRING SourceString,

And not
  _In_    PCUNICODE_STRING SourceString,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54072725-a836-f637-0fb9-d71952fcb791
* Version Independent ID: fa678a6c-4de1-0b93-1e01-b22821c92728
* Content: [RtlUpcaseUnicodeString function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-rtlupcaseunicodestring)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-rtlupcaseunicodestring.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-rtlupcaseunicodestring.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello MajorTom2oo1,

Thanks for your comment. As per the declaration in ntddk.h, the API is declared as:

_IRQL_requires_max_(PASSIVE_LEVEL)
_When_(AllocateDestinationString, _Must_inspect_result_)
NTSYSAPI
NTSTATUS
NTAPI
RtlUpcaseUnicodeString(
_When_(AllocateDestinationString, _Out_ _At_(DestinationString->Buffer, __drv_allocatesMem(Mem)))
_When_(!AllocateDestinationString, _Inout_)
PUNICODE_STRING DestinationString,
_In_ PCUNICODE_STRING SourceString,
_In_ BOOLEAN AllocateDestinationString
);

PCUNICODE_STRING is defined as:

typedef const UNICODE_STRING *PCUNICODE_STRING;

Thanks,

PageWriter
