### ISSUE TITLE
return value is PSLIST_ENTRY and not void

### ISSUE THREAD

**Issue by sirotnikov** [MicrosoftDocs/windows-driver-docs-ddi#284]
as per other documenatation - 
ExInterlockedPushEntrySList returns a pointer to the first entry of the list before the new entry was inserted. If the list was empty, the routine returns NULL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd523b-4576-7f63-f74c-3874a2141efe
* Version Independent ID: d4f75b38-043d-d041-98ba-7aa76d6b8cb1
* Content: [ExInterlockedPushEntrySList macro - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-exinterlockedpushentryslist)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exinterlockedpushentryslist.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exinterlockedpushentryslist.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @sirotnikov thanks again, and apologies for the delay.  I've just pushed a change to fix this.  It should appear on the live site within a half hour or so.
