### ISSUE TITLE
Deref operator (*) of possible ObjectType arguments improperly escaped

### ISSUE THREAD

**Issue by iamahuman** [MicrosoftDocs/windows-driver-docs-ddi#287]
The asterisks (`*`) before the possible values for the ObjectType parameters are not preceded by backslash (`\`) and thus interpreted as the *italics* formatting for the Markdown renderer. This also applies to other documentations describing kernel APIs that take the same type of argument.

Related: #288

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b24f38-757d-d7ab-fc56-3e68c0d91cb1
* Version Independent ID: 71e0d5b7-52cc-a5d8-2d5f-d94d50984947
* Content: [ObReferenceObjectByHandle function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-obreferenceobjectbyhandle)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-obreferenceobjectbyhandle.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-obreferenceobjectbyhandle.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @iamahuman.
I believe that I got all the guilty topics. If you see some I missed, please let me know.
