### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#290]
Link to PNP_DEVICE_STATE is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3aca3e3-bd94-4f0b-a33a-2d4fcbc4dffc
* Version Independent ID: 6e6c636d-7884-385a-8e5c-02abca8fdde0
* Content: [IoInvalidateDeviceState function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioinvalidatedevicestate)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioinvalidatedevicestate.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioinvalidatedevicestate.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @BrianCatlin. 
This is fixed in the source. Should be live in a little bit. Correct link is [PNP_DEVICE_STATE](https://docs.microsoft.com/windows-hardware/drivers/kernel/handling-an-irp-mn-surprise-removal-request#about-pnpdevicestate)
