### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#291]
How are we supposed to use these if there isn't a definition of what each constant means?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ed0679-e142-2ae6-d5ac-2f0d60e17970
* Version Independent ID: eca3ef39-2a6e-d14c-f3c5-a703ee3b1017
* Content: [_WDF_DEVICE_PNP_STATE - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfdevice/ne-wdfdevice-_wdf_device_pnp_state)
* Content Source: [wdk-ddi-src/content/wdfdevice/ne-wdfdevice-_wdf_device_pnp_state.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdevice/ne-wdfdevice-_wdf_device_pnp_state.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks for the feedback @BrianCatlin and apologies for the delay.  The state machine APIs are just there for internal MS use.  I've added a note to that effect to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfdevice/nf-wdfdevice-wdfdevicegetdevicepnpstate and related pages.
