### ISSUE TITLE
NDIS_RECEIVE_FLAGS_SINGLE_ETHER_TYPE description not consistent

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs-ddi#293]
From the documentation (I emphasized the relevant parts in **bold**):

> NDIS_RECEIVE_FLAGS_SINGLE_ETHER_TYPE is **optionally set by miniport drivers** that are certain all NBLs in an NBL chain have the same EtherType. By setting this flag, the miniport driver informs NDIS and upper layer protocols that they do not have to examine each packet for its EtherType, which increases performance. **Miniport drivers are never required to set this flag**.

So should the miniport driver set this flag or not in case all NBLs in an NBL chain have the same EtherType?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f54076d4-f3ce-e458-e6cd-2fc541e5e6be
* Version Independent ID: 06b6527f-0a09-4a19-4c51-52e2c23377d8
* Content: [NdisMIndicateReceiveNetBufferLists function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/nf-ndis-ndismindicatereceivenetbufferlists)
* Content Source: [wdk-ddi-src/content/ndis/nf-ndis-ndismindicatereceivenetbufferlists.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nf-ndis-ndismindicatereceivenetbufferlists.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @I-gor-C, thanks for the question. Sorry if it's not clear, but the description should be accurate as Jeffrey Tippet and I worked together on this particular flag a little while back. The bottom line is that miniport drivers are never **required** to set that flag. NDIS does not mandate it as a contract. But, if all the NBLs in a chain do have the same EtherType, miniport drivers can set it to increase performance. So whether they *should* is up to the driver writer. There could be cases where a miniport driver would like upper layer drivers (LWFs or protocols) to examine each NBL, so the driver might choose not to set the flag. But, in most cases, I would assume better performance is desired so setting the flag would help with that.

Hope this helps!
