### ISSUE TITLE
Returned status explanation insufficient

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#298]
The circumstances that cause the various return statuses to be returned must be listed! E.g. what causes STATUS_INVALID_PARAMETER to be returned? Are we supposed to guess? How do we troubleshoot this? This isn't just for this page; it needs to be fixed across ALL the WDK docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1266e050-abcb-d9c4-b637-b832e805d05f
* Version Independent ID: 896db7db-4f8a-4159-71c7-f3193ccad507
* Content: [IOCTL_USB_GET_HUB_INFORMATION_EX - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_usb_get_hub_information_ex)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_hub_information_ex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_hub_information_ex.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
