### ISSUE TITLE
No useful information

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#302]
How about describing how this routine differs from the non-"Ex" version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9746f99-effc-60bb-c2de-5b1878eaa925
* Version Independent ID: f2929861-0f9c-3ff0-6885-f2c9d80d74c8
* Content: [IoQueueWorkItemEx function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioqueueworkitemex)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioqueueworkitemex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioqueueworkitemex.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hey Brian, I just added the following the doc pg, should be live soon.

The **IoQueueWorkItemEx** routine differs from [**IoQueueWorkItem**](https://docs.microsoft.com/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioqueueworkitem) in that the **WorkerRoutine** parameter is a pointer to a <a href="https://msdn.microsoft.com/library/windows/hardware/ff566381">WorkItemEx</a> callback routine, which provides the driver with a pointer to the [**IO_WORKITEM**](https://docs.microsoft.com/windows-hardware/drivers/kernel/eprocess) structure for the work item.
