### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs-ddi#306]
Links to Compatible IDs and Hardware IDs in this document are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeccc3c3-d02f-b0b7-5809-ed64f6c387ff
* Version Independent ID: 7475174b-db79-d74c-3b51-7d98bdf159ce
* Content: [IoGetDeviceProperty function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-iogetdeviceproperty)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iogetdeviceproperty.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iogetdeviceproperty.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @I-gor-C. I fixed the two links as well as some other markdown issues. Should be live shortly.
