### ISSUE TITLE
"Example code" doesn't actually have example code

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs-ddi#307]
The "Example Code" section above just has a function with "// Function body" in it.  That's not an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fdbe194-d0b3-51f3-0aa2-5045e561f04e
* Version Independent ID: e52298a3-46de-e7c0-7327-cb2ffc63ebaf
* Content: [KBUGCHECK_REASON_CALLBACK_ROUTINE - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nc-wdm-kbugcheck_reason_callback_routine)
* Content Source: [wdk-ddi-src/content/wdm/nc-wdm-kbugcheck_reason_callback_routine.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nc-wdm-kbugcheck_reason_callback_routine.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Sorry for the delay @jakeoshins.  Just looked at the file above and I didn't see any Example section at all.  So either this is fixed or the link above isn't the one you were looking at.  Please reopen if needed.
