### ISSUE TITLE
"section object" link broken

### ISSUE THREAD

**Issue by Cazra** [MicrosoftDocs/windows-driver-docs-ddi#308]
The "section object" link is not working as expected. Instead of taking the user to documentation about section objects, it just directs the user to the Windows Driver Kit documentation home page: https://docs.microsoft.com/en-us/windows-hardware/drivers/.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e60ea10-5a11-6331-a47b-9472e444fbcb
* Version Independent ID: 3d19e81c-bdaf-db90-8f39-9b364f3e7404
* Content: [ZwCreateSection function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwcreatesection)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwcreatesection.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwcreatesection.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for calling this out, @Cazra.

I fixed the link to point to [https://docs.microsoft.com/windows-hardware/drivers/kernel/section-objects-and-views](https://docs.microsoft.com/windows-hardware/drivers/kernel/section-objects-and-views) and merged to the master branch. Should be live shortly.
