### ISSUE TITLE
"Allocating and Building URBs." is a dead link

### ISSUE THREAD

**Issue by efalk** [MicrosoftDocs/windows-driver-docs-ddi#31]
https://msdn.microsoft.com/library/windows/hardware/hh450844 is a dead link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7be700b-25eb-630c-c5e4-8c3a678d8f4c
* Version Independent ID: 686a1a82-02d0-9328-afcb-64580ff12533
* Content: [USBD_UrbAllocate function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbdlib/nf-usbdlib-usbd_urballocate)
* Content Source: [wdk-ddi-src/content/usbdlib/nf-usbdlib-usbd_urballocate.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbdlib/nf-usbdlib-usbd_urballocate.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @efalk! I pushed the fix to direct to https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/how-to-add-xrb-support-for-client-drivers. Should be live shortly.
