### ISSUE TITLE
when I building the sysvad.sln，which was downloaded from "https://github/microsoft/windows-driver-samples", get the error "can't find sidebandaudio.h"

### ISSUE THREAD

**Issue by xialiangfeng** [MicrosoftDocs/windows-driver-docs-ddi#310]
where should I to download those header files, either sidebandaudio.h or usbsidebandaudio.h?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b188482-0a88-d88f-61c0-92411db97643
* Version Independent ID: 712b3771-1ab2-5bc7-7d2b-70a9986e2209
* Content: [usbsidebandaudio.h header - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbsidebandaudio/)
* Content Source: [wdk-ddi-src/content/usbsidebandaudio/index.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbsidebandaudio/index.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @xialiangfeng.
Thanks for reaching out. Both headers are included in the latest version of the WDK, which can be downloaded from [https://docs.microsoft.com/windows-hardware/drivers/download-the-wdk](https://docs.microsoft.com/windows-hardware/drivers/download-the-wdk).

Happy coding!
@EliotSeattle
