### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#311]
What is the purpose of BdCbStatusPrepareForDependencyLoad? When will it be sent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e582965-264e-b236-e95a-fed904a5e35c
* Version Independent ID: 8e1c7774-a80d-dbe8-1abd-9fad15850c1e
* Content: [_BDCB_STATUS_UPDATE_TYPE - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/ne-ntddk-_bdcb_status_update_type)
* Content Source: [wdk-ddi-src/content/ntddk/ne-ntddk-_bdcb_status_update_type.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/ne-ntddk-_bdcb_status_update_type.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi Brian.
Looks like the content dropped during migration. The description for BdCbStatusPrepareForDependencyLoad is "Windows will start loading driver dependencies next."
I've updated the topic, and it should appear shortly.
Thanks for taking the time to let us know about this omission and sorry for any inconvenience.
Eliot
