### ISSUE TITLE
Function return type doesn't match description

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#312]
The Return Value section specifies that the routine returns an NTSTATUS value, but the function prototype above shows 'void' and the function definition BOOT_DRIVER_CALLBACK_FUNCTION shows 'void'. So, which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bbfa58-57f1-96a4-bd67-9449ab0264e7
* Version Independent ID: d02cb64f-355b-2c3c-44e4-6bbebfd61e65
* Content: [BOOT_DRIVER_CALLBACK_FUNCTION - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nc-ntddk-boot_driver_callback_function)
* Content Source: [wdk-ddi-src/content/ntddk/nc-ntddk-boot_driver_callback_function.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nc-ntddk-boot_driver_callback_function.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @BrianCatlin good find.  It is void indeed.  I removed the return value block from the doc page, should be live in ~30 min
