### ISSUE TITLE
Return Value is None?

### ISSUE THREAD

**Issue by annie-li** [MicrosoftDocs/windows-driver-docs-ddi#316]
Return Value is None here? I assume the return value would be "If the compared blocks are the same, the return value is 1. Otherwise, this function returns a 0."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9effd73-8eb8-b908-641d-fe9aab82e6b4
* Version Independent ID: c8f11536-3a1a-0403-078b-6ad4425b2db5
* Content: [NdisEqualMemory macro - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/nf-ndis-ndisequalmemory)
* Content Source: [wdk-ddi-src/content/ndis/nf-ndis-ndisequalmemory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nf-ndis-ndisequalmemory.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @annie-li, good question. NdisEqualMemory is actually a wrapper around [RtlEqualMemory](https://docs.microsoft.com/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlequalmemory) and therefore assumes that macro's return value, which is TRUE if the memory blocks are equivalent and FALSE if not. 

This is part of a larger-scoped project to go through and verify the return value on all NDIS macros, which is currently in progress but the updates haven't been published yet. Look for those soon; in the meantime, I'd recommend checking the `#define` in the header file to see if a macro you're not sure about wraps another. 

Thanks for bearing with us while we work on updating the docs.
