### ISSUE TITLE
More than 1 F-state can be used on a StorPort adapter device

### ISSUE THREAD

**Issue by tzimmer1** [MicrosoftDocs/windows-driver-docs-ddi#319]
Regarding "For a adapter device component, a maximum of one F-state (F0) is permitted", we have found from debug and discovery that a StorPort miniport can indeed go beyond 1 F-state.
A current example of this is the Microsoft StorNVME driver.  It can place multiple F-states on the StorPort adapter.

Can the documentation on this page be updated to clarify that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdaa6c4f-c22f-cd66-25d5-f5a5cd1cde8b
* Version Independent ID: c5dd4fe5-36ef-7a4f-8e8d-c38b2d5eb2b1
* Content: [_STOR_POFX_COMPONENT - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/storport/ns-storport-_stor_pofx_component)
* Content Source: [wdk-ddi-src/content/storport/ns-storport-_stor_pofx_component.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/storport/ns-storport-_stor_pofx_component.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by lorihollasch** [comment]
@tzimmer1, thanks for reporting this. The page has been updated to reflect the new F-state requirements. Let me know if you need further information.
