### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by maperr** [MicrosoftDocs/windows-driver-docs-ddi#32]
missing return error codes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf17787b-9c5d-3858-2baf-0472e15105af
* Version Independent ID: 58672917-f56c-b191-784d-899f480fab82
* Content: [ZwOpenKey function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwopenkey)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwopenkey.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwopenkey.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello Maxime,

Thanks for finding the missing content. I have updated the page.

PageWriter
