### ISSUE TITLE
The grouping of content on this page doesnt seem right

### ISSUE THREAD

**Issue by pankajbharti** [MicrosoftDocs/windows-driver-docs-ddi#320]
E.g. PO_FX_COMPONENT_V1 has little to do with CM_PARTIAL_xyz structures. 

But then this is missing : PoFx related methods. e.g. PoFxActivateComponent. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589fc5cd-8d96-b640-d9ae-e0638b32fa2f
* Version Independent ID: 37d302b0-35ea-6356-b302-9a469bf29ffb
* Content: [wudfwdm.h header - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wudfwdm/)
* Content Source: [wdk-ddi-src/content/wudfwdm/index.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wudfwdm/index.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @pankajbharti sorry for the delay.  We removed this header from the docs a month or so ago after feedback for Shyamal and Wei
