### ISSUE TITLE
Broken link : power management framework (PoFx).

### ISSUE THREAD

**Issue by pankajbharti** [MicrosoftDocs/windows-driver-docs-ddi#321]
The link: s power management framework (PoFx) is broken, it takes you to general WDK reference page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ddb5d4b-d5a9-1aa1-87a0-2bdcd8525a76
* Version Independent ID: 45a65f10-daba-bd80-50a6-0b6b66a61969
* Content: [PoFxRegisterPlugin function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/pepfx/nf-pepfx-pofxregisterplugin)
* Content Source: [wdk-ddi-src/content/pepfx/nf-pepfx-pofxregisterplugin.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/pepfx/nf-pepfx-pofxregisterplugin.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Fixed this one as well. Thanks, again, @pankajbharti!!
