### ISSUE TITLE
Formatting Off on DataIn

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#323]
Formatting of the DataIn section is a bit weird. It doesn't actually show what values should be set there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b086b27-107e-a0f9-45a2-79033e1ddea4
* Version Independent ID: 43498fe1-bea0-387e-8ed1-b3384c119aae
* Content: [_SCSI_PASS_THROUGH_DIRECT - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddscsi/ns-ntddscsi-_scsi_pass_through_direct)
* Content Source: [wdk-ddi-src/content/ntddscsi/ns-ntddscsi-_scsi_pass_through_direct.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddscsi/ns-ntddscsi-_scsi_pass_through_direct.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @csm10495. We lost the data as the topic was ported to GitHub. I added it and merged to master. Should be live shortly.
