### ISSUE TITLE
Missing DataDirection Description

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#325]
Very similar to https://github.com/MicrosoftDocs/windows-driver-docs-ddi/issues/323

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a34a1eb-15b8-ecfd-6dee-c422369c20eb
* Version Independent ID: f504d8ad-b227-4c39-9310-d87a9b75a613
* Content: [_SCSI_PASS_THROUGH_DIRECT_EX - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddscsi/ns-ntddscsi-_scsi_pass_through_direct_ex)
* Content Source: [wdk-ddi-src/content/ntddscsi/ns-ntddscsi-_scsi_pass_through_direct_ex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddscsi/ns-ntddscsi-_scsi_pass_through_direct_ex.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Yup. Same issue as #323. Added the content.  It should go live later in the week, when people return.

Thanks for spotting this.

|Data Transfer Type | Meaning |
|---- |----|
|SCSI_IOCTL_DATA_IN | Read data from the device.|
|SCSI_IOCTL_DATA_OUT | Write data to the device.|
|SCSI_IOCTL_DATA_UNSPECIFIED | No data is transferred.|
|SCSI_IOCTL_DATA_BIDIRECTIONAL | Data is valid for both input and output.|
