### ISSUE TITLE
Question: Incorrect break statement in example?

### ISSUE THREAD

**Issue by yongjiunnn** [MicrosoftDocs/windows-driver-docs-ddi#326]
In the [example](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfrequest/nf-wdfrequest-wdfrequestretrieveoutputbuffer.md#examples) on **WdfRequestRetrieveOutputBuffer** docs, the switch statement breaks if the status is not equal to `STATUS_BUFFER_TOO_SMALL`. Should it not be the other way around?

```
if (status != STATUS_BUFFER_TOO_SMALL) {
    break;
}
```

**Comment by tedhudek** [comment]
Thanks @yongjiunnn for reporting this, and sorry it took us a while to get back to you.  You are absolutely right!  I just made the correction.  The fix should appear on the live site within 30 min
