### ISSUE TITLE
Incorrect tips for FWPS_FIELD_ALE_AUTH_CONNECT_V4_REAUTHORIZE_REASON

### ISSUE THREAD

**Issue by GreatFireWall** [MicrosoftDocs/windows-driver-docs-ddi#328]
The tips of FWPS_FIELD_ALE_AUTH_CONNECT_V4_REAUTHORIZE_REASON:

![image](https://user-images.githubusercontent.com/4510984/50525935-a8777600-0b19-11e9-9949-03fc52d37f4f.png)

The link direct me to https://docs.microsoft.com/en-us/windows-hardware/drivers/network/filtering-condition-flags , but there isn't any docs of `FWP_CONDITION_REAUTHORIZE_REASON_*`.

It's reside here: https://docs.microsoft.com/en-us/windows/desktop/FWP/filtering-condition-flags-

It take me a long time for finding docs of `FWP_CONDITION_REAUTHORIZE_REASON_*`. 

😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8dbcfa3-37d9-e579-53c4-1c76741dd4ed
* Version Independent ID: 4a48319a-f945-4e5b-7bce-084c353afc22
* Content: [FWPS_FIELDS_ALE_AUTH_CONNECT_V4_ - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fwpsk/ne-fwpsk-fwps_fields_ale_auth_connect_v4_)
* Content Source: [wdk-ddi-src/content/fwpsk/ne-fwpsk-fwps_fields_ale_auth_connect_v4_.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fwpsk/ne-fwpsk-fwps_fields_ale_auth_connect_v4_.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @GreatFireWall, sorry you had that issue trying to find the content you were looking for. Some information for WFP pertains only to kernel-mode callout drivers, and some pertains to both user mode and kernel mode. In this case, that flag is defined in a header that is shared between user mode and kernel mode, so we might have missed documenting it here in the kernel mode docs. Generally, info that is kernel mode-only is documented here, while information that is either user mode-only or shared is documented on the SDK side.

I've added a note at the top of the [Filtering Condition Flags](https://docs.microsoft.com/windows-hardware/drivers/network/filtering-condition-flags) topic that directs you to the SDK page if you can't find the flag you're looking for here. That should be live later today. Hope that helps. Thanks again for helping to improve the docs!
