### ISSUE TITLE
IoRegisterPlugPlayNotification: formatting glitch 

### ISSUE THREAD

**Issue by cxw42** [MicrosoftDocs/windows-driver-docs-ddi#329]
The `Context` and `NotificationEntry` parameters are run together rather than being their own paragraphs.  There should be paragraph breaks at the marked places in this screenshot:

![image](https://user-images.githubusercontent.com/10515894/50527300-5ade1780-0adf-11e9-89a9-6a3a274b3903.png)

I looked at the markdown, but I don't see an obvious error (whence this issue rather than a PR :) ).  Thanks!

Environment | Value
-- | --
Google Chrome | 71.0.3578.98 (Official Build) (64-bit) (cohort: Stable)
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 8.1 Enterprise x64
JavaScript | V8 7.1.302.31

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d76f8a96-49b1-eba0-4b09-cda4705a27eb
* Version Independent ID: b7d729b1-0af4-cf28-0d86-7304e22b1607
* Content: [IoRegisterPlugPlayNotification function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioregisterplugplaynotification)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioregisterplugplaynotification.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioregisterplugplaynotification.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Well, whatever I did worked. Closing out this Issue as the content now looks good.
