### ISSUE TITLE
DriverInitialize or DriverEntry?

### ISSUE THREAD

**Issue by cxw42** [MicrosoftDocs/windows-driver-docs-ddi#331]
The page for `DriverEntry` refers to the routine itself (not its function-pointer type) as `DriverInitialize` in some places.  As far as I can tell, `DriverEntry` is more common --- e.g., [this](https://technet.microsoft.com/en-us/ff566402(v=vs.96)) for but one example.  In fact, the body copy says

> While it is possible to name this routine something other than DriverEntry, doing so is not recommended.

Would someone in the know please clarify the proper use (if any) of `DriverInitialize`?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82661062-353b-67f1-4287-558e34967974
* Version Independent ID: 2b6340e8-3b93-03b7-77ef-c7bde6da8f3b
* Content: [DRIVER_INITIALIZE - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nc-wdm-driver_initialize)
* Content Source: [wdk-ddi-src/content/wdm/nc-wdm-driver_initialize.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nc-wdm-driver_initialize.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @cxw42, thanks for the question and apologies for the delay.  This page used to be called **DriverEntry**, but recently we adopted a system that helps generate our ref docs by matching entities in header files with doc pages.  Therefore we had to rename this page to match the actual def in the header:

```
NTSTATUS
DRIVER_INITIALIZE (
    _In_ struct _DRIVER_OBJECT *DriverObject,
    _In_ PUNICODE_STRING RegistryPath
    );
```
