### ISSUE TITLE
DriverEntry link points to an ATA-specific page rather than a generic page

### ISSUE THREAD

**Issue by cxw42** [MicrosoftDocs/windows-driver-docs-ddi#332]
In the description of the `DriverObject` parameter, the document links to `DriverEntry` at https://msdn.microsoft.com/library/windows/hardware/ff552644 .  This page is specific to the ATA miniport driver.  Should it instead link elsewhere?  E.g., one of:

 - the generic `DriverEntry` page at https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nc-wdm-driver_initialize
- the "Writing a `DriverEntry`" article at https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/writing-a-driverentry-routine

Either of those options would seem more obviously applicable to drivers for other types of hardware.  Thanks for your consideration of this question!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2db8c7db-e044-aeda-d424-dd0fa494d35f
* Version Independent ID: 92cadf47-d035-055f-ae03-d8b8e4a3cd4b
* Content: [IoCreateDevice function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-iocreatedevice)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iocreatedevice.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iocreatedevice.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks again @cxw42 and sorry it took us a while.  You are absolutely right!  Translating that link out of our old doc system was an automated process, and in some cases the automation picked the wrong link target.  I've just updated the page to point to the first of your two suggestions above.  The update should appear on the live site within half an hour
