### ISSUE TITLE
Broken link to KeLowerIrql

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs-ddi#333]
The internal link to [KeLowerIrql](https://msdn.microsoft.com/library/windows/hardware/ff552968) is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a396471-b162-5e5f-8906-606ac13d4a95
* Version Independent ID: bb4be5b0-014d-8c4c-efad-dd40b8734b88
* Content: [KeRaiseIrqlToDpcLevel function - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-keraiseirqltodpclevel)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-keraiseirqltodpclevel.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-keraiseirqltodpclevel.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @I-gor-C 
The fix is made and merged into our private repo. It should show up in the live branch shortly.
Cheers.
@EliotSeattle
