### ISSUE TITLE
Return value not possible.

### ISSUE THREAD

**Issue by Arush-Agarampur** [MicrosoftDocs/windows-driver-docs-ddi#336]
How can the function return a TRUE or FALSE value if the return type is void as shown in the syntax area?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af3c58b9-2a43-f2ef-986b-7e2f8a8ea96b
* Version Independent ID: fe9e9d8d-a357-ea89-223a-200daa17fdb7
* Content: [IoIsErrorUserInduced macro - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioiserroruserinduced)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioiserroruserinduced.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioiserroruserinduced.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @Arush-Agarampur for the sharp eye, and apologies for the delay.  You are correct, the return value for this macro is of type BOOLEAN.  I have just updated the doc page, should be live in ~30 min.  It will appear on https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-ioiserroruserinduced
