### ISSUE TITLE
Missing OS version info for Windows Server versions

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs-ddi#337]
Missing definitions for Windows Server 2012R2 and newer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e8cb445-1d31-bc73-dceb-82bccece4bb0
* Version Independent ID: 016e23b3-53da-d6d9-c313-7b6976747b07
* Content: [_OSVERSIONINFOEXW - Windows driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_osversioninfoexw)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_osversioninfoexw.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_osversioninfoexw.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @I-gor-C for pointing this out, apologies for the delay.

I've updated the doc page but due to some internal issues the change won't go live until next Monday.  In the meantime, this is the updated info:

* Server 2012 R2 -> 6.3
* Server 2016 -> 10.0
* Server 2019 -> 10.0
