### ISSUE TITLE
Dead links on this page

### ISSUE THREAD

**Issue by mburnicki** [MicrosoftDocs/windows-driver-docs-ddi#350]
Some of the links in the "See also" section result in a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39339d20-f2e9-c7fd-02d6-05d62bd9fed2
* Version Independent ID: a8fd1472-4557-c51b-e467-e06d02a65e70
* Content: [KeQueryPerformanceCounter function - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-kequeryperformancecounter)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-kequeryperformancecounter.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-kequeryperformancecounter.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mburnicki, I've fixed the broken links. Thanks for reporting them!
