### ISSUE TITLE
Need clarification on what happens if the workitem is not enqueued.

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs-ddi#351]
I think that this page should clearly say that it is legal to flush a workitem that is not enqueued and has never been enqueued.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a6cf38-f7c1-7515-c2fe-ee2a4bf41a3d
* Version Independent ID: 835ad007-7915-2ff5-3071-a081a5889247
* Content: [WdfWorkItemFlush function - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfworkitem/nf-wdfworkitem-wdfworkitemflush)
* Content Source: [wdk-ddi-src/content/wdfworkitem/nf-wdfworkitem-wdfworkitemflush.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfworkitem/nf-wdfworkitem-wdfworkitemflush.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @jakeoshins I confirmed this and added it to the docs.  Should be live within half an hour.
