### ISSUE TITLE
ExGetFirmwareEnvironmentVariable / "remarks" should not recommend the zero guid as "dummy guid"

### ISSUE THREAD

**Issue by lersek** [MicrosoftDocs/windows-driver-docs-ddi#354]
[Enter feedback here]

The Remarks section for `ExGetFirmwareEnvironmentVariable` recommends,

> To identify these conditions, call the function with a dummy `VariableName`
string (for example, an empty string) and a dummy GUID such as `"{00000000-0000-0000-0000-000000000000}"` for the VendorGuid parameter.

This is wrong; the reader should be instructed to generate their own GUID with sufficient randomness (such as the `uuidgen` utility), *statically* of course, and then look for whatever variable in that namespace.

Alternatively, Microsoft should invent a well-known GUID (also with `uuidgen`), or introduce another variable under a namespace GUID Microsoft already owns, and then normatively specify that (GUID, variable) pair for the check.

The zero GUID is a bad choice because
* it was not generated with any amount of randomness, and
* it is not clearly associated with any one vendor (in any specification).

Therefore there's a high risk of conflicts between variable names within that namespace.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebf9376e-f0d1-fe4b-8be4-82ab23718d5b
* Version Independent ID: a0eedd57-48a4-44b7-1c5d-22c69ace3482
* Content: [ExGetFirmwareEnvironmentVariable function - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-exgetfirmwareenvironmentvariable)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exgetfirmwareenvironmentvariable.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exgetfirmwareenvironmentvariable.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback @lersek, I just made this change, should be live within the hour.  Apologies for the delay.  Please note that you can also click Edit from the original documentation page if you'd like to submit a PR against the docs..
