### ISSUE TITLE
"Do not send this request to the root hub" - incorrect advice?

### ISSUE THREAD

**Issue by tonysepia** [MicrosoftDocs/windows-driver-docs-ddi#356]
Dear Sir/Madam,

Following up from https://github.com/MicrosoftDocs/windows-driver-docs-ddi/issues/346, is it fair to say that the advice "Do not send this request to the root hub." on [IOCTL_USB_GET_NODE_CONNECTION_INFORMATION IOCTL](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information) is also incorrect? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44212907-af57-bc8d-61b7-343e90d47da7
* Version Independent ID: ba81e446-879b-0cde-bf90-eb9177bc2738
* Content: [IOCTL_USB_GET_NODE_CONNECTION_INFORMATION - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information.md)
* Product: **windows-hardware**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @tonysepia, that's correct. Looks like I missed this one when I was removing that sentence from the _EX and _EX_V2 versions of this IOCTL. I'll go ahead and remove it, and those changes should be live later today. 

For minor edits like this one, you can feel free to edit the page directly and submit a pull request if you'd like as another option. Just a heads up. :) Thanks again!
