### ISSUE TITLE
missing SILO pointer in C++ example

### ISSUE THREAD

**Issue by zodiacon** [MicrosoftDocs/windows-driver-docs-ddi#357]
should be:
PESILO PreviousSilo = PsAttachSiloToCurrentThread(SomeSilo);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49a4b337-51a0-f7ce-91e3-67f7b5ffa346
* Version Independent ID: 2e3a4213-87e3-46d8-bf7b-f81e6ec985f6
* Content: [PsAttachSiloToCurrentThread function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-psattachsilotocurrentthread)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-psattachsilotocurrentthread.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-psattachsilotocurrentthread.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @zodiacon good find.  Sorry for the delay!  Fix will be live within the hour.  Also note that you can open a PR against the docs by clicking Edit from any page.  Thanks again!
