### ISSUE TITLE
Incorrect summary

### ISSUE THREAD

**Issue by sba923** [MicrosoftDocs/windows-driver-docs-ddi#360]
The summary for this function should read:

The RtlSetProcessPlaceholderCompatibilityMode function sets the placeholder compatibility mode for the current process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0796369e-f7a1-3272-ead2-eb14082f722b
* Version Independent ID: fa13eac8-00b5-ac6c-7fb3-6de23c17144e
* Content: [RtlSetProcessPlaceholderCompatibilityMode function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlsetprocessplaceholdercompatibilitymode)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-rtlsetprocessplaceholdercompatibilitymode.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-rtlsetprocessplaceholdercompatibilitymode.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@sba923, thanks for catching this. I've updated the page with the noted correction.
