### ISSUE TITLE
Structure fields are severly lacking detail

### ISSUE THREAD

**Issue by Ron-Hu** [MicrosoftDocs/windows-driver-docs-ddi#362]
A miniport writer could not write code to these field descriptions.  What versions are allowed?  Size is what? Most likely bytes.

Do we define a "NODE" Structure in docs?  NodeCount is the count I'm sure of an array of "node", but who knows how to fill that in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df37577c-f0be-4e43-0e41-a734dc4727ea
* Version Independent ID: ac945c16-922a-ac66-83d6-b6f66e80f1f0
* Content: [_STORAGE_PHYSICAL_TOPOLOGY_DESCRIPTOR (ntddstor.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddstor/ns-ntddstor-_storage_physical_topology_descriptor)
* Content Source: [wdk-ddi-src/content/ntddstor/ns-ntddstor-_storage_physical_topology_descriptor.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddstor/ns-ntddstor-_storage_physical_topology_descriptor.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@Ron-Hu, thanks for reporting the big holes on this page. I've updated the page with missing information and corrections. Let me know if there is anything more missing.
