### ISSUE TITLE
Incorrect formatting on page

### ISSUE THREAD

**Issue by skalldri** [MicrosoftDocs/windows-driver-docs-ddi#364]
This page has ## and ### blocks scatered throughout the document. Something is wrong with the formatting, which is causing these sections (which I think should be titles) to appear as part of the paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72d221cc-d111-c592-f2ae-00006077db41
* Version Independent ID: 5c79b052-46e5-4027-47d8-e3d662cbf533
* Content: [WdfPdoInitAssignRawDevice function (wdfpdo.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfpdo/nf-wdfpdo-wdfpdoinitassignrawdevice)
* Content Source: [wdk-ddi-src/content/wdfpdo/nf-wdfpdo-wdfpdoinitassignrawdevice.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfpdo/nf-wdfpdo-wdfpdoinitassignrawdevice.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @skalldri this is fixed now
