### ISSUE TITLE
Links to functions

### ISSUE THREAD

**Issue by JonAxtell** [MicrosoftDocs/windows-driver-docs-ddi#365]
Could links and a bit more description about each function be added please. Information about how and when and why the structure is used would also be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea095d09-3829-1858-991f-9819ce056c63
* Version Independent ID: 7785fa0e-4eb8-0860-1240-23faa3c5ec92
* Content: [_MONITOR2 (winsplp.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/winsplp/ns-winsplp-_monitor2)
* Content Source: [wdk-ddi-src/content/winsplp/ns-winsplp-_monitor2.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/winsplp/ns-winsplp-_monitor2.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team with your comments about the MONITOR2 structure (winsplp.h). 

You may have success posting your question about how the structure is used in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
