### ISSUE TITLE
Graphics WDK docs seems to be corrupted / missing

### ISSUE THREAD

**Issue by g0blue** [MicrosoftDocs/windows-driver-docs-ddi#366]
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dukmdt/ns-d3dukmdt-_d3dddi_synchronizationobjectinfo2

Most of the actual documentation for this structure is missing. Other D3DKMT / D3DDDI structures have similar issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a8a85a-a25b-7976-1943-a05fbbf5c3f3
* Version Independent ID: 0f41c087-22dd-8321-8c58-66bc9aa0200e
* Content: [_D3DDDI_SYNCHRONIZATIONOBJECTINFO2 (d3dukmdt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dukmdt/ns-d3dukmdt-_d3dddi_synchronizationobjectinfo2)
* Content Source: [wdk-ddi-src/content/d3dukmdt/ns-d3dukmdt-_d3dddi_synchronizationobjectinfo2.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dukmdt/ns-d3dukmdt-_d3dddi_synchronizationobjectinfo2.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@g0blue Hi Dan, We are aware of this issue and currently have a bug open to fix it. In order to see the actual content, please click Edit on the upper right corner of the topic.

**Comment by duncanmacmichael** [comment]
This is now fixed.
