### ISSUE TITLE
Incorrect function's link is mentioned for "DxgkDdiPresentDisplayOnly"

### ISSUE THREAD

**Issue by vnvsrikanth** [MicrosoftDocs/windows-driver-docs-ddi#37]
For "DxgkDdiPresentDisplayOnly", 
A pointer to the KMDOD's DxgkDdiQueryVidPnHWCapability function's link is mentioned.

Following link has to be mentioned:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/nc-d3dkmddi-dxgkddi_presentdisplayonly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e1ebdf-ba7b-282a-30c5-bdb41a9fa834
* Version Independent ID: 089aa3b5-728e-dd9f-b3ee-85075ec708ae
* Content: [_KMDDOD_INITIALIZATION_DATA](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dispmprt/ns-dispmprt-_kmddod_initialization_data#remarks)
* Content Source: [wdk-ddi-src/content/dispmprt/ns-dispmprt-_kmddod_initialization_data.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dispmprt/ns-dispmprt-_kmddod_initialization_data.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
This should be fixed now. Thank you!
