### ISSUE TITLE
Misprint

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#370]
"Note If the call to this function occurs in user mode, you should use the name "NtCreateFile" instead of "NtCreateFile"."

Probably meant to say "from kernel mode" and "name ZwCreateFIle"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91b87ed3-cc07-a11d-54bb-61e41670bf65
* Version Independent ID: 770a9821-b066-0436-3bcc-0d950c9e97aa
* Content: [NtCreateFile function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntcreatefile)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ntcreatefile.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ntcreatefile.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@alfaunits, thanks for catching this - it is now corrected (use NtCreateFile instead of ZwCreateFile).
