### ISSUE TITLE
Return values

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#371]
The return value section of this page says "DxgkDdiUpdateActiveVidPnPresentPathreturns one of the following values:" and has nothing listed afterwards.  What are the return values?  I'm sure they were here in a previous version of the page.

Also, I don't remember the "Note: The display miniport driver's DxgkDdiUpdateActiveVidPnPresentPath function must support gamma ramps." being here.  Does this apply to every OS, or maybe it's new for Win10?  I'm fairly sure that it used to be documented that you could return STATUS_GRAPHICS_PATH_CONTENT_GEOMETRY_TRANSFORMATION_NOT_SUPPORTED.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e224484-10ff-53c5-945c-2f77bd5f2a13
* Version Independent ID: e6297782-75e3-3910-a06e-598102f0efff
* Content: [DXGKDDI_UPDATEACTIVEVIDPNPRESENTPATH (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/nc-d3dkmddi-dxgkddi_updateactivevidpnpresentpath)
* Content Source: [wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_updateactivevidpnpresentpath.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_updateactivevidpnpresentpath.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
Hi @englishb I've inserted the missing return values. You should see the change by tomorrow. To answer your question, yes, STATUS_GRAPHICS_PATH_CONTENT_GEOMETRY_TRANSFORMATION_NOT_SUPPORTED is an available return value. And the Note has been there since the function was available in Windows Vista.
