### ISSUE TITLE
Link to argument missing

### ISSUE THREAD

**Issue by rtsrao** [MicrosoftDocs/windows-driver-docs-ddi#372]
Link to 'D3DKMT_PRESENT_REDIRECTED' is missing. Besides, it would be great, if more description is added to the API to differentiate between 'D3DKMTPresent' & 'D3DKMTPresentRedirected'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e72be4c-1be4-be25-2ee3-aa520913a36c
* Version Independent ID: 5a92cb55-7ef6-5ba6-ced1-eef3f43fa17b
* Content: [D3DKMTPresentRedirected function (d3dkmthk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmthk/nf-d3dkmthk-d3dkmtpresentredirected)
* Content Source: [wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtpresentredirected.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtpresentredirected.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
Thank you @rtsrao, the link should be fixed tomorrow.
