### ISSUE TITLE
IRQL specs are wrong

### ISSUE THREAD

**Issue by bkmckenzie** [MicrosoftDocs/windows-driver-docs-ddi#374]
IoCreateStreamFileObjectLite is in the .PAGE section of nt, you CANNOT call this routine at IRQL == DISPATCH_LEVEL.  The IRQL requirement should say "&lt; DISPATCH_LEVEL" NOT "&lt;= DISPATCH_LEVEL"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46c7ad44-7575-4019-e631-e62cdb8b688e
* Version Independent ID: bf310f44-7609-8ce1-188a-915c628111e2
* Content: [IoCreateStreamFileObjectLite function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-iocreatestreamfileobjectlite)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-iocreatestreamfileobjectlite.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-iocreatestreamfileobjectlite.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@bkmckenzie, great catch and thanks for reporting this. Page now reflects proper IRQL.
