### ISSUE TITLE
"??\D:" Should Be "\??\D:"?

### ISSUE THREAD

**Issue by pukras** [MicrosoftDocs/windows-driver-docs-ddi#38]
In my test, "??\D:" doesn't work but "\??\D:" does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61fd640f-5387-dea6-4e7b-5a0070459e5d
* Version Independent ID: e0bff228-163a-35f7-1e79-dfc2df2a727d
* Content: [FltGetVolumeFromName function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltgetvolumefromname)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetvolumefromname.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetvolumefromname.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by AndrewHarryKim** [comment]
Missing char added.
