### ISSUE TITLE
Link to argument is missing

### ISSUE THREAD

**Issue by rtsrao** [MicrosoftDocs/windows-driver-docs-ddi#397]
Link to 'D3DKMT_SUBMITPRESENTBLTTOHWQUEUE' is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3582474-6e91-b0bd-fbb0-a4da4f8ea4d1
* Version Independent ID: 0b6413b2-a6e9-f46e-49d5-687dfaa0f380
* Content: [D3DKMTSubmitPresentBltToHwQueue function (d3dkmthk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmthk/nf-d3dkmthk-d3dkmtsubmitpresentblttohwqueue)
* Content Source: [wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtsubmitpresentblttohwqueue.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtsubmitpresentblttohwqueue.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@rtsrao You should see the fix tomorrow. Thank you!
