### ISSUE TITLE
RtlGetCompressionWorkSpaceSize() does not specify all supported compression algorithms

### ISSUE THREAD

**Issue by wxin3** [MicrosoftDocs/windows-driver-docs-ddi#40]
[The driver doc](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlgetcompressionworkspacesize) for RtlGetCompressionWorkSpaceSize() only specifies COMPRESSION_FORMAT_LZNT1 as a valid compression format where in fact COMPRESSION_FORMAT_XPRESS and COMPRESSION_FORMAT_XPRESS_HUFF should also be valid formats.

The doc is specially misleading in that it indicates COMPRESSION_FORMAT_LZNT1 is the *only* supported compression format.

**Comment by AndrewHarryKim** [comment]
COMPRESSION_FORMAT_XPRESS and COMPRESSION_FORMAT_XPRESS_HUFF should indeed be valid formats. They have been added in.
