### ISSUE TITLE
Handle cleanup

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#400]
After using this function, does the returned handle need to be closed with D3DKMTCloseAdapter?  This page doesn't mention it, nor does the documentation for the D3DKMT_OPENADAPTERFROMHDC structure, and the documentation for D3DKMTCloseAdapter only says it closes handles "previously opened by various functions".  Is it a resource leak if this is not called?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2d48d8-6924-d6d4-c246-d2cb9b27954c
* Version Independent ID: 88d22e65-7aac-3a98-88f7-93209c0074fc
* Content: [D3DKMTOpenAdapterFromHdc function (d3dkmthk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmthk/nf-d3dkmthk-d3dkmtopenadapterfromhdc)
* Content Source: [wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtopenadapterfromhdc.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmthk/nf-d3dkmthk-d3dkmtopenadapterfromhdc.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@englishb Hi Ben, That's a good question. Yes, the handle must be “closed” with that method, to avoid resource leaks. I'll update the documentation to state this.
