### ISSUE TITLE
More information about compatibility

### ISSUE THREAD

**Issue by h4tr3d** [MicrosoftDocs/windows-driver-docs-ddi#402]
This function is inlined for x64 systems from Windows XP till Windows 7. Beginning from Windows 8 this function exported from NTOSKRNL. So, if you use new WDK to build driver compatible with Windows 7 and point target Windows version to 10 (single binary approach, but you need NX pool usage to pass Win10 HLK tests), you must define WIN9X_COMPAT_SPINLOCK (sic!). 

Otherwise, you will got error on Windows 7 x64:
> Windows cannot load the device driver for this hardware. The driver may be corrupted or missing. (Code 39)

due to unresolved symbols.

For 32 bit Windows 7 all works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f36df67f-de3d-2a6a-16f0-1750937c11f1
* Version Independent ID: 2ab1aeab-046f-c6dd-b556-a606d8cbdbad
* Content: [KeInitializeSpinLock function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-keinitializespinlock)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-keinitializespinlock.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-keinitializespinlock.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @h4tr3d thanks for the suggestion.  Sorry for the delay!  Fix will be live within the hour.  Also note that you can open a PR against the docs by clicking Edit from any page.  Thanks again!
