### ISSUE TITLE
What is a DAX volume?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#403]
In the description of FLTFL_REGISTRATION_SUPPORT_DAX_VOLUME, there should be a link to where DAX volumes are described, and a description of when and why a DAX volume should/would be filtered

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 020480f3-b724-f282-cce8-43d7cde038d2
* Version Independent ID: 84eeb4e3-4d88-862c-276e-7496c0f35f9b
* Content: [_FLT_REGISTRATION (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/ns-fltkernel-_flt_registration)
* Content Source: [wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_registration.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_registration.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi @briancatlin, thanks for this excellent suggestion. I had hoped to get this done, but other priorities continue to drive this work out. I've filed an internal task for myself to add this information, so am going to close out this issue. In the interim, you can learn more by scanning through a couple of presentations done by Neal Christiansen about persistent memory and DAX:
https://www.flashmemorysummit.com/English/Collaterals/Proceedings/2016/20160810_FR21_Christiansen.pdf
https://www.snia.org/sites/default/files/SDC/2017/presentations/Solid_State_Stor_NVM_PM_NVDIMM/Christiansen_Neal_Update_on_Windows_Persistent_Memory_Support.pdf
