### ISSUE TITLE
FLTFL_INSTANCE_SETUP_DETACHED_VOLUME description is incomplete

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#405]
The description reads: "The instance is being attached to a detached volume. It is possible, on some filesystems (such as FAT and CDFS), to reattach a volume after it has detached". So, under what circumstances can a reattach happen? What is special about FAT and CDFS that allows this behavior? If the volume is dismounted, how could a reattach ever happen? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2653b0f7-277b-a360-ad88-bf96537e54ac
* Version Independent ID: dc2e62ba-efc1-8335-9820-d6cb2f945019
* Content: [PFLT_INSTANCE_SETUP_CALLBACK (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nc-fltkernel-pflt_instance_setup_callback)
* Content Source: [wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_instance_setup_callback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_instance_setup_callback.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@BrianCatlin , thanks for your questions. I've added the explanation that FAT and CDFS are frequently used by removable media, which of course means that they can be attached, detached, and reattached (perhaps multiple times).
