### ISSUE TITLE
All members not described

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#406]
Why aren't all the members of this structure documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d8ff1b5-23cf-fd65-8e4d-4f23aeea08dd
* Version Independent ID: 0c3adfc6-8847-e7f9-e15a-5a564d5d2e0c
* Content: [_FLT_TAG_DATA_BUFFER (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/ns-fltkernel-_flt_tag_data_buffer)
* Content Source: [wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_tag_data_buffer.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_tag_data_buffer.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@briancatlin, thanks for reporting this. The missing descriptions are now there.
