### ISSUE TITLE
When is FLTFL_FILTER_UNLOAD_MANDATORY set?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#407]
What user- or kernel-mode operations/actions/events cause this flag to be set? How are those operations/actions/events handled if the filter doesn't have an unload routine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f522a783-c1d1-b3b0-6845-f3cb391ae3ca
* Version Independent ID: f855f235-4e1c-3506-0c4e-3fe0559ad842
* Content: [PFLT_FILTER_UNLOAD_CALLBACK (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nc-fltkernel-pflt_filter_unload_callback)
* Content Source: [wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_filter_unload_callback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_filter_unload_callback.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@BrianCatlin , great questions. I have edited the page to be more clear, and added a link to a page with more information about load/unload (and what might cause the unload).
