### ISSUE TITLE
The docs are poisoned with html escapes

### ISSUE THREAD

**Issue by Kojoley** [MicrosoftDocs/windows-driver-docs-ddi#412]
I wanted to open a PR fixing `&amp;` on one of the pages (https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-iocreatefile), but find out there are bunch html escapes all over the place.

**Comment by EliotSeattle** [comment]
Thanks, @Kojoley. We became aware of these -- and the extent of the problem -- this week. I am working through some of them, and we're working on solutions for a couple of special, special cases.  I'll leave this open to track this in our reference repo.

**Comment by tedhudek** [comment]
Thanks for the sharp eye @Kojoley. I just pushed fixes for ampersand and greater than/less than, across the DDI docs.  Changes should be visible within an hour or two.  Sorry for taking so long!
