### ISSUE TITLE
NtCreateFile function: `returns` section renders incorrectly

### ISSUE THREAD

**Issue by Kojoley** [MicrosoftDocs/windows-driver-docs-ddi#413]
It collapsed to a parameter for some reason:
![image](https://user-images.githubusercontent.com/2743474/53827606-90462c00-3f8c-11e9-9da7-c2716229dcb7.png)

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntcreatefile

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blame/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ntcreatefile.md#L661

**Comment by EliotSeattle** [comment]
Working on the topic.

**Comment by EliotSeattle** [comment]
Thanks, @Kojoley. I took care of the issue you saw and cleaned up more of the markdown. Should go live in a few hours. 
Thanks for pointing this out.
