### ISSUE TITLE
Hint index does not seem to guarantee past-the-index return value

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#414]
http://www.osronline.com/article.cfm?id=36

While the article indicates this was pre-Win2K behaviour, we have observed that on Windows 7, the API is not guaranteed to return an index that is greater or equal to the passed in hint index.

If this is the case, documentation should indicate that the API can return such index, and RtlFindNextForwardRunClear should be used instead of hint index must be observed (i.e. if we want an index greater than or equal to some value).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f9289-7c82-dd49-8680-b0d59ff01ca8
* Version Independent ID: 05585a87-8080-b259-a2c7-30fe321ea2b9
* Content: [RtlFindClearBits function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlfindclearbits)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtlfindclearbits.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlfindclearbits.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @alfaunits you are exactly right.  I have confirmed this in the source code.  I updated the doc with a Note in the Remarks section, should be live within ~30 min.

Apologies for the delay getting to this.
