### ISSUE TITLE
No explanation of most fields

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#420]
The fields are just mentioned by name, and except for the first 3, the others have no explanation as to what exactly they represent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3004a4-4bf4-4725-7fb5-64ad8da7bbfc
* Version Independent ID: 10eafe9d-6895-bdbe-bf4c-5f2f9853a40b
* Content: [_REPARSE_DATA_BUFFER (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_reparse_data_buffer)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_reparse_data_buffer.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_reparse_data_buffer.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@alfaunits , thanks for reporting this! Information was dropped from some of our pages during a doc conversion, including this one. I have added the missing information back. Let me know if you find anything else - thanks!
