### ISSUE TITLE
Rtl*ByteSwap inconsistent documentation

### ISSUE THREAD

**Issue by dhaavi** [MicrosoftDocs/windows-driver-docs-ddi#421]
The documentation defines the functions `RtlUshortByteSwap`, `RtlUlongByteSwap`, `RtlUlonglongByteSwap ` as
```
void Rtl*ByteSwap(
   _x
);
``` 
but then the it states
```
Return Value
The byte-swapped version of the input parameter value.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c436df4b-90ef-4ee2-8330-315ac600e9da
* Version Independent ID: 28a9cae9-0c54-8846-919f-5acc2324e886
* Content: [RtlUshortByteSwap macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlushortbyteswap#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtlushortbyteswap.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlushortbyteswap.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @dhaavi for the feedback and apologies for the delay getting back to you.  This is now fixed on the 3 pages you mentioned:

* https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlushortbyteswap
* https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlulongbyteswap
* https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlulonglongbyteswap
