### ISSUE TITLE
IO_IGNORE_SHARE_ACCESS_CHECK behavior

### ISSUE THREAD

**Issue by snowkoan** [MicrosoftDocs/windows-driver-docs-ddi#43]
The docs are missing an important piece of behavior when IO_IGNORE_SHARE_ACCESS_CHECK is specified.
Yes, it allows the current open to succeed in many cases.
It ALSO means that the file system does not keep track of the current open's desired access or share access. So, a subsequent open can still succeed even if it normally wouldn't. For example:

Open an existing file via FltCreateFileEx2 (or similar) with:
DesiredAccess = FILE_READ_DATA
ShareAccess = FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE
Flags = IO_IGNORE_SHARE_ACCESS_CHECK

While the file handle is still open, open the same file with:
DesiredAccess = FILE_WRITE_DATA
ShareAccess = 0
Flags = 0

Based on the current docs, we expected that the second open would fail with STATUS_SHARING_VIOLATION, since the handle was already opened for READ.

However, the second open succeeded. We found the same regardless of the desired access of the second open — FILE_READ_DATA and DELETE also worked. We even tried on an older operating system (Windows 7 SP1) and found the same behavior.

I've written a blog post about this and will cross-post it to NTFSD for feedback.

https://needleinathreadstack.wordpress.com/2018/04/09/io_ignore_share_access_check/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a61ac7bc-452e-b273-3253-da8e4a277b4f
* Version Independent ID: 7af41083-d22e-7cbf-26dd-9c645baad104
* Content: [FltCreateFileEx2 function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltcreatefileex2)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcreatefileex2.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcreatefileex2.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
@aahill I missed this one when I reassigned the issues that Andrew had before he left the team. Can you please pick this up? So sorry, @snowkoan

**Comment by aahill** [comment]
Hi @snowkoan, @EliotSeattle, thanks for the notification. I've put this information into the topic and will have it live shortly. Thanks for this pull request, and for documenting the process - we appreciate it!
