### ISSUE TITLE
Possibly puzzling STATUS_FLT_INVALID_NAME_REQUEST

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#434]
A note should be added that if the CreatePreOp has FILE_OPEN_BY_FILE_ID flag, and the FileName does not contain a valid File ID, the API will return STATUS_FLT_INVALID_NAME_REQUEST (i.e. modify the docs to include this as a possible reason for STATUS_FLT_INVALID_NAME_REQUEST).

It is otherwise hard to figure why the API fails with that code in IRP_MJ_CREATE PreOp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c69953-3606-33d2-1c71-fa25b72a82da
* Version Independent ID: 67b78c7c-0fdc-ab17-d7d7-53a6b3eaded0
* Content: [FltGetFileNameInformation function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltgetfilenameinformation#see-also)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetfilenameinformation.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetfilenameinformation.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@alfaunits , can you submit a code snippet that shows STATUS_FLT_INVALID_NAME_REQUEST being returned for an invalid file ID? Assuming you made a *valid* name query with an *invalid* file id, depending on what this “invalid” file id looks like, one might get STATUS_OBJECT_NAME_INVALID (0 length file name) or STATUS_INVALID_PARAMETER (non-existing file for instance). I'm not seeing how STATUS_FLT_INVALID_NAME_REQUEST would be returned in this situation. I'm gonna close this for now. We can reopen if you can repo the condition. Appreciate your interest in enhancing the docs!
