### ISSUE TITLE
what is MessageId argument? 

### ISSUE THREAD

**Issue by russli1993** [MicrosoftDocs/windows-driver-docs-ddi#437]
What is the meaning of the MessageId argument? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eae4f799-e1ae-6d1c-da69-e270f821cdc9
* Version Independent ID: 1917cdd2-3996-abb9-556a-3f4c587d45b1
* Content: [KMESSAGE_SERVICE_ROUTINE (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nc-wdm-kmessage_service_routine)
* Content Source: [wdk-ddi-src/content/wdm/nc-wdm-kmessage_service_routine.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nc-wdm-kmessage_service_routine.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @russli1993 thanks for pointing this out, and apologies for the delay.  I've just updated the page with the info -- https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nc-wdm-kmessage_service_routine.  Thanks again for helping the docs improve!
