### ISSUE TITLE
Return value is not void

### ISSUE THREAD

**Issue by pankajbharti** [MicrosoftDocs/windows-driver-docs-ddi#438]
Return value of this function is not void. The document syntax incorrectly states that it is void. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4176e6e8-60de-1e81-ad5b-20831be5cb94
* Version Independent ID: 50e5965d-388f-adea-57f8-57f54778be4b
* Content: [WdfDeviceStopIdle macro (wdfdevice.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfdevice/nf-wdfdevice-wdfdevicestopidle#feedback)
* Content Source: [wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicestopidle.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicestopidle.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Fixed. Thanks @pankajbharti
