### ISSUE TITLE
Discrepancy of definition

### ISSUE THREAD

**Issue by GrafThomas** [MicrosoftDocs/windows-driver-docs-ddi#44]
The actual definition of USB_NODE_CONNECTION_INFORMATION_EX_V2_FLAGS in usbioctl.h differs from the one given in this documentation (it is a union not a struct and bit [1] and [2] are interchanged).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7a5f00b-157b-7bd6-ae29-43309f18b7f0
* Version Independent ID: 6ac889e6-d85e-038a-8166-00f5abc6dbcc
* Content: [_USB_NODE_CONNECTION_INFORMATION_EX_V2_FLAGS](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbioctl/ns-usbioctl-_usb_node_connection_information_ex_v2_flags)
* Content Source: [wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_node_connection_information_ex_v2_flags.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ns-usbioctl-_usb_node_connection_information_ex_v2_flags.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello:

Thanks for noticing the bug! This has now been fixed. Please let us know if you find other issues.
