### ISSUE TITLE
Tilde is 0x7E, not 0x126.

### ISSUE THREAD

**Issue by mrolle45** [MicrosoftDocs/windows-driver-docs-ddi#443]
Same correction has been made to the ExAllocatePoolWithTag page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a6cb22-0679-752f-e6c5-89cb4d3782da
* Version Independent ID: aaa9d239-876d-2ba1-2f13-d91fa60ccbee
* Content: [ExFreePoolWithTag function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-exfreepoolwithtag#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exfreepoolwithtag.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exfreepoolwithtag.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by billlattimer** [comment]
@mrolle45 thank you for catching this; corrected.
