### ISSUE TITLE
Bug in code example

### ISSUE THREAD

**Issue by Eljay-Adobe** [MicrosoftDocs/windows-driver-docs-ddi#445]
Cannot have a global variable and a global function with the same name.  Developers who try to follow the example may be confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3f72fa6-a7b0-9ca4-0e13-fb09d1aa13f2
* Version Independent ID: 5a45eb90-0f2c-eff4-49cf-aff0a9d7b266
* Content: [PCREATE_THREAD_NOTIFY_ROUTINE (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nc-ntddk-pcreate_thread_notify_routine#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/nc-ntddk-pcreate_thread_notify_routine.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nc-ntddk-pcreate_thread_notify_routine.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @Eljay-Adobe, apologies for the delay.  Are you sure you opened this issue from the right page?  I don't see an example on https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nc-ntddk-pcreate_thread_notify_routine.  Please reopen if I'm missing something.  Thanks for the feedback!
