### ISSUE TITLE
The left had side index is not in aphabatical order

### ISSUE THREAD

**Issue by pankajbharti** [MicrosoftDocs/windows-driver-docs-ddi#448]
The left hand side index that shows all the APIs under wdfdriver.h are not in alphabetical order. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 354cc9b8-bd82-29b0-ce15-894d7d30defd
* Version Independent ID: 7836c59e-9315-cc73-92ec-e6f9944ceee9
* Content: [WdfDriverRetrieveDriverDataDirectoryString function (wdfdriver.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfdriver/nf-wdfdriver-wdfdriverretrievedriverdatadirectorystring)
* Content Source: [wdk-ddi-src/content/wdfdriver/nf-wdfdriver-wdfdriverretrievedriverdatadirectorystring.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdriver/nf-wdfdriver-wdfdriverretrievedriverdatadirectorystring.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @pankajbharti I totally agree that these should be alphabetized. I don't have control over that part of the docs however. I reached out to the publishing team and they've created a work item to track it.  I'll send you the link internally.
