### ISSUE TITLE
Page formating

### ISSUE THREAD

**Issue by reuvenab** [MicrosoftDocs/windows-driver-docs-ddi#45]
Section titles for "Result",  "Remarks" and "Examples" have bad formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bb2377-bca2-2c5f-35c2-96e35c3050cc
* Version Independent ID: 68a7b48c-7c0e-a061-59c5-324e6aabaae9
* Content: [WdfTimerStart function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdftimer/nf-wdftimer-wdftimerstart)
* Content Source: [wdk-ddi-src/content/wdftimer/nf-wdftimer-wdftimerstart.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdftimer/nf-wdftimer-wdftimerstart.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @reuvenab. I believe the page is now rendering in all its beauty. Let us know if you see anything else like this. You can always edit the content and submit a pull request, too. 
Cheers!
Eliot
