### ISSUE TITLE
IRQL missing

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#451]
Why isn't the IRQL at which this routine is called not specified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c26496b-a5ab-b87d-888f-277f7588c9b6
* Version Independent ID: 499ccc72-38c4-2823-0fce-547209873304
* Content: [PFLT_SECTION_CONFLICT_NOTIFICATION_CALLBACK (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nc-fltkernel-pflt_section_conflict_notification_callback)
* Content Source: [wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_section_conflict_notification_callback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_section_conflict_notification_callback.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@BrianCatlin , thanks for flagging this - the IRQL is now there. FYI that I hope to get to your other submitted issues soon!
