### ISSUE TITLE
Are "MembersFlags" and "Flags" exactly the same?

### ISSUE THREAD

**Issue by sun-xm** [MicrosoftDocs/windows-driver-docs-ddi#452]
What's the difference between "MembersFlags" and "Flags"? The descriptions are same for these two fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf25ecb4-4514-6967-a803-e0a951fa1511
* Version Independent ID: 90b506aa-c3e1-c85b-85c7-09ccc6cd493d
* Content: [KSPROPERTY_MEMBERSHEADER (ks.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ks/ns-ks-ksproperty_membersheader)
* Content Source: [wdk-ddi-src/content/ks/ns-ks-ksproperty_membersheader.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ks/ns-ks-ksproperty_membersheader.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks @sun-xm, you have highlighted a probable error in the docs. I will open an internal work item to address this issue. 

However, I would also recommend that you post your question in the following forums, where other driver developers and Microsoft engineers can be found. 

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
