### ISSUE TITLE
Name provider flags are not mentioned

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#454]
even though the NameChanger sample uses Name Provider flags in this call, as can be used in FltGetFileNameInformation, the docs do not mention them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1002d23-2f37-2eaa-f40b-fa5aba120d5a
* Version Independent ID: dc26a275-6cfe-1a71-0e80-376276edba0a
* Content: [FltGetDestinationFileNameInformation function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltgetdestinationfilenameinformation)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetdestinationfilenameinformation.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetdestinationfilenameinformation.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@alfaunits , thanks for reporting this. I've added file name flags and descriptions to FltGetDestinationFileNameInformation.
