### ISSUE TITLE
Unicode String links broken

### ISSUE THREAD

**Issue by molocules** [MicrosoftDocs/windows-driver-docs-ddi#462]
Hi! The links to UNICODE STRING are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875369f5-4ea7-052a-66e0-07607b6f1557
* Version Independent ID: 10e9d3d4-83f6-e4c8-855d-c1e93a9887b2
* Content: [WdfDeviceCreateSymbolicLink function (wdfdevice.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfdevice/nf-wdfdevice-wdfdevicecreatesymboliclink#feedback)
* Content Source: [wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicecreatesymboliclink.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicecreatesymboliclink.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by billlattimer** [comment]
@molocules, thanks for catching this - fixed.
