### ISSUE TITLE
InitializeObjectAttributes link is broken.

### ISSUE THREAD

**Issue by MolusMS** [MicrosoftDocs/windows-driver-docs-ddi#463]
The link in this sentence is broken:
"Use InitializeObjectAttributes to initialize this structure."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7c72f2-ea7a-b6e9-cafd-e9c6a0b41451
* Version Independent ID: 57678e7f-5c9a-2798-1eea-7b6662beb7c0
* Content: [ZwOpenSection function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwopensection#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwopensection.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwopensection.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @MolusMS for the feedback and apologies for the delay getting back to you.  This is now fixed.  I updated all the links in the doc repo to point to the new page, which is: 

https://docs.microsoft.com/en-us/windows/desktop/api/ntdef/nf-ntdef-initializeobjectattributes
