### ISSUE TITLE
Documented header for TargetIPv6Addresses is incorrect

### ISSUE THREAD

**Issue by jtippet** [MicrosoftDocs/windows-driver-docs-ddi#464]
It should be
TargetIPv6Addresses[2][16]
not
TargetIPv6Addresses[2]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c837ceeb-9564-7df5-0e4e-a8d279a88b33
* Version Independent ID: abd93fcd-9e5b-4b41-f44e-72d9951e112d
* Content: [_NDIS_PM_PROTOCOL_OFFLOAD (ntddndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddndis/ns-ntddndis-_ndis_pm_protocol_offload#feedback)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_pm_protocol_offload.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_pm_protocol_offload.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Thanks for finding this, @jtippet. I've made the fix for the syntax on this page; the changes should be live for that next Monday after our publishing pipeline opens up again.
