### ISSUE TITLE
Which are mandatory?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#469]
Are all of these entry points required, or are some optional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a87f351-6b9b-38a5-7db7-d4f51aafdfa4
* Version Independent ID: b4f98dac-db93-f77a-ed4c-76b798a17ba4
* Content: [_UFX_DEVICE_CALLBACKS (ufxclient.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ufxclient/ns-ufxclient-_ufx_device_callbacks)
* Content Source: [wdk-ddi-src/content/ufxclient/ns-ufxclient-_ufx_device_callbacks.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ufxclient/ns-ufxclient-_ufx_device_callbacks.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin, good question. The example on [UfxDeviceCreate](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ufxclient/nf-ufxclient-ufxdevicecreate) fills in some but not all of the callbacks, so it's unclear which ones are mandatory and when. Let me email the USB folks to see what I can find out.

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
