### ISSUE TITLE
IMiniportWaveRTStream interface lists no methods

### ISSUE THREAD

**Issue by GeoffPark** [MicrosoftDocs/windows-driver-docs-ddi#47]
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/portcls/nn-portcls-iminiportwavertstream

Under:
"Methods
The IMiniportWaveRTStream interface has these methods."

Nothing is listed. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8137714-ff4e-2e4c-e584-914df90e52c8
* Version Independent ID: e1e92835-868f-d7cf-4635-b8260c328261
* Content: [IMiniportWaveRTStream](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/portcls/nn-portcls-iminiportwavertstream)
* Content Source: [wdk-ddi-src/content/portcls/nn-portcls-iminiportwavertstream.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nn-portcls-iminiportwavertstream.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@GeoffPark - This was a glitch in our new API/DDI publishing system, that has since been fixed. Thanks for pointing out this issue.
