### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#470]
1. The description for FdoAttributes appears to have been cut off. 
2. What WDF attributes should a driver set for UFX? 
3. Please add SAL annotations to ALL the UFX APIs (not just this one) so we know which are input and output parameters!
4. The code example has HTML tags (&amp;) in them, and needs considerably more detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcc517e9-3d65-2ca2-ad18-51d21ec8237e
* Version Independent ID: 305df2b6-fb8d-6888-1735-7f257320668f
* Content: [UfxFdoInit function (ufxclient.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ufxclient/nf-ufxclient-ufxfdoinit)
* Content Source: [wdk-ddi-src/content/ufxclient/nf-ufxclient-ufxfdoinit.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ufxclient/nf-ufxclient-ufxfdoinit.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
