### ISSUE TITLE
Parameters are not described

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#471]
How about describing the parameters? Just specifying their data type is not helpful. Please annotate them with SAL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4786a627-e46a-c580-3c30-78171d9f9efc
* Version Independent ID: 72ffce5b-4cdc-5acd-ffa0-0b9fc12528ef
* Content: [EVT_UFX_DEVICE_DEFAULT_ENDPOINT_ADD (ufxclient.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ufxclient/nc-ufxclient-evt_ufx_device_default_endpoint_add)
* Content Source: [wdk-ddi-src/content/ufxclient/nc-ufxclient-evt_ufx_device_default_endpoint_add.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ufxclient/nc-ufxclient-evt_ufx_device_default_endpoint_add.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
