### ISSUE TITLE
More detail needed

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#472]
How is anyone supposed to code from this? This needs a LOT more information on the two queues, how the attributes should be set (there is a note in the listing comments that needs to be fully explained), the context blocks, and the architecture (some pictures would be great!) behind this. The parameters also need to be annotated with SAL, so we know which are _In_, _Out_, or _InOut_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b0593ca-5ddf-958b-076b-bd2fe7f91b98
* Version Independent ID: 0dea6ef4-432d-e3a4-6262-5aabe806031d
* Content: [UfxEndpointCreate function (ufxclient.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ufxclient/nf-ufxclient-ufxendpointcreate)
* Content Source: [wdk-ddi-src/content/ufxclient/nf-ufxclient-ufxendpointcreate.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ufxclient/nf-ufxclient-ufxendpointcreate.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
