### ISSUE TITLE
GroupID doesn't make sense

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#475]
What does this mean? Please provide an example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d7bda6-bdde-3714-bc38-16b76f225c51
* Version Independent ID: 36b1c623-a4e2-8008-33f3-65c414c638c4
* Content: [_UFX_DEVICE_CAPABILITIES (ufxbase.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ufxbase/ns-ufxbase-_ufx_device_capabilities)
* Content Source: [wdk-ddi-src/content/ufxbase/ns-ufxbase-_ufx_device_capabilities.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ufxbase/ns-ufxbase-_ufx_device_capabilities.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
