### ISSUE TITLE
Description for Max is repeated in the description for Step

### ISSUE THREAD

**Issue by saredd** [MicrosoftDocs/windows-driver-docs-ddi#479]
The first sentence in the description is a repeat of the description for Max.
It should be deleted

"The maximum range value for the setting in VideoProc."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ecd96da-f4b9-985e-f77c-a0ba1646550b
* Version Independent ID: c5e5efa8-de92-4e65-ab89-4eb84df8e94a
* Content: [tagKSCAMERA_EXTENDEDPROP_VIDEOPROCSETTING (ksmedia.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ksmedia/ns-ksmedia-tagkscamera_extendedprop_videoprocsetting#feedback)
* Content Source: [wdk-ddi-src/content/ksmedia/ns-ksmedia-tagkscamera_extendedprop_videoprocsetting.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ksmedia/ns-ksmedia-tagkscamera_extendedprop_videoprocsetting.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Updated description and eliminated duplication.
