### ISSUE TITLE
Info Missed

### ISSUE THREAD

**Issue by ahmad-ghafouri** [MicrosoftDocs/windows-driver-docs-ddi#48]
Hello Microsoft,
The following link's article is not finished. At the end and after the 'following' there is nothing.
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddndis/ns-ntddndis-_ndis_tcp_large_send_offload_v1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50cc7425-6faf-23a8-561a-0d850db7a129
* Version Independent ID: 72a1a6bf-535a-72db-6cc8-c9e35b7d4d4c
* Content: [_NDIS_TCP_LARGE_SEND_OFFLOAD_V1](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddndis/ns-ntddndis-_ndis_tcp_large_send_offload_v1)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_tcp_large_send_offload_v1.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_tcp_large_send_offload_v1.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Oops, it does indeed look like some content got dropped on both that page and the offload_v2 page. I've taken care of it and the changes should be live soon. Thanks for the catch, @ahmad-ghafouri!
