### ISSUE TITLE
Syntax and Return Value sections do not match

### ISSUE THREAD

**Issue by mghiya** [MicrosoftDocs/windows-driver-docs-ddi#483]
The Syntax section specifies that the function returns a void whereas the Return Value section specifies that the function return TRUE or FALSE. So, I'd imagine, the Syntax should have been:

BOOLEAN RtlEqualMemory(
   Destination,
   Source,
   Length
);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebe1e355-b322-9120-0fc3-e93dc37fc85f
* Version Independent ID: 9f2bafb7-6f65-244b-4d79-4c2540254f6c
* Content: [RtlEqualMemory macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlequalmemory#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtlequalmemory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlequalmemory.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Fixed!  Thanks for the alert @mghiya
