### ISSUE TITLE
STATUS_FLT_CONTEXT_ALLOCATION_NOT_FOUND

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#487]
The description for STATUS_FLT_CONTEXT_ALLOCATION_NOT_FOUND should be expanded to include: "FltAllocateContext returns this status if the requested ContextSize does not match the Size specified in the FLT_CONTEXT_REGISTRATION  structure for the specified ContextType". Of course, more detail would be required in the case of variable-sized context structures, but this is the most important idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 320eee19-e3dc-2080-af62-1cdb7c139896
* Version Independent ID: 0e8ae0f1-69e1-bef1-8af7-757f022586e6
* Content: [FltAllocateContext function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltallocatecontext)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltallocatecontext.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltallocatecontext.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@BrianCatlin , thanks for reporting this! I have added this additional error condition to FltAllocateContext.
