### ISSUE TITLE
Reentrance

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs-ddi#489]
This page should state very clearly whether this callback is reentrant, i.e. whether it can be running simultaneously on multiple processors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e464da00-4c10-8edb-4a71-2ddd2d529bb6
* Version Independent ID: b7abfc25-89f9-2255-59b8-5e9ac3d78572
* Content: [EVT_WDF_INTERRUPT_DPC (wdfinterrupt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfinterrupt/nc-wdfinterrupt-evt_wdf_interrupt_dpc#feedback)
* Content Source: [wdk-ddi-src/content/wdfinterrupt/nc-wdfinterrupt-evt_wdf_interrupt_dpc.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfinterrupt/nc-wdfinterrupt-evt_wdf_interrupt_dpc.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @jakeoshins for the suggestion.

Fixed in #558, should be live in 10 min
