### ISSUE TITLE
Targeted Processor

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs-ddi#490]
This page should state whether the enqueued DPC runs on the processor that enqueued it, or the processor on which the ISR would run, either or neither.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a724e2-e5ab-749c-f321-4e8e4cbc2fd9
* Version Independent ID: 4425cc3f-cb48-1cc5-4518-022e2eb9300f
* Content: [WdfInterruptQueueDpcForIsr function (wdfinterrupt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfinterrupt/nf-wdfinterrupt-wdfinterruptqueuedpcforisr)
* Content Source: [wdk-ddi-src/content/wdfinterrupt/nf-wdfinterrupt-wdfinterruptqueuedpcforisr.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfinterrupt/nf-wdfinterrupt-wdfinterruptqueuedpcforisr.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @jakeoshins for the suggestion.

Fixed in #558, should be live in 10 min
