### ISSUE TITLE
Fields not documented

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#493]
What aren't all the fields documented? What is BirthVolumeID, BirthObjectID, and DomainID? It is most certainly not "User provided data"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef116b04-b17e-f171-3947-8ce3fe32b98e
* Version Independent ID: d547926b-ec46-66f5-58ec-f570cc9f5417
* Content: [_FILE_OBJECTID_INFORMATION (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_file_objectid_information)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_file_objectid_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_file_objectid_information.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@BrianCatlin , thanks for reporting this. I've added information for the missing fields. Our build process changed about a year ago to be more automated based on headers. It's really great for the most part, but we see some anomalies, especially in unions with unnamed structs. Please continue to submit issues to better the docs - much appreciated!
