### ISSUE TITLE
ZwCreateSection page contains broken links

### ISSUE THREAD

**Issue by MSxDOS** [MicrosoftDocs/windows-driver-docs-ddi#497]
Links to `OBJECT_ATTRIBUTES` and `InitializeObjectAttributes` return 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e60ea10-5a11-6331-a47b-9472e444fbcb
* Version Independent ID: 3d19e81c-bdaf-db90-8f39-9b364f3e7404
* Content: [ZwCreateSection function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwcreatesection)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwcreatesection.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwcreatesection.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @MSxDOS for the feedback and apologies for the delay getting back to you.  This is now fixed.  I updated the links across the doc repo.  The new pages are:

https://docs.microsoft.com/en-us/windows/desktop/api/ntdef/nf-ntdef-initializeobjectattributes
https://docs.microsoft.com/en-us/windows/desktop/api/ntdef/ns-ntdef-_object_attributes
