### ISSUE TITLE
Missing control mode behavior page?

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#498]
I cannot find a page on MSDN describing the DXGKDDI_CONTROLMODEBEHAVIOR entry point, and there is no link to it here where all of the other entry point page links are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42e4ce3a-a8be-f917-8aed-6f911b5496cc
* Version Independent ID: d756ae62-7772-e4da-9d03-26a6767f61dc
* Content: [_DRIVER_INITIALIZATION_DATA (dispmprt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dispmprt/ns-dispmprt-_driver_initialization_data)
* Content Source: [wdk-ddi-src/content/dispmprt/ns-dispmprt-_driver_initialization_data.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dispmprt/ns-dispmprt-_driver_initialization_data.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@englishb , thanks for reporting the missing page. I've created a DXGKDDI_CONTROLMODEBEHAVIOR callback refpage, and added a link to it from the DRIVER_INITIALIZATION_DATA page.
