### ISSUE TITLE
Return Value incorrectly states None

### ISSUE THREAD

**Issue by ablaylock** [MicrosoftDocs/windows-driver-docs-ddi#499]
The `OEMEscape` function returns a value but the documentation says it returns "None" which clearly conflicts. Since the OEMEscape function return value likely depends on the escape code it would be nice to know if there are any universal return codes. For example are there any codes that inform the caller that the escape code is not implemented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136c6902-415d-1113-fc9d-b60b8251f336
* Version Independent ID: 11a54a67-a437-e3d7-83c4-5c1c1464f05b
* Content: [OEMEscape function (printoem.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/printoem/nf-printoem-oemescape)
* Content Source: [wdk-ddi-src/content/printoem/nf-printoem-oemescape.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/printoem/nf-printoem-oemescape.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@ablaylock, thanks for pointing out the incorrect return values. I'm opening an internal work item to correct and update the OEMEscape function topic.

Also, you may have success posting your question about correct return values for the OEMEscape function in the following forums, where other driver developers and Microsoft engineers can be found. 

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
