### ISSUE TITLE
Missing Library entry for ```HidD_GetAttributes```

### ISSUE THREAD

**Issue by LokiMidgard** [MicrosoftDocs/windows-driver-docs-ddi#5]
At the top of the documentation of [HidD_GetAttribtes](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/hidsdi/nf-hidsdi-hidd_getattributes#requirements) is the entry for Library missing.

But at the top of the corresponding MarkDown file there is a metadata entry ```req.lib: Hid.lib```.

I assume the generator should include the library on the site.

**Comment by tedhudek** [comment]
Thanks @LokiMidgard this is a backend issue that we hope to have fixed soon.  I'm keeping this issue open to track it in the meantime

**Comment by PageWriter-MSFT** [comment]
Thanks @LokiMidgard. This issue is now fixed.
