### ISSUE TITLE
VM_OPERATION spelling

### ISSUE THREAD

**Issue by MarcoPeretti** [MicrosoftDocs/windows-driver-docs-ddi#50]
It is actually PROCESS_VM_OPERATION, without the final "S".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9beaec6a-c99a-3de9-f89a-8e8f1995240a
* Version Independent ID: 196da704-5288-514b-120a-ae747ae9c4f5
* Content: [_OB_PRE_CREATE_HANDLE_INFORMATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_ob_pre_create_handle_information)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_ob_pre_create_handle_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_ob_pre_create_handle_information.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello Marco,

This is now fixed. Thanks for catching that.

PageWriter
