### ISSUE TITLE
Should this API also be called for DFx Power Up?

### ISSUE THREAD

**Issue by tzimmer1** [MicrosoftDocs/windows-driver-docs-ddi#502]
Per https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nc-wdm-po_fx_directed_power_up_callback,
it is stated this API should also be called for the DFx PowerUp API.

Can that info be added here for clarity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6105b0cb-abf9-8568-a6c4-2fb08b038d96
* Version Independent ID: 90feb8b7-a698-1158-cf33-9dcab9b099f5
* Content: [PoFxCompleteDirectedPowerDown function - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-pofxcompletedirectedpowerdown)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-pofxcompletedirectedpowerdown.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-pofxcompletedirectedpowerdown.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @tzimmer1, apologies for the delay.  Thanks for spotting an error in the docs.  The power up callback should actually call **PoFxReportDevicePoweredOn** to complete the callback.  I've just made the change, and it should propagate to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nc-wdm-po_fx_directed_power_up_callback within the hour.
