### ISSUE TITLE
Missing documentation of FltMgr pseudo IRPs

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#503]
There is no documentation for IRP_MJ_ACQUIRE_FOR_SECTION_SYNCHRONIZATION, IRP_MJ_RELEASE_FOR_SECTION_SYNCHRONIZATION, IRP_MJ_ACQUIRE_FOR_MOD_WRITE, IRP_MJ_RELEASE_FOR_MOD_WRITE, IRP_MJ_ACQUIRE_FOR_CC_FLUSH, IRP_MJ_RELEASE_FOR_CC_FLUSH, IRP_MJ_QUERY_OPEN, IRP_MJ_FAST_IO_CHECK_IF_POSSIBLE, IRP_MJ_NETWORK_QUERY_OPEN, IRP_MJ_MDL_READ, IRP_MJ_MDL_READ_COMPLETE, IRP_MJ_PREPARE_MDL_WRITE, IRP_MJ_MDL_WRITE_COMPLETE, IRP_MJ_VOLUME_MOUNT, IRP_MJ_VOLUME_DISMOUNT. These are all valid (and defined in FltKernel.h), but there are no descriptions of these IRPs, such as when they are sent and what a filter driver can do with them in pre and post callbacks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14708bcf-22c4-9e1f-cb80-d800e0f77eaf
* Version Independent ID: a5ee16f6-1fd1-6a41-5faa-97b8e612459c
* Content: [_FLT_OPERATION_REGISTRATION (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/ns-fltkernel-_flt_operation_registration)
* Content Source: [wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_operation_registration.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_operation_registration.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@briancatlin, [FLT_PARAMETERS](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/ns-fltkernel-_flt_parameters) now contains links for each pseudo-IRP that you mention above. There aren't equivalent pages like [IRP_MJ_CLEANUP](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-cleanup) because (as you point out) these are pseudo-IRPs that legacy filters won't see.
