### ISSUE TITLE
Missing description of ExtendedInfo

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#505]
The description of ExtendedInfo is meaningless. What EXACTLY is "Additional information about the file system volume"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c0ce943-6a02-4219-1321-a5dd4aa425af
* Version Independent ID: be2d7396-6ee5-d00d-b26a-b089023d0a46
* Content: [_FILE_FS_OBJECTID_INFORMATION (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/ns-ntddk-_file_fs_objectid_information)
* Content Source: [wdk-ddi-src/content/ntddk/ns-ntddk-_file_fs_objectid_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/ns-ntddk-_file_fs_objectid_information.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by lorihollasch** [comment]
Thanks for this feedback, @BrianCatlin - I've updated the description. Not sure if this is of any additional help, but here is a link to the [FileFsObjectIdInformation ](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/dbf535ae-315a-4508-8bc5-84276ea106d4
)page of the MS-FSCC specification.
