### ISSUE TITLE
Need more detail

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#516]
In the sentence, "If a minifilter driver retrieves normalized file name information in the preoperation callback routine (PFLT_PRE_OPERATION_CALLBACK) for a create, hard-link, or rename operation, it must call FltGetTunneledName from its postoperation callback routine (PFLT_POST_OPERATION_CALLBACK) to retrieve the correct file name information for the file.", it does not explain HOW a pre-op callback is supposed to detect "a create, hard-link, or rename operation"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73416777-1f77-eda4-e72b-e2c07222c04e
* Version Independent ID: 825abd6b-f8a3-4fe2-348a-535a301deadf
* Content: [FltGetTunneledName function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltgettunneledname)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgettunneledname.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgettunneledname.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@briancatlin, thanks for flagging this. I have added pre-op create, hard-link, rename detection info to the page.
