### ISSUE TITLE
Very bad example

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#532]
This code example is terrible, because the values of the constants aren't provided, the reader must go to the sample and then search to find them. Also, there should be a discussion of how to choose an alignment value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50aa3053-7e22-be46-a2d9-1f9d15ff08c3
* Version Independent ID: db63447f-72e5-3895-f7bd-55a40ab95cd9
* Content: [WdfDeviceSetAlignmentRequirement function (wdfdevice.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfdevice/nf-wdfdevice-wdfdevicesetalignmentrequirement)
* Content Source: [wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicesetalignmentrequirement.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicesetalignmentrequirement.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback.  The exact value is totally dependent on the hardware, so there's not a lot to add here.  I updated the page to indicate that, and added the list of values from wdm.h.  Give it an hour or so to propagate to the live site.
