### ISSUE TITLE
Repeat of the last 2 paragraphs.

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#537]
Title says it all ;)
They are repeated 6 and 7 paragraphs above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2679ffa-4774-8de8-3ee8-d75c18aa48f4
* Version Independent ID: af7a279a-93aa-5e5b-fbb5-1e0c2ee14a07
* Content: [KeWaitForSingleObject function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-kewaitforsingleobject#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-kewaitforsingleobject.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-kewaitforsingleobject.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Done.
Thanks for the catch, @alfaunits
