### ISSUE TITLE
FsRtlIsNameInExpression can raise STATUS_NO_MEMORY exception

### ISSUE THREAD

**Issue by kobykahane** [MicrosoftDocs/windows-driver-docs-ddi#538]
In low resource conditions, the FsRtlIsNameInExpression function can raise a structured exception with code STATUS_NO_MEMORY. However, this is not mentioned in its documentation page.
Additionally, the title incorrectly says "_FSRTL_ADVANCED_FCB_HEADER::FsRtlIsNameInExpression function", but this is a global API completely unrelated to the FSRTL_ADVANCED_FCB_HEADER structure and certainly not a member of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a79a15-8ae0-3056-e883-994969448a60
* Version Independent ID: 36a2a3cc-5b46-eaad-514b-40ad9baf1001
* Content: [FsRtlIsNameInExpression function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlisnameinexpression#feedback)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlisnameinexpression.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlisnameinexpression.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@kobykahane, GREAT CATCH - very important! I've added the raised structured exception info to the page. Sadly, I cannot do anything about the mashing of FSRTL_ADVANCED_FCB_HEADER onto this page - this is a known parsing bug in our doc building tools. We are tracking the issue with an internal bug, so I am going to close this out. Sorry for the degraded reading experience that this causes.
