### ISSUE TITLE
Content not in location where other pages expect it.

### ISSUE THREAD

**Issue by RonaldAi** [MicrosoftDocs/windows-driver-docs-ddi#539]
The pages for the interlocked API are not where other pages expect it.
https://docs.microsoft.com/en-us/windows/desktop/sync/interlocked-variable-access, for instance, expects the content at https://docs.microsoft.com/en-us/windows/desktop/api/WinBase/nf-winbase-interlockeddecrement
https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/mmcreatemdl uses links to old content, which gets redirected to https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-interlockeddecrement as well.
Maybe add yet another redirect fromhttps://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-interlocked* to this location, or move the content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7420579-6f2e-a870-7c24-d172e680aadc
* Version Independent ID: fc71af9b-8caf-9262-344e-a12c24cf7576
* Content: [InterlockedDecrement function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-interlockeddecrement)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-interlockeddecrement.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-interlockeddecrement.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
I think this is fixed now for the page you opened it on.  Specifically, on https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/mmcreatemdl, I can click InterlockedDecrement, InterlockedExchange, and InterlockedIncrement, and they all go to expected places in the https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-interlockeddecrement neighborhood.

For the pages that have /desktop/ in the URL, that's a different writer team, so you would need to open an issue against those pages if you so desire.

Thanks for the feedback, and apologies for the delay in responding!
