### ISSUE TITLE
ZeroBits parameter

### ISSUE THREAD

**Issue by TomaszNowakSanDiego** [MicrosoftDocs/windows-driver-docs-ddi#54]
Looks like description for ZeroBits parameter is coming from old 32-bit systems. On x64 ZeroBits can be bigger than mentioned 21 (as everyone can see it is defined as ULONG_PTR which covers all 64 bits). 
If ZeroBits is greater than 32 it becomes a bitmask. 

Also in AllocationType there's an option MEM_WRITE_WATCH not described above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63532e27-812d-b8c3-b9b8-46e6cbb3f45b
* Version Independent ID: 9cac464a-c5d6-9b5c-1816-f17fb2d41944
* Content: [NtAllocateVirtualMemory function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntallocatevirtualmemory)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ntallocatevirtualmemory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ntallocatevirtualmemory.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @TomaszNowakSanDiego, Thanks for reaching out to us! I've updated the description for ZeroBits, and added the missing option to AllocationType. 
Thanks for catching this; feel free to let us know if you come across anything else in the documentation!
