### ISSUE TITLE
Structure member definitions repeated twice

### ISSUE THREAD

**Issue by vnvsrikanth** [MicrosoftDocs/windows-driver-docs-ddi#542]
In the structure "DXGK_SET_TIMING_RESULTS", member variable "Value" is defined twice instead of once here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9160c96-7cd1-9b7c-74a6-00c3c3370ac8
* Version Independent ID: d536b7ed-95a4-da1b-1e8a-40d60ba0a9f1
* Content: [_DXGK_SET_TIMING_RESULTS (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/ns-d3dkmddi-_dxgk_set_timing_results)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_set_timing_results.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_set_timing_results.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@vnvsrikanth , thanks for reporting this. This behavior is because of a bug in our internal documentation build tools. There is an internal bug filed against this behavior, so I am closing this GitHub issue. Thanks again, and apologies for the rendering glitch!
