### ISSUE TITLE
Structure members are repeated twice.

### ISSUE THREAD

**Issue by vnvsrikanth** [MicrosoftDocs/windows-driver-docs-ddi#543]
MonitorConnect/TargetConnect/TargetJoin are repeated twice in the structure definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cdec7f5-7781-bc22-dff0-f6ced982868c
* Version Independent ID: a388bc12-370b-bb73-5c80-df7cd3ac4460
* Content: [_DXGK_CONNECTION_CHANGE (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/ns-d3dkmddi-_dxgk_connection_change)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_connection_change.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_connection_change.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@vnvsrikanth , thanks for reporting this. This behavior is because of a bug in our internal documentation build tools. There is an internal bug filed against this behavior, so I am closing this GitHub issue. Thanks again, and apologies for the rendering glitch!
