### ISSUE TITLE
Incorrect reason for FLTFL_INSTANCE_TEARDOWN_INTERNAL_ERROR

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#545]
It is almost never the case that failure to allocate memory is why an instance is torn down with flags set to FLTFL_INSTANCE_TEARDOWN_INTERNAL_ERROR. Please list all the reasons. The use of this status code is laziness on the part of the developers. Most of the time, the reason has to do with the minifilter not configuring something properly (frequently a registration structure). Why not pass a status code that informed the driver writer what they did wrong (or writing an ETW message), instead of making them guess?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5ebdc2e-3bb6-f957-7e71-f198e983a169
* Version Independent ID: 63e05127-2d31-eb13-dbc8-30477c7f1476
* Content: [PFLT_INSTANCE_TEARDOWN_CALLBACK (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nc-fltkernel-pflt_instance_teardown_callback)
* Content Source: [wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_instance_teardown_callback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_instance_teardown_callback.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@briancatlin, thanks for submitting this. The dev team did some digging in the code and assured me that this error is returned due to something that happened in the system, and that there is nothing a minifilter can do. Regarding incorrect configuration, descriptive error codes are returned from registration-related routines.
