### ISSUE TITLE
File attributes missing

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#546]
Says "one of the following:", with the next parameter following :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d33d0e-9170-b491-3357-5ffb147626d6
* Version Independent ID: 9d637b9c-a040-c4c1-3af1-e0740285971c
* Content: [_FILE_DIRECTORY_INFORMATION (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_file_directory_information#requirements)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_file_directory_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_file_directory_information.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by EliotSeattle** [comment]
Thanks, @alfaunits 
I added the missing attributes, and the updated topic has been merged into the master branch. It should be live shortly. Appreciate the catch!!
