### ISSUE TITLE
Need WPP info for FltMgr

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs-ddi#549]
Please put the complete WPP trace information for FltMgr in the FltMgr.pdb file that is released to the Microsoft public symbol server. This would greatly help writers of minifilter drivers!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebc43d8a-58e9-d50a-d90e-fd52ddf8de3f
* Version Independent ID: 857d2fc4-c181-9c9d-b57a-7ea26c7ff8df
* Content: [FltRegisterFilter function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltregisterfilter)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltregisterfilter.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltregisterfilter.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@briancatlin, sorry, but the team does not have any plans to release private symbols for components such as FltMgr at this time (or in the foreseeable future).
