### ISSUE TITLE
Removal race

### ISSUE THREAD

**Issue by SylviaElse** [MicrosoftDocs/windows-driver-docs-ddi#55]
There is a potential race between the filter manager removing an entry because it has been cancelled, and the filter driver removing it because it has been completed. It is not clearly stated that the context remains valid after the first removal, such that it can be used to attempt (but fail) to remove the entry on the second occasion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f29f6a0d-5d37-3880-76b2-95f862759ff6
* Version Independent ID: 7939b2cf-6f41-828e-6224-75fbc8783ebf
* Content: [FltCbdqRemoveIo function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltcbdqremoveio)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcbdqremoveio.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcbdqremoveio.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @SylviaElse, thanks for letting us know about this. I've added this note to the "remarks" section in the topic - it should be visible shortly. Thanks again, and feel free to reach out again if you find anything else in the documentation!
