### ISSUE TITLE
Version member of this structure

### ISSUE THREAD

**Issue by TomaszNowakSanDiego** [MicrosoftDocs/windows-driver-docs-ddi#550]
There's no "#define SERVER_SILO_MONITOR_REGISTRATION_VERSION", it is called SILO_MONITOR_REGISTRATION_VERSION...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab17c2be-56c7-8148-6ad5-faccd4121fb1
* Version Independent ID: 547c4d83-2177-ab98-db9b-5decc526ddbd
* Content: [_SILO_MONITOR_REGISTRATION (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/ns-ntddk-_silo_monitor_registration#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/ns-ntddk-_silo_monitor_registration.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/ns-ntddk-_silo_monitor_registration.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @TomaszNowakSanDiego and apologies for the delay.  You are correct!  I just made the update.  It should appear on the page within an hour.
