### ISSUE TITLE
When function returns FALSE

### ISSUE THREAD

**Issue by szalkerous** [MicrosoftDocs/windows-driver-docs-ddi#551]
In the API library code hidsdi.h, there is a comment that states: 

Return Value:
   TRUE if successful.
   FALSE otherwise  -- Use GetLastError() to get extended error information

I don't understand why the usage of GetLastError was not included on this page, but it's here for anyone that needs it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21b1fe19-5d70-860d-ac69-a3787e4b53e7
* Version Independent ID: 3453d243-7167-3980-51a0-cf78d4f682ee
* Content: [HidD_GetPreparsedData function (hidsdi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/hidsdi/nf-hidsdi-hidd_getpreparseddata#feedback)
* Content Source: [wdk-ddi-src/content/hidsdi/nf-hidsdi-hidd_getpreparseddata.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/hidsdi/nf-hidsdi-hidd_getpreparseddata.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @szalkerous, thanks for pointing this out! I've added the note to link to `GetLastError()` to this page and all other functions in this header that had the same note in the source header file. Those changes should be live shortly, once the changes go through our content build system. Thanks for helping to improve the docs!
