### ISSUE TITLE
Also need the Indexable Concept to work with LINQ

### ISSUE THREAD

**Issue by billti** [MicrosoftDocs/windows-driver-docs-ddi#557]
Worth noting above (as I just found out) that while implement just the IterableConcept will allow you to return collections in "dx" commands, you also need the IndexableConcept to be able to run LINQ like queries over the results (e.g. ".Select(p =&gt; ...") - else you just get a very unhelpful "Interface not supported" error in the UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4f952be-abb7-35e1-8519-604376cbb7c0
* Version Independent ID: 40874646-a80d-c505-61b4-e04759beac1b
* Content: [IIterableConcept (dbgmodel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dbgmodel/nn-dbgmodel-iiterableconcept)
* Content Source: [wdk-ddi-src/content/dbgmodel/nn-dbgmodel-iiterableconcept.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dbgmodel/nn-dbgmodel-iiterableconcept.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@billti - I checked with the dev team and they indicated that you should be able to use the dx command and LINQ by just implementing IIterableConcept interface, so closing this as a docs issue.
