### ISSUE TITLE
"Best Practices: Using URBs" link is broken

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs-ddi#559]
Best Practices: Using URBs link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523d6870-fb41-ffb0-9f82-d622a33dff97
* Version Independent ID: c7c62028-6012-c8fd-46ca-3896c24bad76
* Content: [USBD_CreateHandle function (usbdlib.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/usbdlib/nf-usbdlib-usbd_createhandle#feedback)
* Content Source: [wdk-ddi-src/content/usbdlib/nf-usbdlib-usbd_createhandle.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbdlib/nf-usbdlib-usbd_createhandle.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Good catch @Shyamal-V. I've fixed that link, along with the link to Allocating and Building URBs, across the entire reference repo, and those changes should be live later today. Thanks for pointing this out!
