### ISSUE TITLE
Insertion/cancellation race

### ISSUE THREAD

**Issue by SylviaElse** [MicrosoftDocs/windows-driver-docs-ddi#56]
There is a potential race between a filter driver inserting an FLT_CALLBACK_DATA and the associated IRP being cancelled. It's possible that the filter driver handles this situation by immediately invoking the queue's cancellation routine if the IRP has already been cancelled. If this is the case, then it should be stated, so that the filter driver does not have to handle this race.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94abb29-c713-002f-c0f8-c6fe71c0b3cc
* Version Independent ID: c6f64fae-b1b6-363a-ee10-e0d3100f7f56
* Content: [FltCbdqInsertIo function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltcbdqinsertio)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcbdqinsertio.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcbdqinsertio.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Thanks @SylviaElse, this is very valuable information. I've added it to the "remarks" section of the page. It should be visible soon. Thanks for bringing this to our attention!
