### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#560]
The link to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddscsi/ns-ntddscsi-storage_protocol_data_descriptor is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65bf40cb-7302-24b1-a41f-a60c9769c98b
* Version Independent ID: f583158c-3388-8736-d291-f6eb50361707
* Content: [IOCTL_MINIPORT_SIGNATURE_SET_PROTOCOL - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddscsi/ni-ntddscsi-ioctl_miniport_signature_set_protocol)
* Content Source: [wdk-ddi-src/content/ntddscsi/ni-ntddscsi-ioctl_miniport_signature_set_protocol.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddscsi/ni-ntddscsi-ioctl_miniport_signature_set_protocol.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Fixed the link. Now points to https://docs.microsoft.com/windows-hardware/drivers/ddi/content/ntddstor/ns-ntddstor-_storage_protocol_data_descriptor

Thanks for pointing this out!

Eliot
