### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#561]
Link to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddstor/ni-ntddstor-storage_protocol_specific_data_ext is dead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938be15f-9427-a7d4-9efb-54d3ee4b701c
* Version Independent ID: 52f5173a-e04d-ddfd-b887-10a6ef7c4e52
* Content: [IOCTL_STORAGE_SET_PROPERTY (ntddstor.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddstor/ni-ntddstor-ioctl_storage_set_property)
* Content Source: [wdk-ddi-src/content/ntddstor/ni-ntddstor-ioctl_storage_set_property.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddstor/ni-ntddstor-ioctl_storage_set_property.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@csm10495 , thanks for reporting this - the broken link is now fixed!
