### ISSUE TITLE
Document IOCTL_STORAGE_GET_DEVICE_NUMBER_EX

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#562]
I believe this is in the SDK but missing from docs.microsoft.com now. Also link that new page to this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c418cb23-f9b7-7286-4ebd-babe412d8385
* Version Independent ID: 350edde9-fe26-91f7-a7db-4af00dfe24af
* Content: [IOCTL_STORAGE_GET_DEVICE_NUMBER (ntddstor.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddstor/ni-ntddstor-ioctl_storage_get_device_number)
* Content Source: [wdk-ddi-src/content/ntddstor/ni-ntddstor-ioctl_storage_get_device_number.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddstor/ni-ntddstor-ioctl_storage_get_device_number.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@csm10495 , thanks for flagging this as missing. I've added a page for IOCTL_STORAGE_GET_DEVICE_NUMBER_EX, along with its associated structure. I appreciate your PRs and desire to make our docs better for everyone - thank you!
