### ISSUE TITLE
Wrong function definition

### ISSUE THREAD

**Issue by TomaszNowakSanDiego** [MicrosoftDocs/windows-driver-docs-ddi#563]
One param (Context) is missing. Proper declaration is:
IoCsqInsertIrpEx(
    _Inout_ PIO_CSQ               Csq,
    _Inout_ PIRP              Irp,
    _Out_opt_ PIO_CSQ_IRP_CONTEXT Context,
    _In_opt_ PVOID                InsertContext
    );

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27d5354d-02a7-6244-9acb-d69d304cdcf7
* Version Independent ID: 79122225-9ed9-93d7-6e6e-84827c67ddbf
* Content: [IO_CSQ_INSERT_IRP_EX (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nc-wdm-io_csq_insert_irp_ex)
* Content Source: [wdk-ddi-src/content/wdm/nc-wdm-io_csq_insert_irp_ex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nc-wdm-io_csq_insert_irp_ex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @TomaszNowakSanDiego thanks for the report.  I don't repro this however.  In the 19H1 version of wdm.h, line 32921, I see:

```
typedef NTSTATUS
IO_CSQ_INSERT_IRP_EX (
    _In_ struct _IO_CSQ    *Csq,
    _In_ PIRP              Irp,
    _In_ PVOID             InsertContext
    );

typedef IO_CSQ_INSERT_IRP_EX *PIO_CSQ_INSERT_IRP_EX;
```

Please reopen if I am missing something!
