### ISSUE TITLE
Does not specify required libraries

### ISSUE THREAD

**Issue by FriskyDev** [MicrosoftDocs/windows-driver-docs-ddi#564]
For example, these are required by the calls that load the ExtennsionApis global, which is likely the first thing that you would need to do.

#pragma comment(lib, "dbghelp")
#pragma comment(lib, "dbgeng")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef6e70c-ec20-7e45-ab67-53ebdfc81008
* Version Independent ID: c543acab-32f5-1f98-7e54-92781f5ac994
* Content: [DebugCreate function (dbgeng.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dbgeng/nf-dbgeng-debugcreate)
* Content Source: [wdk-ddi-src/content/dbgeng/nf-dbgeng-debugcreate.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dbgeng/nf-dbgeng-debugcreate.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@FriskyDev - Thanks for this input on the needed libraries for the debugger engine API. I have not been able to work with the dev team to expand this topic to include this information. If you have a specific docs update, feel free to submit a PR with that information. It sounds like you found the correct libraries for your code, but the OSR community groups can be a good resource for code development. https://community.osr.com/
