### ISSUE TITLE
Formatting broken under "Remarks"

### ISSUE THREAD

**Issue by Contentmaudlin** [MicrosoftDocs/windows-driver-docs-ddi#565]
Quoting:

Any I/O completion processing that needs to be performed at IRQL &lt; dispatch_level="" cannot="" be="" performed="" directly="" in="" the="" postoperation="" callback="" routine.="" instead,="" it="" must="" be="" posted="" to="" a="" work="" queue="" by="" calling="" a="" routine="" such="" as=""&gt;FltDoCompletionProcessingWhenSafe or FltQueueDeferredIoWorkItem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c54609f-5bac-41f9-cc9b-65f40e4900dc
* Version Independent ID: fbf86498-496a-fed8-76f0-9a62457db534
* Content: [PFLT_POST_OPERATION_CALLBACK (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nc-fltkernel-pflt_post_operation_callback)
* Content Source: [wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_post_operation_callback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nc-fltkernel-pflt_post_operation_callback.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@contentmaudlin, thanks for reporting this issue - it is now fixed!
