### ISSUE TITLE
Incorrect return value specified

### ISSUE THREAD

**Issue by billwandel** [MicrosoftDocs/windows-driver-docs-ddi#57]
The RtlUlonglongByteSwap macro takes a longlong as the parameter and returns the resulting longlong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a463f4e1-7c79-c9e5-a40b-d49b5833ca04
* Version Independent ID: 0f7f5900-184e-4ff7-8e48-cd0d2af445c0
* Content: [RtlUlonglongByteSwap macro](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlulonglongbyteswap)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtlulonglongbyteswap.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlulonglongbyteswap.md)
* Service: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
@billwandel

Thanks for noticing the dropped content. The fix should be live soon.

PageWriter
