### ISSUE TITLE
Can this be called at DISPATCH_LEVEL

### ISSUE THREAD

**Issue by russli-tianyu** [MicrosoftDocs/windows-driver-docs-ddi#576]
Can ExAcquireRundownProtection and ExReleaseRundownProtection, ExAcquireRundownProtectionEx and ExReleaseRundownProtectionEx be called at DISPATCH_LEVEL. In addition, is there a cache aware version of the EX_RUNDOWN_REF?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52bb0d1c-284b-38c7-cafc-d89263f1278d
* Version Independent ID: 4fc89df0-fada-3e67-ca3e-2f0b22a37255
* Content: [ExAcquireRundownProtectionEx function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-exacquirerundownprotectionex#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exacquirerundownprotectionex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exacquirerundownprotectionex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @russli-tianyu, yes, as long as the run-down block itself is nonpaged, these functions can be called at DISPATCH_LEVEL.   (ExAcquireRundownProtection, ExAcquireRundownProtectionEx, ExReleaseRundownProtection, ExReleaseRundownProtectionEx)

I just added a note to the Remarks section of those pages, and updated the IRQL in the Requirements block.  That change should appear on the live site within a half hour or so.
