### ISSUE TITLE
Parameter names/order are incorrect

### ISSUE THREAD

**Issue by mebersol** [MicrosoftDocs/windows-driver-docs-ddi#586]
RtlRunOnceExecuteOnce and RTL_RUN_ONCE_INIT_FN callback function have wrong parameter names/order for Parameter/Context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d44ce02b-8b06-2a0f-6c43-ff56056cc410
* Version Independent ID: 72e87f62-2425-a15e-a5db-71494323ec72
* Content: [RtlRunOnceExecuteOnce function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-rtlrunonceexecuteonce#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-rtlrunonceexecuteonce.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-rtlrunonceexecuteonce.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Verified.  I've opened an internal engineering bug to track this.  Thanks for the report.
