### ISSUE TITLE
Wrong DataRanges member description

### ISSUE THREAD

**Issue by emuzychenko** [MicrosoftDocs/windows-driver-docs-ddi#591]
While the Interfaces and Mediums point to the appropriate structures themselves, DataRanges points to an array of pointers to KSDATARANGE structures, whose are not necessary are to be organized into a single array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19cec481-a90b-0b0d-86e1-6f80d75d0630
* Version Independent ID: 86813fbf-ba99-99a8-21d8-d29468c9bc9a
* Content: [KSPIN_DESCRIPTOR (ks.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ks/ns-ks-kspin_descriptor#feedback)
* Content Source: [wdk-ddi-src/content/ks/ns-ks-kspin_descriptor.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ks/ns-ks-kspin_descriptor.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@emuzychenko, thanks for pointing out the incorrect DataRanges member description. 

I'm opening an internal work item to correct and update the KSPIN_DESCRIPTOR structure topic.
