### ISSUE TITLE
"Comparand" is misspelled

### ISSUE THREAD

**Issue by bviglietta** [MicrosoftDocs/windows-driver-docs-ddi#596]
"Comparand" is misspelled everywhere that it appears on this page.

A comparand is something that you compare.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 552b2c09-82f1-87a0-7b93-3ea91ee3e37a
* Version Independent ID: d10cf6fc-7282-09b6-c3f7-85ba6ddd2357
* Content: [InterlockedCompareExchange function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-interlockedcompareexchange)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-interlockedcompareexchange.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-interlockedcompareexchange.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @bviglietta you are absolutely right!  Sadly, in `wdm.h`, the score is 15 to 1 in occurrences of `comperand` vs. `comparand`, respectively.  So I wish I could change it, but we need the doc to match the header.  Appreciate the heads-up, though!
