### ISSUE TITLE
FltAcquirePushLockExclusive: PushLock parameter description

### ISSUE THREAD

**Issue by kITerE** [MicrosoftDocs/windows-driver-docs-ddi#60]
* missing PushLock parameter description: TBD
 * missing argument type (PEX_PUSH_LOCK). Same problem: FltAcquirePushLockShared (https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltacquirepushlockshared) and FltReleasePushLock (https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltreleasepushlock)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e888a8-b5b6-6f46-98f5-bd356a93e61c
* Version Independent ID: edce67e3-d1c1-f57e-fa1f-50fee4f0b601
* Content: [FltAcquirePushLockExclusive macro](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltacquirepushlockexclusive)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltacquirepushlockexclusive.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltacquirepushlockexclusive.md)
* Service: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @kITerE, thanks for sending this to us. I've updated the topics you mention with the argument type in the description. Should be live shortly!
