### ISSUE TITLE
Typo in Header description

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs-ddi#600]
Text says to set the Header.Revision field to "NDIS_TCP_CONNECTION_OFFLOAD_VERSION_1", should be "NDIS_TCP_CONNECTION_OFFLOAD_REVISION_1".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19fff21f-1da8-d81b-b562-36f6b305f21a
* Version Independent ID: 65619693-65c1-0e7b-c9a7-b3388e70b802
* Content: [_NDIS_TCP_CONNECTION_OFFLOAD (ntddndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddndis/ns-ntddndis-_ndis_tcp_connection_offload)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_tcp_connection_offload.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_tcp_connection_offload.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @druske, thanks for pointing this out. I've corrected the doc, and it should be live shortly. Also, if you'd like to in the future, you can edit the doc directly and submit a PR to make the change. Either way works. Thanks!
