### ISSUE TITLE
Code indentation is broken

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs-ddi#601]
Code indentation is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 017c49d4-3011-7209-dba1-9349387328d0
* Version Independent ID: 67bd05ae-b262-b884-1e77-67052dfd29bd
* Content: [WdfUsbTargetPipeFormatRequestForUrb function (wdfusb.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfusb/nf-wdfusb-wdfusbtargetpipeformatrequestforurb)
* Content Source: [wdk-ddi-src/content/wdfusb/nf-wdfusb-wdfusbtargetpipeformatrequestforurb.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfusb/nf-wdfusb-wdfusbtargetpipeformatrequestforurb.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @Shyamal-V, I updated the doc source.  Give it an hour to reach the live site
