### ISSUE TITLE
prototype mistype

### ISSUE THREAD

**Issue by zodiacon** [MicrosoftDocs/windows-driver-docs-ddi#603]
The function/macro return PVOID rather than void.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91469850-43a0-b162-74e8-795e69d97942
* Version Independent ID: 18eafedb-812a-581d-76c7-e771811dc953
* Content: [MmGetSystemAddressForMdl macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmgetsystemaddressformdl)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmgetsystemaddressformdl.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmgetsystemaddressformdl.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the report @zodiacon and apologies for the delay.  You are absolutely right!

I just updated https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmgetsystemaddressformdl with the correct syntax.

Appreciate the feedback :)
