### ISSUE TITLE
NDIS_SIZEOF_PCI_DEVICE_CUSTOM_PROPERTIES_REVISION_1

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs-ddi#604]
If you specify NDIS_OBJECT_TYPE_PCI_DEVICE_CUSTOM_PROPERTIES_REVISION_1 as directed in the description of the Header.Revision field, you may want to use the defined NDIS_SIZEOF_PCI_DEVICE_CUSTOM_PROPERTIES_REVISION_1 in the Header.Size. Depending on Windows version and supported NDIS version defines, the actual size of the NDIS_PCI_DEVICE_CUSTOM_PROPERTIES may be larger than expected for a revision 1 structure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb005a4-2051-6f0b-089e-de4657130213
* Version Independent ID: b098c7c2-03e6-8f2c-003a-46298bd2d164
* Content: [_NDIS_PCI_DEVICE_CUSTOM_PROPERTIES (ntddndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddndis/ns-ntddndis-_ndis_pci_device_custom_properties)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_pci_device_custom_properties.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_pci_device_custom_properties.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @druske, thanks for the insightful comment. I do understand what you're saying and most NDIS structures do use that pattern for the Header.Size, but this is not the case with this structure. For NDIS_PCI_DEVICE_CUSTOM_PROPERTIES, NDIS is the one who provides this information to the miniport driver, and the Header field description reflects that by saying "NDIS sets the … **Size** member to sizeof(NDIS_PCI_DEVICE_CUSTOM_PROPERTIES)". I have confirmed that this is correct by examining internal source code, so here we are merely stating what the system does, not any sort of recommendation for that field. Hope this helps.
