### ISSUE TITLE
Information is out of date

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#606]
More info is needed about surprise removal other than during hibernation.  The article says "Note: This function is called only if the disconnected external display device was in hibernation mode. This is indicated by RemovalType = DxgkRemovalHibernation, the only available value."  This is not true anymore, RemovalType can also be DxgkRemovalPnPNotify.  There is no information here about when the OS calls with this value, what the driver should do, what should be returned, and how the OS responds to success and failure when RemovalType = DxgkRemovalPnPNotify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec56f06-23dc-0593-4139-25f3b875ed9f
* Version Independent ID: db07b5c5-7820-cfe4-ea07-14e644cb8c79
* Content: [DXGKDDI_NOTIFY_SURPRISE_REMOVAL (dispmprt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dispmprt/nc-dispmprt-dxgkddi_notify_surprise_removal)
* Content Source: [wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_notify_surprise_removal.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_notify_surprise_removal.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@englishb , again my apologizes for the slow response! Page is updated.
