### ISSUE TITLE
union definition is duplicated 3 times

### ISSUE THREAD

**Issue by andy-bis** [MicrosoftDocs/windows-driver-docs-ddi#609]
It is duplicated in both C++ definition and Members documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c4f56f7-62c1-b240-e671-da97ea874de1
* Version Independent ID: c8509b8d-30e4-b427-ae6f-69df91b9731c
* Content: [_D3DKMT_PRESENT_DISPLAY_ONLY_FLAGS (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/ns-d3dkmddi-_d3dkmt_present_display_only_flags#feedback)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_d3dkmt_present_display_only_flags.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_d3dkmt_present_display_only_flags.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@andy-bis, thanks for reporting this! There is a bug in our doc build tools that is causing replication in some unions. We are tracking this issue through an internal bug, so I am going to close this GitHub issue. Hopefully it will be fixed soon.
