### ISSUE TITLE
WdfFdoInitSetFilter page missing information about it's influence on power management for the queues

### ISSUE THREAD

**Issue by reuvenab** [MicrosoftDocs/windows-driver-docs-ddi#610]
WdfFdoInitSetFilter page doesn't state explicitly the fact that after calling this function 
power handling for the queues will **NOT** be handled by framework.

This information appears  only at [WDF_IO_QUEUE_CONFIG](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfio/ns-wdfio-_wdf_io_queue_config) 
page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395441d4-95b0-de6c-1760-3f401c13e0ae
* Version Independent ID: fe14fab6-3c07-e802-cf8f-f8024ffafe08
* Content: [WdfFdoInitSetFilter function (wdffdo.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdffdo/nf-wdffdo-wdffdoinitsetfilter)
* Content Source: [wdk-ddi-src/content/wdffdo/nf-wdffdo-wdffdoinitsetfilter.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdffdo/nf-wdffdo-wdffdoinitsetfilter.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @reuvenab, I circled back with the feature team and the decision was to leave **WdfFdoInitSetFilter** as-is because we'd prefer to doc that behavior centrally in the expected place and not doc cascaded behavior.  Thanks for the feedback, and apologies for the delay getting back to you.
