### ISSUE TITLE
KeFlushQueuedDpcs clarification

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs-ddi#615]
The behavior of _KeFlushQueuedDpcs_ isn't completely clear from the documentation:

> Drivers can use this routine to wait until all currently-queued DPCs are run

Does it mean that all the DPCs have been removed from the queue(s) and started executing or that they have not only started execution but also the execution handlers have finished running?
Also, what happens if a new DPC is scheduled while KeFlushQueuedDpcs runs? Will it also be handled by the running KeFlushQueuedDpcs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c43e7409-000d-c6b3-e326-3a589de18cd5
* Version Independent ID: b3ef539b-e91b-78b2-3136-018577419e9e
* Content: [KeFlushQueuedDpcs function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-keflushqueueddpcs)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-keflushqueueddpcs.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-keflushqueueddpcs.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @I-gor-C for the feedback, and apologies for the delay.

Please see https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-keflushqueueddpcs for updated top level description, and new paragraph in Remarks.  Feel free to reopen if this does not address your questions :)
