### ISSUE TITLE
Since only UMDF drivers can use this API this page should clarify what KMDF drivers should do

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs-ddi#617]
To retrieve or modify a device interface property, a KMDF driver must call IoGetDeviceInterfacePropertyData or IoSetDeviceInterfacePropertyData directly.

https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/accessing-the-unified-device-property-model

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d655649-44f6-23cc-8ed1-009534ad039e
* Version Independent ID: 63bee429-9fb2-b416-d2cd-3d01ac6ef0d5
* Content: [WdfDeviceAssignInterfaceProperty function (wdfdevice.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfdevice/nf-wdfdevice-wdfdeviceassigninterfaceproperty)
* Content Source: [wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdeviceassigninterfaceproperty.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdeviceassigninterfaceproperty.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @Shyamal-V see the note I added to the top of https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfdevice/nf-wdfdevice-wdfdeviceassigninterfaceproperty
