### ISSUE TITLE
NtQueryVirtualMemory Available starting with Windows 10.

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/windows-driver-docs-ddi#618]
in C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\km\ntifs.h

you can see:

#if (NTDDI_VERSION >= NTDDI_WIN2K)
//@[comment("MVI_tracked")]
_Must_inspect_result_
__kernel_entry NTSYSCALLAPI
NTSTATUS
NTAPI
NtQueryVirtualMemory (
    _In_ HANDLE ProcessHandle,
    _In_opt_ PVOID BaseAddress,
    _In_ MEMORY_INFORMATION_CLASS MemoryInformationClass,
    _Out_writes_bytes_(MemoryInformationLength) PVOID MemoryInformation,
    _In_ SIZE_T MemoryInformationLength,
    _Out_opt_ PSIZE_T ReturnLength
    );
#endif

只不过，这个函数在以前的系统上没有导出而已，微软个大骗子，自相矛盾。

https://correy.webs.com

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a307db7-3d17-d025-8c04-5dd80bddf8cc
* Version Independent ID: c7c80dd0-04a2-5c0b-a486-14d123f8f74f
* Content: [NtQueryVirtualMemory function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntqueryvirtualmemory#feedback)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ntqueryvirtualmemory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ntqueryvirtualmemory.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@kouzhudong, thanks for catching this - it's now fixed!
