### ISSUE TITLE
Is MmMapLockedPagesSpecifyCache() stdcall?

### ISSUE THREAD

**Issue by gvanem** [MicrosoftDocs/windows-driver-docs-ddi#619]
This function seems to be `stdcall`. Since using `nm` on my `ntoskrn.lib` shows a
`MmMapLockedPagesSpecifyCache@24`.

Nothing in the documentation indicates this important detail AFAICS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29754578-a398-609e-917e-62ab556accc7
* Version Independent ID: 5ec9b557-c146-03c6-67a7-c714e0e77204
* Content: [MmMapLockedPagesSpecifyCache function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmmaplockedpagesspecifycache)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmmaplockedpagesspecifycache.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmmaplockedpagesspecifycache.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Closing out due to inactivity - please reactivate if you have thoughts on the above
