### ISSUE TITLE
Windows Server 2012 is incorrect

### ISSUE THREAD

**Issue by tawmoto** [MicrosoftDocs/windows-driver-docs-ddi#621]
![image](https://user-images.githubusercontent.com/35702340/63499411-7e236000-c4d0-11e9-996b-40c018012abe.png)

Version number 6.3, but dwMajorVersion is 10? :-)

Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e8cb445-1d31-bc73-dceb-82bccece4bb0
* Version Independent ID: 016e23b3-53da-d6d9-c313-7b6976747b07
* Content: [_OSVERSIONINFOEXW (wdm.h) - Windows drivers](https://docs.microsoft.com/en-gb/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_osversioninfoexw#feedback)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_osversioninfoexw.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_osversioninfoexw.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @tawmoto, thanks for the feedback!  I actually just looked up the email that I sent to the product team a few months ago asking them the same question, and found the reply that confirmed that the doc page is correct.  So it seems unusual, but apparently it is true :)
