### ISSUE TITLE
IRQL requirements

### ISSUE THREAD

**Issue by wurdack** [MicrosoftDocs/windows-driver-docs-ddi#623]
Rundown protection is most useful in hot paths where a lock is too heavy. So I was surprised that the IRQL requirements are &lt;=APC. Surprised enough that I took a look at the implementation of the acquire and release routines. Acquire is, for the most part, interlocked compare/exchange. Release is, for the most part, interlocked compare/exchange plus a KeSetEvent. The latter signal happens with Wait set to FALSE, which is valid at DISPATCH.

Lo and behold, the WDK headers indicate both are callable at DISPATCH. So I think this documentation (and the docs for ExAcquireRundownProtection) aren't correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65098501-6531-549b-5719-87db3688947b
* Version Independent ID: 1ccd6dc3-37d7-1f18-57b3-d480f6f842f9
* Content: [ExReleaseRundownProtection function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-exreleaserundownprotection#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exreleaserundownprotection.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exreleaserundownprotection.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by KalleOlaviNiemitalo** [comment]
This was already fixed in <https://github.com/MicrosoftDocs/windows-driver-docs-ddi/commit/31e600d472194b58922571dbdfe616adddb99e25> for <https://github.com/MicrosoftDocs/windows-driver-docs-ddi/issues/576>.
