### ISSUE TITLE
IRQL <= APC_LEVEL

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs-ddi#625]
This function is far more useful if it can be called at DISPATCH_LEVEL.  The implementation seems to be just fine at DISPATCH_LEVEL.  Please change this page to read IRQL &lt;= DISPATCH_LEVEL unless there is a compelling reason to leave it as it is.

Note also that the SAL annotations for this function don't include an IRQL.  It should.  The SAL annotation for ExReleaseRundownProtection says _IRQL_requires_max_(DISPATCH_LEVEL), which makes me think that when Neill wrote this code, he intended it to work at DISPATCH_LEVEL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa25e4cb-016e-9520-3e9e-98e52391b194
* Version Independent ID: e5f6ac0c-3da2-5134-666b-275e6ff5ff5f
* Content: [ExAcquireRundownProtection function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-exacquirerundownprotection)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exacquirerundownprotection.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exacquirerundownprotection.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by KalleOlaviNiemitalo** [comment]
This was already fixed in <https://github.com/MicrosoftDocs/windows-driver-docs-ddi/commit/31e600d472194b58922571dbdfe616adddb99e25> for <https://github.com/MicrosoftDocs/windows-driver-docs-ddi/issues/576>.

**Comment by tedhudek** [comment]
Thanks @KalleOlaviNiemitalo!
