### ISSUE TITLE
Incorrect TrackData description

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/windows-driver-docs-ddi#626]
It doesn't look like a pointer to me. That's a real array being stored right in the struct. Either the struct def is wrong or the description is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf22500-2f47-cd4c-3fee-8f1d76cd6964
* Version Independent ID: ce49f9bd-c5ae-b2c4-a4b5-ff1692c30838
* Content: [_CDROM_TOC (ntddcdrm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddcdrm/ns-ntddcdrm-_cdrom_toc)
* Content Source: [wdk-ddi-src/content/ntddcdrm/ns-ntddcdrm-_cdrom_toc.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddcdrm/ns-ntddcdrm-_cdrom_toc.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@henke37 , thanks for reporting this -- I have updated the description!
