### ISSUE TITLE
Slight ambiguity in wording.

### ISSUE THREAD

**Issue by gauraVsehgaL** [MicrosoftDocs/windows-driver-docs-ddi#628]
The first line of the second last paragraph looks ambiguous as in it reflects as, if the macro is not defined, we have to **always** use Avl form of the routines. It should be something like below:
**If you want to use AVL tables and** if RTL_USE_AVL_TABLES is not defined, you must use the AVL form of the generic table routines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac4663e-c210-39ef-fb1e-f320987808c7
* Version Independent ID: 1edf0597-8b85-8776-c35c-a430a1e90553
* Content: [RtlInitializeGenericTable function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-rtlinitializegenerictable#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-rtlinitializegenerictable.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-rtlinitializegenerictable.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Better late than never!  Fix should be live within the hour :)
