### ISSUE TITLE
Important documentation is missing

### ISSUE THREAD

**Issue by MajorTom2oo1** [MicrosoftDocs/windows-driver-docs-ddi#633]
Missing in remarks question, a note that successfully caller to this function needs to call ZwClose for the retuned handle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f528e59c-53f2-457c-b63e-ee7a599b01cb
* Version Independent ID: d95ec778-2361-f14d-d4dd-5fc267214242
* Content: [NtOpenProcess function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-ntopenprocess#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-ntopenprocess.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-ntopenprocess.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback and apologies for the delay.  I just pushed the following addition that will be live within the hour:

As is the case with kernel handles opened by other system service calls such as **ZwCreateKey** and **ZwCreateFile**,
the caller is responsible for calling [**ZwClose**](https://docs.microsoft.com/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntclose) to close the handle when it is no longer required.
