### ISSUE TITLE
Had to chase references to determine CSV refers to "Cluster Shared Volume"

### ISSUE THREAD

**Issue by kyanha** [MicrosoftDocs/windows-driver-docs-ddi#634]
The enumeration named CSV_CONTROL_OP, and everything in 5 degrees of separation it links to, has no mention of CSV being something specific to Cluster Shared Volume File System.  I was trying to figure out what it was, so I could figure out if I had to interact with it.

(Is it appropriate to be documented as part of the IFS kit?  Is it something that can legitimately be reimplemented by a third party?  Is the standard for documentation in _ifsk something other than "can be legitimately reimplemented"?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a5168c-5f2d-95bc-0546-b5920da1746a
* Version Independent ID: 010ff4bf-422c-e3ef-81c5-6775830e944c
* Content: [Installable file system - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/_ifsk/)
* Content Source: [wdk-ddi-src/content/_ifsk/index.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/_ifsk/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by lorihollasch** [comment]
@kyanha, thanks for reporting this. I've spelled out "cluster shared volume" on this page and on the actual refpage, and have asked the SDK team to update some of their CSV-specific pages to do the same.
I pinged the dev team regarding CSV and minifilters. The answer that I got is "it depends". If your filter is supposed to be used with Failover Cluster based solutions that use SAN and S2D then the answer is yes … depending on what exactly your filter does. Some guidance can be found here: http://www.snia.org/sites/default/files/files2/files2/SDC2013/presentations/Revisions/VladimirPetter_Cluster_Shared_Volume_revision.pdf. You can detect if you are offered to attach to CSVFS from file system type passed to instance attach ([FLT_FILESYSTEM_TYPE](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltuserstructures/ne-fltuserstructures-_flt_filesystem_type)). For CSVFS, the value will be equal FLT_FSTYPE_CSVFS.
The dev team also provided a pointer to this article as a great place to learn more about CSV: https://techcommunity.microsoft.com/t5/Failover-Clustering/Cluster-Shared-Volume-CSV-Inside-Out/ba-p/371872. I've filed an internal work item to determine what additional information needs to be added to our docs.
Not sure what you mean by "IFS Kit", as that is something that no longer exists?
