### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ChuckM2** [MicrosoftDocs/windows-driver-docs-ddi#635]
The links in the bottom Remarks section appear broken. 
Specifically these links:
Populated DXGK_DRIVERCAPS structure
Populated DXGK_QUERYSEGMENTOUT structure
Populated DXGK_QUERYSEGMENTOUT3 structure
etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 596ed6e6-093b-5192-4d2d-e8f1f6790118
* Version Independent ID: 28d071c9-0105-2383-61d0-805ce9bfbff4
* Content: [_DXGK_QUERYADAPTERINFOTYPE (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/ne-d3dkmddi-_dxgk_queryadapterinfotype#feedback)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ne-d3dkmddi-_dxgk_queryadapterinfotype.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ne-d3dkmddi-_dxgk_queryadapterinfotype.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@chuckm2, thanks for reporting these broken links! They are now fixed.
