### ISSUE TITLE
Wrong value of SUPPORTED_FS_FEATURES_QUERY_OPEN

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-driver-docs-ddi#640]
The description of `Type.MiniFilter.SupportedFeatures` in the "INSTANCE_AGGREGATE_STANDARD_INFORMATION structure" topic claims that the value of SUPPORTED_FS_FEATURES_QUERY_OPEN is 0x00000002. According to the "FsRtlGetSupportedFeatures function" topic, the correct value is 0x00000004.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955fc6ff-c8b6-6d44-a2c1-436ce3eb0466
* Version Independent ID: 27959143-52a5-ad1f-f0d2-82f27eabddf7
* Content: [_INSTANCE_AGGREGATE_STANDARD_INFORMATION (fltuserstructures.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltuserstructures/ns-fltuserstructures-_instance_aggregate_standard_information#feedback)
* Content Source: [wdk-ddi-src/content/fltuserstructures/ns-fltuserstructures-_instance_aggregate_standard_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltuserstructures/ns-fltuserstructures-_instance_aggregate_standard_information.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@KalleOlaviNiemitalo , thanks for flagging this error - it is now fixed!
