### ISSUE TITLE
SAL annotation left in the syntax section 

### ISSUE THREAD

**Issue by tandasat** [MicrosoftDocs/windows-driver-docs-ddi#642]
It has SAL annotation that are usually removed in the syntax section. 
```
NTSTATUS KeWaitForSingleObject(
  PVOID                                                                         Object,
  KWAIT_REASON                                                                  WaitReason,
  __drv_strictType(KPROCESSOR_MODE / enum _MODE,__drv_typeConst)KPROCESSOR_MODE WaitMode,
  BOOLEAN                                                                       Alertable,
  PLARGE_INTEGER                                                                Timeout
);
``` 
The page for the KeWaitForMultipleObjects has the same issue, so there should be multiple instances of this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2679ffa-4774-8de8-3ee8-d75c18aa48f4
* Version Independent ID: af7a279a-93aa-5e5b-fbb5-1e0c2ee14a07
* Content: [KeWaitForSingleObject function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-kewaitforsingleobject)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-kewaitforsingleobject.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-kewaitforsingleobject.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @tandasat, I fixed this on those two pages.  Thanks for the heads-up, and apologies for the delay.
