### ISSUE TITLE
Formatting of the code snippet is broken

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs-ddi#645]
Formatting of the code snippet is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 303db252-ab3f-78b5-889b-854654701bd6
* Version Independent ID: 3604a054-1e30-8728-6c44-ec384730a57f
* Content: [WdfIoTargetOpen function (wdfiotarget.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfiotarget/nf-wdfiotarget-wdfiotargetopen)
* Content Source: [wdk-ddi-src/content/wdfiotarget/nf-wdfiotarget-wdfiotargetopen.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfiotarget/nf-wdfiotarget-wdfiotargetopen.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
See #646
