### ISSUE TITLE
Code formatting broken. Please review other WDF code snippets as well. This problem is pretty widespread

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs-ddi#646]
Please review other WDF code snippets as well. This problem is pretty widespread

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05480c0c-78c1-8904-c7d9-e3840867b6ba
* Version Independent ID: f9adf17b-4b8e-6dd0-d446-68b833e97be5
* Content: [WdfIoTargetCloseForQueryRemove function (wdfiotarget.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfiotarget/nf-wdfiotarget-wdfiotargetcloseforqueryremove)
* Content Source: [wdk-ddi-src/content/wdfiotarget/nf-wdfiotarget-wdfiotargetcloseforqueryremove.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfiotarget/nf-wdfiotarget-wdfiotargetcloseforqueryremove.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Fix should be live in half an hour.  Thanks for the examples.
