### ISSUE TITLE
Do *NOT* mix verifier and instances

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#649]
Lori (or whoever).
I just had a crash when mixing a non verified FLT_INSTANCE with a verified driver (helper function called via a DLL entry point) which called this function.  I can pull together PR if you want (or you might want to get the bug fixed instead).  Dump + Stack probably available (if needed) but its a trivial reproducer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a6a327-8031-040d-cc97-bc282b69bb07
* Version Independent ID: b00ef526-ef8a-2dad-1b4f-e40195ae1c91
* Content: [FltAllocateCallbackData function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/nf-fltkernel-fltallocatecallbackdata?redirectedfrom=MSDN#feedback)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltallocatecallbackdata.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltallocatecallbackdata.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , closing this per our email discussion. We can reopen if necessary once you and Craig work through dump files!
