### ISSUE TITLE
INTERFACE hyperlink is broken

### ISSUE THREAD

**Issue by PFroese** [MicrosoftDocs/windows-driver-docs-ddi#650]
Links to an unrelated xml reference page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f43c82b-fe09-fd84-ab9c-85c5c68f699a
* Version Independent ID: 19ebc355-cd07-e705-c3c7-1adf10fc3b88
* Content: [WdfFdoQueryForInterface function (wdffdo.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdffdo/nf-wdffdo-wdffdoqueryforinterface#feedback)
* Content Source: [wdk-ddi-src/content/wdffdo/nf-wdffdo-wdffdoqueryforinterface.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdffdo/nf-wdffdo-wdffdoqueryforinterface.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @PFroese for the report.  I found 62 occurrences of this bad link!  Just pushed the update to replace them with https://docs.microsoft.com/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_interface.  That change should appear on the live site within an hour.  Thanks again for your eagle eye!
