### ISSUE TITLE
Error code E_NOT_SET is hard to find information about

### ISSUE THREAD

**Issue by jazzdelightsme** [MicrosoftDocs/windows-driver-docs-ddi#651]
It doesn't seem to be a standard error code. Internal sources give the hint that some people use it to mean `HRESULT_FROM_WIN32(ERROR_NOT_FOUND)`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85184c7a-3eb7-a63f-1cba-632cd350a9f9
* Version Independent ID: 69751824-9e5a-5115-eac7-5b4adf912fea
* Content: [IModelObject::GetKeyValue (dbgmodel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dbgmodel/nf-dbgmodel-imodelobject-getkeyvalue)
* Content Source: [wdk-ddi-src/content/dbgmodel/nf-dbgmodel-imodelobject-getkeyvalue.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dbgmodel/nf-dbgmodel-imodelobject-getkeyvalue.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@jazzdelightsme - Apologies for the delay here. I have not been able to gather information on what  E_NOT_SET means in the context of GetKeyValue usage. I may be wrong, but there appears to be some variation in what it means for objects being defined in different contexts. Feel free to follow up with me in email, if you have any additional information. You are also welcome to create a docs PR, to update the topic directly.  For more information on that see https://docs.microsoft.com/contribute/ Thanks for your interest in improving the dbgmodel return error code information.
