### ISSUE TITLE
Strange error in displayed text

### ISSUE THREAD

**Issue by SIISII** [MicrosoftDocs/windows-driver-docs-ddi#653]
The last paragraph of "Remarks" section is displayed with a strange error in my browser (Firefox) although its source code is good as far as I can see. Below I inserted the paragraph's text as I see it:

Callers of WdmlibRtlInitUnicodeStringEx can be running at IRQL &lt;= dispatch_level="" if="" the=""&gt;DestinationString buffer is nonpageable. Usually, callers run at IRQL = PASSIVE_LEVEL because most other RtlXxxString routines cannot be called at IRQL &gt; PASSIVE_LEVEL.

A source of ="" and =""&gt; is unknown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ec7eaf-c01d-6da6-9307-a3e99fcea2cf
* Version Independent ID: f8af46ad-c063-9402-9007-06c8ff3ece9e
* Content: [WdmlibRtlInitUnicodeStringEx function (wdmsec.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdmsec/nf-wdmsec-wdmlibrtlinitunicodestringex#feedback)
* Content Source: [wdk-ddi-src/content/wdmsec/nf-wdmsec-wdmlibrtlinitunicodestringex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdmsec/nf-wdmsec-wdmlibrtlinitunicodestringex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by aviviano** [comment]
Thanks @SIISII for letting us know. The fix is now up.
