### ISSUE TITLE
Syntax problem in documentation

### ISSUE THREAD

**Issue by balintszabo96** [MicrosoftDocs/windows-driver-docs-ddi#654]
Hello!
This macro actually returns ULONG, not void.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6943e4b9-acab-dbcf-129a-83afe54429c2
* Version Independent ID: 54dcce5f-30aa-efe7-32f3-7c29168b80dd
* Content: [RtlAnsiStringToUnicodeSize macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlansistringtounicodesize#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-rtlansistringtounicodesize.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-rtlansistringtounicodesize.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by aviviano** [comment]
Thanks @balintszabo96.  The fix is up.
