### ISSUE TITLE
too much bold font

### ISSUE THREAD

**Issue by W3LLD0NE** [MicrosoftDocs/windows-driver-docs-ddi#655]
error in &lt;b&gt; tagging makes the whole page BOLD

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: b2aafbf5-4a9e-adc8-fef0-504b5b94b772
* Version Independent ID: d449d42c-4b58-3ff6-30af-7a7a4a506130
* Content: [ZwUnloadDriver function (wdm.h) - Windows drivers](https://docs.microsoft.com/ru-ru/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwunloaddriver#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwunloaddriver.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwunloaddriver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks Alex, I just pushed a fix for this.  Should appear on the live site within an hour
