### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#658]
The hyperlink for DXGKARG_CONTROLMODEBEHAVIOR points to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/ns-d3dkmddi-_dxgarg_controlmodebehavior, which displays a 404 error.  The URL is missing the 'k' in dxgkarg; the correct link is https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/ns-d3dkmddi-_dxgkarg_controlmodebehavior

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c9727da-1ed8-ab35-8117-2f74d4799777
* Version Independent ID: a45eccf0-aeb2-c687-e783-cf19b5bd1210
* Content: [DXGKDDI_CONTROLMODEBEHAVIOR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dkmddi/nc-d3dkmddi-dxgkddi_controlmodebehavior)
* Content Source: [wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_controlmodebehavior.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_controlmodebehavior.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @englishb 
Fixed the link. Should be live in a minute.
