### ISSUE TITLE
The note about "NT_SUCCESS macro recognizes all of these status values as "success" values." should be made more obvious.

### ISSUE THREAD

**Issue by jmc5113** [MicrosoftDocs/windows-driver-docs-ddi#665]
Under the table of return values is an important note that NT_SUCCESS recognizes all of the return values as success. This note is not very obvious. I think it would be better if it was above the table and contained some bold font to make sure that a reader scanning for the return codes sees it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2679ffa-4774-8de8-3ee8-d75c18aa48f4
* Version Independent ID: af7a279a-93aa-5e5b-fbb5-1e0c2ee14a07
* Content: [KeWaitForSingleObject function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-kewaitforsingleobject)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-kewaitforsingleobject.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-kewaitforsingleobject.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hey Jay, sorry for the delay. Great idea! I just pushed the fix, should be live within the hour.
