### ISSUE TITLE
Is REG_CALLBACK_CONTEXT_CLEANUP_INFORMATION provided for all handles of registry key?

### ISSUE THREAD

**Issue by drmkeeper** [MicrosoftDocs/windows-driver-docs-ddi#666]
"The RegNtCallbackObjectContextCleanup notification occurs when the driver has called CmUnRegisterCallback or the driver's RegistryCallback routine has just finished processing a RegNtPreKeyHandleClose notification."

Notification occurs when any handle of a key object has been closed or when the last handle to key object has been closed?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: def3ee58-24c1-bfc8-645c-539d912abc70
* Version Independent ID: 7d0598fc-8251-e504-ba43-68b6923f37a1
* Content: [_REG_CALLBACK_CONTEXT_CLEANUP_INFORMATION (wdm.h) - Windows drivers](https://docs.microsoft.com/ru-ru/windows-hardware/drivers/ddi/wdm/ns-wdm-_reg_callback_context_cleanup_information)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_reg_callback_context_cleanup_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_reg_callback_context_cleanup_information.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Sorry for the delay @drmkeeper. I was unable to track down any additional information for you regarding your question.

If it's still an issue, you may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
* [OSR's ntdev List](http://www.osronline.com/showlists.cfm?list=ntdev)

If you find the answer, let me know and I will add it to the docs. Thanks again for reaching out!

**Comment by tedhudek** [comment]
Update- I was able to get some info on this and updated https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_reg_callback_context_cleanup_information#remarks.  Should be on the live site within an hour
