### ISSUE TITLE
Memory leak in sample code?

### ISSUE THREAD

**Issue by colemandavid** [MicrosoftDocs/windows-driver-docs-ddi#668]
Should free(ConnectionInfo) on exit paths after malloc'ing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8da312b-a7f3-9797-e0ea-09806d790748
* Version Independent ID: 4d3cff4f-ca06-29b8-af44-6fe0290eb45b
* Content: [IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX (usbioctl.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information_ex#feedback)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information_ex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_node_connection_information_ex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @colemandavid, good call. Oftentimes, we simplify our sample code to leave out most (if not all) error handling code so we can make it clearer, but in this case I agree it's a good idea to make sure we don't include a memory leak in our example. :) I've fixed the last few lines of code to make sure we free the memory; those changes should be live later today. Thanks!
