### ISSUE TITLE
mapped-to address space

### ISSUE THREAD

**Issue by RaoulSteffen** [MicrosoftDocs/windows-driver-docs-ddi#671]
In the remarks section, it says "MmMapIoSpaceEx maps the physical address returned in the resource list to a _logical_ address through which the driver can access […]". However, the driver can access _virtual_ address space, while _logical_ is for access by the device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee9422c4-790b-cbef-eecc-fcbee9947a92
* Version Independent ID: 83818220-ec75-bb41-8bb9-79ee77c1a461
* Content: [MmMapIoSpaceEx function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmmapiospaceex)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmmapiospaceex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmmapiospaceex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Valid point, thanks. Apologies for the delay - I just pushed this fix.
