### ISSUE TITLE
Can return a failure if the CBD completed Synchronously

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#672]
You say
&gt; Note that the NTSTATUS value returned by FltPerformAsynchronousIo indicates only whether the I/O operation was successfully initiated.

This is not correct.  I have a dump (if Craig  cares) where a perform has failed `STATUS_OPLOCK_NOT_GRANTED` and I have gone to free the contex , only to discover that it has been freed by my `CallbackRoutine`.

Good luck documenting this: "some of the time a failure status means that the request hasn't been sent, but sometimes it has been".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4590d7-4f8a-c1f5-376a-3af10ed95c40
* Version Independent ID: 632bd07c-b98e-7c71-c46c-8e742660b0a9
* Content: [FltPerformAsynchronousIo function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltperformasynchronousio?redirectedfrom=MSDN)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltperformasynchronousio.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltperformasynchronousio.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , thanks for reporting this. I've updated the page to hopefully be more clear about status codes and context freeing (which can totally be done in the callback routine)!

**Comment by rodwiddowson** [comment]
looks fantastic.  Thanks @lorihollasch
