### ISSUE TITLE
[NET_BUFFER] A lot of members do not have details

### ISSUE THREAD

**Issue by xiaoyinl** [MicrosoftDocs/windows-driver-docs-ddi#674]
The members of struct `NET_BUFFER` such as `Next`, `CurrentMdl`, etc., lack explanations.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c4439666-d0cb-01e2-985b-e994b2b2d16c
* Version Independent ID: dd99a34b-1156-605c-1bff-5f265a0217d3
* Content: [_NET_BUFFER (ndis.h) - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/ddi/ndis/ns-ndis-_net_buffer)
* Content Source: [wdk-ddi-src/content/ndis/ns-ndis-_net_buffer.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/ns-ndis-_net_buffer.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @xiaoyinl, thanks for finding this. It looks like the NET_BUFFER structure got updated in a recent release to include the members of the NET_BUFFER_DATA structure in the NET_BUFFER itself, but those changes slipped by us. I've updated the member descriptions and have published the changes for the English version of the page; they should also be live for the Chinese version as soon as our localization team does another sweep over the content soon.

Thanks!
