### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by vkamath1** [MicrosoftDocs/windows-driver-docs-ddi#675]
The link to DEVICE_REGISTRY_PROPERTY is broken. The correct link is https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ne-wdm-device_registry_property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b509b635-f6c0-1649-847d-a2c349fadb22
* Version Independent ID: d7e77199-f0e6-49d5-e9c3-f4011669adc1
* Content: [WdfDeviceQueryProperty function (wdfdevice.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdevice/nf-wdfdevice-wdfdevicequeryproperty#feedback)
* Content Source: [wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicequeryproperty.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdevice/nf-wdfdevice-wdfdevicequeryproperty.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by aviviano** [comment]
Thanks @vkamath1 and @hsebs. This fix is up.
