### ISSUE TITLE
FlipImmediateNoTearing?

### ISSUE THREAD

**Issue by kpsam2000** [MicrosoftDocs/windows-driver-docs-ddi#677]
Kindly provide description for FlipImmediateNoTearing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 366f4eaf-5608-1c35-0ce5-c646e1efffb7
* Version Independent ID: 99bf419f-c667-a391-c409-adecc6c56d23
* Content: [_DXGK_PLANE_SPECIFIC_INPUT_FLAGS (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ns-d3dkmddi-_dxgk_plane_specific_input_flags#feedback)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_plane_specific_input_flags.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_plane_specific_input_flags.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@kpsam2000 , thanks for reporting this! I've added the missing description.
