### ISSUE TITLE
Mcb

### ISSUE THREAD

**Issue by mcb0006** [MicrosoftDocs/windows-driver-docs-ddi#678]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e0eee3-f834-691d-d436-295e53630dc5
* Version Independent ID: 719b667f-9743-e62a-1995-4f50157ae7c5
* Content: [MapSecurityError function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-mapsecurityerror?redirectedfrom=MSDN)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-mapsecurityerror.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-mapsecurityerror.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mcb0006 , I'm closing this issue because it doesn't include a description that I can act on, and I don't see an issue with the page that this issue is filed against. Feel free to reopen with a description if I've missed something!
