### ISSUE TITLE
Must Complete The Request

### ISSUE THREAD

**Issue by PeterGV** [MicrosoftDocs/windows-driver-docs-ddi#679]
I just got an email from a student who was confused about this... and that stimulated me to provide this feedback:

The docs for this callback should say that the driver is responsible for ultimately completing the Request provided in this callback (or sending it with SEND_AND_FORGET).... in just the same way it's responsible for handling a Request presented at a (Queue-based) EvtIo Event Processing Callback.  This is a a reasonably common point of confusion encountered by my students.

Also, while I'm here, the docs read:

&gt;This callback function is called synchronously, in the context of the user thread that opens the device.

Kudos for being specific about the context.  Minus a half point, though, for the word "user" in the above sentence... the callback is called in the context of the thread that opens the device, regardless of whether that thread originates in user-mode or kernel-mode.

It also might be nice to mention here that Create Requests can also be Presented by a Queue, by configuring Request dispatching.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffefa56a-599c-47ae-4790-00f61498c954
* Version Independent ID: c2f1f4cb-9896-aaeb-007f-3bcc06fc7f81
* Content: [EVT_WDF_DEVICE_FILE_CREATE (wdfdevice.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdevice/nc-wdfdevice-evt_wdf_device_file_create)
* Content Source: [wdk-ddi-src/content/wdfdevice/nc-wdfdevice-evt_wdf_device_file_create.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfdevice/nc-wdfdevice-evt_wdf_device_file_create.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @PeterGV, really appreciate the specific feedback.  Will get the updates in as soon as I can.

**Comment by tedhudek** [comment]
Updates should be live within half an hour.

**Comment by tedhudek** [comment]
Thanks again for opening this, Peter.  Please check out the third to last and second to last paragraphs of https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdevice/nc-wdfdevice-evt_wdf_device_file_create#remarks when you have a sec.

**Comment by PeterGV** [comment]
Awesome, Ted, thank you as always for your prompt attention to these little matters.  FYI, I also let my student (whose confusion instigated my post here) know the docs were changed due to his noticing this was missing.
