### ISSUE TITLE
Clarification regarding execution of SG allocation callback

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs-ddi#682]
> When a miniport driver calls NdisMAllocateNetBufferSGList to create a scatter/gather list, NDIS calls HAL to create the list. After creating the list, NDIS calls the miniport driver's MiniportProcessSGList function.

Will the NDIS always call the MiniportProcessSGList or only if the allocation succeeded (i.e., only if NdisMAllocateNetBufferSGList returns NDIS_STATUS_SUCCESS) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f5372f8-1302-9a8e-1c10-3c4aebd4b3ee
* Version Independent ID: c0418a60-b94c-e019-84f9-06454bf595fb
* Content: [MINIPORT_PROCESS_SG_LIST (ndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/nc-ndis-miniport_process_sg_list)
* Content Source: [wdk-ddi-src/content/ndis/nc-ndis-miniport_process_sg_list.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nc-ndis-miniport_process_sg_list.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by tedhudek** [comment]
Thanks for the feedback @I-gor-C and apologies for the delay.  I updated the docs with clarification; see commit link above.

Cheers!
