### ISSUE TITLE
windows server 2012-r2 info

### ISSUE THREAD

**Issue by zvilius** [MicrosoftDocs/windows-driver-docs-ddi#683]
The table of version information for supported Windows o/s's seems to have an error for Windows Server 2012 R2: the "version number" column shows 6.3, which is correct, but the dwMajor and dwMinor columns show 10 and 0, respectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aec28be5-41e6-1634-f4a3-0311df18628b
* Version Independent ID: d718deaa-d2eb-54ef-f25c-35532c383fb0
* Content: [_OSVERSIONINFOEXW (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_osversioninfoexw#feedback)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_osversioninfoexw.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_osversioninfoexw.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thx for the feedback, apologies for the delay. Yes, you are correct - just pushed the fix. Should be live within the hour
