### ISSUE TITLE
Formatting is broken

### ISSUE THREAD

**Issue by DyessGG** [MicrosoftDocs/windows-driver-docs-ddi#685]
The formatting of the section documenting the fields in this structure is broken.  I've tried wtih Edge, Internet Explorer, Chrome and Firefox.  On all, it shows the html source instead of being formatted for reading.

This isn't the only NDIS structure documentation page that is similarly broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d88ac221-7a6b-4460-fc07-52eecb039e7b
* Version Independent ID: 1bcd65e9-9bb5-ed36-47fb-061b67ff706b
* Content: [_NDIS_MINIPORT_INIT_PARAMETERS (ndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/ns-ndis-_ndis_miniport_init_parameters#feedback)
* Content Source: [wdk-ddi-src/content/ndis/ns-ndis-_ndis_miniport_init_parameters.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/ns-ndis-_ndis_miniport_init_parameters.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by EliotSeattle** [comment]
Thanks so much @DyessGG for this.
It turned out that this was a system-wide build issue. We've made the fix and all topics should be rendering correctly now.
Eliot
