### ISSUE TITLE
Members of LINKED_DEVICE structure is not showing properely.

### ISSUE THREAD

**Issue by rajatkumarv** [MicrosoftDocs/windows-driver-docs-ddi#686]
[Enter feedback here]
Members of LINKED_DEVICE structure is not showing properely and it is showing actual hyperlinks instead of link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd1fdc43-ae5d-c6fd-93be-7f1652b83dd1
* Version Independent ID: 735bbca2-27e9-3f11-cd2e-0f9fc26d7ec2
* Content: [_LINKED_DEVICE (dispmprt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dispmprt/ns-dispmprt-_linked_device)
* Content Source: [wdk-ddi-src/content/dispmprt/ns-dispmprt-_linked_device.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dispmprt/ns-dispmprt-_linked_device.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rajatkumarv , thanks for taking the time to write. I don't see any issues on this page. LINKED_DEVICE matches what is shipped in dispmprt.h, and the only links on the page are rendered correctly and jump to the correct page. Did you perhaps find an issue on another page? I'm closing this for now - let me know if I've missed anything.
