### ISSUE TITLE
FS_FILTER_PARAMETERS.NotifyStreamFileObject is not described

### ISSUE THREAD

**Issue by 21street** [MicrosoftDocs/windows-driver-docs-ddi#69]
There's no subject structure in the FS_FILTER_PARAMETERS one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3aed758-d5dc-0128-62fb-2bc69c635540
* Version Independent ID: 8351a690-5a4c-8c30-11f6-eb0a62ed3ded
* Content: [FsRtlRegisterFileSystemFilterCallbacks function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks#parameters)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @21street , sorry about the delay in getting this fixed. NotifyFileStreamObject has been deprecated and removed from FS_FILTER_PARAMETERS starting in the next release of Windows. The development team would like to discourage its use, so I've gone ahead and removed it from the syntax block and description for that structure even though it does still appear in the public header for Windows 10, version 1809. Please disregard FS_FILTER_PARAMETERS.NotifyFileStreamObject. Thanks again for your interest in the docs!
