### ISSUE TITLE
RtlAllocateHeap (return value)

### ISSUE THREAD

**Issue by yagyaansh-goenka** [MicrosoftDocs/windows-driver-docs-ddi#690]
The return value behavior is not consistent with the description in this document. Looks like the function returns a NULL if it fails and the return codes are to be retrieved using GetLastError.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 698fe114-8325-6a79-6134-7b9d60259601
* Version Independent ID: fa955e25-c623-68bd-5827-7e6965d7db2e
* Content: [RtlAllocateHeap function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlallocateheap#feedback)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-rtlallocateheap.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-rtlallocateheap.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@yagyaansh-goenka , thanks for reporting this! You are right that it returns NULL on failure - I've updated the page accordingly.
