### ISSUE TITLE
PsSetLoadImageNotifyRoutineEx 难道不需要PsRemoveLoadImageNotifyRoutine 么？

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/windows-driver-docs-ddi#691]
[Enter feedback here]

文档中应该加上：
A driver must remove any callbacks it registers before it unloads. You can remove the callback by calling the PsRemoveLoadImageNotifyRoutine routine.

是不是？

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a941f3b-de63-d215-b43c-6c390d968c1f
* Version Independent ID: c83108af-35a7-8f90-e3a3-1cd76517ca3d
* Content: [PsSetLoadImageNotifyRoutineEx function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-pssetloadimagenotifyroutineex?source=docs)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-pssetloadimagenotifyroutineex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-pssetloadimagenotifyroutineex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Fixed in #752, thanks @hsebs.  Thanks @kouzhudong for this feedback
