### ISSUE TITLE
Notes about IOCTL_USBPRINT_GET_1284_ID IOCTL

### ISSUE THREAD

**Issue by interactii** [MicrosoftDocs/windows-driver-docs-ddi#696]
For IOCTL_USBPRINT_GET_1284_ID IOCTL, the output buffer length is placed directly into the USB packet, and using the recommended 65535 bytes can cause the call to fail with error 23 on some USB print devices. Reduce the buffer to 4094 bytes or less to resolve this issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58b2c2e-bb91-44e2-b9a8-a2665128887c
* Version Independent ID: 00b9e275-87c2-f277-bee0-77ad7336a346
* Content: [IOCTL_USBPRINT_GET_1284_ID (usbprint.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/usbprint/ni-usbprint-ioctl_usbprint_get_1284_id#feedback)
* Content Source: [wdk-ddi-src/content/usbprint/ni-usbprint-ioctl_usbprint_get_1284_id.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbprint/ni-usbprint-ioctl_usbprint_get_1284_id.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@interactii, thanks for submitting this issue on the possible error with the output buffer length.

The topic has been updated to reflect the information you provided.
