### ISSUE TITLE
Field indirection mismatch: Data

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/windows-driver-docs-ddi#707]
The description says it's a pointer. The actual declaration says it's an array. It clearly can't be both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a31a787-18d8-58aa-9a41-b7e68564f4fd
* Version Independent ID: 766af74e-716a-5f2b-053a-d250591017c3
* Content: [_DISK_GEOMETRY_EX (ntdddisk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntdddisk/ns-ntdddisk-_disk_geometry_ex)
* Content Source: [wdk-ddi-src/content/ntdddisk/ns-ntdddisk-_disk_geometry_ex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntdddisk/ns-ntdddisk-_disk_geometry_ex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@henke37 , thanks for reporting this doc error. I have removed the pointer reference and updated Data's description to be more clear about the structures that can be accessed through it.
