### ISSUE TITLE
Missing table of return values.

### ISSUE THREAD

**Issue by svnscha** [MicrosoftDocs/windows-driver-docs-ddi#708]
The return values are missing for this function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdb02197-0409-e009-1f65-00c756564e1d
* Version Independent ID: 290b85f0-a11b-0b4e-d060-2a44d4f97b09
* Content: [ZwSetValueKey function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwsetvaluekey#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwsetvaluekey.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwsetvaluekey.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Just pushed a fix for this. Should be live within the hour.

Sorry it took so long! Appreciate the feedback!
