### ISSUE TITLE
PreAcquireForSectionSynchronization callback's success status values besides STATUS_SUCCESS

### ISSUE THREAD

**Issue by 21street** [MicrosoftDocs/windows-driver-docs-ddi#71]
The subject callback can return a number of success status values besides STATUS_SUCCESS:
- STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY (0x00000126)
- STATUS_FILE_LOCKED_WITH_ONLY_READERS (0x0000012A)
- STATUS_FILE_LOCKED_WITH_WRITERS (0x0000012B)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3aed758-d5dc-0128-62fb-2bc69c635540
* Version Independent ID: 8351a690-5a4c-8c30-11f6-eb0a62ed3ded
* Content: [FsRtlRegisterFileSystemFilterCallbacks function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks#parameters)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @21street, I've added this information to the topic, and it should be live shortly. Thanks!
