### ISSUE TITLE
Argument sequence and types are confused

### ISSUE THREAD

**Issue by emuzychenko** [MicrosoftDocs/windows-driver-docs-ddi#710]
The "Parameter" argument is the second, with "PVOID" type. The "Size" argument is the third, with "SIZE_T" type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ad3b97d-fac8-9f5a-9f6d-a49818f2944a
* Version Independent ID: 796528a1-d67e-449d-9077-35cf6b2de0c9
* Content: [KeExpandKernelStackAndCallout function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-keexpandkernelstackandcallout)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-keexpandkernelstackandcallout.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-keexpandkernelstackandcallout.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Just pushed a fix, should be live soon. Thanks for the feedback and apologies for the delay!
