### ISSUE TITLE
Mussed up formatting

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#712]
Happy new year Lori!
I never use this method but I popped by to answer an NTFD question and I spotted what is at bets confusing indentation.  

In the remarks section the paragraph starting "If IRQL &gt;= DISPATCH_LEVEL, " is very weird. 

I'm guessing that there is some sort of "if" missing after the first bullet so that bullets (2,3) are one leg of it and (4,5) are the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f34883-8830-f378-182b-a38835b60268
* Version Independent ID: cb96e525-8b9b-4c5c-8bb5-d8fbf0fa9403
* Content: [FltDoCompletionProcessingWhenSafe function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltdocompletionprocessingwhensafe)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltdocompletionprocessingwhensafe.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltdocompletionprocessingwhensafe.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Happy New Year to you, too, @rodwiddowson ! Thanks for reporting this page - there was indeed an IF condition missing from it. I've updated it to be complete. Cheers!
