### ISSUE TITLE
loading is delayed

### ISSUE THREAD

**Issue by sethbrenith** [MicrosoftDocs/windows-driver-docs-ddi#714]
I think it's worth mentioning in remarks on this page that AddExtension does not actually load or initialize the extension DLL. It does not even check whether the file exists, and will return S_OK if you request to add a nonexistent extension. After AddExtension, the extension shows up in `.chain` output but in an unloaded state. To cause the extension to load, you can use a subsequent call to GetExtensionFunction. Attempting to get a nonexistent extension function will of course return a failure, but it will cause the extension to be fully loaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a845ac8b-ed11-556b-c577-c529588e6567
* Version Independent ID: c1861fd7-e4fc-e239-618b-25c68b3722c0
* Content: [IDebugControl::AddExtension (dbgeng.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgeng/nf-dbgeng-idebugcontrol-addextension#feedback)
* Content Source: [wdk-ddi-src/content/dbgeng/nf-dbgeng-idebugcontrol-addextension.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dbgeng/nf-dbgeng-idebugcontrol-addextension.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@sethbrenith - Thanks for this issue. I added wording as you suggested to remind people that AddExtension does not complete the process of loading and initializing the extension DLL. And that to make the extension available for use, you need to also call GetExtensionFunction. Thanks for this issue and the interest in our docs.
