### ISSUE TITLE
TypeSpecificCompletionOutput

### ISSUE THREAD

**Issue by odiassle** [MicrosoftDocs/windows-driver-docs-ddi#715]
Size should be 64-bit field and not 32-bit field, No?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c54657a-4b8c-b7fe-b7af-c83ff9418a7c
* Version Independent ID: f789afa8-1353-3e85-1862-58416fdadbf8
* Content: [_NDK_RESULT_EX (ndkpi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ndkpi/ns-ndkpi-_ndk_result_ex)
* Content Source: [wdk-ddi-src/content/ndkpi/ns-ndkpi-_ndk_result_ex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndkpi/ns-ndkpi-_ndk_result_ex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by billlattimer** [comment]
@odiassle thank you for the question. As noted in article, the size is dependent on the type of return. See the link below for more information on the data type: 

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/21eec394-630d-49ed-8b4a-ab74a1614611
