### ISSUE TITLE
the function definition and the description don't match.

### ISSUE THREAD

**Issue by wdcui** [MicrosoftDocs/windows-driver-docs-ddi#717]
It should be PVOID Parameter, and then PVOID *Context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 093c08d9-0750-842d-cfe1-936ff2b36851
* Version Independent ID: ad0b1555-a6de-9129-e978-f76376e62535
* Content: [RtlRunOnceExecuteOnce function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-rtlrunonceexecuteonce#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-rtlrunonceexecuteonce.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-rtlrunonceexecuteonce.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by aviviano** [comment]
@wdcui Thanks very much for this issue. The fix is now up.
