### ISSUE TITLE
Errors in the definition.

### ISSUE THREAD

**Issue by wdcui** [MicrosoftDocs/windows-driver-docs-ddi#718]
It should be "PVOID Parameter" and "PVOID *Context".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa940e0-4b82-9078-7e3d-30adbca29289
* Version Independent ID: 7978598b-ebee-7cbe-93fa-3210c2d22ce7
* Content: [RTL_RUN_ONCE_INIT_FN (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nc-ntddk-rtl_run_once_init_fn)
* Content Source: [wdk-ddi-src/content/ntddk/nc-ntddk-rtl_run_once_init_fn.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nc-ntddk-rtl_run_once_init_fn.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Just pushed the update, should be live soon.  Thanks for the feedback, and apologies for the delay.
