### ISSUE TITLE
The Flags field is not reserved

### ISSUE THREAD

**Issue by 21street** [MicrosoftDocs/windows-driver-docs-ddi#72]
The subject field can contain the following bits:
#define FS_FILTER_SECTION_SYNC_SUPPORTS_ASYNC_PARALLEL_IO         (0x00000001)
#define FS_FILTER_SECTION_SYNC_SUPPORTS_DIRECT_MAP_DATA           (0x00000002)
#define FS_FILTER_SECTION_SYNC_SUPPORTS_DIRECT_MAP_IMAGE          (0x00000004)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa562d2-3fae-9523-26c6-1f8506268a6c
* Version Independent ID: ae355f8d-7bbe-4111-95bd-ede16b9894e1
* Content: [_FS_FILTER_SECTION_SYNC_OUTPUT](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_fs_filter_section_sync_output)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_fs_filter_section_sync_output.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_fs_filter_section_sync_output.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Thanks @21street, I've added this information into the page. Should be visible soon!
