### ISSUE TITLE
Member sections spurious

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#722]
hey Lori,
The only value that the "members" section provides is to exercise your scrolling talents to get to the Remarks sections.
I know this is auto-generated, but any chance to dropping the section?

Tnx
/Rod

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4209424c-ef49-d9c7-7183-5049a6fa4a92
* Version Independent ID: 185422d4-4b0b-1a4a-944e-b1c7e40e8354
* Content: [_FLT_PARAMETERS (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-gb/windows-hardware/drivers/ddi/fltkernel/ns-fltkernel-_flt_parameters#feedback)
* Content Source: [wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_parameters.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_parameters.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by tedhudek** [comment]
Hi @rodwiddowson, thanks for the question. Sadly there is currently no way to suppress those members.  Best I have for you is to use the `In this article` sidebar on the right edge of the page, which contains links to the various subsections, including **Remarks**.
