### ISSUE TITLE
Question regarding the parameters

### ISSUE THREAD

**Issue by SJKU** [MicrosoftDocs/windows-driver-docs-ddi#724]
I have a question regarding this api. Can you clarify whether the first parameter for this function "CallbackFunction" is optional or mandatory .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b824e25f-2251-8f4c-f4d2-cb437304036c
* Version Independent ID: 811f7ff7-95fe-91a6-bcde-3bf139701be1
* Content: [IoRegisterBootDriverCallback function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-ioregisterbootdrivercallback?redirectedfrom=MSDN#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-ioregisterbootdrivercallback.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-ioregisterbootdrivercallback.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
It's mandatory.  This API takes in a function pointer to be called at a later time, so if there's no function pointer, calling the API makes no sense.
