### ISSUE TITLE
Wrong return type

### ISSUE THREAD

**Issue by impugachev** [MicrosoftDocs/windows-driver-docs-ddi#727]
KeAcquireSpinLock actually return void, but in this article it is KIRQL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa3c15d-359f-d2aa-ba54-237f63c0e2f6
* Version Independent ID: 7aeea6e4-0625-7987-4859-9a0750c1895b
* Content: [KeAcquireSpinLock macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-keacquirespinlock#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-keacquirespinlock.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-keacquirespinlock.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @impugachev you are correct!  I've just pushed the fix.  It should be reflected on the live site within an hour.  If not please let us know.
