### ISSUE TITLE
Missing hyperlink

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#728]
Most of the dxgk ddi pages link to the page for the structure that makes up their arguments.  This page should similiarly have a link to the DXGKARG_GETPOSTCOMPOSITIONCAPS page where this structure is referenced here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4958b281-e63f-fadb-f111-b755aa56aa7d
* Version Independent ID: 314b68e7-4e6b-3de4-9551-531aa89899ee
* Content: [DXGKDDI_GETPOSTCOMPOSITIONCAPS (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/nc-d3dkmddi-dxgkddi_getpostcompositioncaps)
* Content Source: [wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_getpostcompositioncaps.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_getpostcompositioncaps.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@englishb , fixed by @hsebs #738 (thanks again) - links will be live by end of day.
