### ISSUE TITLE
No references to the FS_FILTER_SECTION_SYNC_OUTPUT structure

### ISSUE THREAD

**Issue by 21street** [MicrosoftDocs/windows-driver-docs-ddi#73]
There are at least two structures that contain references to the subject structure:
- FS_FILTER_PARAMETERS
- FLT_PARAMETERS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa562d2-3fae-9523-26c6-1f8506268a6c
* Version Independent ID: ae355f8d-7bbe-4111-95bd-ede16b9894e1
* Content: [_FS_FILTER_SECTION_SYNC_OUTPUT](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_fs_filter_section_sync_output)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_fs_filter_section_sync_output.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_fs_filter_section_sync_output.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @21street , sorry for the delay in getting this fixed. I've added a link to FS_FILTER_SECTION_SYNC_OUTPUT from the [FsRtlRegisterFileSystemFilterCallbacks](https://docs.microsoft.com/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks) page, where FS_FILTER_PARAMETERS is described. I also added a link to it from the [FLT_PARAMETERS for IRP_MJ_ACQUIRE_FOR_SECTION_SYNCHRONIZATION union](https://docs.microsoft.com/windows-hardware/drivers/ifs/flt-parameters-for-irp-mj-acquire-for-section-synchronization) topic that describes the part of FLT_PARAMETERS you're looking at. Those changes should be live later today.

Thanks for pointing this out!
