### ISSUE TITLE
Missing hyperlink

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#730]
The hyperlink to the page for the argument type DXGKARG_CHECKMULTIPLANEOVERLAYSUPPORT3 is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9fade1-01d8-a968-19b4-bd5570e1da88
* Version Independent ID: 2a37952f-405a-0e0e-b8e1-57e97805b94e
* Content: [DXGKDDI_CHECKMULTIPLANEOVERLAYSUPPORT3 (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/nc-d3dkmddi-dxgkddi_checkmultiplaneoverlaysupport3)
* Content Source: [wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_checkmultiplaneoverlaysupport3.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_checkmultiplaneoverlaysupport3.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by EliotSeattle** [comment]
Hi @englishb (Ben).

I made the fix and have asked @lorihollasch to review before we push live. Should be today.
Thanks for the Issue.
Eliot
