### ISSUE TITLE
Can we please update WDDM constants page?

### ISSUE THREAD

**Issue by kevinf28** [MicrosoftDocs/windows-driver-docs-ddi#731]
Looks like its missing many WDDM versions from 19h1 and newer.
https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1903_(May_2019_Update)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 504c6508-5f83-159f-be97-2c19af548d04
* Version Independent ID: 7b284030-fd41-c4e1-5455-514529df33ac
* Content: [_DXGK_WDDMVERSION (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ne-d3dkmddi-_dxgk_wddmversion#feedback)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ne-d3dkmddi-_dxgk_wddmversion.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ne-d3dkmddi-_dxgk_wddmversion.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@kevinf28, thanks for reporting this - it is now up to date!
