### ISSUE TITLE
File names(urls) are wrong.

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/windows-driver-docs-ddi#733]
https://github.com/MicrosoftDocs/windows-driver-docs-ddi/tree/staging/wdk-ddi-src/content/ntifs

I know that _FSRTL_ADVANCED_FCB_HEADER is removed from UIDs, but file names still include _FSRTL_ADVANCED_FCB_HEADER.

The worst news is that other pages refer to pages with these names.

**Comment by lorihollasch** [comment]
@hsebs, as mentioned in #735 , the URL names are correct as they are. Thanks for checking!
