### ISSUE TITLE
Incorrect NDIS version specified

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs-ddi#741]
> The NDIS_ENCAPSULATED_PACKET_TASK_OFFLOAD_V2 structure contains packet encapsulation information for Virtual Extensible LAN (VXLAN) task offload. VXLAN is similar to NVGRE task offload, but with a different protocol.
> 
> This structure is used in the EncapsulatedPacketTaskOffloadVxlan member of the NDIS_OFFLOAD structure in NDIS 6.70 and later.
> 

That seems to be incorrect. According to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_offload and the actual definition in ntddndis.h the **EncapsulatedPacketTaskOffloadVxlan** is available for usage since NDIS **6.50**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 603f8730-8df3-cdd2-d075-05490fc11677
* Version Independent ID: 317cdd6d-94b9-207c-4f49-b8146b923786
* Content: [_NDIS_ENCAPSULATED_PACKET_TASK_OFFLOAD_V2 (ntddndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_encapsulated_packet_task_offload_v2)
* Content Source: [wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_encapsulated_packet_task_offload_v2.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddndis/ns-ntddndis-_ndis_encapsulated_packet_task_offload_v2.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Hi @I-gor-C thanks for the sharp eye as always and apologies for the delay.  You are correct- I've made the change.
