### ISSUE TITLE
MdlChain for FsRtlMdlReadEx must point to the PMDL initialized to NULL.

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/windows-driver-docs-ddi#745]
If `MdlChain` points the `PMDL` which is not initialized with `NULL`, `FsRtlMdlReadEx` can cause BSOD.

If `MdlChain` is the pointer to an uninitialized `PMDL`, `FsRtlMdlReadEx` sometimes calls `CcMdlRead` with `MdlChain`.

![image](https://user-images.githubusercontent.com/19328795/75157813-3f5cb400-5758-11ea-8caa-cea37e8c3ca4.png)

If `MdlChain` point to the pointer to a freed  `MdlChain`, `FsRtlMdlReadEx` reuse it without locking page.
It looks like *Dangling pointer* problem. (I'm not sure if it is vulnerability.)

![image](https://user-images.githubusercontent.com/19328795/75177265-2a444d00-5779-11ea-95f6-0cb6f995c44f.png)

My test code for second case:
```
VOID Test(
	_In_		PFLT_INSTANCE	SourceFileInstance,
	_In_		PFILE_OBJECT	SourceFileObject
)
{
	NTSTATUS		status = STATUS_SUCCESS;
	LARGE_INTEGER	offset = { 0L };
	ULONG			length = 0;
	IO_STATUS_BLOCK				statusBlock = { 0, };
	FILE_STANDARD_INFORMATION	fileStandardInformation = { 0, };
	PMDL						mdl = NULL;

	if (KeGetCurrentIrql() > PASSIVE_LEVEL)
		return;

	if (IoGetTopLevelIrp() != NULL)  
		return;

	status = FltQueryInformationFile(SourceFileInstance, SourceFileObject, &fileStandardInformation, sizeof(FILE_STANDARD_INFORMATION), FileStandardInformation, &length);

	if (NT_SUCCESS(status))
	{
		offset.QuadPart = 0;
		for (status = STATUS_SUCCESS; NT_SUCCESS(status) && offset.QuadPart < fileStandardInformation.EndOfFile.QuadPart;)
		{
			FsRtlMdlReadEx(SourceFileObject, &offset, 1024, 0, &mdl, &statusBlock);
			if (statusBlock.Status == STATUS_SUCCESS)
			{
				CcMdlReadComplete(SourceFileObject, mdl);

				offset.QuadPart += statusBlock.Information;
			}
			else
			{
				if (statusBlock.Information == 0)
				{
					KdPrint(("FsRtlMdlReadEx : Failed\n"));
					break;
				}
			}
		}
	}
}
```

Result of test code:

```
1: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

PFN_LIST_CORRUPT (4e)
Typically caused by drivers passing bad memory descriptor lists (ie: calling
MmUnlockPages twice with the same list, etc).  If a kernel debugger is
available get the stack trace.
Arguments:
Arg1: 0000000000000007, A driver has unlocked a page more times than it locked it
Arg2: 0000000000020f7b, page frame number
Arg3: 0000000000000001, current share count
Arg4: 0000000000000000, 0

Debugging Details:
------------------

```

My test environment : `Windows 10 Kernel Version 17134 MP (2 procs) Free x64` on Hyper-V

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0f4a84a-9f36-6918-85f5-f0a58901c8f8
* Version Independent ID: ec193bea-303f-cb14-439e-4f5258f6dba4
* Content: [FsRtlMdlReadEx function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreadex)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreadex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreadex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@hsebs, thanks for PR #746  to fix this.
