### ISSUE TITLE
Typo error in GNSS_DRIVERCOMMAND_TYPE

### ISSUE THREAD

**Issue by JSFamily** [MicrosoftDocs/windows-driver-docs-ddi#748]
In GNSS_SetNMEALogging section, is that mean the NMEA string will be providing via GNSS_FIXDATA even there is no space for the NMEA strings.
I think it is typo error and it should be change to GNSS_EVENT as GNSS_Event_NmeaData.

> This command causes the GNSS driver to start/stop providing the data fix information via NMEA strings. The GNSS driver must continue providing fixes in the GNSS_FIXDATA structure. The parameter is a DWORD with the following values:

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 463b5059-0396-9074-4103-134f006abbab
* Version Independent ID: 678fcc9d-75ba-630f-3f90-3242779e436b
* Content: [GNSS_DRIVERCOMMAND_TYPE (gnssdriver.h) - Windows drivers](https://docs.microsoft.com/ko-kr/windows-hardware/drivers/ddi/gnssdriver/ne-gnssdriver-gnss_drivercommand_type#feedback)
* Content Source: [wdk-ddi-src/content/gnssdriver/ne-gnssdriver-gnss_drivercommand_type.md

**Comment by barrygolden** [comment]
@JSFamily, thanks for pointing out a probable error in the GNSS docs. I'm opening an internal work item to correct and update the GNSS_DRIVERCOMMAND_TYPE enumeration topic.

Also, you may have success posting your question about the GNSS_DRIVERCOMMAND_TYPE enumeration in the following forums, where other driver developers and Microsoft engineers can be found.

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
