### ISSUE TITLE
Length is not always the size of buffer that the Buffer parameter points to.

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/windows-driver-docs-ddi#749]
When an MDL is provided in *Mdl*, *Length* is the size of data that MDL describes.

If MDL is provided in *Mdl*, It should not be zero even if *Buffer* is NULL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874d11f4-3849-5656-80ed-f4bfd18cb26f
* Version Independent ID: 18e54d16-16a9-3a29-74e3-1c5d042c8be9
* Content: [FltWriteFileEx function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltwritefileex)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltwritefileex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltwritefileex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@hsebs, thanks for PR to fix this.
