### ISSUE TITLE
How to specify you support a fearure

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#751]
I'm relatively certain that a Minifilters get to set `SupportedFeatures=&lt;mask&gt;`. and that value is what happens here here.  But what about FSDs (I see for instance that luafv has this setting but NTFS doesn't).

Either way it would be nice to mention how this is flagged here, and at `ifs/flt-parameters-for-irp-mj-query-open` and probably also at `ddi/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 082caca6-0df3-363b-8c66-2aff0cbdbc8f
* Version Independent ID: 1d4d1da3-0961-b48f-a0e8-8f98809e14c9
* Content: [FsRtlGetSupportedFeatures function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-fsrtlgetsupportedfeatures)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlgetsupportedfeatures.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlgetsupportedfeatures.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , I added some details to FsRtlGetSupportedFeatures. Not sure where to add them on the other pages you mentioned. Closing for now, but feel free to reopen with suggestions, thanks. :)
