### ISSUE TITLE
Get failure reason on E_FAIL?

### ISSUE THREAD

**Issue by holc-tkomp** [MicrosoftDocs/windows-driver-docs-ddi#759]
Is there a way to retrieve more information why the OpenDumpFile call failed, when it returns just the E_FAIL (0x80004005)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67dc6b8e-22b9-a922-cf96-90cf5768b338
* Version Independent ID: f319bfb6-96f8-ee5e-be03-a6e4df80143b
* Content: [IDebugClient::OpenDumpFile (dbgeng.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgeng/nf-dbgeng-idebugclient-opendumpfile#feedback)
* Content Source: [wdk-ddi-src/content/dbgeng/nf-dbgeng-idebugclient-opendumpfile.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dbgeng/nf-dbgeng-idebugclient-opendumpfile.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@holc-tkomp - Apologies for the delay here. I don't know a way when OpenDumpFile call fails and returns E_FAIL to gather more information. I would wonder if it could be wrapped in a try catch,  or use WaitForEvent or check the location of the dmp file using some other file or directory open call to check its health. 

For information on how to implement code like this, one resource is the OSR debugger forum. 

•	[OSR's windbg List](https://community.osr.com/categories/windbg)

Good luck in your work with the debugger.
