### ISSUE TITLE
NdisOpenFile, NdisCloseFile, NdisMapFile, and NdisUnmapFile are not supported on ARM64.

### ISSUE THREAD

**Issue by neilsh-msft** [MicrosoftDocs/windows-driver-docs-ddi#762]
Please update this page to state that NdisOpenFile, NdisCloseFile, NdisMapFile and NdisUnmapFile are not supported on ARM64.  The functions should be substituted with code that uses ZwCreateFile, and ZwReadFile or other similar operations.

The header file km\ndis.h in the driver SDK has the following code which does not define these functions for ARM64:

#if defined(_M_IX86) || defined(_M_AMD64) || defined(_M_ARM)

//
// Simple I/O support
//

_IRQL_requires_(PASSIVE_LEVEL)
EXPORT
VOID
NdisOpenFile(
    _Out_ PNDIS_STATUS            Status,
    _Out_ PNDIS_HANDLE            FileHandle,
    _Out_ PUINT                   FileLength,
    _In_  PNDIS_STRING            FileName,
    _In_  NDIS_PHYSICAL_ADDRESS   HighestAcceptableAddress
    );
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70bb91f0-d0ce-a5cb-d73e-8faab239c8c2
* Version Independent ID: 477fac55-fbfb-90f6-208c-2ed855e1ae71
* Content: [NdisOpenFile function (ndis.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/nf-ndis-ndisopenfile#feedback)
* Content Source: [wdk-ddi-src/content/ndis/nf-ndis-ndisopenfile.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ndis/nf-ndis-ndisopenfile.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Thanks Neil, great point and sorry it took so long to get it done.  I just pushed the fix.
