### ISSUE TITLE
Duplicate ms.assetid

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/windows-driver-docs-ddi#767]
[nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreaddev.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreaddev.md) and [nf-fltkernel-fltfastiomdlread.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltfastiomdlread.md) have same assetid.

[nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreadcompletedev.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreadcompletedev.md) and [nf-fltkernel-fltfastiomdlreadcomplete.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltfastiomdlreadcomplete.md) have same assetid.

I wanted to fix it but don't know how to assign assetid. Could you tell me how to assign assetid?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0770a4a-0649-17a6-2c04-22a2eb835491
* Version Independent ID: a8cde675-26db-415e-8048-b7c3d13a4cd6
* Content: [FsRtlMdlReadDev function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreaddev)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreaddev.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreaddev.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488f38b1-5610-215c-68c9-ea15018b89b0
* Version Independent ID: 141da909-2c50-3a58-6799-f28242765e38
* Content: [FsRtlMdlReadCompleteDev function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreadcompletedev)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreadcompletedev.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlmdlreadcompletedev.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@hsebs , thanks for reporting this! It is best that metadata be updated internally only - I've made the fixes.
