### ISSUE TITLE
Minor mis-print

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#769]
IOCTL_STORAGE_READ_CAPACITIY  should probably end with _CAPACITY :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ad57fc9-40f2-5fa9-4020-4e659465345b
* Version Independent ID: 46e32a85-f62b-6f63-e92a-6eee636c5f37
* Content: [_STORAGE_READ_CAPACITY (ntddstor.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddstor/ns-ntddstor-_storage_read_capacity)
* Content Source: [wdk-ddi-src/content/ntddstor/ns-ntddstor-_storage_read_capacity.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddstor/ns-ntddstor-_storage_read_capacity.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @csm10495 , and thanks to @hsebs for fix #770 ! Fix will be live sometime today.
