### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#772]
The links to NETWORK_OPEN_INTEGRITY_QUALIFIER and NETWORK_OPEN_LOCATION_QUALIFIER are broken (old content).

I can see the content in git
```
Directory of .....github\windows-driver-docs-ddi\wdk-ddi-src\content\ntifs

28/01/2020  13:23             2,466 ne-ntifs-network_open_integrity_qualifier.md
28/01/2020  13:23             2,352 ne-ntifs-network_open_location_qualifier.md
```
But I cannot find them "live" so I am not sure how to link them in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3354b2c5-22cf-25c6-538f-771944b0f0bb
* Version Independent ID: 037abbef-8540-4b69-c407-58adf46c6486
* Content: [_NETWORK_OPEN_ECP_CONTEXT (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_network_open_ecp_context)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_network_open_ecp_context.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_network_open_ecp_context.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , I finally got these broken links fixed. Thanks for reporting them. So sorry for the slow response!
