### ISSUE TITLE
No information for redirector *writers*

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#773]
It sates "This is read only".  But if you are the redirector you have to populate this somehow.  I guess it isn't rocket science, but it would be nice to know how to do it.  Or if youcannot why not or what else you do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3354b2c5-22cf-25c6-538f-771944b0f0bb
* Version Independent ID: 037abbef-8540-4b69-c407-58adf46c6486
* Content: [_NETWORK_OPEN_ECP_CONTEXT (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_network_open_ecp_context)
* Content Source: [wdk-ddi-src/content/ntifs/ns-ntifs-_network_open_ecp_context.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/ns-ntifs-_network_open_ecp_context.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , thanks for this PR and sorry for the ambiguous read-only statement. You are right that this structure is for redirectors, and that filters should not alter it. I've updated the page accordingly.
