### ISSUE TITLE
PreOpen/PostOpen not supported by MUP

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#774]
It might be worth pointing this out because it means that redirector needn't try to support it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fc2474e-09f0-1c44-ab50-c2e4740ba55d
* Version Independent ID: aacb5686-0939-53c0-f4a8-ecb09f35984f
* Content: [FsRtlRegisterFileSystemFilterCallbacks function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlregisterfilesystemfiltercallbacks.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , I'm going to close this issue since the dev team isn't sure what you mean by pre/post-open. I sent you email - feel free to respond with clarification there if this is still an issue and we can reopen, thanks!
