### ISSUE TITLE
Storport Driver Link is broken

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#775]
https://docs.microsoft.com/windows-hardware/drivers/storage/storport-driver appears to be 404'ing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02ce1cb7-023f-63ed-ede2-82787c6c1066
* Version Independent ID: 175ae808-9009-9737-6b03-35ecad2969a3
* Content: [IOCTL_SCSI_GET_INQUIRY_DATA (ntddscsi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddscsi/ni-ntddscsi-ioctl_scsi_get_inquiry_data)
* Content Source: [wdk-ddi-src/content/ntddscsi/ni-ntddscsi-ioctl_scsi_get_inquiry_data.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddscsi/ni-ntddscsi-ioctl_scsi_get_inquiry_data.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@csm10495 , thanks for reporting this, and thanks to @hsebs for fixing one instance. I've fixed the broken links in other ntddscsi-relevant files as well.
