### ISSUE TITLE
Can SevenBitI2CAddress be changed to EightBitI2CAddress ?

### ISSUE THREAD

**Issue by vnvsrikanth** [MicrosoftDocs/windows-driver-docs-ddi#779]
As per DDC/CI standard 0x6E is 8 bit i2c address for i2c-write.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ba3e2f-2a93-0898-09b8-2e6a118a5f60
* Version Independent ID: ff9e8d04-8f1a-c74b-8dfc-a86489b2883e
* Content: [DXGKDDI_I2C_TRANSMIT_DATA_TO_DISPLAY (dispmprt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dispmprt/nc-dispmprt-dxgkddi_i2c_transmit_data_to_display#feedback)
* Content Source: [wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_i2c_transmit_data_to_display.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_i2c_transmit_data_to_display.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@vnvsrikanth , thanks for asking. Sorry, but we cannot change the name of the SevenBitI2CAddress parameter on this page since that is how it was defined and released in dispmprt.h. The description - along with the spec - make it clear that it isn't actually 7 bits.
