### ISSUE TITLE
SUPPORTED_FS_FEATURES_QUERY_OPEN is not described

### ISSUE THREAD

**Issue by 21street** [MicrosoftDocs/windows-driver-docs-ddi#78]
The SUPPORTED_FS_FEATURES_QUERY_OPEN flag is not mentioned in description of the Type.MiniFilter.SupportedFeatures and Type.LegacyFilter.SupportedFeatures fields

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955fc6ff-c8b6-6d44-a2c1-436ce3eb0466
* Version Independent ID: 27959143-52a5-ad1f-f0d2-82f27eabddf7
* Content: [_INSTANCE_AGGREGATE_STANDARD_INFORMATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltuserstructures/ns-fltuserstructures-_instance_aggregate_standard_information)
* Content Source: [wdk-ddi-src/content/fltuserstructures/ns-fltuserstructures-_instance_aggregate_standard_information.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltuserstructures/ns-fltuserstructures-_instance_aggregate_standard_information.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Thanks @21street, I've update both topics with the information you provided. Thanks for letting us know about this!
