### ISSUE TITLE
Out of date or incorrect information

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#781]
A section of this page states "Note  This function is called only if the disconnected external display device was in hibernation mode. This is indicated by RemovalType = DxgkRemovalHibernation, the only available value."  This is not correct; the enumeration also has DxgkRemovalPnPNotify available, and I am seeing this function called with this value.
The "Return Value" section does not describe the behavior that the driver should have for this value, nor the OSes response if an error is returned, as it does for DxgkRemovalHibernation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c285b04e-31ac-6894-f29f-85963325ef3a
* Version Independent ID: 56e42ba0-179c-7d68-df8b-a28a7b47530f
* Content: [DXGKDDI_NOTIFY_SURPRISE_REMOVAL (dispmprt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dispmprt/nc-dispmprt-dxgkddi_notify_surprise_removal)
* Content Source: [wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_notify_surprise_removal.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_notify_surprise_removal.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@englishb , thanks for submitting your thoughtful issues and I apologize for my slow response. I was finally able to connect with the SME, and have updated this page significantly with technical details. Let me know if you have any further questions!
