### ISSUE TITLE
Threading and Synchronization level details

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#782]
This page states that "The operating system guarantees that [DxgkDdiQueryDependentEngineGroup] follows the first level synchronization mode as defined in Threading and Synchronization First Level."  But 1st level is split into many function classes; which class is this function a part of?  I have looked through the docs for each class, and this function is not listed under any of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31cc07fd-8814-4f44-106b-8c58ff04eb89
* Version Independent ID: 677ea812-cce8-e23f-e4b2-4820f34daf91
* Content: [DXGKDDI_QUERYDEPENDENTENGINEGROUP (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/nc-d3dkmddi-dxgkddi_querydependentenginegroup)
* Content Source: [wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_querydependentenginegroup.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/nc-d3dkmddi-dxgkddi_querydependentenginegroup.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@englishb , I've updated the "Threading and Synchronization First Level" topic to list this function (it's a GUP Scheduler class function). I also consolidated all First Level classes onto one page so that you and other readers don't have to search through several pages for the info you need. Thanks for reporting this!
