### ISSUE TITLE
Threading and synchronization level

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#783]
What is the threading and synchronization level for DxgkDdiNotifySurpriseRemoval?  It is not mentioned on this page, nor can I find this function listed on any of the pages for the individual levels linked from https://docs.microsoft.com/en-us/windows-hardware/drivers/display/threading-and-synchronization-model-of-display-miniport-driver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c285b04e-31ac-6894-f29f-85963325ef3a
* Version Independent ID: 56e42ba0-179c-7d68-df8b-a28a7b47530f
* Content: [DXGKDDI_NOTIFY_SURPRISE_REMOVAL (dispmprt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dispmprt/nc-dispmprt-dxgkddi_notify_surprise_removal)
* Content Source: [wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_notify_surprise_removal.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/dispmprt/nc-dispmprt-dxgkddi_notify_surprise_removal.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@englishb , another great catch. I've updated the page to indicate that DxgkDdiNotifySurpriseRemoval is a level zero function.
