### ISSUE TITLE
there is no hyperlink of GNSS_DEVICE_CAPABILITY

### ISSUE THREAD

**Issue by JSFamily** [MicrosoftDocs/windows-driver-docs-ddi#784]
There is no the hyperlink of GNSS_DEVICE_CAPABILITY in Output buffer section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbc82902-7e42-b905-3182-621f3158f219
* Version Independent ID: 1c1ad2cc-1937-01f3-951f-4c7f800048c6
* Content: [IOCTL_GNSS_GET_DEVICE_CAPABILITY (gnssdriver.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/gnssdriver/ni-gnssdriver-ioctl_gnss_get_device_capability#feedback)
* Content Source: [wdk-ddi-src/content/gnssdriver/ni-gnssdriver-ioctl_gnss_get_device_capability.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/gnssdriver/ni-gnssdriver-ioctl_gnss_get_device_capability.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by EliotSeattle** [comment]
Fixed in source and confirmed on live site.
Thanks!!
Eliot
