### ISSUE TITLE
there is no hyperlink of GNSS_EVENT

### ISSUE THREAD

**Issue by JSFamily** [MicrosoftDocs/windows-driver-docs-ddi#785]
There is no hyperlink of GNSS_EVENT in Output buffer section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60830c64-b814-907f-ce2a-21ced5b603a5
* Version Independent ID: ff043a76-f3fa-93d3-6b0e-545dd8ab9dc3
* Content: [IOCTL_GNSS_LISTEN_ERROR (gnssdriver.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/gnssdriver/ni-gnssdriver-ioctl_gnss_listen_error)
* Content Source: [wdk-ddi-src/content/gnssdriver/ni-gnssdriver-ioctl_gnss_listen_error.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/gnssdriver/ni-gnssdriver-ioctl_gnss_listen_error.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by EliotSeattle** [comment]
Fixed in source and confirmed on live site.
Thanks!!
Eliot
