### ISSUE TITLE
Question about FALSE return value

### ISSUE THREAD

**Issue by englishb** [MicrosoftDocs/windows-driver-docs-ddi#788]
According to the documentation, if KeRemoveQueueDPC return FALSE, then either the DPC was not in the queue (as described in the "Return Value" section) or it had started to run before it was removed (as described in the "Remarks" section).  If the DPC had started to run, will it complete?  Or is there a chance that it can be preempted and cancelled in the middle of execution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39aa5843-454d-7129-438e-905e2e9a4b8f
* Version Independent ID: d938d3aa-30ea-f228-4810-e0886428d5e4
* Content: [KeRemoveQueueDpc function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-keremovequeuedpc)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-keremovequeuedpc.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-keremovequeuedpc.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @englishb, thanks for the feedback and apologies for the delay. I think that the FALSE return value always indicates that the specified DPC object is not in the DPC queue, so it's basically a no-op.  The caveat in the ref page (that it could return TRUE even as the DPC was already running) was just on pre-Vista SP1.
