### ISSUE TITLE
SUPPORTED_FS_FEATURES_QUERY_OPEN is not described

### ISSUE THREAD

**Issue by 21street** [MicrosoftDocs/windows-driver-docs-ddi#79]
The SUPPORTED_FS_FEATURES_QUERY_OPEN flag is not mentioned as a possible output bit value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614974bc-8870-35f5-7b5b-b169b325dec3
* Version Independent ID: 40cc7a69-ab44-9b2c-75c4-09b9c0282a60
* Content: [FsRtlGetSupportedFeatures function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-fsrtlgetsupportedfeatures)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlgetsupportedfeatures.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlgetsupportedfeatures.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Thanks @21street, I've update both topics with the information you provided. Thanks for letting us know about this!
