### ISSUE TITLE
typo: 'diver' used instead of 'driver'

### ISSUE THREAD

**Issue by gokultv-private** [MicrosoftDocs/windows-driver-docs-ddi#790]
typo: 'diver' used instead of 'driver'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4362dc55-a5a4-aaac-13b5-318e6e738a00
* Version Independent ID: 892e7a6b-9d05-53f7-989b-4bb2ff36b637
* Content: [IOCTL_USB_GET_TRANSPORT_CHARACTERISTICS (usbioctl.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/usbioctl/ni-usbioctl-ioctl_usb_get_transport_characteristics#feedback)
* Content Source: [wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_transport_characteristics.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ni-usbioctl-ioctl_usb_get_transport_characteristics.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by EliotSeattle** [comment]
Oops!
Fixed and merged to live branch.
Thanks for spotting this, @gokultv-private 
Eliot
