### ISSUE TITLE
See also link is bogus "User-Mode IOCTLs for USB"

### ISSUE THREAD

**Issue by JHentges** [MicrosoftDocs/windows-driver-docs-ddi#793]
See also link is bogus "User-Mode IOCTLs for USB" goes to https://docs.microsoft.com/windows/iot-core/learn-about-hardware/hardwarecompatlist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634cb97c-d3a6-020d-e428-6c59693cdf9e
* Version Independent ID: b0956453-08ec-b873-6771-c3f6c0447c8f
* Content: [UcxIoDeviceControl function (ucxcontroller.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ucxcontroller/nf-ucxcontroller-ucxiodevicecontrol?redirectedfrom=MSDN#feedback)
* Content Source: [wdk-ddi-src/content/ucxcontroller/nf-ucxcontroller-ucxiodevicecontrol.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ucxcontroller/nf-ucxcontroller-ucxiodevicecontrol.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by EliotSeattle** [comment]
Thanks for pointing this out, @JHentges 
I've corrected the link to point to this target:
[https://docs.microsoft.com/windows-hardware/drivers/ddi/_usbref#user-mode-ioctls-sent-by-applications-and-services](https://docs.microsoft.com/windows-hardware/drivers/ddi/_usbref#user-mode-ioctls-sent-by-applications-and-services)

The content it points to and the correct link will be live shortly.
Thanks,
Eliot
