### ISSUE TITLE
When does this callback get called?

### ISSUE THREAD

**Issue by qsneeze** [MicrosoftDocs/windows-driver-docs-ddi#795]
Is the callback routine called before the image is loaded by the loader, while the loader is loading the image, or after the loader has finished loading the image, and then called the callback function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d0bfa8-68c2-0594-eaf3-8a77d4404157
* Version Independent ID: c8e2634a-a965-fb18-e68f-07b6682605ae
* Content: [PLOAD_IMAGE_NOTIFY_ROUTINE (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nc-ntddk-pload_image_notify_routine#feedback)
* Content Source: [wdk-ddi-src/content/ntddk/nc-ntddk-pload_image_notify_routine.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nc-ntddk-pload_image_notify_routine.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @qsneeze, the callback is called after the image is mapped into memory, but before the image’s entry point is invoked.  If you feel this info might be useful in the doc page, please feel free to submit a PR.  To get started, just click **Edit** in the upper right of the page on docs.microsoft.com.
