### ISSUE TITLE
The link to MmGetSystemAddressForMdlSafe is not working

### ISSUE THREAD

**Issue by wangxfdu** [MicrosoftDocs/windows-driver-docs-ddi#797]
att

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8215d69a-ba86-a545-b663-fee5d770118b
* Version Independent ID: d976c430-3738-daed-9d82-15da165a01a3
* Content: [MmGetSystemAddressForMdl macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-mmgetsystemaddressformdl)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmgetsystemaddressformdl.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmgetsystemaddressformdl.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Sorry, I don't see any feedback above.  Please reopen if it was omitted in error.
