### ISSUE TITLE
When (in which condition) will GNSS adapter call IOCTL_GNSS_LISTEN_AGNSS?

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs-ddi#798]
I want to understand whether IOCTL_GNSS_LISTEN_AGNSS is initiated by GNSS adapter itself or is triggered by a user mode Application, e.g. LBS application, through Location Service.

If it is triggered by user mode application, which API should be called?

If it is only initiated by GNSS adapter (or Location Service), in which condition or situation, it will be called?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 545816c1-9cd4-e1b5-6923-c1459c8a4ba4
* Version Independent ID: 2e931a3a-5467-923f-62a4-e8c4e8e90d64
* Content: [IOCTL_GNSS_LISTEN_AGNSS (gnssdriver.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/gnssdriver/ni-gnssdriver-ioctl_gnss_listen_agnss)
* Content Source: [wdk-ddi-src/content/gnssdriver/ni-gnssdriver-ioctl_gnss_listen_agnss.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/gnssdriver/ni-gnssdriver-ioctl_gnss_listen_agnss.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. 

You may have success posting your question (about whether IOCTL_GNSS_LISTEN_AGNSS is initiated by a GNSS adapter or is triggered by a user mode application) in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/products/windows#hardware-and-application-developers)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
