### ISSUE TITLE
Page missing links

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#799]
This page is missing links to the various pages describing the different storage property IDs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d627413-60dd-9226-ee79-1b8ea234c179
* Version Independent ID: ff32a5d1-0182-93bd-c75d-6fd9d9605ccf
* Content: [STORAGE_PROPERTY_ID - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddstor/ne-ntddstor-storage_property_id#feedback)
* Content Source: [wdk-ddi-src/content/ntddstor/ne-ntddstor-storage_property_id.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddstor/ne-ntddstor-storage_property_id.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by lorihollasch** [comment]
@csm10495 , thank you for reporting the missing information. My apologies for the slow response, but I just finally found some cycles to get this page updated. Appreciate your issues and desire to make the docs better - thank you.
