### ISSUE TITLE
Bad link in initial description sentence.

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#80]
"The ZwMapViewOfSection routine maps a view of a section into the virtual address space of a subject process."

The link on the word "view" in the above sentence goes to a completely unrelated topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3ee14b8-7fe3-d780-6166-6587076199ef
* Version Independent ID: e9beb1a4-8c89-f40f-ff5d-7e0d4b37e002
* Content: [ZwMapViewOfSection function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwmapviewofsection)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwmapviewofsection.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwmapviewofsection.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
@BenWestbrook, thanks for catching that. It's fixed. Should be live soon.

**Comment by GabeSJones** [comment]
Apparently it was fixed by removing the word "view" entirely:

"The ZwMapViewOfSection routine maps a of a section"

**Comment by EliotSeattle** [comment]
Ooops. Thanks, @GabeSJones. The word is back, minus the link.
