### ISSUE TITLE
Link 404s

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs-ddi#800]
This link: https://docs.microsoft.com/windows-hardware/drivers/ddi/ntddstor/ns-ntddstor-ioctl_storage_get_device_number_ex

Is 404ing. Replace with correct link. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a46d069-1bad-6d4a-d8c3-54cbd6186b50
* Version Independent ID: bcbd5b7c-994f-ce16-06bb-8ea32cb2ed39
* Content: [IOCTL_STORAGE_GET_DEVICE_NUMBER (ntddstor.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddstor/ni-ntddstor-ioctl_storage_get_device_number)
* Content Source: [wdk-ddi-src/content/ntddstor/ni-ntddstor-ioctl_storage_get_device_number.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddstor/ni-ntddstor-ioctl_storage_get_device_number.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@csm10495 , the broken link is now fixed - thanks for reporting it!
