### ISSUE TITLE
TargetFileObject clarification

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#801]
It should be clarified if TargetFileObject is the same as FltObjects-&gt;FileObject during the same Pre/PostOp callback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b3e6aa0-8301-5b6e-c38b-dc3b31a1a0e7
* Version Independent ID: 8a3a371c-9349-0f01-2c3d-dc1681f0227e
* Content: [_FLT_IO_PARAMETER_BLOCK (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/ns-fltkernel-_flt_io_parameter_block)
* Content Source: [wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_io_parameter_block.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_io_parameter_block.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@alfaunits , I've added the clarification that you asked for!
