### ISSUE TITLE
FLT_FILE_NAME_ALLOW_QUERY_ON_REPARSE

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#802]
This flag appears not be applicable to this API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a380ed8e-cd20-fa24-230c-0b7da7ff4f3b
* Version Independent ID: 21149e9f-6321-4afa-50ff-233fa3cb804e
* Content: [FltGetDestinationFileNameInformation function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetdestinationfilenameinformation)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetdestinationfilenameinformation.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetdestinationfilenameinformation.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@alfaunits , good catch on the nonrelevance of FLT_FILE_NAME_ALLOW_QUERY_ON_REPARSE, thanks! I've updated the page with an explanation.
