### ISSUE TITLE
How to unmap this mdl?

### ISSUE THREAD

**Issue by AzAgarampur** [MicrosoftDocs/windows-driver-docs-ddi#804]
Other functions like MmMapLockedPagesSpecifyCache have MmUnmapLockedPages as a function to unmap the pages. Since this function is new, is there another routine to unmap the mdl after it has been mapped by MmMapMdl?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce647767-1e84-d092-a555-7392b3b75aff
* Version Independent ID: 47b407cb-ae17-5d7e-c2dd-2f05e12aacee
* Content: [MmMapMdl function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-mmmapmdl#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmmapmdl.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmmapmdl.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @AzAgarampur, thanks for the question and apologies for the delay.  I just added the following remark to the doc page (it should be live momentarily):

**MmMapMdl** maps the MDL (if it's not already mapped), invokes the callback, then releases the mapping (if one was created). The caller does not need to perform any cleanup.
