### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by imtiazdc** [MicrosoftDocs/windows-driver-docs-ddi#805]
StorPortInitilize --&gt; You may want to fix the typos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e290fc-6386-21b8-0af3-242acb582a8e
* Version Independent ID: 249f0dd4-053f-e9e0-e0a7-ba8a2308a4af
* Content: [StorPortInitialize function (storport.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/storport/nf-storport-storportinitialize#feedback)
* Content Source: [wdk-ddi-src/content/storport/nf-storport-storportinitialize.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/storport/nf-storport-storportinitialize.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for catching this, @imtiazdc  - I have fixed the typos!
