### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by chcurlet-msft** [MicrosoftDocs/windows-driver-docs-ddi#806]
[InterfaceDereference]nc-wdm-pinterface_dereference.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ddc744-0ffe-91e3-a63a-bd2d271d3bdb
* Version Independent ID: da3ab3dd-daa8-9b36-acc3-35c51be8d1bb
* Content: [_D3COLD_AUX_POWER_AND_TIMING_INTERFACE (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_d3cold_aux_power_and_timing_interface#feedback)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_d3cold_aux_power_and_timing_interface.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_d3cold_aux_power_and_timing_interface.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Thanks, @chcurlet-msft 
Fixed and merged to master. Should be live shortly.
