### ISSUE TITLE
STATUS_NOT_SAME_DEVICE is not a documented error code for this API

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#807]
and yet it can occur quite often, e.g. when a symbolic link/mountpoint resolves to a different volume (the API will not attempt to resolve it, but will return STATUS_NOT_SAME_DEVICE).

I currently have a list of over 60 cases where FltGetFileNameInformation does not work, or does not work at least on earlier OSes (XP the most, Server 2008 and Vista next, and some Windows 7/8 - Windows 10 is mostly untested still).
I have to have case code for all those 60 cases, to handle getting the file name myself :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3791685f-ae6e-06d3-d42b-07f498a5e36a
* Version Independent ID: 254f85ed-231d-c3e4-db43-fd13d8150db1
* Content: [FltGetFileNameInformation function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltgetfilenameinformation#feedback)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetfilenameinformation.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltgetfilenameinformation.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@alfaunits , thanks for your feedback (and sorry for your pain). I've added the status code with an explanation.
