### ISSUE TITLE
No data type information on this page

### ISSUE THREAD

**Issue by cmusta** [MicrosoftDocs/windows-driver-docs-ddi#810]
There are no data types associated with these constants.  One needs to know the data type in order to extract if correctly from the ClassifyValues, incomingValue structure.  If they are not referenced in the sample code, one has to write debug code to view them and make adjustments.  That's a pain for someone new to the interface.

There is also no definition what the new FWPS_FIELD_OUTBOUND_MAC_FRAME_ETHERNET_COMPARTMENT_ID is or what it is used for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5b4424e-ff2b-9bf1-c058-49d57e48de28
* Version Independent ID: 8e5735eb-a637-3045-f7bb-16b33a89ffa8
* Content: [FWPS_FIELDS_OUTBOUND_MAC_FRAME_ETHERNET_ (fwpsk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ne-fwpsk-fwps_fields_outbound_mac_frame_ethernet_#see-also)
* Content Source: [wdk-ddi-src/content/fwpsk/ne-fwpsk-fwps_fields_outbound_mac_frame_ethernet_.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fwpsk/ne-fwpsk-fwps_fields_outbound_mac_frame_ethernet_.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Hi @cmusta, 

Thanks for the feedback and apologies for the delay.  I just pushed the above commit to address your question.  Note that the enum renders as expected for me, i.e. it matches the layout in the `fwpsk.h` header file.
