### ISSUE TITLE
FwpsAcquireWritableLayerDataPointer rights assignment is incorrect

### ISSUE THREAD

**Issue by john-soklaski** [MicrosoftDocs/windows-driver-docs-ddi#818]
In the "Remarks" section under "FwpsAcquireWritableLayerDataPointer0 sets the following members of the FWPS_CLASSIFY_OUT0 structure:", I believe `classifyOut->rights = ~FWPS_RIGHT_ACTION_WRITE` should be `classifyOut->rights &= ~FWPS_RIGHT_ACTION_WRITE`

The intent is to remove the `FWPS_RIGHT_ACTION_WRITE` bit, not to set all other bits. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f785ce7-f52d-981f-c2be-7354673580a1
* Version Independent ID: ea09174d-9bb8-815c-880f-245de5ac549d
* Content: [FwpsAcquireWritableLayerDataPointer0 function (fwpsk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/nf-fwpsk-fwpsacquirewritablelayerdatapointer0#feedback)
* Content Source: [wdk-ddi-src/content/fwpsk/nf-fwpsk-fwpsacquirewritablelayerdatapointer0.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fwpsk/nf-fwpsk-fwpsacquirewritablelayerdatapointer0.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Thanks for the sharp eye @john-soklaski, and apologies for the delay.  I just pushed the fix.
