### ISSUE TITLE
Is Device Extension uninitialized?

### ISSUE THREAD

**Issue by OZ1** [MicrosoftDocs/windows-driver-docs-ddi#819]
Please state explicitly whether the allocated device extension is uninitialized or zeroed. (for an example, see https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepoolwithtag)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3fcb78-63b5-8f9b-cb81-3fef485c3417
* Version Independent ID: 6a28639d-1a75-b02c-8e72-93377b2dc3ee
* Content: [IoCreateDevice function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iocreatedevice#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iocreatedevice.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iocreatedevice.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @OZ1, thanks for the question and apologies for the delay.  I've just added the following to the doc page (should be live momentarily):

The device extension of the device object is zeroed.
