### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs-ddi#824]
"To retrieve information about the volume associated with a given file, directory, or storage device, see FltQueryVolumeInformation".
The API should be ZwQueryVolumeInformationFile here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf0a7bb-5f75-bb4e-194d-c5ea23cb74b6
* Version Independent ID: 533b061d-9b48-d2fc-a9d0-cd53a7c95b85
* Content: [FsRtlAreVolumeStartupApplicationsComplete function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-fsrtlarevolumestartupapplicationscomplete)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlarevolumestartupapplicationscomplete.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlarevolumestartupapplicationscomplete.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@alfaunits , thanks for catching the typo - it is now fixed!
