### ISSUE TITLE
Boilerplate / tautological / useless documentation

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#825]
> **Parameters**
> 
> *pInArgs*
> 
> Input arguments used by EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION.
> 
> *pOutArgs*
> 
> Output arguments generated by EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION.
> 
> **Return value**
> 
> (NTSTATUS) If the operation is successful, the callback function must return STATUS_SUCCESS, or another status value for which NT_SUCCESS(status) equals TRUE. Otherwise, an appropriate NTSTATUS error code.

Looks like this was auto-generated and hasn't been looked over by anyone yet? There's no real information here that couldn't be deduced from the function signature, i.e., to paraphrase:

> The input arguments are the arguments the function uses as input, and the output arguments are the arguments the function generates as output. The return value is STATUS_SUCCESS if things succeeded, otherwise it's an appropriate error code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2e938c-9389-1aaa-4f66-f5167ebd0316
* Version Independent ID: 8083cd68-1e08-3b4c-93e8-da836a024e1c
* Content: [EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION (iddcx.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/iddcx/nc-iddcx-evt_idd_cx_parse_monitor_description)
* Content Source: [wdk-ddi-src/content/iddcx/nc-iddcx-evt_idd_cx_parse_monitor_description.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/iddcx/nc-iddcx-evt_idd_cx_parse_monitor_description.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting the lack of info on this page, @mr-intj . I've updated it with parameter descriptions and links to relevant structures.
