### ISSUE TITLE
ECP list can be changed on return

### ISSUE THREAD

**Issue by PisarevSergey** [MicrosoftDocs/windows-driver-docs-ddi#827]
It is said “Upon returning from the call of FltCreateFileEx2, the ECP list is unchanged”.
However fs filter can remove ecp from this list during irp_mj_create dispatching with FltRemoveExtraCreateParameter function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836407ad-5c84-5483-38bc-7f4e51c45546
* Version Independent ID: 450273c2-0c28-8f9f-7cd1-55435d733a29
* Content: [FltCreateFileEx2 function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltcreatefileex2)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcreatefileex2.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcreatefileex2.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@PisarevSergey , thanks for the issue - sorry for the slow response. I added some details that should clarify.
