### ISSUE TITLE
The sequence of UsagePage and Usage is incorrect

### ISSUE THREAD

**Issue by petercoin** [MicrosoftDocs/windows-driver-docs-ddi#828]
Using this structure with the sequence on this page in C# through DllImport causes the HidP_GetCaps fills in the wrong value for UsagePage and Usage. The correct sequence should be Usage then UsagePage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c659f9ab-41d9-1898-439e-7d4eae1a3cab
* Version Independent ID: 5f131874-7fa6-f239-d726-3facd3f36dda
* Content: [_HIDP_CAPS (hidpi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/ns-hidpi-_hidp_caps)
* Content Source: [wdk-ddi-src/content/hidpi/ns-hidpi-_hidp_caps.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/hidpi/ns-hidpi-_hidp_caps.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Thanks for the feedback and apologies for the delay.  When I look at the page in question, the syntax block shows Usage and then UsagePage. So maybe this was fixed in the interim? If not, please reopen and let me know specifically what you would like to change.  Thank you!
