### ISSUE TITLE
Function limitations aren't clear

### ISSUE THREAD

**Issue by reuvenab** [MicrosoftDocs/windows-driver-docs-ddi#829]
Documentation has 2 slightly confusing sentences: 

1) The KeQueryDpcWatchdogInformation routine **can** be called from a DPC routine **or** at an IRQL= DISPATCH_LEVEL

One could conclude that function could be called or from DPC routine or from another code that is running at DISPATCH level 

2) KeQueryDpcWatchdogInformation **must** be called while a DPC is running or invoked at an IRQL= DISPATCH_LEVEL or higher on the current processor. 

This one says that function could be called from DPC only

Could you elaborate on the issue please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136bf0cf-fd1f-4994-0ddb-9b5629d5d712
* Version Independent ID: 3a9de5b4-092b-7bf6-cd1c-b3d7ce9b9703
* Content: [KeQueryDpcWatchdogInformation function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kequerydpcwatchdoginformation?redirectedfrom=MSDN)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-kequerydpcwatchdoginformation.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-kequerydpcwatchdoginformation.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @reuvenab, thanks for the question and apologies for the delay. The docs are correct here.  Both statements that you include above use **or**, which is right.  Call the routine either from a DPC **or** at IRQL=DISPATCH_LEVEL or higher.  Hope this helps!
