### ISSUE TITLE
parameter clarification

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#83]
HighestAcceptableAddress does not specify a "just give me some memory, I don't care where it is" value. And as you know, assumptions always cause problems...otherwise I would just assume (PHYSICAL_ADDRESS)-1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6cf2130-c0be-e132-fc94-2ef50232d726
* Version Independent ID: 835e70c0-df21-56a9-60db-52c9fedd167a
* Content: [MmAllocateContiguousMemory function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmallocatecontiguousmemory)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmallocatecontiguousmemory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmallocatecontiguousmemory.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello,

Thanks for pointing out the missing information. The Windows Kernel team suggests setting to MAXULONG64. I have updated the description.

PageWriter
