### ISSUE TITLE
Incorrect MEM_WRITE_WATCH description

### ISSUE THREAD

**Issue by aeikum** [MicrosoftDocs/windows-driver-docs-ddi#830]
The description for MEM_WRITE_WATCH is incorrect. It seems to be copied from MEM_TOP_DOWN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2abc2bc3-80b2-7837-a292-6a438159fc95
* Version Independent ID: d5192069-ddd6-db55-f25c-8de363f0f26f
* Content: [NtAllocateVirtualMemory function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntallocatevirtualmemory#feedback)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ntallocatevirtualmemory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ntallocatevirtualmemory.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@aeikum, thanks for reporting this. I've updated the page to document the main flags, and included a link to VirtualAlloc where the other, less used flags are described.
