### ISSUE TITLE
IPreFetchOffset

### ISSUE THREAD

**Issue by lvliang0414** [MicrosoftDocs/windows-driver-docs-ddi#833]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a98f14f-2659-76e4-49af-0d74d28a4b8c
* Version Independent ID: 6f9953e2-18f6-34c6-b582-5e0b55eb6a9b
* Content: [IPreFetchOffset::SetPreFetchOffset (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nf-portcls-iprefetchoffset-setprefetchoffset)
* Content Source: [wdk-ddi-src/content/portcls/nf-portcls-iprefetchoffset-setprefetchoffset.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nf-portcls-iprefetchoffset-setprefetchoffset.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@lvliang0414 - I don't see any feedback in this issue, so closing. Let us know if you see something we need to work on in the audio reference documentation.
