### ISSUE TITLE
404 - Page not found

### ISSUE THREAD

**Issue by sadhermit** [MicrosoftDocs/windows-driver-docs-ddi#835]
Hello, Microsoft!
The description of the EventDescriptor parameter on the current page leads to a page with code 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b0f3f0-3494-0486-21d2-92b069e6b377
* Version Independent ID: 149834a5-38db-7c6e-c66e-13bd514d7d72
* Content: [EtwWrite function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-etwwrite#feedback)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-etwwrite.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-etwwrite.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Thanks, @sadhermit for finding this.
Made the quick fix and pushed to master branch. Should show up in live shortly.
Appreciate the feedback.
Eliot
