### ISSUE TITLE
XML doc error in iddCx.h

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#839]
Not sure where to report this, so hopefully you can pass it along.

There is an error in the iddCx.h header file that interferes with Intellisense:
```
enum IDDCX_MONITOR_DESCRIPTION_TYPE : UINT
{
    IDDCX_MONITOR_DESCRIPTION_TYPE_UNINITIALIZED = 0,
    /// <summary>
    /// The monitor description is EDID or no EDID description available
    /// If the monitor has no description then IDDCX_MONITOR_DESCRIPTION_TYPE_EDID shall be used with zero description size
    /// and null pointer for data</summary>
    /// </summary>
```

Note the extra closing "summary" tag.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e513c434-165e-53ee-d4bc-ff3197adab18
* Version Independent ID: 0b3a7ddd-ea41-ec9b-dafc-18ddbcf1ca1a
* Content: [IDDCX_MONITOR_DESCRIPTION_TYPE (iddcx.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/iddcx/ne-iddcx-iddcx_monitor_description_type)
* Content Source: [wdk-ddi-src/content/iddcx/ne-iddcx-iddcx_monitor_description_type.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/iddcx/ne-iddcx-iddcx_monitor_description_type.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @mr-intj ! We have filed an internal bug - it is on the dev team's radar to get this fixed for IddCx 1.7.
