### ISSUE TITLE
Remarks link in second paragraph is incorrect

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs-ddi#843]
The link target is a generic documents page rather than the #remarks section on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce4c926-b13e-babe-eb77-5f495e149c2c
* Version Independent ID: 77169674-fe2a-ccf0-4c35-ec05469f5950
* Content: [KdPrint macro (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kdprint)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-kdprint.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-kdprint.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Thanks once more, @druske 
Removed the link and replaced with "see below" language, then did some more housekeeping for formatting and the like. I've created the PR. It should be approved and pushed live later today, unless I inserted some simple error, in which case it'll go live when I fix *that*.
Thanks again for your feedback on the docs. Oh, and cute dog!
Eliot
Cc: @tedhudek
