### ISSUE TITLE
wrong return value type

### ISSUE THREAD

**Issue by PisarevSergey** [MicrosoftDocs/windows-driver-docs-ddi#846]
this macro actually returns NTSTATUS and not void.
this is correctly stated in remarks, but not in definition:

void WppRecorderLogCreate(
   CreateParams,
   RecorderLog
);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3dc5e3-78ae-f982-f815-d03a668ae999
* Version Independent ID: 998ba0e9-522e-ca9f-5ec2-ff1f7d58b145
* Content: [WppRecorderLogCreate macro (wpprecorder.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wpprecorder/nf-wpprecorder-wpprecorderlogcreate)
* Content Source: [wdk-ddi-src/content/wpprecorder/nf-wpprecorder-wpprecorderlogcreate.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wpprecorder/nf-wpprecorder-wpprecorderlogcreate.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks for spotting this, @PisarevSergey 
I've overridden the automatically added (and wrong) syntax block with one that contains the NTSTATUS return value. It's been checked in and merged to our master branch and will be mirrored to the Live branch overnight.
Thanks so much,
Eliot
