### ISSUE TITLE
The POOL_FLAGS link is broken.

### ISSUE THREAD

**Issue by AzAgarampur** [MicrosoftDocs/windows-driver-docs-ddi#852]
The hyperlink that is supposed to redirect to the page containing information about the POOL_FLAGS enum is broken. This is probably because W10 version 2004 is still really new and this documentation just came out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4088c928-a19e-b223-3f6f-503e8c7f459e
* Version Independent ID: 9f39cccc-fcb4-7ea0-b915-95497671100b
* Content: [ExAllocatePool2 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool2)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exallocatepool2.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exallocatepool2.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Fixed! Please try again.  Thanks for the report!
