### ISSUE TITLE
not searchable in Help Viewer by index

### ISSUE THREAD

**Issue by PisarevSergey** [MicrosoftDocs/windows-driver-docs-ddi#855]
Present in offline help (Help Viewer 2.3 for Visual Studio 2019) but not searchable in index. Can be found through search tab.

<img width="1730" alt="Screenshot 2020-06-12 at 04 22 34" src="https://user-images.githubusercontent.com/11599134/84455147-3e975180-ac65-11ea-8311-7bcffd501ea5.png">

<img width="1727" alt="Screenshot 2020-06-12 at 04 25 14" src="https://user-images.githubusercontent.com/11599134/84455175-4f47c780-ac65-11ea-8418-9051c0ff361b.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a39b4d45-43aa-5a0c-9a37-fb0e32beb698
* Version Independent ID: 6d767c49-f9e4-2fe1-68b6-c3d24fe61ee9
* Content: [_FLT_CALLBACK_DATA (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/ns-fltkernel-_flt_callback_data)
* Content Source: [wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_callback_data.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_callback_data.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@PisarevSergey , the offline books were updated in June. Are you still seeing this issue?

**Comment by lorihollasch** [comment]
Closing this as I believe this issue was fixed. @PisarevSergey , let me know if this is still an issue for you, thanks.

**Comment by PisarevSergey** [comment]
Unfortunately the problem still persists. I have freshly installed windows, so everything is definitely up to date

**Comment by tedhudek** [comment]
It is actually in the index, but it has an underscore prepended. So the index entry is `_FLT_CALLBACK_DATA`.  The front of the index has all of the entries starting with underscore.

**Comment by lorihollasch** [comment]
I just removed and then re-added the WDK books under "Manage Content", and got notification of several updated during the Add. I can now discover _FLT_CALLBACK_DATA in an Index search as Ted indicates.

**Comment by PisarevSergey** [comment]
I understand that documentation automatically generated from include file(correct me if I’m wrong).
So I can see why _FLT_CALLBACK_DATA considered a correct spelling since this is “true” name of the type.
However non-underscore version actually used. Always. 
Such typedef is a classic C trick so that you don’t need to prepend type name with struct and just use name itself.

Maybe index generating algorithm can be changed ?

**Comment by tedhudek** [comment]
Working on it :)

**Comment by tedhudek** [comment]
Ok Sergey, I just updated the WDK ref book.  I tested it and `FLT_CALLBACK_DATA` now appears under F in the index.

Please remove it from your Help Viewer and then add it again to download the most recent.

**Comment by PisarevSergey** [comment]
Thank you !
Works perfectly after update.
Didn’t even need to remove book explicitly
