### ISSUE TITLE
Link in Help Viewer leads to online resource and not local

### ISSUE THREAD

**Issue by PisarevSergey** [MicrosoftDocs/windows-driver-docs-ddi#856]
Link in Help Viewer 2.3 for Visual Studio 2019 point to online MSDN library even though topic present in offline help

<img width="1727" alt="Screenshot 2020-06-12 at 04 33 20" src="https://user-images.githubusercontent.com/11599134/84455613-6c30ca80-ac66-11ea-8e38-f2b4fb980b37.png">

Should lead to this offline help

<img width="1726" alt="Screenshot 2020-06-12 at 04 35 57" src="https://user-images.githubusercontent.com/11599134/84455626-7357d880-ac66-11ea-9d7d-2b6d04e447a0.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4209424c-ef49-d9c7-7183-5049a6fa4a92
* Version Independent ID: 185422d4-4b0b-1a4a-944e-b1c7e40e8354
* Content: [_FLT_PARAMETERS (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/ns-fltkernel-_flt_parameters)
* Content Source: [wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_parameters.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_parameters.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@PisarevSergey , thanks for reporting this. I'm afraid that we don't have a quick and easy fix for cross-book linking. Our tools team is aware and is considering various options for offline books. Until then, I apologize for the inconvenience!
