### ISSUE TITLE
Exact failure semantcs need to be stated

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#858]
The phrase 

> KeExpandKernelStackAndCallout returns STATUS_SUCCESS if the operation succeeds or an appropriate NTSTATUS value if the operation fails.

Could be tightened up.  You'll need a dev to tell you what the precise semantics are but my hope would be that adding the following would not be incorrect

> If a failure status is returned then `Callout` has not bee called.  If STATUS_SUCCESS is returned then `Callout` has been called.

It might also be cool to have some words about whether anything special needs to be done about Event handling - ISTR that `Calloit` has to catch exceptions and then the calling code can resignal but my memories are vague.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ad3b97d-fac8-9f5a-9f6d-a49818f2944a
* Version Independent ID: 796528a1-d67e-449d-9077-35cf6b2de0c9
* Content: [KeExpandKernelStackAndCallout function (ntddk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-keexpandkernelstackandcallout)
* Content Source: [wdk-ddi-src/content/ntddk/nf-ntddk-keexpandkernelstackandcallout.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddk/nf-ntddk-keexpandkernelstackandcallout.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Good call, your proposed text for the return value is accurate. I've updated the doc page, should be live within the hour. Re: exception handling, if you click the *ExpandedStackCall* link on https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-keexpandkernelstackandcallout, it takes you to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nc-ntddk-expand_stack_callout, which does address the exceptions question in the Remarks.
