### ISSUE TITLE
POOL_RAISE_IF_ALLOCATION_FAILURE vs. POOL_QUOTA_FAIL_INSTEAD_OF_RAISE in ExAllocatePoolQuotaZero

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-driver-docs-ddi#871]
The documentation of the `PoolType` parameter of **ExAllocatePoolQuotaZero** implies that running out of memory _does not cause_ an exception by default:

> You can modify the enumeration value by performing a bitwise-OR with the **POOL_RAISE_IF_ALLOCATION_FAILURE** flag defined in `wdm.h`. This flag causes an exception to be raised if the request cannot be satisfied. Use of this flag is not recommended because it is costly.

However, the documentation of the return value says that running out of memory _causes_ an exception by default:

> If the request cannot be satisfied, **ExAllocatePoolQuotaZero** raises an exception unless POOL_QUOTA_FAIL_INSTEAD_OF_RAISE is specified. Using POOL_QUOTA_FAIL_INSTEAD_OF_RAISE is preferred for performance reasons.

Surely these cannot both be right. The documentation of [ExAllocatePoolQuotaUninitialized](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepoolquotauninitialized) has the same problem.

(In contrast, the documentation of [ExAllocatePoolPriorityZero](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepoolpriorityzero) and [ExAllocatePoolPriorityUninitialized](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepoolpriorityuninitialized) is clear that these two functions care about **POOL_RAISE_IF_ALLOCATION_FAILURE** and not **POOL_QUOTA_FAIL_INSTEAD_OF_RAISE**.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f3dd824-40ab-40d0-9d3c-c53838c46197
* Version Independent ID: 8031e81a-492b-141c-9235-73a7739edfdd
* Content: [ExAllocatePoolQuotaZero - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepoolquotazero)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exallocatepoolquotazero.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exallocatepoolquotazero.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @KalleOlaviNiemitalo, thanks for bringing this to our attention. You are right - POOL_RAISE_IF_ALLOCATION_FAILURE is not a valid flag to pass ExAllocatePoolQuotaZero or ExAllocatePoolQuotaUninitialized.  I just merged the change and it should appear on the live site within half an hour.
