### ISSUE TITLE
[!ALERT] isn't rendered as a color block

### ISSUE THREAD

**Issue by NextTurn** [MicrosoftDocs/windows-driver-docs-ddi#875]
https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/57ce491f8497f100ee817203313a23b3c286e8d6/wdk-ddi-src/content/wdm/nf-wdm-iocreatedevice.md#L65-L66

AFAIK there are 5 kinds of alerts: https://docs.microsoft.com/contribute/markdown-reference#alerts-note-tip-important-caution-warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3fcb78-63b5-8f9b-cb81-3fef485c3417
* Version Independent ID: 6a28639d-1a75-b02c-8e72-93377b2dc3ee
* Content: [IoCreateDevice function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iocreatedevice?redirectedfrom=MSDN)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iocreatedevice.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iocreatedevice.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Looks like [!ALERT] is not one of them! Just pushed a fix, should be live within the hour.  Thanks for the report!
