### ISSUE TITLE
InstanceSetupCallback description

### ISSUE THREAD

**Issue by 21street** [MicrosoftDocs/windows-driver-docs-ddi#88]
There's no comment "If a NULL is specified for this routine, the attachment is always made".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 020480f3-b724-f282-cce8-43d7cde038d2
* Version Independent ID: 84eeb4e3-4d88-862c-276e-7496c0f35f9b
* Content: [_FLT_REGISTRATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/fltkernel/ns-fltkernel-_flt_registration)
* Content Source: [wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_registration.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/ns-fltkernel-_flt_registration.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
hi @21street, I'll add this to the topic and have it visible shortly! Thanks!
