### ISSUE TITLE
Vanished from Help Viewer 2.3

### ISSUE THREAD

**Issue by PisarevSergey** [MicrosoftDocs/windows-driver-docs-ddi#882]
After recent updates vanished from offline help
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f30189f-18df-1474-4bd0-84dfa6f73e22
* Version Independent ID: beb5b914-9f72-e25b-7c3f-3b47bb5973eb
* Content: [ZwCreateFile function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwcreatefile)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwcreatefile.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwcreatefile.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
AFAIK we haven't republished the offline books yet.  Can you provide detail on how you updated your offline books and what you're seeing? Sorry this hasn't been the smoothest path

**Comment by PisarevSergey** [comment]
This is my installed books:

<img width="1727" alt="Screenshot 2020-06-24 at 02 19 57" src="https://user-images.githubusercontent.com/11599134/85476629-6d94b800-b5c1-11ea-8fce-ce827c29c166.png">


ZwCreateFile topic cannot be found through both Index and Search tabs

**Comment by tedhudek** [comment]
I'm tracking this issue separately with the team that manages our offline books, so closing this out.  Appreciate the report

**Comment by tedhudek** [comment]
Just pushed a fix for this btw Sergey - will need to rebuild offline books for you to see the fix

**Comment by PisarevSergey** [comment]
Thank you

**Comment by tedhudek** [comment]
Update - I just updated the "Windows Driver Kit(WDK)" offline book.  Note- I have not yet updated the WDK ref book.  Let me know if it looks as expected for you

**Comment by PisarevSergey** [comment]
Have installed documentation update. Still no zwcreatefile topic in help viewer - this is expected since ref book not updated, right ?
Otherwise everything looks the same

**Comment by tedhudek** [comment]
Right.  The top node should have what's new for Win10 v 2004

**Comment by tedhudek** [comment]
I just pushed the new ref book. Try removing the one you have, re-adding from online, and then search for ZwCreateKey.  It's back!

It's a known issue that there are duplicate index entries for many pages.  This is because of the TOC behavior described at https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/

**Comment by PisarevSergey** [comment]
Didn't remove the old book, just installed the update. 
ZwCreateFile now searchable through Search and Index tabs.

Is it actually required/ recommended to remove old book before update ?

**Comment by tedhudek** [comment]
I think you might get two copies of each page if you have two versions of the same book installed.  But if it works for you, then it's good :)

**Comment by PisarevSergey** [comment]
I removed and reinstalled all documentation. 
Looks the same so far. 
I'm getting one result for ZwCreateFile in Index, but 2 results in Search - both point to the same page.
But I guess this is not a big problem, I almost exclusively use Index and very rarely Search.
