### ISSUE TITLE
IoConnectInterrupt function: Missing return values 

### ISSUE THREAD

**Issue by xiaoyinl** [MicrosoftDocs/windows-driver-docs-ddi#883]
The "Returns" section doesn't specify what NTSTATUS values this function can return.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08160025-8f95-c7a7-ae54-30c7865f75ee
* Version Independent ID: 3d353f9e-86d0-e50c-73ec-113628c0b4d6
* Content: [IoConnectInterrupt function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-ioconnectinterrupt)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-ioconnectinterrupt.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-ioconnectinterrupt.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the report @xiaoyinl, I've just pushed the fix, should be live within the hour.

**STATUS_SUCCESS**

**STATUS_INVALID_PARAMETER**: No processors were specified.

**STATUS_INSUFFICIENT_RESOURCES**: There was not enough nonpaged pool.
