### ISSUE TITLE
Ownership of memory allocated for  localRedirectContext

### ISSUE THREAD

**Issue by gyani84** [MicrosoftDocs/windows-driver-docs-ddi#886]
[Enter feedback here]
Hi, 
As per comment, from windows 8 onwards, wfp takes ownership of memory allocated by driver for localRedirectContext. Does that means driver don’t have to take care of freeing this memory. Will it be not catch by driver verifier??

I tried it on win10 and dv complains about memory leak. Is there any workaround for this?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a094452f-3181-c5c2-72a2-4ee16e5fc13e
* Version Independent ID: 2d8f6130-7df5-00a6-10bf-85883a7f9141
* Content: [_FWPS_CONNECT_REQUEST0 (fwpsk.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fwpsk/ns-fwpsk-_fwps_connect_request0)
* Content Source: [wdk-ddi-src/content/fwpsk/ns-fwpsk-_fwps_connect_request0.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fwpsk/ns-fwpsk-_fwps_connect_request0.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks @gyani84 for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don't have the resources to offer individual technical advice to the broad array of customers who use the driver documentation. You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The communities are quite responsive. If you learn anything on the forums you'd like to add to the docs, let us know or you can open a PR. 
[Windows Hardware WDK and driver development forum] (https://social.msdn.microsoft.com/Forums/windowshardware/en-US/home?forum=wdk)
[OSR NTDEV forum] (https://community.osr.com/categories/ntdev)
Again, thanks for reaching out. Best of luck with this issue.
