### ISSUE TITLE
"EX_POOL_PRIORITY" link leads to 404

### ISSUE THREAD

**Issue by justanotheranonymoususer** [MicrosoftDocs/windows-driver-docs-ddi#887]
"EX_POOL_PRIORITY" link leads to 404 - https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ne-wdm-ex_pool_priority

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2331e6e-738c-b279-c317-10aa824f9140
* Version Independent ID: e93e6587-4d50-c9c5-a99e-6d0dacd9d9cf
* Content: [ExAllocatePoolPriorityZero - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepoolpriorityzero)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-exallocatepoolpriorityzero.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-exallocatepoolpriorityzero.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Added!  Thanks for the heads-up.
