### ISSUE TITLE
Invalid EventType flag for ZwCreateEvent

### ISSUE THREAD

**Issue by dmex** [MicrosoftDocs/windows-driver-docs-ddi#891]
The documentation mentions a modifier flag for the EventType parameter:
```The event type can be modified with the REALTIME_OBJECT_FLAG modifier to provide priority-ordered queuing of wait requests.```

The above mentioned flag doesn't exist in the WDK or the SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c845f6-fd94-5bad-8350-c22b719e9a01
* Version Independent ID: 6999942a-637f-f4f8-2411-ead4c97dbc2c
* Content: [ZwCreateEvent function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-zwcreateevent)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-zwcreateevent.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-zwcreateevent.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@dmex , thanks for reporting this! You are correct that this flag is not in the WDK or SDK. I have removed documentation about it.
