### ISSUE TITLE
Unreadable Text in Remarks

### ISSUE THREAD

**Issue by matwilli** [MicrosoftDocs/windows-driver-docs-ddi#898]
Text in remarks section isn't readable (text captured below).  Looks like this could be a simple Markdown formatting error

[1]
The data is typically accessed at <= apc_level,="" but="" it="" might="" need="" to="" be="" accessed="" at="" higher="" irql="" levels="" for="" short="" periods.="">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d25ad53-a1b5-d745-c29a-9755bcf37481
* Version Independent ID: 6956f78b-cce7-faec-b251-eaa39f820e45
* Content: [MmLockPagableDataSection function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-mmlockpagabledatasection)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-mmlockpagabledatasection.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-mmlockpagabledatasection.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the report @matwilli 

I just pushed the change, should be live within an hour.  If you like, next time, note that you can open a pull request by clicking Edit from the page on docs
