### ISSUE TITLE
FlagsWddm2 not documented correctly?

### ISSUE THREAD

**Issue by bujji00** [MicrosoftDocs/windows-driver-docs-ddi#906]
[Enter feedback here]

Here is the what the documentation says for FlagsWddm2 but it doesn't look right.  Appreciate your help in taking a look.

FlagsWddm2

[out] The index of the physical adapter.

Support for this member started with Windows 10 and WDDM 2.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a49cd56-edb8-6013-f61b-9334110ad8bd
* Version Independent ID: 163fdc06-9b62-6284-0d66-6e0c8ecb180b
* Content: [_DXGK_ALLOCATIONINFO (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ns-d3dkmddi-_dxgk_allocationinfo)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_allocationinfo.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_allocationinfo.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@bujji00 , great catch and thanks for reporting this. I've fixed the description for FlagsWddm2 and added a refpage for its associated structure.
