### ISSUE TITLE
Text Block Misplaced

### ISSUE THREAD

**Issue by johnfeit** [MicrosoftDocs/windows-driver-docs-ddi#920]
[Enter feedback here]

The comment for the 

D3DDDI_PERIODIC_MONITORED_FENCE  is in the previous block of text for the D3DDDI_MONITORED_FENCE

Example:

D3DDDI_MONITORED_FENCE | The synchronization object is a monitored fence.Supported starting with Windows 10.The synchronization object is a periodic monitored fence.Supported starting with Windows 10.
D3DDDI_PERIODIC_MONITORED_FENCE

**Should be...**

D3DDDI_MONITORED_FENCE | The synchronization object is a monitored fence.Supported starting with Windows 10.
D3DDDI_PERIODIC_MONITORED_FENCE | The synchronization object is a periodic monitored fence.Supported starting with Windows 10.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d32c52a5-1c19-99d2-c69f-6e1b722fa2aa
* Version Independent ID: 819f8062-180e-9759-38af-d6e064c595e7
* Content: [_D3DDDI_SYNCHRONIZATIONOBJECT_TYPE (d3dukmdt.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dukmdt/ne-d3dukmdt-_d3dddi_synchronizationobject_type)
* Content Source: [wdk-ddi-src/content/d3dukmdt/ne-d3dukmdt-_d3dddi_synchronizationobject_type.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dukmdt/ne-d3dukmdt-_d3dddi_synchronizationobject_type.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by EliotSeattle** [comment]
Thanks for catching this, @johnfeit 

I made the fix and checked it into the main branch. Should be live soon.

Eliot

**Comment by johnfeit** [comment]
Thanks!
