### ISSUE TITLE
missed opportunity for helpful link

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#93]
The second parameter for this function is PSTOR_LOG_EVENT_DETAILS. If that text were also a link to the page describing the structure it might be useful to the reader. My guess at the appropriate link is below.

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/storport/ns-storport-_stor_log_event_details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b29b681-98fd-c448-c616-5473bbbb756f
* Version Independent ID: 05524d20-aac2-aeea-dec4-b586ae6916cc
* Content: [StorPortLogSystemEvent function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/storport/nf-storport-storportlogsystemevent)
* Content Source: [wdk-ddi-src/content/storport/nf-storport-storportlogsystemevent.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/storport/nf-storport-storportlogsystemevent.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @BenWestbrook, thanks for bringing this to our attention. You do indeed have the correct link, and I've added it to the parameter on the page. It should show up in the next day or so!

Thanks so much for the feedback, feel free to reach out again!
