### ISSUE TITLE
Document Details

### ISSUE THREAD

**Issue by Sir-Jay** [MicrosoftDocs/windows-driver-docs-ddi#931]
[Enter feedback here]

---
#### 

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6908a7a2-3f8c-6541-8d97-71ff95e7a35a
* Version Independent ID: 75d9ce06-aa01-125e-ec28-ea5079d86b6d
* Content: [Hardware notifications - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/_gpiobtn/)
* Content Source: [wdk-ddi-src/content/_gpiobtn/index.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/_gpiobtn/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @Sir-Jay 
I don't see any actionable work to be done in this request, so I am going to close the issue. If there's something you've noticed in the docs or something you're asking for, please open another issue and add greater detail.
Thanks so much,
Eliot
