### ISSUE TITLE
Defination dismatches between D3DDDI_HDR_METADATA_HDR10 and DXGI_HDR_METADATA_HDR10?

### ISSUE THREAD

**Issue by RRRichardLi** [MicrosoftDocs/windows-driver-docs-ddi#934]
In **D3DDDI_HDR_METADATA_HDR10**:

- MaxMasteringLuminance

The maximum number of nits of the display used to master the content. Values are in whole nits.

- MinMasteringLuminance

The minimum number of nits of the display used to master the content. Values are in 1/10000th of a nit (0.0001 nits).

In **DXGI_HDR_METADATA_HDR10**:

- MaxMasteringLuminance

The maximum number of nits of the display used to master the content. Values are normalized to 10,000.

- MinMasteringLuminance

The minimum number of nits of the display used to master the content. Values are normalized to 10,000.

It seems these two definations in each structure don't match each other. If the display's Max/Min luminance is 1000nit/0.001nit. Does it mean I should set Max/MinMasteringLuminance 1000 *10000 and 0.001 * 10000?

**Comment by lorihollasch** [comment]
@RRRichardLi , thanks for this issue; sorry for my slow response. Where are you getting the different definitions? The definitions on [D3DDDI_HDR_METADATA_HDR10](https://docs.microsoft.com/windows-hardware/drivers/ddi/d3dukmdt/ns-d3dukmdt-_d3dddi_hdr_metadata_hdr10) and [DXGI_HDR_METADATA_HDR10](https://docs.microsoft.com/windows/win32/api/dxgi1_5/ns-dxgi1_5-dxgi_hdr_metadata_hdr10) are virtually identical and should be straightforward. I'm going to close this, but feel free to respond with a pointer to the erroneous DXGI_HDR_METADATA_HDR10 page.
