### ISSUE TITLE
dead link in page

### ISSUE THREAD

**Issue by seedkar1** [MicrosoftDocs/windows-driver-docs-ddi#943]
dead link under "OpenEvent Fails in a Non-Administrator Account"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e9ef9d-c821-66a5-add5-ca2889a4b299
* Version Independent ID: 23767e29-a42c-3703-24a0-ce8d6c354d22
* Content: [IoCreateNotificationEvent function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iocreatenotificationevent)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iocreatenotificationevent.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iocreatenotificationevent.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the report.  I had a look around and could not find the target article, so I removed the link.

The update should be live within an hour.
