### ISSUE TITLE
What does STATUS_SUCCESS mean in the context of this call

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs-ddi#945]
There is some (I would say reasonable) confusion over in [NTFSD ](https://community.osr.com/discussion/292329/fltcbdqinsertio-query-about-return-value)about what `STATUS_SUCCESS` means.

* `STATUS_PENDING` means "I queued it"
* What could `STATUS_SUCESS` mean?  "The operation to queued the CBD worked, but the CBD wasn't queued?".

My instinct is that it cannot happen - even in the case when the CBD was executed inline for instance  it should return STATUS_PENDING, but you'd need to check.  Either way the confusion should be addressed.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9faa19c-2fcf-aa0c-9bf7-09c636af332e
* Version Independent ID: eeb5af1a-a188-f063-c2d2-30162a74654a
* Content: [FltCbdqInsertIo function (fltkernel.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/fltkernel/nf-fltkernel-fltcbdqinsertio)
* Content Source: [wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcbdqinsertio.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/fltkernel/nf-fltkernel-fltcbdqinsertio.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @rodwiddowson!  I've updated the Return value section to clear up the confusion (and it was indeed confusing). Happy New Year to you.
