### ISSUE TITLE
Wrong struct definition

### ISSUE THREAD

**Issue by UweSieber** [MicrosoftDocs/windows-driver-docs-ddi#947]
Actual definition is

typedef enum _USB_HUB_TYPE {
    UsbRootHub        = 1,
    Usb20Hub          = 2,
    Usb30Hub          = 3
} USB_HUB_TYPE;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b769aa2-7ac6-ef81-8d12-ef88e0d844ff
* Version Independent ID: b8fe1a5a-6b36-da74-fb36-2453a079d7f6
* Content: [_USB_HUB_TYPE (usbioctl.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/usbioctl/ne-usbioctl-_usb_hub_type)
* Content Source: [wdk-ddi-src/content/usbioctl/ne-usbioctl-_usb_hub_type.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbioctl/ne-usbioctl-_usb_hub_type.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by billlattimer** [comment]
@UweSieber thank you for pointing this out. Correct and appears to be a rendering error in our publishing engine. I will address this with our publishing tools team right away and update the doc accordingly. 

typedef enum _USB_HUB_TYPE {
    UsbRootHub        = 1,
    Usb20Hub          = 2,
    Usb30Hub          = 3
} USB_HUB_TYPE;
