### ISSUE TITLE
The link to "Using the Registry in a Driver" is broken (404)

### ISSUE THREAD

**Issue by rhymu8354** [MicrosoftDocs/windows-driver-docs-ddi#948]
The link to "Using the Registry in a Driver" in this page (https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/using-the-registry-in-a-driver) is broken (404 Not Found)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b636b5a9-c3b9-b80f-6c5a-e1da53418cdc
* Version Independent ID: 065eb7fc-9b4e-1493-471e-fd49d1f2b7c4
* Content: [ZwOpenKey function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwopenkey)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-zwopenkey.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-zwopenkey.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the heads-up @rhymu8354.  I put a redirect in place.
