### ISSUE TITLE
IOCTL_USBPRINT_GET_LPT_STATUS

### ISSUE THREAD

**Issue by szalkerous** [MicrosoftDocs/windows-driver-docs-ddi#955]
The return buffer description is incorrect for this function and appears to describe the return buffer for IOCTL_USBPRINT_GET_1284_ID instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c969f65b-81d5-5ff0-d4ee-651e238d72bf
* Version Independent ID: 3a9f2707-8fe5-153a-af0e-1ff1a7975807
* Content: [IOCTL_USBPRINT_GET_LPT_STATUS (usbprint.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/usbprint/ni-usbprint-ioctl_usbprint_get_lpt_status)
* Content Source: [wdk-ddi-src/content/usbprint/ni-usbprint-ioctl_usbprint_get_lpt_status.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/usbprint/ni-usbprint-ioctl_usbprint_get_lpt_status.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@szalkerous, thanks for pointing out the incorrect text in this topic. 

I've updated the output buffer and output buffer length descriptions in the IOCTL_USBPRINT_GET_LPT_STATUS IOCTL (usbprint.h) topic and removed the IEEE 1284 device reference.
