### ISSUE TITLE
Incorrect parameter documentation

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#958]
The following looks like a copy/paste error to me:

> BufferSize
>
> Output pointer for the number of bytes that the method has written to the Attributes buffer. This parameter points to a ULONG variable into which the method writes the byte count.

The BufferSize parameter is an _In_ parameter, and not a pointer type:
```
    STDMETHODIMP_(VOID) FreeAudioBuffer
    (
        _In_opt_  PMDL                    AudioBufferMdl,
        _In_  ULONG                   BufferSize
    );
```

Also, the `AudioBufferMdl` parameter is apparently optional (and sample code _does_ check this parameter for NULL), but the documentation doesn't mention when/why this parameter would be NULL, or what that might indicate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd305f50-d72b-1d50-4f8d-28478f26b1c3
* Version Independent ID: 31c9946c-cde1-6971-6743-b4dbc8da9642
* Content: [IMiniportWaveRTStream::FreeAudioBuffer (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nf-portcls-iminiportwavertstream-freeaudiobuffer)
* Content Source: [wdk-ddi-src/content/portcls/nf-portcls-iminiportwavertstream-freeaudiobuffer.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nf-portcls-iminiportwavertstream-freeaudiobuffer.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - I believe the descriptions are accurate for FreeAudioBuffer. One way to check the usage of these is to look at the sysvad sample. It has the following code. 

```
#pragma code_seg("PAGE")
VOID CMiniportWaveRTStream::FreeAudioBuffer
(
_In_opt_    PMDL        Mdl_,
_In_        ULONG       Size_
)
{
    UNREFERENCED_PARAMETER(Size_);

    PAGED_CODE();

    if (Mdl_ != NULL)
    {
        if (m_pDmaBuffer != NULL)
        {
            m_pPortStream->UnmapAllocatedPages(m_pDmaBuffer, Mdl_);
            m_pDmaBuffer = NULL;
        }

        m_pPortStream->FreePagesFromMdl(Mdl_);
    }

    m_ulDmaBufferSize = 0;
    m_ulNotificationsPerBuffer = 0;
}
```
Beyond the sysvad sample, one resource for WDM audio driver development is the OSR forums. 
https://community.osr.com/
We also recently moved the MSDN Forums to this location for Windows development.
https://docs.microsoft.com/answers/products/windows. 
Good luck with your WDM audio driver development work.
