### ISSUE TITLE
Referenced "for more information" topics should be links(?)

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#959]
> For more information about the sources of hardware latency in an audio stream, see the Stream Latency during Playback and Stream Latency during Recording topics.

These ought to be links?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 157961bb-fff8-5b83-fa96-8f7c66670480
* Version Independent ID: db790634-3752-8070-45f6-1919a26ef32d
* Content: [IMiniportWaveRTStream::GetHWLatency (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nf-portcls-iminiportwavertstream-gethwlatency)
* Content Source: [wdk-ddi-src/content/portcls/nf-portcls-iminiportwavertstream-gethwlatency.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nf-portcls-iminiportwavertstream-gethwlatency.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - Thanks for this input. Those text references are now links as they should be. Thanks for the interest in improving the audio driver docs.
