### ISSUE TITLE
IMiniportWaveRTStream::GetPositionRegister method is missing from overview page and index

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#961]
In portcls.h, the **IMiniportWaveRTStream** interface is declared as having eight methods:

- AllocateAudioBuffer
- FreeAudioBuffer
- GetClockRegister
- GetHWLatency
- GetPosition
- **GetPositionRegister**
- SetFormat
- SetState

The **overview** page and index in the left pane are missing the **GetPositionRegister** method. The detail page for this method _exists_, so I think this is just a case of missing list/index entries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f88bb5eb-1633-d0b5-0e7a-a86c429739ad
* Version Independent ID: cba05873-e842-50bf-cdab-d569c2009aba
* Content: [IPortWaveRTStream (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nn-portcls-iportwavertstream)
* Content Source: [wdk-ddi-src/content/portcls/nn-portcls-iportwavertstream.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nn-portcls-iportwavertstream.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - Thanks for this PR. It looks like the specific method you mentioned (IMiniportWaveRTStream::GetPositionRegister) is now present. 

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nf-portcls-iminiportwavertstream-getpositionregister

And is listed in the interface topic, and in the TOC on the left.

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nn-portcls-iminiportwavertstream

That said, if you see anything else that is missing in portcls.h open an issue and I will investigate. As you have seen there are a set of interfaces that have some overlapping in naming with similar names, so errors can occur.
