### ISSUE TITLE
One or more IMiniportWaveRTStream interface methods missing from overview/index

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#962]
In #961, I reported this for a different URL; but there seems to be multiple versions of both the **overview** page and index pane at different URLs under docs.microsoft.com. They're similar, but the pages referred to by #961 are missing a single method, and this issue refers to nearly-identical pages, but missing two methods. Hope that makes sense.
 
In portcls.h, the **IMiniportWaveRTStream** interface is declared as having eight methods:

- AllocateAudioBuffer
- FreeAudioBuffer
- GetClockRegister
- GetHWLatency
- GetPosition
- GetPositionRegister
- SetFormat
- SetState

In this case, I believe the **overview** page lists only 7 out of 8 interface methods. The index (in the pane on the far left) lists only 6 out of 8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f88bb5eb-1633-d0b5-0e7a-a86c429739ad
* Version Independent ID: cba05873-e842-50bf-cdab-d569c2009aba
* Content: [IPortWaveRTStream (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nn-portcls-iportwavertstream)
* Content Source: [wdk-ddi-src/content/portcls/nn-portcls-iportwavertstream.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nn-portcls-iportwavertstream.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - Yes it looks like there are issues here with all of the methods being listed and rendered. I will investigate.

**Comment by DOMARS** [comment]
@mr-intj - Thanks for this issue. I have restored SetFormat and SetState to  IMiniportWaveRTStream so that all 8 of the 8 methods are now present.
