### ISSUE TITLE
Remarks section references non-existent COM interface(?)

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#964]
The **Remarks** section on this page mentions an interface implemented by the object pointed to by the `UnknownAdapter` parameter:

> see the definition and implementation of the IAdapterObject interface in the sb16 and msvad sample audio drivers

As far as I can tell, there's no other surviving references to this interface (in the docs or code examples).

A related, but separate issue is that given that the class pointed to by the optional `UnknownAdapter` parameter only seems to need to implement **IUnknown**, it's unclear what PortCls could possibly do with it, other than AddRef/Release(?). The docs mention that this param can be `nullptr` (and based upon MS sample code, so can **Irp** and **ResourceList**), but there's no explanation of what difference passing `nullptr` might make, if any...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bbda5ba-1e00-6f60-3aca-32f2056c44e6
* Version Independent ID: fa4348b8-019c-21e2-cd4d-78863fdc2a97
* Content: [IPort::Init (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nf-portcls-iport-init)
* Content Source: [wdk-ddi-src/content/portcls/nf-portcls-iport-init.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nf-portcls-iport-init.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - I updated this topic to point to the CMiniportWaveRT::Init definition and implementation in the newer Sysvad audio driver sample. Good luck with your audio driver development work.
