### ISSUE TITLE
Provided reference doesn't address details of struct type equivalence

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#968]
> For backward compatibility, any wave format that can be specified by a stand-alone **WAVEFORMATEX** structure can also be defined by a **WAVEFORMATEXTENSIBLE** structure.

...

> For more information, see [Converting Between Format Tags and Subformat GUIDs](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/converting-between-format-tags-and-subformat-guids).

Unfortunately, the link above leads to a page that only seems to describe how to map the well-known GUID of one type to another (e.g. Format Tag to SubFormat GUID) for a given audio data binary format description.

The quote at the top of this issue says that it's easy to map from the old **struct** to the new one. I don't see how mapping the GUIDs relates to that.

Is there missing documentation here, or am I just missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7bc3470-75a9-14eb-f136-a5383b1e7ae0
* Version Independent ID: 062d4c16-588c-38fe-a5b1-6f48f75aef8d
* Content: [WAVEFORMATEXTENSIBLE (ksmedia.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ksmedia/ns-ksmedia-waveformatextensible)
* Content Source: [wdk-ddi-src/content/ksmedia/ns-ksmedia-waveformatextensible.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ksmedia/ns-ksmedia-waveformatextensible.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by DOMARS** [comment]
@mr-intj - The purpose of the link on the tags is to provide information on the format of the GUID. I would also look at [Subformat GUIDs for Compressed Audio Formats](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/subformat-guids-for-compressed-audio-formats) as well as of course the two WAVEFORMATEX and WAVEFORMATEXTENSIBLE structures. To see and example of how they are implemented, I would look at the sysvad sample, which is discussed in [Sample Audio Drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/sample-audio-drivers).   For additional questions, I would recommend these two resources, The OSR dev forums at https://community.osr.com/ and we recently moved the MSDN Forums to this location for Windows development. https://docs.microsoft.com/answers/products/windows.
