### ISSUE TITLE
Possibly incomplete list (conflicts with driver code samples)

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#971]
The **Remarks** section states:

> Possible values for `PropTypeSet.Id` include:
> 
> - `VT_I4` - Signed 4-byte quantity
> - `VT_UI4` - Unsigned 4-byte quantity

...and that's it. Just those two.

The audio driver sample code includes a request handler for KSPROPERTY_AUDIO_MUTE that sets `PropTypeSet.Id` to **`VT_BOOL`** when the Verb is KSPROPERTY_TYPE_BASICSUPPORT.

That suggests to me that the list on this page was never filled out(?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cdf2751-c365-3dfc-3109-68b7ef8f549b
* Version Independent ID: 9c18f961-770f-42c5-3763-0be0163ef18a
* Content: [KSPROPERTY_VALUES (ks.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ks/ns-ks-ksproperty_values)
* Content Source: [wdk-ddi-src/content/ks/ns-ks-ksproperty_values.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ks/ns-ks-ksproperty_values.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Added additional [VT_ constants](https://docs.microsoft.com/windows-hardware/drivers/ddi/ks/ns-ks-ksproperty_values#remarks) commonly used in streaming media code (audio/camera).

Populated the [VARENUM enumeration (ks.h)](https://docs.microsoft.com/windows-hardware/drivers/ddi/ks/ne-ks-varenum)  constant descriptions and usage table.
