### ISSUE TITLE
Requirement stated with no information as to how it can be satisfied

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#972]
> The method always allocates an integral number of pages. If sufficient memory is available, the memory allocation is the requested size rounded up to the next page. Otherwise, the memory allocation can be less than the requested size. **The caller must verify how many bytes are actually allocated.** _(emphasis mine)_

Presumably, this would be done via a call to `void MmGetMdlByteCount(Mdl)`, but this API isn't mentioned on this page, or even in the **See Also** section.

Also, **none** of the sample code that I've seen actually verifies this (and kernel code is usually pretty careful about that sort of thing), so I'm wondering whether this warning is still valid(?)

---

Sorry to beat a dead horse, but another (related) thing occurred to me. One place where this API call shows up is in IMiniportWaveRTStream::AllocateAudioBuffer. MS Sample audio driver code checks to see if the requested size passed in is an even multiple of the format's `nBlockAlign` value. If not, the sample code rounds _down_. I've seen several posts from driver developers that say that it's fine if you allocate _more_ than is requested, but not if you allocate _less_ (they were referring to WaveCyclic--WaveRT may differ).

Given that rounding down would result in returning less than requested, I adjusted my code to round _up_ to the nearest `nBlockAlign` bytes. My code initially had a bug that was _always_ adding four bytes even though the block alignment was correct, and PortCls always rejected a return value (ActualSize) that was four bytes greater than RequestedSize.

OK, I mention all of that because the documentation for this function says that it allocates an _integral number of pages_. And that callers should verify the _actual_ number of bytes allocated. So that means that when PortCls asks the Miniport driver to allocate N bytes for the DMA buffer, either:

- N had better be an even multiple of the 'page' size, or...
- N had better be an even multiple of the `nBlockAlign` size, and the caller can check the actual number of bytes allocated to ensure that it's not less than requested, but must not return ActualSize if it's _greater_ than Requested size, because we know that PortCls will reject it, or...
- ???

The sample code seems to work _without checking_, but I'd never have written it that way based upon the documentation above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45733877-92fe-906b-cd95-d675c51f7efc
* Version Independent ID: 80a5d049-b55d-82b5-c5c0-d0b56c24f347
* Content: [IPortWaveRTStream::AllocatePagesForMdl (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nf-portcls-iportwavertstream-allocatepagesformdl)
* Content Source: [wdk-ddi-src/content/portcls/nf-portcls-iportwavertstream-allocatepagesformdl.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nf-portcls-iportwavertstream-allocatepagesformdl.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - Thanks for this input on the portcls call IPortWaveRTStream::AllocatePagesForMdl.  I don't have much additional information I can offer on best strategies for alignment and size allocation. I see this code in Sysvad, in miniwavertstream, that you could consider looking to as a model for the use of AllocatePagesForMdl.

```cpp

    PHYSICAL_ADDRESS highAddress;
    highAddress.HighPart = 0;
    highAddress.LowPart = MAXULONG;


    PMDL pBufferMdl = m_pPortStream->AllocatePagesForMdl (highAddress, RequestedSize_);

    if (NULL == pBufferMdl)
    {
        return STATUS_UNSUCCESSFUL;
    }


    m_pDmaBuffer = (BYTE*)m_pPortStream->MapAllocatedPages(pBufferMdl, MmCached);
    m_ulDmaBufferSize = RequestedSize_;

    *AudioBufferMdl_ = pBufferMdl;
    *ActualSize_ = RequestedSize_;
    *OffsetFromFirstPage_ = 0;
    *CacheType_ = MmCached;


```

If you are still working with audio memory allocation, I would recommend posting the code that you have tried, and what you are trying to achieve to one of the forums, such as those provided by OSR - [OSR's ntdev List](https://community.osr.com/categories/ntdev) or [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html).

I hope longer term to better tie the code in sysvad to these docs, but I don't have a timeframe for that. Thanks again for this input, and good luck with your WDM kernel mode audio driver development.
