### ISSUE TITLE
What is 'OffsetFromFirstPage' parameter actually for?

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs-ddi#974]
> `OffsetFromFirstPage`
> 
> Output pointer for the buffer's offset, in bytes, from the start of the first page in the MDL. This parameter points to a caller-allocated `ULONG` variable into which the method writes the offset value.

It's not clear what this _is_. It kind of sounds like it may be an initial PlayOffset or WriteOffset, but it might also be a way for vendors to reserve an area at the beginning of a buffer for private vendor metadata or similar.

If this is the latter, then there needs to be more information; If a buffer of N bytes is requested, and I return a size of N with a non-zero offset, what does that actually mean? Wouldn't I have to allocate N + X and then return an offset of X?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab27fe16-85eb-4695-49bc-631514547040
* Version Independent ID: 74929cef-44a6-84da-32a1-795865016201
* Content: [IMiniportWaveRTStream::AllocateAudioBuffer (portcls.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/portcls/nf-portcls-iminiportwavertstream-allocateaudiobuffer)
* Content Source: [wdk-ddi-src/content/portcls/nf-portcls-iminiportwavertstream-allocateaudiobuffer.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/portcls/nf-portcls-iminiportwavertstream-allocateaudiobuffer.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
Thanks for this input on the portcls call IMiniportWaveRTStream::AllocateAudioBuffer. I added a link to the kernel memory topic [Using MDLs](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/using-mdls) as this call is making use of that structure. I also frequently refer to Windows Internals Mark Russinovich book when working with Windows memory structures, such as MDLs.

For the specific use of OffsetFromFirstPage, I would think that would be dependent on the specifics of the audio driver that is being developed. It looks like in Sysvad, in miniwavertstream, that it is set to zero, at least initially.

```cpp
    *AudioBufferMdl_ = pBufferMdl;
    *ActualSize_ = RequestedSize_;
    *OffsetFromFirstPage_ = 0;
```

If you are still working with audio memory allocation, I would recommend posting the code that you have tried and what you are trying to achieve to one of the forums, such as those provided by OSR -[OSR's ntdev List](https://community.osr.com/categories/ntdev) or [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html).

Thanks again for this input, and good luck with your WDM kernel mode audio driver development.
