### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/windows-driver-docs-ddi#977]
ZwQuerySecurityObject has the same problem as #949 

`SecurityInformation` is not pointer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 308a2812-ae6a-e933-1454-759e72b45e79
* Version Independent ID: 97f8681a-7667-0517-2325-16686043c5dd
* Content: [ZwQuerySecurityObject function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-zwquerysecurityobject)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-zwquerysecurityobject.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-zwquerysecurityobject.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @hsebs  - it's now fixed. Apologies for the overlap in your PR versus mine!
