### ISSUE TITLE
Incorrect / misleading link for DriverEntry

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs-ddi#98]
Greetings,

The link for DriverEntry on this page goes to the ATA section. It should go to the StorPort section. I suspect the correct landing spot is somewhere in the following tree:

Docs
Windows Hardware
Programming reference for Windows Driver Kit
Storage
Storport.h

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56e0fb8-807d-b4fc-0102-7ae659a1ac85
* Version Independent ID: 892ac911-5317-b90a-fc79-3669bc99224b
* Content: [StorPortInitialize function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/storport/nf-storport-storportinitialize)
* Content Source: [wdk-ddi-src/content/storport/nf-storport-storportinitialize.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/storport/nf-storport-storportinitialize.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @BenWestbrook, thanks for finding this. I've updated the page to point to our [storage miniport](https://docs.microsoft.com/windows-hardware/drivers/storage/storage-miniport-drivers) documentation, where people can find the driverEntry info for their miniport type. Should be live soon.

Thanks again!
