### ISSUE TITLE
Clarify what happens then underlying file system is not NTFS

### ISSUE THREAD

**Issue by vaintroub** [MicrosoftDocs/windows-driver-docs-ddi#988]
I think better documentation is needed, of the effects of calling this function, using Flags  different from 0 ,on file system different from NTFS.

Current documentation states:

*[in] Flush operation flags. Flags can be 0 or one of the following values if the file is on an NTFS file system.*

From what I can from my experiments with FAT32 RAMDISK formatted partition and FLUSH_FLAGS_FILE_DATA_SYNC_ONLY flag, passing not 0 flags seems to 

1.  return success
2.  Do something that resembles metadata flush (e.g when syncing R:\data\file ,NtFlushBuffersFileEx it would also cause Writes to 
    R:\data, and to R:\) (shown in procmon)
3. procmon would show FileFlushBuffers and SUCCESS

So, my conclusion is that non-0 flags are ignored and handled as 0, when the underlying system is not NTFS, but it is better to have it documented.
With current documentation it is not clear what to expect on non-NTFS, and Flags != 0, and it could be any of 
full flush, or NTSTATUS returns error, or NTSTATUS indicates success, but call results into no-op.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d54580f8-53ef-db25-71e1-dfccd8bfff5e
* Version Independent ID: ce8ef8a9-708b-a915-9bb6-1004e1842ec2
* Content: [NtFlushBuffersFileEx function (ntifs.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntflushbuffersfileex)
* Content Source: [wdk-ddi-src/content/ntifs/nf-ntifs-ntflushbuffersfileex.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-ntflushbuffersfileex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for this great doc enhancement request, @vaintroub . I've listed the Windows FSs supported for each flag value.
