### ISSUE TITLE
OS version 

### ISSUE THREAD

**Issue by taotal** [MicrosoftDocs/windows-driver-docs-ddi#991]
[Enter feedback here]
Hi ,
this API supported from RS5 or RS4? 
We need this info to understand which driver to be updated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aff8014-16ee-a60e-f129-e57e261a585e
* Version Independent ID: 5f7bd3b7-2540-26a4-32a9-e20c7b52ddd6
* Content: [IoGetDriverDirectory function (wdm.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-iogetdriverdirectory)
* Content Source: [wdk-ddi-src/content/wdm/nf-wdm-iogetdriverdirectory.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-iogetdriverdirectory.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @taotal for the question.

This API was introduced in **Windows 10, version 1803 (RS4)**. I have pushed an update to https://docs.microsoft.com/windows-hardware/drivers/ddi/wdm/nf-wdm-iogetdriverdirectory - the update should be live in less than an hour.
