### ISSUE TITLE
Small mistake in the given example (inexistant pointer)

### ISSUE THREAD

**Issue by aleaforny** [MicrosoftDocs/windows-driver-docs-ddi#992]
I guess there is a (**very**) small mistake in the example given: The `DestinationString `of the `RtlInitUnicodeString `should be `&myKeyStr` and not `&mySubKey` (which doesn't exist by the way).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df06439-9c44-d1cb-d652-a12362c906a2
* Version Independent ID: eede9e72-d5d0-b3df-7505-02c975183580
* Content: [WdfRegistryCreateKey function (wdfregistry.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfregistry/nf-wdfregistry-wdfregistrycreatekey)
* Content Source: [wdk-ddi-src/content/wdfregistry/nf-wdfregistry-wdfregistrycreatekey.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdfregistry/nf-wdfregistry-wdfregistrycreatekey.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @aleaforny,

Thanks for the heads-up and apologies for the delay.  This fix is now live!
