### ISSUE TITLE
NVME_IDENTIFY_CNS_ACTIVE_NAMESPACES cannot be applied to NVMeDataTypeIdentify

### ISSUE THREAD

**Issue by tim-oleksii** [MicrosoftDocs/windows-driver-docs-ddi#997]
Hello,

Can you please tell whether it's an issue that NVME_IDENTIFY_CNS_ACTIVE_NAMESPACES is in header files, but documentation tells that it cannot be used? I'm trying to apply this CNS in user mode (not from kernel).

Sorry, I cannot test all Windows version, maybe you can help? 

Is this change expected in future? Is it Windows regression?

Best regards,
tim

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab9b8ae5-522f-099e-0b1a-f6a47e38d7bd
* Version Independent ID: c28134e5-19c7-89e5-dbc2-c180557afe2c
* Content: [_STORAGE_PROTOCOL_NVME_DATA_TYPE (ntddstor.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddstor/ne-ntddstor-_storage_protocol_nvme_data_type)
* Content Source: [wdk-ddi-src/content/ntddstor/ne-ntddstor-_storage_protocol_nvme_data_type.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntddstor/ne-ntddstor-_storage_protocol_nvme_data_type.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@tim-oleksii , NVME_IDENTIFY_CNS_ACTIVE_NAMESPACES is indeed currently not supported (it is not a regression). I've added a note to this page accordingly. The dev team told me they would add support in the future (no timeline provided).
